warp-drive-data/warp-drive

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/unit/store/push_test.js

Previously, if your payload sent "firstName", but the value of "firstName" did not change, your observers would fire anyway. It seems like if we are going to do observers we should not cause observers to fire when they wouldn't if the underlying `_data` object were an `Ember.Object`. This also helps reduce zalgo when you are developing an app and wondering why observers are firing when they shouldn't be.
cc @rwjblue

Only trigger changes for changed properties

---

packages/ember-data/tests/integration/debug_adapter_test.js

Since support for Ember <= 1.7.1 has been removed, I'm guessing it's safe to remove this.

Remove workaround for Ember 1.5

---

packages/ember-data/tests/unit/store/push_test.js

This removes the store.update deprecation warning when running tests

Use store.push instead of store.update in test

---

packages/ember-data/lib/adapters/rest_adapter.js

Removes this warning from the build:
```
info: (yuidoc): YUIDoc Starting from: packages
warn: (docparser): Missing item type:  packages/ember-data/lib/adapters/rest_adapter.js:605
warn: (docparser):             http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers
```

Remove yuidoc warning

---

packages/ember-data/lib/system/relationships/state/belongs_to.js
packages/ember-data/tests/integration/relationships/belongs_to_test.js

When using polymorphic models in an ember app, the `addCanonicalRecord` method does not check for a model's superclass when comparing equality of a `newRecord` to the expected `type`
Because there previously was no check for a type's super class, this assertion pops up: `Ember.assert("You can only add a '" + type.typeKey + "' record to this relationship", newRecord instanceof type);`
My solution to this is to add a check for `Ember.MODEL_FACTORY_INJECTIONS` like in the `addRecord` method inside the `belongs_to` class:
```
Ember.assert("You can only add a '" + type.typeKey + "' record to this relationship", (function () {
if (newRecord instanceof type) {
return true;
} else if (Ember.MODEL_FACTORY_INJECTIONS) {
return newRecord instanceof type.superclass;
}
return false;
})());
```

Checking superclass type for equality in addCanonicalRecord method for a belongsTo relationship

---

.travis.yml

http://docs.travis-ci.com/user/workers/container-based-infrastructure/
Running CI in docker container should be more performant. This is already
being done in
[ember/ember.js](https://github.com/emberjs/ember.js/blob/dca9c74de7136deff79b9cb2f2de4f6b6b8237c7/.travis.yml#L6-L10)

Run Travis-CI with Docker / Cache

---

packages/ember-data/tests/unit/model/lifecycle_callbacks_test.js
packages/ember-data/tests/unit/model/merge_test.js
packages/ember-data/tests/unit/model/relationships_test.js
packages/ember-data/tests/unit/model_test.js
packages/ember-data/tests/unit/record_array_test.js
packages/ember-data/tests/unit/store/adapter_interop_test.js
packages/ember-data/tests/unit/store/create_record_test.js
packages/ember-data/tests/unit/store/metadata_for_test.js
packages/ember-data/tests/unit/store/push_test.js
packages/ember-data/tests/unit/store/unload_test.js

`expect` calls within callbacks ensure that all expectations are invoked
and passing.

Add `expect` calls when async is involved

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/unit/store/push_test.js

This is not pretty but it was the least ugly thing I could come up with. This also allows for regular attributes ending in "Type", like:
```javascript
App.Thing = DS.Model.extend({
fakeType: DS.attr('string')
});
```
Fixes #2599

Don't warn for polymorphic belongsTo type keys

---

packages/activemodel-adapter/tests/integration/active_model_serializer_test.js
packages/ember-data/tests/integration/relationships/has_many_test.js
packages/ember-data/tests/integration/serializers/embedded_records_mixin_test.js
packages/ember-data/tests/unit/model/lifecycle_callbacks_test.js
packages/ember-data/tests/unit/model_test.js
packages/ember-data/tests/unit/store/push_test.js
packages/ember-data/tests/unit/store/unload_test.js

Cleaned up some tests to remove all warnings when running the test suit. The only warnings left are two of these:
```
WARNING: The payload for 'comment' contains these unknown keys: [messageType]. Make sure they've been defined in your model.
```
..but they will disappear when/if #2677 is merged.

Test warnings cleanup

---

packages/ember-data/lib/adapters/rest_adapter.js
packages/ember-data/tests/integration/adapter/rest_adapter_test.js

Related to #2694 and https://github.com/emberjs/ember.js/pull/10215. This change will make the stack trace in the error object more relevant as its closer to the failed ajax request. Instead of originating from `RSVP.onerrorDefault`

Wrap the errorThrown in an Error object if it's a string

---

packages/ember-data/lib/system/record_arrays/many_array.js

Before: 
@extends DS.RecordArray
But `DS.ManyArray` does not extend `DS.RecordArray`!
After:
@extends Ember.Object
@uses Ember.MutableArray, Ember.Evented

Fixed `@extends` and `@uses` for ManyArray doc

---

CONTRIBUTING.md

- Version 1 was missing ember-template-compiler.js which caused it to error out
- Link to the latest version

Update JSBin link

---

packages/ember-data/lib/system/store.js

Previously, when you've defined application's store, like outdated documentation suggested:
~~~~
MyApp.Store = DS.Store.extend();
~~~~
It raised deprecation warning:
~~~~
DEPRECATION: Specifying a custom Store for Ember Data on your global namespace as `App.Store` has been deprecated. Please use `App.ApplicationStore` instead.
at ember$data$lib$initializers$store$$initializeStore (http://builds.emberjs.com/canary/ember-data.js:10308:13)
at ember$data$lib$setup$container$$setupContainer (http://builds.emberjs.com/canary/ember-data.js:10621:7)
at http://builds.emberjs.com/tags/v1.9.1/ember.js:3079:11
at visit (http://builds.emberjs.com/tags/v1.9.1/ember.js:2002:7)
at visit (http://builds.emberjs.com/tags/v1.9.1/ember.js:2000:9)
at DAG.topsort …

[DOCS]Update about defining application's store

---

packages/ember-data/lib/system/relationships/belongs_to.js
packages/ember-data/lib/system/relationships/has_many.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/relationships/has_many_test.js

I think this is my bad to begin with, sometimes I'm not letting go of the alt key fast enough after writing a `|` followed by a space. This results in a non-breaking space being inserted instead of a regular space. Fixes #2716.

Remove non-breaking spaces

---

packages/ember-data/lib/system/store.js

This is for #2516 
The documentation should also be updated to reflect the actual parameters being passed

generateIdForRecord gets type & object properties passed to it

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/store_test.js

* `store.fetchById` behaves like `store.fetch` used to.
* `store.fetch` is aliased to `store.fetchById` and deprecated.
* `store.fetchAll` behaves like `store.findAll` used to. 
* `store.findAll` is aliased to `store.fetchAll`.
Note that there was already a private method named `fetchAll` with a different signature. I've renamed it to `store._fetchAll` and is used internally.

Created `store.fetchById` and `store.fetchAll`.

---

packages/ember-data/lib/adapters/rest_adapter.js
packages/ember-data/tests/integration/adapter/rest_adapter_test.js

When developing APIs, is pretty common to place a high level cachingmechanism, like Varnish, to cache requests to public API endpoints, and those tools use the URL string to determine if they have a cached
response.
As an example, if one user requests `/posts?sort=price&category=pets` and another requests `/posts?category=pets&sort=price`, the cached request won't be used in the second call.
Varnish by example has some modules to sort query parameters when caching, but it's not the default behavior and requires custom config.
Although the URL specification does not say that the order of the query parameters is meaningless, in the bast mayority (read: all) of the APIs I've seen, 2 requests are considered identical regardless of the the order.
Because of that, sorting the query params …

Sort query params in ajax calls.

---

packages/activemodel-adapter/tests/integration/active_model_serializer_test.js
packages/ember-data/lib/initializers/store_injections.js
packages/ember-data/lib/initializers/transforms.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/tests/integration/adapter/find_test.js
packages/ember-data/tests/integration/inverse_test.js
packages/ember-data/tests/integration/relationships/belongs_to_test.js
packages/ember-data/tests/integration/serializers/embedded_records_mixin_test.js
packages/ember-data/tests/integration/serializers/json_serializer_test.js
packages/ember-data/tests/integration/serializers/rest_serializer_test.js
packages/ember-data/tests/integration/setup-container-test.js
packages/ember-data/tests/integration/store_test.js
packages/ember-data/tests/unit/record_array_test.js
packages/ember-data/tests/unit/store/adapter_interop_test.js
packages/ember-data/tests/unit/store/push_test.js
packages/ember-data/tests/unit/transform/boolean_test.js
packages/ember-data/tests/unit/transform/date_test.js
packages/ember-data/tests/unit/transform/number_test.js
packages/ember-data/tests/unit/transform/string_test.js

property.
See https://github.com/emberjs/ember.js/pull/10323
cc @ebryn @igorT

Fix tests on canary. They broke when Ember.js removed the meta.descs

---

packages/ember-data/lib/system/relationships/belongs_to.js

Display the correct doc block for the model header.

---

packages/activemodel-adapter/tests/integration/active_model_serializer_test.js
packages/ember-data/tests/integration/adapter/fixture_adapter_test.js
packages/ember-data/tests/integration/adapter/rest_adapter_test.js
packages/ember-data/tests/integration/record_array_manager_test.js
packages/ember-data/tests/integration/records/reload_test.js
packages/ember-data/tests/integration/relationships/belongs_to_test.js
packages/ember-data/tests/integration/serializers/embedded_records_mixin_test.js
packages/ember-data/tests/integration/serializers/json_serializer_test.js
packages/ember-data/tests/integration/serializers/rest_serializer_test.js
packages/ember-data/tests/unit/model/relationships/has_many_test.js
packages/ember-data/tests/unit/store/push_test.js
tests/ember_configuration.js

`Ember.Registry` has not yet landed on `stable`, but floods the console
with deprecation warnings for `beta` and `canary`.
This PR replaces all calls of `env.container.register` with
`env.registry.register` throughout the test suite.
When the Registry is available, it will handle registration. Otherwise,
it will defer to the Container.

Replace calls to `container` with `registry`

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/adapter/find_test.js

This dematerializes records that has been created when doing a `store.find('thing', 1)` and it fails/gets rejected. Not 100% sure if `isEmpty` is the correct condition here though.
Also, is this the behaviour we want?
Fixes #1747, fixes #1767, fixes #1931, fixes #2150

Dematerialize rejected _find() if record isEmpty

---

packages/ember-data/lib/system/record_arrays/many_array.js

Found some dead code while tracing the inverseRelationship / ImplicitRelationship code paths.
* ManyArray doesn't appear to use the `diff` array
* Relationship doesn't use addCanonicalRecords

Remove unused relationship code

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/integration/adapter/store_adapter_test.js

Addresses #1877
@tchak @igorT ping

Allow errors on arbitrary properties, not just defined attributes or relationships.

---

packages/ember-data/lib/main.js
packages/ember-data/lib/serializers/json_serializer.js
packages/ember-data/lib/system/serializer.js

`serializer.extract()` and `serializer.serialize()` should be the only methods you need to implement if you're building your own serializer but I've included `serializer.normalize()` since it's used by `store.normalize()` and there's no checking if it exists or not (as opposed to `store.pushPayload()` that asserts that `serializer.pushPayload()` has been implemented).
Closes #1658

Add a Serializer base class

---

packages/activemodel-adapter/lib/system/active_model_serializer.js
packages/activemodel-adapter/tests/integration/active_model_serializer_test.js
packages/ember-data/lib/adapters/fixture_adapter.js
packages/ember-data/lib/adapters/rest_adapter.js
packages/ember-data/lib/main.js
packages/ember-data/lib/serializers/embedded_records_mixin.js
packages/ember-data/lib/serializers/json_serializer.js
packages/ember-data/lib/serializers/rest_serializer.js
packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/snapshot.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/serializers/embedded_records_mixin_test.js
packages/ember-data/tests/integration/serializers/json_serializer_test.js
packages/ember-data/tests/integration/serializers/rest_serializer_test.js
packages/ember-data/tests/integration/snapshot_test.js

This is a first stab at the new Snapshot API, `serializer.serialize()` now receives a Snapshot instead of a record instance.
- **Caching** - Right now, attributes are cached eagerly (on instantiation) and relationships are cached on first access. Is this the design we want?
- **snapshot.belongsTo()** - Returns a new snapshot (with at least an ID) or undefined. Is this what we want or should we always return a new snapshot?
- **snapshot.hasMany()** - Always returns an array.
- **snapshot.get() deprecated** - ~~To only use `attr()`, `belongsTo()` and `hasMany()` would require some work in serializers. Should that be done in the scope of this PR or separately?~~ Done in this PR.
[@sly7-7]: Just to clean issues when that awesome work is merged: 
Closes #2551, Fixes #2385, Fixes #2508, Closes …

Initial implementation of the Snapshot API

---

packages/ember-data/lib/system/model/states.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/adapter/find_test.js

- Use store.unloadRecord() in favor of store.dematerializeRecord() (Fixes #2780)
- Deprecate store.dematerializeRecord()

Unload record instead of dematerialize

---

lib/ember-addon/blueprints/ember-data/index.js

We should migrate Ember Data to an ember addon soon.
Until then, we remove a step that could be automated in the
release pipeline by using the version in package.json

use package.json for ember addon

---

packages/ember-data/lib/system/model/model.js

Previous doc was ambiguous and could be interpreted to mean when the record is created using createRecord(). Clarifies that the event is fired when a new record is saved.

[DOC] Clarify when didCreate is fired

---

packages/ember-data/lib/system/relationships/state/belongs_to.js
packages/ember-data/lib/system/relationships/state/has_many.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/relationships/polymorphic_mixins_belongs_to_test.js
packages/ember-data/tests/integration/relationships/polymorphic_mixins_has_many_test.js
tests/index.html

Now it's possible to reference mixins in polymorphic relationships.
For example:
```
var Comment = DS.Model.extend({
owner: belongsTo('commentable'. { polymorphic: true })
});
var Commentable = Ember.Mixin.create({
comments: hasMany('comment')
});
```

Adds support for using mixins in polymorphic relationships

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/integration/records/unload_test.js

Previously if you had records such as:
```
var Group = DS.Model.extend({
people: hasMany('person')
});
var Person = DS.Model.extend({
name: attr()
});
```
If you unloaded the person, it would not get removed from it's group.
We now properly clean the implicit relationships, so now the person gets
removed properly.

CLean up implicit relationships on record unload

---

packages/ember-data/lib/system/relationships/state/belongs_to.js
packages/ember-data/tests/integration/relationships/belongs_to_test.js

Improved the error message for ensuring belongsTo has proper relationship. 
This is for #2802

improve error message for belongsTo

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/unit/model_test.js

Without explicitly declaring `store` on a `DS.Model` instance,
[`setUnknownProperty`][unknown] will be invoked, breaking any
user-overridden behavior.
[unknown]: https://github.com/emberjs/ember.js/blob/c9af09524a191ba155d98de8b9bbabaf802245e2/packages/ember-runtime/lib/system/core_object.js#L157-L159

Declare `store` property on DS.Model

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/unit/model_test.js

Currently, the `store` property is "injected" into each model's record when it is created. This can potentially conflict with a `store` attribute on the model. (E.g. modeling a data set that includes Retailers and Stores.)
Attempting to subclass Model with a `store` attribute *will* produce an error, but it is not instructive as to what went wrong. I was helping a developer who is new to Ember and he was confused/misled by the existing error message:
```
Error while processing route: index Cannot use 'in' operator to search for 'store' in undefined TypeError: Cannot use 'in' operator to search for 'store' in undefined
at ember$data$lib$system$model$attributes$$getValue
```
I have implemented an assertion and test based on those for the also-protected `data` property. Any feedback on how …

Add assertion for `store` property on DS.Model subclasses

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/unit/store/model_for_test.js

`modelFor` is throwing an incorrect error when it cannot find a model. Corrects it.

Correct modelFor model not found errors

---

packages/ember-data/lib/initializers/store.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/application_test.js
packages/ember-data/tests/integration/setup-container-test.js

I propably want to add a test.
And also people want to feedback on this.
#2818

Register the store as a service

---

package.json

Without this change, Ember CLI 0.2.0 will have the following warning for
all ember-data + ember-cli users:
```
% ember s
The package `ember-data` is not a properly formatted package, we have used a fallback lookup
to resolve it at `/some-path/goes/here/node_modules/ember-data`. This is generally caused by
an addon not having a `main` entry point (or `index.js`).
```

Add main entry point for package.json.

---

packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/unit/model/rollback_test.js

Fix #2126, #2169, #2708 
Defines the `root.deleted.invalid` state and its different events. 
Now  a record which has been invalidated during its `deletion` can be rollbacked on the same way that if it would receive an error response.

Fix: a record in state deleted.invalid can be rollbacked

---

packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/unit/model/lifecycle_callbacks_test.js

Now newly created and uncommited records will fire its livecycle events
when deleted.

Fire didDelete event/callback when in uncommited state

---

packages/ember-data/tests/integration/debug_adapter_test.js

Use different callbacks for watchRecords in order to make failures
easier to understand

Cleanup debug adapter test: Watching Records

---

packages/ember-data/lib/adapters/build_url_mixin.js
packages/ember-data/lib/adapters/rest_adapter.js
packages/ember-data/lib/main.js

This is my first step towards emberjs/rfcs#4.
The intent here is to separate url building from the RESTAdapter so that
it can eventually be included in other adapters and hold the logic for the
path template concept described in emberjs/rfcs#4.
Even though it's a fairly small change, I've written this pull request to:
1. Get my foot in the door. Since this is my first pull request to ember-data, I figure starting small is a good idea.
2. Make a place for the url-templates feature before starting a longer-lived branch. I think this will help prevent conflict management overhead as I work on the url-templates feature.

Move buildURL and related methods to a mixin

---

packages/ember-data/lib/system/relationships/state/has_many.js

In https://github.com/emberjs/data/pull/2576 we added a runloop inside ED,
in order to handle relationship deserializing and make sure we coalesce hasMany
/belongsTo changes. However in that PR we missed the findHasMany call, causing us
to trigger a flush(triggering an arrayWill/DidChange) once for every record being
parsed. This commit ensures we first process all the records together, and then call
flush only once. Was not sure how test this without a super specific unit test.
fixes #2856

Run findHasMany inside an ED runloop

---

Brocfile.js
package.json

fixes #2871, although I think that https://github.com/ember-cli/ember-cli-uglify/issues/4 has not actually been fixed.
cc @stefanpenner @ef4 @bmac

bump ember-cli to 2.0 & remove sourcemapping comments in production

---

packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/serializer.js
packages/ember-data/lib/transforms/base.js

Delete `Ember.required` (it is deprecated).

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/store-test.js
packages/ember-data/tests/unit/store/adapter-interop-test.js
packages/ember-data/tests/unit/store/has_record_for_id_test.js

This pr is built on top of #2659

Store.hasRecordForId should true only if a record for a given type and ID is already loaded.

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/unit/model-test.js

A better long term solution may be to move attributes off of the Model but for now this will give users a clear warning if they try to do something that will break Ember Data's assumptions about the model.
Closes #602 #2230 #2328

Assert if the user tries to redefine a reserved property name.

---

packages/ember-data/lib/initializers/store-injections.js
packages/ember-data/lib/initializers/store.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/lib/system/store/serializers.js
packages/ember-data/tests/integration/multiple_stores_test.js
packages/ember-data/tests/integration/relationships/belongs-to-test.js
packages/ember-data/tests/integration/setup-container-test.js
tests/ember-configuration.js

Adapters and Serializers are now store managed - with each store
instance holding a unique instance of each serializer and adapter. They
are no longer singletons.
This allows multiple stores to be used with ember-data.
rebased version of pr #2617

Adapters and Serializers are Store Managed

---

packages/ember-data/lib/system/snapshot.js

Method returns an object, not an array.
This will fix #2923

Fix doc for Snapshot.attributes()

---

packages/ember-data/tests/integration/store-test.js

`Using store.fetch() has been deprecated. Use store.fetchById for fetching individual records or store.fetchAll for collections`

Fix deprecation warning in store test

---

packages/ember-data/lib/main.js
packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/model/errors/invalid.js

Extracts InvalidError into a separate file and makes it a subclass of Ember.Error

---

packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/tests/integration/adapter/build-url-mixin-test.js
packages/ember-data/tests/integration/adapter/rest-adapter-test.js
packages/ember-data/tests/unit/adapters/build-url-mixin/path-for-type-test.js

This is another step toward emberjs/rfcs#4.
Others have requested ways to handle different urls per request type (see emberjs/data#1078).
Once url-templates lands, most users extending `BuildURLMixin` will not need to handle
`requestType` explicitly, as it will be possible to define a template for each request type.

Pass requestType to buildURL

---

packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/relationships/belongs-to-test.js
packages/ember-data/tests/integration/relationships/has-many-test.js

**This is a first stab at making relationships aware if data exists for the relationship or not.**
There's currently no way of knowing if the contents of a relationship is _unknown_, _empty_ or _set_ just by looking at a snapshot (which is what serializers must do). This PR lays the groundwork of having snapshots returning an _unknown_ state for calls to `.belongsTo()` and `.hasMany()` when we don't know the contents of the relationship yet.
_This should most likely be reviewed and thought through at least once before we merge it._

Introduce relationship.hasData

---

packages/ember-data/lib/system/model/model.js

This triggered an assert that readonly CPs are not allowed to have setters (old-style).

Remove value from retrieveFromCurrentState CP

---

lib/jscs-rules/require-spaces-after-closing-parenthesis-in-function-declaration.js
package.json
packages/ember-data/lib/system/many-array.js
packages/ember-data/lib/system/model/attributes.js
packages/ember-data/tests/integration/adapter/find-all-test.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js
packages/ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
packages/ember-data/tests/unit/model/merge-test.js

The jscs package was locked to 1.11.0 in #2945 due to failing builds. The build failed because `getTokenPosByRangeStart()` was removed in 1.12.0.
This PR implements the same changes as https://github.com/emberjs/ember.js/pull/10747 and unlocks the version of jscs in package.json.

Fix JSCS rule and unlock v1.11.0

---

packages/ember-data/lib/system/adapter.js

Since the beta 16, the serialize method of adapter base class receives a snapshot, not a record. It should not use record._createSnapshot anymore.

adapter.serialize receives a snapshot

---

packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/tests/unit/adapters/build-url-mixin/path-for-type-test.js

handle empty values returned by pathForType in buildURL method of
the build url mixin.
refs emberjs/data#2844

Handle null/empty type paths in build url mixin

---

packages/ember-data/lib/system/model/attributes.js
packages/ember-data/lib/system/relationships/belongs-to.js
packages/ember-data/lib/utils/computed-polyfill.js
packages/ember-data/lib/utils/supports-computed-getter-setter.js

This fixes the ~3400 deprecation warnings `Using the same function as getter and setter is deprecated` for beta and canary builds.

Use new getter/setter for computed if available

---

packages/ember-data/lib/main.js

When `Ember.VERSION` contains some version suffix (such as '1.11.0.72d2409e'),
This check will reject this version of Ember unexpectedly.

Make version check for Ember.js strict

---

packages/ember-data/lib/system/model/errors.js
packages/ember-data/lib/system/model/model.js

Replaces  `{{#each ... in ...}}` syntax with block params style `{{#each ... as |...|}}`.

[DOC] Use block params style {{#each}}

---

packages/ember/lib/main.js

The reference to `self` is breaking FastBoot. 
The issue was outlined here: https://github.com/tildeio/ember-cli-fastboot/issues/11

Fix: remove self reference

---

packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/tests/integration/adapter/build-url-mixin-test.js

If you provide `namespace` as `/api/v1` it will end up using `//api/v1`.
As of this change, if `namespace` is absolute it will not prepend a slash.

Do not prepend a `/` if namespace is absolute.

---

packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/lib/adapters/rest-adapter.js

This provides separate abstract methods that can be used for different request types with better signatures. It also passes the `query` in from `findQuery`.
I still need to write tests for this, but I'm putting it up before I go to sleep.
PS: @wycats I still want to be able to pass query to `findAll` but I wasn't able to find a good way of doing that.

Break buildURL into multiple requestType methods

---

packages/ember-data/lib/system/relationships/state/belongs-to.js
packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/lib/system/snapshot.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/snapshot-test.js

This is the second part of solving the problem described in #2936.
Snapshots are now aware of unknown relationships and can return `undefined` from `belongsTo()` and `hasMany()` if that is the case.
~~Ping @igorT re: f67ab9c13cd4cf20deb494a85826aa2468636a28~~

Snapshots unknown relationships

---

packages/activemodel-adapter/lib/system/active-model-serializer.js
packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/tests/integration/serializers/embedded-records-mixin-test.js

This is my first attempted contribution to Ember Data, so if I'm approaching anything the wrong way, please let me know!
When extending the `DS.EmbeddedRecordsMixin`, if you configure a `belongsTo` relationship as `{ serialize: 'id', deserialize: 'records' }`, it won't actually pay attention to the `serialize: 'id'` option, but use the `deserialize: 'records'` option. This is because of [`serializeBelongsTo`](https://github.com/emberjs/data/blob/f1be2af71d7402d034bc034d9502733647cad295/packages/ember-data/lib/serializers/embedded_records_mixin.js#L194) and the reimplementation of [`keyForRelationship`](https://github.com/emberjs/data/blob/f1be2af71d7402d034bc034d9502733647cad295/packages/ember-data/lib/serializers/embedded_records_mixin.js#L126-L132), which notices the `deserialize` …

Embedded records mixin should use the correct serialization key when deserialize configuration is set, Fixes #2556

---

config/package-manager-files/package.json

Currently it's possible to install ember via jspm, now this adds jspm support to ember-data.

jspm support

---

packages/ember-data/lib/serializers/json-serializer.js

I believe that this is a mistake in the description, but I'm unfamiliar enough with Ember Data to be unsure. :)

Fix serialization results in the documentation.

---

packages/ember-data/tests/unit/adapters/build-url-mixin/path-for-type-test.js

Add tests for urlFor methods

---

packages/ember-data/lib/system/store.js

Original intent of the code is in commit 42d966e43f9ea13d94e61f62fa72b7b8ffe33178.
It was changed in fbabbda32cccf43d79782bbcaa3192fbeecaeb18.
If there is no adapterPayload, why set payload = adapterPayload? Just let it stay empty.

[refactor] Prune code that does nothing

---

packages/ember-data/lib/adapters/rest-adapter.js

This check is already done in [urlPrefix()](https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/ember-data/lib/adapters/build-url-mixin.js#L90-L95), no need to have it duplicated.

Remove unnecessary URL check in findHasMany

---

packages/activemodel-adapter/lib/system/active-model-adapter.js
packages/activemodel-adapter/lib/system/active-model-serializer.js
packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/lib/adapters/fixture-adapter.js
packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/system/debug/debug-adapter.js
packages/ember-data/lib/system/record-array-manager.js
packages/ember-data/lib/system/relationship-meta.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/serializer.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js

Before, we exchanged type and typeKey intermittently. Sometimes it
was one or the other. This changes most usages of `type` to
either `typeKey` or `typeClass` for internal consistency.
The API docs were also changed to reflect this.
The Store API docs have been changed to suggest using a string
for a future patchset where we don't take factories to the store
finder methods.

use typeKey and typeClass instead of using `type` inconsistently

---

packages/activemodel-adapter/lib/system/active-model-adapter.js
packages/activemodel-adapter/tests/integration/active-model-adapter-test.js

Fields are not currently camelized in the model's errors object e.g.
pilot.errors.first_name
should be
pilot.errors.firstName
There is already test for this behavior but because of the way `InvalidError` and `Ember.inspect` are implemented the test passes when it shouldn't do.
ActiveModelAdapter now passes the errors hash directly to `InvalidError` as is expected according to the docs. This assumes that the 422 provides JSON of the form
{
errors: {
first_name: ['is too long']
}
}
as is standard in active model. If `errors` is not present in the JSON response, active model adapter will continue to behave as it did before.

ActiveModelAdapter camelizes keys for errors on 422

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js

In `JSONSerializer`, both `keyForAttribute` and `keyForRelationship` get an extra undocumented parameter, `method` (which can be either `serialize` or `deserialize`). This PR adds the missing bits.
Also there was a call to `keyForAttribute` with a `method` argument missing — 'serialize` is now explicitly being passed there.

Add method argument to key serialization docs

---

CHANGELOG.md
packages/activemodel-adapter/lib/system/active-model-serializer.js
packages/activemodel-adapter/tests/integration/active-model-serializer-namespaced-modelname-test.js

[BUGFIX] AMS polymorphic type for namespaced models

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js

Custom key mappings defined in the `attrs` hash of the JSONSerializer
are now considered when extracting errors.

JSONSerializer#extractErrors respects custom key mappings

---

packages/activemodel-adapter/lib/system/active-model-adapter.js
packages/activemodel-adapter/tests/integration/active-model-adapter-test.js
packages/activemodel-adapter/tests/integration/active-model-serializer-test.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js

This addresses my comment made in https://github.com/emberjs/data/pull/3030#issuecomment-98396379, where I stated that the made changes of camelCase-ing the error keys are a serializer concern:
Since c947e25 (introduced in #3030) the keys of the error object are camelCased in the adapter, which is actually a serializer concern. The JSONSerializer, from which the ActiveModelSerializer extends, does a normalization of the errors object in the `extractErrors` hook (see http://git.io/vJ0A6 & http://git.io/vJ0AS) and this hook gets called by the store when the adapter rejects (see http://git.io/vJ0AI), the camelCase can be removed from inside the adapter.
cc @fivetanley @bdvholmes

Remove logic for camelCase-ing error keys in ActiveModelAdapter

---

packages/ember-data/lib/system/store/finders.js
packages/ember-data/tests/integration/records/load-test.js

`store.getById(typeClass, id)` is used inside the rejection handler of
`find` to get the record and invoke the corresponding hooks. This is
buggy since the record is not loaded yet into the store - a successful
`find` would mark it as such - and hence the `store.getById` returned
`null`. That's why the hooks are not called and the record stays in the
`loading` state, having the `isLoaded` flag still being set to `false`.
The fix is to reuse the `record` parameter, which is passed to the
`find` method. By this, the hooks are invoked and the record is passed
transitioned out of the `loading` state.
---
This partially addresses #3013

Fix bug where record rejected via `find` stayed in loading state

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js

This PR defines `attrs` as a `mergedProperty`, so it can be inherited from superclasses. This is useful if you have a polymorphic type and want to define a base serializer for common attributes.

Merge `attrs` from superclasses into their subclasses.

---

packages/ember-data/tests/integration/serializers/json-serializer-test.js

This adds assertions that defined keys of attributes in the superclass
can be overwritten by subclasses.
This adds more assertions for the merge-able `attrs` has introduced in #3055.

Add more assertions for merged attributes from superclass

---

packages/ember-data/lib/system/many-array.js
packages/ember-data/tests/integration/records/delete-record-test.js
packages/ember-data/tests/integration/relationships/has-many-test.js
packages/ember-data/tests/integration/relationships/many-to-many-test.js
packages/ember-data/tests/integration/relationships/one-to-many-test.js
packages/ember-data/tests/unit/model/rollback-test.js

Basically, if you delete the final object from a ManyArray elsewhere the following will happen:
* The ManyArray will report the correct length of 0.
* The ManyArray's `objectAt(0)` will still return a value.
The issue appears to be that the `currentState` is correctly empty, but the `canonicalState` still retains the deleted item. Because `objectAt` has a fallback, we incorrectly use the value from the `canonicalState`.

Fix for deleting from ManyArray

---

bin/changelog

Looks like a simple typo. It was pointing to the ember.js repo instead.
cc @fivetanley

Fix changelog script to point to emberjs/data

---

packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/unit/model-test.js

Added pushedData hook to root.deleted.uncommitted state.

---

packages/ember-data/lib/system/model/model.js

changed record `person` to match with `App.Mascot`.

[DOC] update typo on #changedAttributes

---

CHANGELOG.md
TRANSITION.md
packages/activemodel-adapter/lib/system/active-model-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/tests/integration/serializers/rest-serializer-test.js

Introduced in this commit is payloadKeyFromModelName, which allows you
to specify the outgoing root key for a model name in the JSON payload.
For example:
```javascript
RESTSerializer.extend({modelNameFromPayloadKey: underscore});
```
```json
{
"taco-party": { }
}
```
becomes
```json
{
"taco_party": {}
}
```
For symmetry, modelNameFromPayloadKey has been introduced to
look up the ember data record in the store given a JSON root
key. This used to be called pathForType, which has been deprecated.
Part of the refactor stuff covered in https://github.com/emberjs/data/pull/2821#issuecomment-79183508

introduce modelNameFromPayloadKey and deprecate typeForRoot

---

packages/activemodel-adapter/lib/system/active-model-adapter.js
packages/activemodel-adapter/tests/integration/active-model-adapter-serializer-test.js
packages/activemodel-adapter/tests/integration/active-model-adapter-test.js

This pull request reverts the changes in #3030, I'd overlooked the role AMS played in error handling and got distracted by some broken tests. Sorry guys.
Kudos to @pangratz for putting together an integration test to make sure the errors hash does indeed get passed through correctly and camelized as expected.
Fixes #3067, cc @fivetanley

Rely on active model serializer to handle error logic

---

packages/ember-data/lib/system/relationships/has-many.js
packages/ember-data/tests/integration/adapter/rest-adapter-test.js
packages/ember-data/tests/integration/relationships/has-many-test.js
packages/ember-data/tests/unit/store/create-record-test.js

allowing to pass an has many relationship on create record. Fixes #1497

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/system/relationship-meta.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/relationships/state/belongs-to.js
packages/ember-data/lib/system/relationships/state/create.js
packages/ember-data/lib/system/relationships/state/has-many.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/tests/integration/inverse-test.js
packages/ember-data/tests/integration/relationships/belongs-to-test.js
packages/ember-data/tests/integration/relationships/has-many-test.js
packages/ember-data/tests/unit/model/relationships-test.js
packages/ember-data/tests/unit/model/relationships/has-many-test.js

When using multiple stores with Ember Data, we want to avoid storing the
state on the factory itself. Because multiple stores currently share the
same factory, this means that the first store to look up the factory
will store itself as the `store` on that factory. That means that any
stores thereafter will receive factories whose `store` property
references the first store, not their own.

Remove store from factories

---

packages/ember-data/tests/integration/serializers/rest-serializer-test.js

Just a test name fix, but it is currently quite confusing given that `pathForType` hasn't been deprecated.

Deprecation test: pathForType -> typeForRoot

---

bin/bower-ember-data-build

From the Travis CI docs:
http://docs.travis-ci.com/user/ci-environment/
For builds not triggered by a pull request this is the name of the
branch currently being built; whereas for builds triggered by a pull
request this is the name of the branch targeted by the pull request (in
many cases this will be master).
This was building for branches not intended to be published because they
were opened as a pull request against master. As Ember Data core
contributors frequently work off the main repository this is an unwanted
side effect.

fix bower publishing

---

packages/ember-data/lib/system/model/model.js

Mention that new records are removed from store on rollback.

Update docs for rollback.

---

packages/ember-data/lib/serializers/rest-serializer.js

Message had still a reference to typeForRoot. I changed that to modelNameFromPayloadKey.

Fix warning message after typeForRoot renaming.

---

packages/ember-data/tests/integration/adapter/build-url-mixin-test.js
packages/ember-data/tests/integration/adapter/rest-adapter-test.js
packages/ember-data/tests/integration/store-test.js

This prevents the original hash provided to ajaxResponse to be modified between multiple adapter runs for the same payload.

Ember.copy() resolved value for ajaxResponse

---

packages/activemodel-adapter/lib/system/active-model-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js

```
warn: (docparser): replacing incorrect tag: returns with return:  packages/activemodel-adapter/lib/system/active-model-serializer.js:140
warn: (docparser): replacing incorrect tag: returns with return:  packages/ember-data/lib/serializers/rest-serializer.js:746
warn: (docparser): replacing incorrect tag: returns with return:  packages/ember-data/lib/serializers/rest-serializer.js:793
```

Fix docparser warnings, @returns => @return

---

packages/ember-data/lib/system/model/model.js

I came across three functions and was wondering what they were for. On closer inspection, they seem to be unused. Perhaps left over from pre-modern adapter/serializer refactors?

Cleanup unused 'materialize' records in model

---

packages/ember-data/lib/system/record-arrays/record-array.js

Was familiarizing myself with the record array manager while looking into the memory leak issue with filter. This condition looks like it can be removed now that `ManyArray` isn't a `RecordArray`, and all possible traffic through that method should be derived from `RecordArray` and therefore have a `manager`.

Cleanup unneeded if after  ManyArray refactor

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/snapshot.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/snapshot-test.js

alows us to have access to changed attributes in snapshot
cc @igorT @wecc

Create snapshots on save not on flush

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/tests/integration/serializers/embedded-records-mixin-test.js

Since the hashs of the polymorphic embedded records are normalized, the - possible - customized primaryKey can be accessed via the `id` property.
---
This addresses #2793.
cc @igorT

Custom primaryKey for embedded polymorphic relations work

---

packages/ember-data/lib/adapters/rest-adapter.js

Update documentation to recommend extended the adapter instead of reopening it.

Extend adapter instead of reopening it

---

packages/ember-data/lib/serializers/rest-serializer.js

The inline documentation is currently recommending `payloadKeyFromModelName` instead of `modelNameFromPayloadKey` which is actually used.

Fix doc for typeForRoot, should recommend modelNameFromPayloadKey.

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/tests/integration/serializers/embedded-records-mixin-test.js

Guard for embedded unknown hasMany relationship

---

packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/unit/model/rollback-test.js

Previously rolling back a new record which has been marked as invalid by
the adapter left the record in the `loaded.created.uncommitted` state.
---
This addresses the issues raised in https://github.com/emberjs/data/pull/2943#discussion_r30555588:
> rolling back a new record which is marked as invalid puts the record in the loaded.created.uncommitted state. Is this the intended behavior? There are currently no tests for this case in [`rollback-test.js`](https://github.com/emberjs/data/blob/master/packages/ember-data/tests/unit/model/rollback-test.js) so it needs to be discussed what should be the intended behavior here.

A new record which is marked as invalid can be rollbacked

---

packages/ember-data/lib/system/record-array-manager.js
packages/ember-data/lib/system/record-arrays/record-array.js

Remove deprecated push record

---

packages/ember-data/tests/unit/model-test.js

Fixes #3159 
Add a test to ensure that an error is thrown when calling `.create()` on a model directly

Add test for error on model.create()

---

packages/ember-data/lib/system/snapshot.js
packages/ember-data/tests/integration/snapshot-test.js

Even though we remove records from their opposite relationships once they are deleted, this commit places this functionality under test and ensures that only non deleted records are returned from snapshot.belongsTo() and snapshot.hasMany().
Closes #3081

Ensure snapshot.belongsTo() and hasMany() do not return deleted records

---

packages/ember-data/tests/integration/snapshot-test.js

* snapshot.attr()
* snapshot.belongsTo()
* snapshot.hasMany()
fixes #3157

add tests for error conditions in snapshot methods

---

packages/ember-data/lib/system/snapshot.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/snapshot-test.js

add Snapshot#serialize method

---

bower.json
packages/ember-data/lib/ember-initializer.js
packages/ember-data/lib/initializers/store-injections.js
packages/ember-data/lib/initializers/store.js
packages/ember-data/lib/instance-initializers/initialize-store-service.js
packages/ember-data/lib/setup-container.js
packages/ember-data/tests/integration/application-test.js
packages/ember-data/tests/integration/backwards-compat/non-dasherized-lookups.js
packages/ember-data/tests/integration/debug-adapter-test.js
packages/ember-data/tests/integration/multiple_stores_test.js
packages/ember-data/tests/integration/setup-container-test.js

This simplifes the process of registering the store when a user
creates a custom one.  This change also fixes deprecations warning
introduces in Ember 1.12. The store service is now injected as a
instanceInitializer.

Lookup the store using store:application instead of store:main

---

packages/ember-data/lib/ember-initializer.js

Fixes Ember Data canary with version of Ember 1.11 or lower. Credit goes to @fivetanley for reporting this issue.

initialize lives on the application instance not the Ember namespace

---

.travis.yml
package.json

The production build is already built at the start of the build due to
the `prepublish` hooks that runs after `npm install`.

stop rebuilding production after successful test runs

---

packages/ember-data/lib/system/record-array-manager.js
packages/ember-data/lib/system/record-arrays/record-array.js

closes https://github.com/emberjs/data/issues/3165
I didn't go further on the record array manager, in order to minimize conflicts with https://github.com/emberjs/data/pull/3167
cc/ @igorT

rename add/removeRecord to add/removeInternalModel in record array

---

packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/relationships/belongs-to.js
packages/ember-data/lib/system/relationships/has-many.js
packages/ember-data/lib/system/relationships/state/create.js
packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/lib/system/snapshot.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/inverse-test.js
packages/ember-data/tests/integration/relationships/belongs-to-test.js
packages/ember-data/tests/integration/relationships/has-many-test.js
packages/ember-data/tests/integration/relationships/inverse-relationships-test.js

This is a rebase of https://github.com/emberjs/data/pull/2741 by @andrewfan.
I've also added a separate commit, that uses the getter in the code that was added after the original PR.
~~Currently 2 of the new tests are failing~~ fixed, thanks to @igorT!

[REBASE] Model relationships getter

---

Brocfile.js
packages/ember-data/tests/integration/snapshot-test.js
packages/ember-data/tests/unit/adapter-populated-record-array-test.js
packages/ember-data/tests/unit/adapters/rest-adapter/ajax-test.js
packages/ember-data/tests/unit/record-arrays/filtered-record-array-test.js

It was getting the babel transpiled output, which made it pretty much
impossible to see where the actual lint warnings were coming from. Now, we pass the original source files.

fix jshint line numbers

---

packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/container-instance-cache.js
packages/ember-data/tests/helpers/custom-adapter.js
packages/ember-data/tests/integration/filter-test.js
packages/ember-data/tests/unit/store/adapter-interop-test.js
packages/ember-data/tests/unit/store/lookup-test.js
tests/ember-configuration.js

In this commit, we refactor store managed instance lookups to have its
own class that takes the store's container. This moves a large portion
of code out of the store and instead uses delegation.
There's also a performance benefit:
If you look up `adapter:post` and fallback to `adapter:application`,
this lookup is cached. So, if you look up `adapter:post` again, that
instance will actually be cached. Previously, we did the lookup for
`adapter:post` every time.
This also removes passing factories as the `adapter` property to
DS.Store.
closes #3050

refactor store managed instances

---

packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js

Fixes #3101
@igorT Let me know if I can remove the deprecation warning (it seems to me that people may override groupsForHasMany and use this property, like in the test)
@pangratz When this is merged, you will have to rebase your PR #3099 :sweat_smile:

maxUrlLength -> maxURLLength

---

packages/ember-data/lib/system/debug/debug-adapter.js
packages/ember-data/tests/integration/debug-adapter-test.js

Related to https://github.com/emberjs/ember.js/pull/11346

Use string model names in debug adapter

---

README.md
packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/many-array.js
packages/ember-data/lib/system/model/attributes.js
packages/ember-data/lib/system/model/errors.js
packages/ember-data/lib/system/model/errors/invalid.js
packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/relationships/belongs-to.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/relationships/has-many.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/transforms/base.js
packages/ember-data/lib/transforms/boolean.js
packages/ember-data/lib/transforms/date.js
packages/ember-data/lib/transforms/number.js
packages/ember-data/lib/transforms/string.js

I'm adjusting the samples to match the [blueprints](https://github.com/ember-cli/ember-cli/tree/master/blueprints) of the `ember-cli` tool as discussed in #3139.
Closes #3155

Adjust code samples to ember-cli

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/store-test.js
packages/ember-data/tests/unit/store/adapter-interop-test.js

- Adds `store.findByRecord()`
- Deprecates `store.findById()`
closes #3228

Add findByRecord and deprecate findById

---

packages/ember-data/lib/system/record-array-manager.js
packages/ember-data/lib/system/record-arrays/record-array.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/record-array-manager-test.js

This addresses #2542 
---
I haven't squashed the commits so the changes are more comprehensible. If this is accepted, I will squash em all!

store.all() is not treated as a filteredRecordArray anymore

---

packages/ember-data/lib/system/record-array-manager.js

`Map.prototype.remove` is deprecated and causes:
```
DEPRECATION: Calling `Map.prototype.remove` has been deprecated, please use `Map.prototype.delete` instead.
```
https://github.com/emberjs/ember.js/commit/39bf8b23a8482eb9fffeda00d8beb914c3b8c444

Use Map.prototype.delete instead of Map.prototype.remove

---

packages/ember-data/lib/serializers/rest-serializer.js

Found two more instances of https://github.com/emberjs/data/issues/3231
This brings the deprecations that come up when running the tests from 70 to 3 :smiley:

Always use dasherized modelName to fetch serializer

---

packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/tests/integration/adapter/queries-test.js
packages/ember-data/tests/integration/adapter/rest-adapter-test.js
packages/ember-data/tests/integration/adapter/store-adapter-test.js
packages/ember-data/tests/integration/store-test.js
packages/ember-data/tests/unit/record-array-test.js
packages/ember-data/tests/unit/store/adapter-interop-test.js

rename store.findQuery to store.query

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/store-test.js
packages/ember-data/tests/unit/store/adapter-interop-test.js

fixes #3228
- renames `store.findByRecord` to `store.findRecord`
- makes `store.findRecord` public

Rename store.findByRecord to store.findRecord

---

packages/ember-data/lib/system/coerce-id.js
packages/ember-data/tests/integration/client-id-generation-test.js

Treats empty strings in ids the same as null or undefined.
---
This is the rebased version of #2352

Treat empty strings in ids the same as null or undefined

---

README.md
TRANSITION.md
packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/adapter/find-all-test.js
packages/ember-data/tests/integration/adapter/find-test.js
packages/ember-data/tests/integration/store-test.js

closes https://github.com/emberjs/data/issues/3227

Make store.findAll(type) public

---

packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/unit/model-test.js

Pass _internalModel into a record when it is created

---

packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/tests/integration/records/property-changes-test.js
packages/ember-data/tests/unit/store/push-test.js

This is a rebased and cleaned version of https://github.com/emberjs/data/pull/2998.
Closes #2937.
Closes #2900.
Closes #2998.

Record property changes

---

packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/system/model/attributes.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/store.js

https://github.com/emberjs/ember.js/blob/master/STYLEGUIDE.md#objects
I think it's important, especially in the docs/examples, to provide consistency.

Pad single-line objects with white-space

---

packages/ember-data/lib/system/clone-null.js
packages/ember-data/lib/system/many-array.js
packages/ember-data/lib/system/record-arrays/adapter-populated-record-array.js
packages/ember-data/lib/system/relationships/state/has-many.js
packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/tests/integration/relationships/has-many-test.js

Happy birthday @wecc 
Copied commit message:
Rebased #2878 and added a test from #2996
Added metadata support behind a feature flag, for hasMany relationships.
For now, until we refactor the internals, the store internally pushes hasMany
metadata around in the `meta` key next to `links` and `data`.
This might lead to overriding meta attribtues with meta relationships,
but will be solved by the upcoming change of the internals to JSONAPI format

Metadata for hasmany

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/tests/integration/serializers/embedded-records-mixin-test.js

Pass store to inverseFor in removeEmbeddedForeignKey

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js

Fixes #3189 
Apologize in advance for my frenglished documentation
cc/ @igorT

serialize:true takes priority over the OneToMany check for relationships

---

packages/ember-data/lib/system/relationships/belongs-to.js
packages/ember-data/tests/unit/model/relationships/belongs-to-test.js

Display a warning when the user specifies ```serialize``` or ```embedded``` in the options for ```belongsTo```. These settings belong in the serializer now, I have linked to the relevant documentation pages in order to help the user to do what they meant to do. Resolves #3187.

Warnings for incorrect options in belongsTo, resolves #3187

---

packages/ember-data/tests/integration/relationships/belongs-to-test.js

Looks like this relationship isn't used in any test though ...

Fix relationship being named `belongsTo` instead of `book`

---

packages/ember-data/lib/initializers/store-injections.js
packages/ember-data/lib/initializers/store.js
packages/ember-data/lib/instance-initializers/initialize-store-service.js
packages/ember-data/lib/main.js
packages/ember-data/tests/integration/application-test.js
packages/ember-data/tests/integration/backwards-compat/non-dasherized-lookups.js
packages/ember-data/tests/integration/debug-adapter-test.js
packages/ember-data/tests/integration/multiple_stores_test.js
packages/ember-data/tests/integration/setup-container-test.js

This pr undoes the `store:application` change added in https://github.com/emberjs/data/pull/3136.

Support custom stores defined on the container as

---

packages/ember-data/lib/system/relationships/state/belongs-to.js
packages/ember-data/lib/system/relationships/state/has-many.js
packages/ember-data/lib/utils.js
packages/ember-data/tests/integration/relationships/belongs-to-test.js
packages/ember-data/tests/integration/relationships/has-many-test.js
packages/ember-data/tests/integration/relationships/polymorphic-mixins-belongs-to-test.js
packages/ember-data/tests/integration/relationships/polymorphic-mixins-has-many-test.js
packages/ember-data/tests/unit/utils-test.js

Currently the logic to check if a record can be added to a (polymorphic) relationship has been duplicated in two places: within [`belongs-to relationship state](http://git.io/vIHxH) and [`has-many relationship state](http://git.io/vIHxh).
This PR extracts the functionality into a `assertPolymorphicType` function, so it can be reused elsewhere. Currently, also the assertion messages are slightly different; by using the same function they are the same for both calls.
---
Caveats: (currently) only the `Ember.assert` within the `assertPolymorphicType` function is stripped for production builds, so a little noise is left. Is this something we can ignore?

Extract polymorphic check

---

packages/ember-data/lib/ember-initializer.js
packages/ember-data/lib/initializers/store-injections.js
packages/ember-data/lib/initializers/store.js
packages/ember-data/lib/instance-initializers/initialize-store-service.js
packages/ember-data/tests/integration/application-test.js
packages/ember-data/tests/integration/backwards-compat/non-dasherized-lookups.js
packages/ember-data/tests/integration/debug-adapter-test.js
packages/ember-data/tests/integration/multiple_stores_test.js
packages/ember-data/tests/integration/setup-container-test.js

Right now Ember Data supports 3 namespaces where you can define the store `store:main`, `store:application` and `service:store`. I want to reduce this to 1 place for Ember Data 2.0 because it simplifies our initializer code and if a user were to define a custom store for more then 1 of those namespaces it can result in multiple stores instances in their app which is confusing to debug.
I'd like to recommend defining a custom store as `service:store` (`app/services/store.js`) as the path going forward. Is this a good idea/bad idea?
I would also like to see this pr become a beta-19.2 patch release to help people upgrading who currently have a custom store defined in `app/store.js`. Let me know what you think about this change?

Deprecate `store:application` and `store:main` in favor of `service:store` 

---

packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/snapshot-record-array.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/tests/integration/adapter/store-adapter-test.js

This pr also introduces a `SnapshotRecordArray` object to pass snapshots, adapterOptions and meta into the adapter findAll.

Allow the store to pass adapter options to the adapter

---

packages/ember-data/lib/system/record-arrays/record-array.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/store-test.js

This pr is build on top of pr #3310 and it is intended to be merged after that one is merged.

Deprecate fetch and replace it with store.findRecord(type, id, { reload: true})

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/unit/store/push-test.js

This fixes #3246 
Deprecates store.pushMany in favor of store.push

Deprecate store.pushMany in favor of store.push

---

packages/ember-data/lib/system/model/errors.js

`Ember.reduceComputed` has been deprecated in emberjs/ember.js#11403. Once this is merged, #3327 can be closed.

Refactor `Errors#errorsByAttributeName` to not use Ember.reduceComputed

---

packages/ember-data/lib/system/store.js

Deprecation if id is Model in deserializeRecordId

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/tests/integration/store/query-record-test.js

The findQueryOne method let developers query their server-side API for a single record and also pass a query parameter to this call.
For instance, you could do the following:
```javascript
this.store.findQueryOne('post', 1, { include: 'comments' });
```

Add queryOne method

---

packages/ember-data/lib/system/record-array-manager.js

The `else if (!shouldBeInArray)` has been replaced with a simple `else`
in during cleanup in b9044fd978c2ff4fc6e6acda1800c57e59351454.
This addresses https://github.com/emberjs/data/pull/3302#discussion_r32233897.

Clear else branch of RecordArrayManager#filter

---

packages/ember-data/lib/utils.js

`warn: (docparser): Missing item type:  packages\ember-data\lib\utils.js:3`

Fix docparser warning

---

packages/ember-data/lib/adapters.js
packages/ember-data/lib/adapters/json-api-adapter.js
packages/ember-data/lib/initializers/store.js
packages/ember-data/lib/main.js
packages/ember-data/lib/serializers.js
packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/tests/integration/adapter/json-api-adapter-test.js
packages/ember-data/tests/integration/serializers/json-api-serializer-test.js
packages/ember-data/tests/unit/adapters/json-api-adapter/ajax-test.js
tests/ember-configuration.js

A basic working JSON-API adapter.

Implement basic JSON-API adapter

---

packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/record-arrays/record-array.js
packages/ember-data/lib/system/snapshot-record-array.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/tests/unit/store/adapter-interop-test.js

This pr implements `shouldReloadRecord` and `shouldBackgroundReloadRecord` hooks from https://github.com/emberjs/rfcs/pull/61.
It is built on top of the changes made in pr https://github.com/emberjs/data/pull/3312

Implement adapter reload hooks from RFC #61

---

packages/ember-data/lib/adapters/fixture-adapter.js
packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/system/many-array.js
packages/ember-data/lib/system/model/errors.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/record-array-manager.js
packages/ember-data/lib/system/relationships/state/has-many.js
packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/lib/system/store/serializer-response.js
packages/ember-data/tests/integration/filter-test.js
packages/ember-data/tests/integration/serializers/embedded-records-mixin-test.js
packages/ember-data/tests/unit/store/push-test.js

Ember.EnumerableUtils is deprecated. Ember.ArrayPollyfills is
private. They are both going away in Ember 2.0 but
Ember.ArrayPollyfills doesn't introduce console noise in user's code
cc @fivetanley @igorT 
@igorT this would just be for the 1.13 release as I've seen a bunch of confusion in slack about Ember deprecation warnings originating from Ember Data's use of `EnumerableUtils`.

Replace Ember.EnumerableUtils with Ember.ArrayPollyfills.

---

packages/ember-data/tests/unit/store/lookup-test.js
tests/ember-configuration.js

This change removes about 2000 deprecation warnings from the console when the tests are run.

Do not register DS.ActiveModelAdapter for all tests.

---

tests/index.html

since it is no longer a dependency of ember and is not installed by bower.

Remove handlebars from the test file 

---

tests/index.html

This is a followup cleanup to #3356, which removes no more needed Handlebars.js in `tests/index.html` (see https://github.com/emberjs/data/pull/3356#issuecomment-112247792).

Don't include Handlebars in the tests

---

packages/ember-data/lib/system/record-array-manager.js

This fixes a deprecation warning that was introduces in https://github.com/emberjs/data/pull/3354

Use MapWithDefault forEach instead of Array#forEach

---

packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/tests/integration/adapter/rest-adapter-test.js

fix jquery error handler

---

packages/ember-data/lib/main.js

Currently, the following assignment is ignored.
``` js
DS.ActiveModelAdapter = null;
Ember.typeOf(DS.ActiveModelAdapter); //=> 'class'
```
To fix this issue, `set` function is required for `Ember.defineProperty`.
Should this commit be backport to 1.13.x release?

Allow overwrite for deprecated adapters

---

packages/ember-data/lib/serializers/json-api-serializer.js
tests/ember-configuration.js

Using the `JSONAPISerializer` didn't make it opt in to the new Serializer API. This PR makes `JSONAPISerializer` always use the new Serializer API.

JSONAPISerializer only supports the new Serializer API

---

packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/tests/integration/serializers/rest-serializer-new-test.js

serializer that does not use the new format.

Assert if the RESTSerializers when using the new format calls another

---

packages/activemodel-adapter/lib/system/active-model-serializer.js

This is planned cleanup due to Ember.String functions now works properly with namespaced modelNames, see  emberjs/ember.js#10980

AMS modelNameFromPayloadKey and serializePolymorphicType cleanup

---

packages/ember-data/lib/system/store.js

When I pushed up the deprecation for the `store.pushMany` function, I missed adding the deprecation in the comments (and thus the documentation).
This just adds that deprecation to the documents. I'm assuming it's just the `@deprecation` line that will fix this.

[DOC] Deprecate store.pushMany in documentation

---

packages/ember-data/lib/system/store.js

right now it will get swallowed as it will error out before it gets to the deprecation message which is confusing to users trying to consume the api
```
Assertion Failed: You must include an `id` for author in an object passed to `push` 
```
http://emberjs.jsbin.com/hiludosuza/1/edit?html,js,console,output

make sure deprecate error doesnt get swallowed when using store.push(type, data)

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/system/record-arrays/adapter-populated-record-array.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/serializer-response.js
packages/ember-data/tests/integration/adapter/rest-adapter-new-test.js

We forgot to deprecate `store.metadataFor` and `store.setMetadataFor` when releasing 1.13. We also failed to keep backwards compatibility with metadata for users that are preparing for 2.0 and switches over to the new Serializer API.
This PR fixes that regression and correctly deprecates `store.metadataFor` and `store.setMetadataFor`.
Fixes #3391

[REGRESSION release] Make meta available with new Serializer API

---

packages/ember-data/lib/system/adapter.js

Fix minor typos in the documentation comments for `DS.Adapter`:
* "chached" -> "cached"
* "form" -> "from"

Fix Typos in Documentation for DS.Adapter

---

packages/ember-data/lib/system/store/serializer-response.js

Because of `Ember.isArray({ length: 1 }) => true`.
`Array.isArray()` used in master is not affected by this.
Fixes #3387

[BUGFIX release] Use typeOf instead of isArray in _normalizeSerializerPayload

---

packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/tests/integration/serializers/json-api-serializer-test.js

[BUGFIX release] JSONAPISerializer missing pushPayload

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/adapter/rest-adapter-new-test.js

Before the new Serializer API the serializers pushed sideloaded records to the store. Now sideloaded records are returned in `included` and it's the store's responsibility to push them.
Fixes #3406

[BUGFIX release] Sideloaded records are not pushed when saving

---

Brocfile.js
package.json
packages/ember-data/lib/system/model/attributes.js
packages/ember-data/lib/system/relationships/belongs-to.js
packages/ember-data/lib/system/relationships/has-many.js

Since v1.13.0 we use Ember.js-v1.13.0, so this addon is no more needed
since the new computed property syntax is supported out of the box with
this Ember.js version.

[CLEANUP] Remove ember-new-computed dependency

---

packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/integration/records/unload-test.js
packages/ember-data/tests/unit/model-test.js
packages/ember-data/tests/unit/model/rollback-attributes-test.js
packages/ember-data/tests/unit/store/metadata-for-test.js

Since Ember.create and Ember.keys have been deprecated, ember-data has become the cause of quite a few deprecation warnings in the console.

[CLEANUP beta] Use Object.keys/Object.create instead of Ember.keys/Ember.create

---

packages/ember-data/tests/integration/adapter/json-api-adapter-test.js
packages/ember-data/tests/integration/application-test.js
packages/ember-data/tests/integration/debug-adapter-test.js
packages/ember-data/tests/unit/store/adapter-interop-test.js
tests/index.html

I kept each commit separately to see which deprecations are fixed how. If this is :+1:, I will squash them and prefix with `[CLEANUP beta]`.

Fix deprecation warnings

---

packages/ember-data/tests/integration/filter-test.js
packages/ember-data/tests/integration/relationships/belongs-to-test.js
packages/ember-data/tests/integration/relationships/many-to-many-test.js
packages/ember-data/tests/integration/relationships/one-to-many-test.js
packages/ember-data/tests/integration/relationships/one-to-one-test.js

This PR will break some tests, but now the the calls to store.push are
using jsonApiFormat

Convert unload test to json api format for `store.push`.. #3223

---

packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/tests/integration/adapter/json-api-adapter-test.js

[BUGFIX release] handle case where linked relationship data is null

---

packages/ember-data/lib/initializers/store.js
packages/ember-data/tests/integration/application-test.js

The following change remove the need of the `service:store` registration after the `store` initializer like:
```
import ApplicationStore from 'app/data/store';
export default {
name: 'setup-store',
after: ['store'],
initialize: function(registry, application) {
registry.register('service:store', ApplicationStore);
}
};
```
Now, the `service:store` could be registered either before or after the store initializer.

[BUGFIX release] Do not register the service store when it has already been registered

---

packages/ember-data/lib/system/adapter.js

The online documentation is incorrect for `Adapter#shouldReloadRecord` and missing for `Adapter#shouldReloadAll `. I expect this should fix that. Bonus typo fixes included.

Fix documentation typos in Adapter

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js

I've duplicated the `Ember.deprecate` calls for `normalizePayload` to prevent the deprecation from being silent when users override `normalizePayload` and don't call super. The example in the docs doesn't even call super.
`RESTSerializer` does not override `normalizePayload`, that's why it's comparing with `JSONSerializer.prototype.normalizePayload `.
Closes #3428

Deprecate normalizePayload and normalizeHash

---

packages/ember-data/lib/system/model/model.js

Before this commit, the property would should up as not having a name
in the docs.

[DOC] Fill @property of DS.Model.modelName

---

packages/ember-data/lib/adapters/errors.js
packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/system/clone-null.js
packages/ember-data/lib/system/merge.js
packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/model/states.js
packages/ember-data/lib/system/object-polyfills.js
packages/ember-data/lib/system/ordered-set.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/relationships/state/belongs-to.js
packages/ember-data/lib/system/relationships/state/create.js
packages/ember-data/lib/system/relationships/state/has-many.js
packages/ember-data/lib/system/snapshot.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/container-instance-cache.js
packages/ember-data/lib/system/store/serializer-response.js
packages/ember-data/tests/integration/adapter/rest-adapter-test.js
packages/ember-data/tests/integration/records/unload-test.js
packages/ember-data/tests/unit/model-test.js
packages/ember-data/tests/unit/model/rollback-attributes-test.js
packages/ember-data/tests/unit/store/metadata-for-test.js
tests/index.html

Closes #3465
cc/ @bmac @stefanpenner

[BUGFIX release] Remove deprecation warning for dev, keep IE 8 compat

---

packages/ember-data/lib/serializers/json-serializer.js

A fix for a small typo found when working on #3477

[DOC release] Fix typo in JSONSerializer.extractAttributes docs

---

packages/ember-data/lib/adapters/errors.js
packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/tests/integration/adapter/rest-adapter-test.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js
packages/ember-data/tests/unit/adapter-errors-test.js

Fixes #3494.
The [current implementation](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/errors.js#L145) reads the `details` property on JSON API errors.
[The JSON API spec](http://jsonapi.org/format/#error-objects) mentions a field named `detail`, which error objects "MAY" contain.
This PR changes all instances to be `detail`.

Use `detail` instead of `details` for JSON API error objects

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/lib/serializers/json-serializer.js
tests/ember-configuration.js

Looks like our tests were injecting a `store` property into the serializers, this does not happen in a real app.

[BUGFIX release] There is no `store` property on a serializer

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js

This makes it a little bit easier to track down issues where serializers collaborates and are using different versions (old/new) of the Serializer API.
Closes #3424

Assert serializers are using the same API

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/lib/serializers/json-serializer.js
tests/ember-configuration.js

Reverts emberjs/data#3506
Looks like I was wrong and a `store` property gets set by `retrieveManagedInstance` https://github.com/bmac/data/blob/18a3c3a356995d1d8f95f02152185699cd99063b/packages/ember-data/lib/system/store.js#L2078

Revert "[BUGFIX release] There is no `store` property on a serializer"

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/unit/store/push-test.js

When pushing data with an unknown type, an error is raised.
Fix #3542

Add error message in _pushInternalMessage when unknown type

---

CHANGELOG.md
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js

Respect an underlying JSON-API payload's `included` property.
Prior to this, records extracted via `EmbeddedRecordsMixin` were being truncated and forgotten.
See #3549

Fix JSONSerializer to pass through `payload.included`

---

packages/ember-data/lib/adapters/errors.js
packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/integration/adapter/store-adapter-test.js

Rename error attribute

---

packages/ember-data/lib/system/store.js

Added a use case for `Store.find()`.
It was unclear in the documentation that you could pass an object as the second parameter of the `Store.find()` that is translated to query parameters.

[DOC release] Update store.js, additionnal doc

---

packages/ember-data/lib/adapters/errors.js
packages/ember-data/tests/unit/adapter-errors-test.js

"pointer: a JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute]."
Closes #3557

[BUGFIX release] Follow JSON-API error object spec

---

packages/activemodel-adapter/lib/system/active-model-adapter.js
packages/activemodel-adapter/lib/system/active-model-serializer.js
packages/activemodel-adapter/tests/integration/active-model-adapter-serializer-test.js
packages/activemodel-adapter/tests/integration/active-model-adapter-test.js
packages/activemodel-adapter/tests/integration/active-model-serializer-namespaced-model-name-new-test.js
packages/activemodel-adapter/tests/integration/active-model-serializer-namespaced-model-name-test.js
packages/activemodel-adapter/tests/integration/active-model-serializer-new-test.js
packages/activemodel-adapter/tests/integration/active-model-serializer-test.js

This brings the ActiveModelAdapter in ember data up to date with
the changes in the ActiveModel repository, as of commit
6e846e74f919e8b4c47450a855963f06329a7bdc, about 1.13.4.

[BUGFIX release] backport ActiveModelAdapter changes

---

packages/ember-data/lib/system/model/errors.js
packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/unit/model/rollback-attributes-test.js

[BUGFIX release] Transition to loaded.saved state after rollback

---

packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/tests/integration/adapter/rest-adapter-test.js

I just added the queryRecord to the RESTAdapter, it still needs more tests (coming soon)

Add queryRecord method to the RESTAdapter

---

packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/lib/adapters/errors.js
packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/initializers/store.js
packages/ember-data/lib/main.js
packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/container-proxy.js
packages/ember-data/lib/system/many-array.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/relationships/belongs-to.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/relationships/has-many.js
packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/lib/system/snapshot.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/container-instance-cache.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/lib/system/store/serializer-response.js
packages/ember-data/lib/system/store/serializers.js

fixes https://github.com/emberjs/data/issues/3568 for release branch
Related: https://github.com/emberjs/data/pull/3570

[BUGFIX release] Update `Ember.deprecate` and `Ember.warn` calls to include required information

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/unit/model-test.js

@bmac as discussed, here is the deprecation for `error` property

Deprecate error property

---

packages/ember-data/lib/system/adapter.js
packages/ember-data/tests/integration/adapter/find-test.js
packages/ember-data/tests/integration/adapter/record-persistence-test.js
packages/ember-data/tests/integration/adapter/rest-adapter-test.js
packages/ember-data/tests/integration/adapter/store-adapter-test.js
packages/ember-data/tests/integration/debug-adapter-test.js
packages/ember-data/tests/integration/filter-test.js
packages/ember-data/tests/integration/multiple_stores_test.js
packages/ember-data/tests/integration/records/reload-test.js
packages/ember-data/tests/integration/records/unload-test.js
packages/ember-data/tests/integration/relationships/belongs-to-test.js
packages/ember-data/tests/integration/relationships/has-many-test.js
packages/ember-data/tests/integration/store-test.js
packages/ember-data/tests/integration/store/query-record-test.js
packages/ember-data/tests/unit/model-test.js
packages/ember-data/tests/unit/model/relationships/belongs-to-test.js
packages/ember-data/tests/unit/model/relationships/has-many-test.js
packages/ember-data/tests/unit/model/relationships/record-array-test.js
packages/ember-data/tests/unit/record-array-test.js
packages/ember-data/tests/unit/store/adapter-interop-test.js
packages/ember-data/tests/unit/store/push-test.js

This pr updates the `shouldReload*` flags to their default state for Ember Data 2.0. 
This pr is built on top of pr #3468 and assumes that will be merged first.

Update shouldReload* flags for 2.0

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/unit/model-test.js

[BUGFIX release] Fix unconsistent behavior in Model.changedAttributes

---

packages/ember-data/lib/adapters/errors.js
packages/ember-data/lib/main.js
packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/system/container-proxy.js
packages/ember-data/lib/system/relationships/belongs-to.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/lib/system/store.js

fixes https://github.com/emberjs/data/issues/3568

Update `Ember.deprecate` and `Ember.warn` calls to include required information

---

packages/ember-data/lib/serializers/json-api-serializer.js

Following the conversation on https://github.com/emberjs/data/issues/3455, this Pull Request adds some documentation for the JSONApiSerializer, and two of its methods *keyForAttribute* and *keyForRelationship*.
This documentation is heavily inspired in the existing documentation of the JSONSerializer, as suggested in the mentioned issue.
I hope it is meets what is expected. Let me know if you think it needs more work.

Adds some documentation for JSONApiSerializer

---

bin/changelog

This pr port's @rwjblue's work from https://github.com/emberjs/ember.js/pull/11732

Update bin/changelog to deal with cherry-picked commits

---

packages/ember-data/lib/system/store.js

`DS.Store#findQuery` [is mistakenly marked `@method query`](https://github.com/emberjs/data/blob/3d40f37767cc84e355033e3e89bf26dd1803d996/packages/ember-data/lib/system/store.js#L1136), so `DS.Store#query` is [improperly documented and marked as deprecated](http://emberjs.com/api/data/classes/DS.Store.html#method_query) in the API documentation.

`DS.Store#findQuery` overrides `DS.Store#query` docs

---

packages/ember-data/lib/system/store/serializer-response.js
packages/ember-data/tests/integration/store/json-api-validation-test.js

Fixes #3603 
JSON API documents returned by `normalizeResponse` now are validated in the following ways
Ensure that...
* the document is an object
* at least one of the following top-level keys exist in said object: data, meta, errors
* top-level keys "data" and "errors" are not both present 
* `data`, if present, is either null, an array or an object
* `errors`, if present, is an array
* `links`, if present, is an object
* `meta`, if present, is an object
* `include`, if present, is an array
* `jsonapi`, if present, is an object

[BUGFIX release] Validate JSON API docs returned by normalizeResponse

---

packages/ember-data/lib/system/adapter.js

- Uses ember-cli style modules
- Removes `id` param

[DOC release] Update misleading example for Adapter.queryRecord()

---

packages/ember-data/lib/system/record-arrays/record-array.js
packages/ember-data/tests/unit/record-array-test.js

This method takes the parameters `key` and an optional `value` and
returns an updating list of records of the `RecordArray`, which'
property value of `key` matches `value`.
---
This addresses #3171

Add `RecordArray#filterBy` which contains a live, filtered subset

---

package.json

Since we are using ember-cli to build ember-data we can take advantage of the work done in ember-cli-dependency-checker to ensure that the deps in `node_modules` and `bower_components` actually match what is specified in the `package.json`/`bower.json`.
With this added, running `ember` commands will error if matching versions are not found.
This will help prevent issues like #3635 in the future.

Add ember-cli-dependency-checker.

---

packages/ember-data/lib/system/adapter.js

[The docs tell us to override `query`][override-docs] so it should be public.
This was made private in a commit in 2013 (ec2e040a) by @rwjblue. Many of the other private methods in that commit are now public.
[override-docs]: https://github.com/emberjs/data/blob/v1.13.8/packages/ember-data/lib/system/adapter.js#L47

Adapter.query should be part of the public overrideable interface.

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/unit/many-array-test.js

Using `registry.resolve` is generally private API, and `container.lookupFactory` provides roughly the same result.
We still need the registry to actually register the model we create, so I added a small matrix inline (this was the only usage of accessing the registry off of `this.container` that I found in the codebase).

[BUGFIX beta] Fix usage of registry for 2.1.0+.

---

packages/ember-data/lib/initializers/store-injections.js
packages/ember-data/lib/initializers/store.js

This way Ember Data won't log deprecation warnings when https://github.com/emberjs/ember.js/pull/12157 lands in Ember.

[BUGFIX beta] Prefer the new injection methods.

---

bower.json
package.json
packages/activemodel-adapter/lib/system/active-model-serializer.js
packages/ember-data/lib/adapters/errors.js
packages/ember-data/lib/adapters/fixture-adapter.js
packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/ext/ember/array.js
packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/system/many-array.js
packages/ember-data/lib/system/model/errors.js
packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/record-array-manager.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/relationships/state/has-many.js
packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/finders.js
packages/ember-data/lib/system/store/serializer-response.js
packages/ember-data/tests/integration/filter-test.js
packages/ember-data/tests/integration/serializers/embedded-records-mixin-test.js
packages/ember-data/tests/unit/store/push-test.js
packages/ember/lib/main.js

There may be more, but this at-least makes my one app work correctly.
Goal:
------
to ease upgrade pain for people

Don’t crash \w Ember 2.0

---

packages/ember-data/lib/system/store.js

`app/stores/application.js` is deprecated in 1.13 and no longer supported in 2.0.

Update the location of the custom store in the API doc example

---

packages/ember-data/lib/system/model/errors.js

This is a workaround for https://github.com/emberjs/ember.js/pull/12218
This should fix the failing tests on canary.

Explicitly set length after setting a new content property

---

packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/system/clone-null.js
packages/ember-data/lib/system/empty-object.js
packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/model/states.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/relationships/state/create.js
packages/ember-data/lib/system/snapshot.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/container-instance-cache.js
packages/ember-data/tests/integration/store-test.js
packages/ember-data/tests/unit/model-test.js

We found these changes substantially improved loading of large datasets in our app.
This PR contains code from the following 2.1.0-beta1 PRs:
#3641 Improve InternalModel (2x - 3x faster)
#3649 Empty object

Backport empty-object performance improvements from 2.1.0-beta1

---

packages/ember-data/lib/initializers/store.js

In globals apps, calling `App.reset()` will cause these initializers to be ran multiple times for each `container` / `registry` instance.  This means that when `App.reset()` is called, `service:store` is already registered **AND** resolved, throwing the following error:
```
Cannot re-register: `service:store`, as it has already been resolved.
```
The fix is to `unregister` before `register`ing again.
Fixes https://github.com/emberjs/ember.js/issues/10310.
---
Please note, this is already a non-issue in 2.0.0 (aka release branch).  This PR is targeting the `release-1-13` branch (which was branched from the `v1.13.11` tag).

[BUGFIX release-1-13] Ensure that `service:store` is cleared before regsitering.

---

packages/ember-data/tests/integration/store-test.js

Started working on fixing https://github.com/emberjs/data/issues/3704 by trying to write a failing test but was not able to reproduce the issue.
Am I missing something?

Improve test coverage for store#findRecord()

---

packages/ember-data/lib/adapters/rest-adapter.js

This partially addresses some of the documentation requirements in emberjs/ember.js#12319
Specifically:
* Clarification that root keys can be pluralized regardless—Ember not being strict about this may help others understand whether they need to normalize a response.
* A further note that—if a HTTP server responds to a findRecord request for a specific ID (or other param) with more than one object in the array—Ember Data will only parse the object with the matching ID/param.
This is low hanging fruit but I wanted to test the appetite for small doc changes like this—I suspect I'll have a few as I work through some Go + Ember stuff!

[DOC beta] Update Object Root docs re: plurals

---

packages/ember-data/lib/adapters/json-api-adapter.js

update coalesceFindRequests doc for JSONAPIAdapter

---

packages/ember-data/lib/serializers/embedded-records-mixin.js

Small cleanup of extracting helper methods to make code more readable,
and potentially extendable (though keeping them private for now)

Break apart embedded serialize methods in EmbeddedRecordsMixin

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/tests/integration/serializers/embedded-records-mixin-test.js

We now refer to the serialized key as `serializedKey` to reduce confusion which
led to this bug

Fix embedded key serialization bug and refactor key serialization

---

packages/ember-data/lib/system/normalize-link.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/unit/store/push-test.js

This PR introduces a private helper called `_normalizeLinks` that accepts a string or an object and returns an normalized "links object", see http://jsonapi.org/format/#document-links
Currently this helper is only used in the store's `setupRelationships` but we should probably have links objects reach further down in ED in the future (store => relationship => adapter) to allow access to meta and additional information on the links object.
Fixes #3588

[BUGFIX beta] Support JSON API links object

---

packages/ember-data/lib/system/model/errors.js

Reverts emberjs/data#3711
The original issue has been fixed in Ember.

Revert "Explicitly set length after setting a new content property"

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js

`JSONSerializer.extractRelationships()` sets the undefined hasMany relationships in the
same way it was for the belongsTo relationships, i.e. to `null`.
I also enriched the corresponding test accordingly in order to cover the case.

[BUGFIX beta] JSONSerializer.extractRelationships() issue #3736

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js

`serializeHasMany()` omits unknown relationships of pushed record rather than
setting them to `undefined`.

[BUGFIX beta] Fix JSONSerializer.serializeHasMany() issue #3760

---

packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/tests/integration/serializers/rest-serializer-test.js

https://github.com/emberjs/data/pull/3725

Port pr #3725 to the release 2.0 branch

---

packages/ember-data/lib/system/store.js

This attempts to resolve #3687 and update other parts of store docs to mention JSONAPI move of ED. It's currently a massive WIP, but I'm open to all feedback.

[DOC release] Update documentation for store

---

packages/ember-data/lib/serializers/embedded-records-mixin.js

Attempts to close #2794 by removing falsy mention of `record` method for deserializing (was it even ever supported?). Some minor changes also, like missed dot and adding backticks when mentioning classes.

[DOC release] Update documentation for EmbeddedRecordsMixin.

---

packages/ember-data/lib/serializers/json-serializer.js

Currently, the [JSONSerializer override process docs](http://emberjs.com/api/data/classes/DS.JSONSerializer.html) are hard to follow because of the markdown formatting. This patch fixes the formatting for rendering.

Format lists in JSONSerializer docs for rendering

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/store-test.js
packages/ember-data/tests/unit/model-test.js

Attempt to close #2348. Do you think it is sufficient or should `Ember.Error` be thrown as @stefanpenner suggested [here](https://github.com/emberjs/data/pull/518#issuecomment-17819789)?

Trigger an assertion when calling `findRecord` with falsy (except 0) id

---

packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/tests/integration/serializers/rest-serializer-test.js

69dca0c fixed this for attributes named `type`, but the RESTSerializer
was still trying to deserialize relationships with that name as
polymorphic, which was causing errors for anyone having a domain
model called "Type".
cc @bttf @bmac

[BUGFIX] Do not deserialize when a relationship named `type` exists

---

packages/ember-data/tests/unit/store/create-record-test.js

In the refactor in #3033 the test for passing a camelCased model name
has been renamed due to deprecations to a dash-erized model name. This
introduced the exact same test.
---
The source code [in lines 60-91](http://git.io/vc5cq) and [the lines 93-125](http://git.io/vc5cY) are equal: https://www.diffchecker.com/xcehwtlm

[CLEANUP] Remove duplicate test for creating record

---

packages/ember-data/lib/system/snapshot.js

`Snapshot` is default export-ed already at the end of the file.

[CLEANUP] Remove duplicate `default export` in snapshot.js

---

packages/ember-data/tests/unit/model/rollback-attributes-test.js

Rejection is handled correctly without having to wrap it inside an call
on the run loop.

[CLEANUP] Remove unecessary wrap of rejection in run-loop

---

packages/ember-data/lib/system/empty-object.js

The back ported performance optimization of using EmptyObject uses
`Object.create`, which is not available in IE8. Hence `Ember.create` is
used, which shims this behavior for IE8 and uses `Object.create` when it
is available.
This closes #3791 
cc @bmac @stefanpenner

[BUGFIX] Restore IE8 compatibility by using Ember.create

---

packages/ember-data/lib/system/model/model.js

`Model#isDirty` has been removed in favor of `hasDirtyAttributes`, but
the docs for `DS.Model` still reference `isDirty`.
This closes #3823

[DOC] Remove reference to `isDirty` in DS.Model documentation

---

packages/ember-data/lib/serializers/json-api-serializer.js

It returns an `Object`, not a `String`. Added some descriptions as well.

Fix API docs for JSONAPISerializer.normalize

---

packages/ember-data/lib/system/adapter.js

Document the return value of DS.Adapter#updateRecord

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/utils.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js
packages/ember-data/tests/unit/utils-test.js

In #3726 a bug is reported, where an attribute or relationship named `type` of an embedded record is mistakenly normalized.
If this is accepted, it should likely be ported back to `1.13` as well I guess.

[BUGFIX] Attribute/relationship named "type" of embedded record is considered before normalization

---

packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/tests/integration/serializers/json-api-serializer-test.js

Fix for [3810](https://github.com/emberjs/data/issues/3810).
This applies `normalizeUsingDeclaredMapping` to both the `attributes` and `relationships` of the resource hash in `normalize`.

[BUGFIX beta] JSONAPI serializer not respecting 'attrs' hash

---

packages/ember-data/lib/adapters/rest-adapter.js

The [docs for DS.Adapter#findAll](https://github.com/emberjs/data/blob/4e79b27d48b71f8ad737471db706149164c4a27a/packages/ember-data/lib/system/adapter.js#L152) already include this and it is already being passed
[when DS.Store#findAll](https://github.com/emberjs/data/blob/8f83fbf27acdd642cb824e3286832acebdac0da1/packages/ember-data/lib/system/store/finders.js#L121) is used.

[DOC] Document snapshotRecordArray param passed to adapter.findAll

---

.jshintrc
packages/ember-data/lib/system/model/attributes.js
packages/ember-data/tests/unit/model-test.js

They often do not work how a user expects.
Closes #3766

Deprecate complex objects as an attributes `defaultValue`.

---

packages/ember-data/lib/system/model/states.js

This flag moved out of the state machine in d5de4e1.

[DOC] remove documentation for `isError` in states

---

packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/integration/records/save-test.js

[BUGFIX beta] Correctly handle invalid errors without payload or pointer

---

packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/unit/model/rollback-attributes-test.js

A rollback of dirty attributes didn't work correctly when a model is
saved more than 1 time and the save fails. The issue is that the `exit`
handler on the invalid state - which is called when the model is saved
again and it is transitioned into the inFlight state - clears the
`_inFlightAttributes` which unfortunately wipes all the data needed to
rollback attributes.
The exit handler has been implemented in the course of #1755, but the
reported issue in that PR seems to be fixed ever since elsewhere in the
code base, since the added test back test still is green.
---
This depends on ~~#3856~~ #3859 and closes #3677.

[BUGFIX beta] rollbackAttributes() works after multiple failed saves

---

packages/ember-data/lib/adapters/rest-adapter.js

Remove conditional statement that is always true

---

packages/ember-data/lib/system/relationships/has-many.js
packages/ember-data/tests/unit/model/relationships/has-many-test.js

Assert that passed array to set a hasMany consists of records

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/tests/integration/serializers/rest-serializer-test.js

This change adds the correct extraction of a polymorphic belongsTo
specified in the payload in the following form:
``` js
{
id: 123,
// ...
message: 1,
messageType: 'post'
}
```
where the model is specified as:
``` js
DS.Model.extend({
message: DS.belongsTo('message', { polymorphic: true })
})
```
---
If this gets accepted, this should likely be ported back to `1.13` as well.
This closes #3806

[BUGFIX] extract polymorphic belongsTo in RESTSerializer

---

packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/system/relationship-meta.js

Instead of importing from the path ember data should import from `ember-inflector` to use the default instance.
related issues: #3887, #3881

[BUGFIX release] import from ember-inflector to use the default instance

---

packages/ember-data/lib/system/store.js

Some simple suggestions of refactoring to squeeze out a little extra performance when calling `store#push`. In our application this shows ~50ms improvement for slower devices on medium-sized payloads. Changes are as follows:
- Don't call `coerceId` in `_load` since it gets called in `_internalModelForId`
- Use `Ember.isArray` instead of `Ember.typeOf`
- Use `for-loop`s instead of `Array.prototype` methods

 [perf] minor adjustments to `store#push` flow

---

packages/ember-data/lib/system/empty-object.js

Fall back to Ember.create if Object.create is missing.
Fixes the deprecation coming back..

Don't use Ember.create by default

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js
packages/ember-data/tests/integration/store-test.js

Closes #3790
cc @wecc could review this pr?

Allow store.push to accept { data: null }

---

blueprints/model/index.js

It is not currently possible to generate a model with a relationship named differently from the model's name ([despite the help indicating it should be](https://github.com/emberjs/data/blob/addonified/blueprints/model/HELP.md))
This patch brings the code's behavior in line with the docs.
I've also filed ember-cli/ember-cli#4986 as a hold-over until ember-cli/ember-cli#4909 lands
(not sure how closely you monitor ED PRs, so cc: @stefanpenner )

fix model relationship name generation

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/tests/integration/serializers/embedded-records-mixin-test.js

This fixes the issue where the `serializePolymorphicType` hook on the
serializer hasn't been invoked when an embedded, polymorphic belongsTo
relationship is serialized.
---
This fixes #3871.

[BACKPORT] [BUGFIX beta] serialize type for embedded, polymorphic belongsTo

---

.codeclimate.yml

Now activemodel-adapter is removed from core package.

Cleanup `.codeclimate.yml`

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/container-instance-cache.js
packages/ember-data/lib/utils.js
packages/ember-data/tests/unit/model/internal-model-test.js
packages/ember-data/tests/unit/store/model-for-test.js
packages/ember-data/tests/unit/store/serializer-for-test.js
tests/ember-configuration.js

Ember 2.3 will include `Ember.getOwner` and `Ember.setOwner` as public API's to access various registry and container features. As of Ember 2.3, using `this.container` in any instance looked up from the container will issue a deprecation (instructing the user to use `Ember.getOwner(this)` instead).
This PR fixes all deprecations against ember#canary channel by adding a simplified polyfill so that the internal code can always operate with the `Ember.getOwner` API.

Use public API for container/registry when possible.

---

packages/ember-data/lib/system/adapter.js

Since the other primary methods for override (findRecord, createRecord,
findAll, etc) in the abstract class have null implementations, it makes
sense to me to have this for findMany as well.

Add null implementation of findMany in DS.Adapter

---

packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/unit/store/push-test.js

If an attribute is changed locally and data is pushed to the store which
matches the changed attribute, then this changed attribute is considered
as confirmed and is no more considered as dirty.
---
This addresses #3265

Reset changed attributes when matching data is pushed

---

packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/tests/integration/serializers/embedded-records-mixin-test.js

This fixes the issue where the `serializePolymorphicType` hook on the
serializer hasn't been invoked when an embedded, polymorphic belongsTo
relationship is serialized.
---
This issue has been reported in #3871 (though for ember-data `v1.13.8`).

[BUGFIX beta] serialize type for embedded, polymorphic belongsTo

---

packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/tests/integration/serializers/json-api-serializer-test.js
packages/ember-data/tests/integration/serializers/json-serializer-test.js
packages/ember-data/tests/integration/serializers/rest-serializer-test.js

The JSONAPISerializer expects
```
attrs: {
'first-name': 'firstname'
}
```
The PR fixes that and now both (dasherized and camelized) work
```
attrs: {
'first-name': 'firstname',
lastName: 'lastname'
}
```
It also fixes #3879 but it breaks a [test](https://github.com/emberjs/data/blob/master/packages/ember-data/tests/integration/serializers/rest-serializer-test.js#L390). I wonder if the test is intentional because it declares a relationship mapping that uses `keyForAttribute` to normalize it. I added a test for an attribute but I'm worried to remove the (wrong) test.
I added two comments where I would add a deprecation if the `attrs` key includes a dash.
@wecc @bmac can you review?

[BUGFIX release] Normalize attrs keys

---

packages/ember-data/lib/adapters/errors.js
packages/ember-data/tests/unit/adapter-errors-test.js

Should fix https://github.com/emberjs/data/issues/3602. As per the JSON API spec object level errors should be placed in an object with pointer `/data`.
I have chosen to put object level data into errors.base, but this could be anything. If anyone is already using base in the form `pointer: '/data/attributes/base` then the object level ones are combined with this.
This is my first ever open source pull request so I fully expect to have missed other things I need to do or improve the code's style.

[BUGFIX beta] Correctly handle object level errors in json api

---

.travis.yml
package.json

The globals only build in production mode, so we change travis to build
that after success.
fixes components/ember-data#31

restore globals publishing to canary build

---

tests/integration/adapter/find-all-test.js

* Use ES6 `() =>` where applicable
* Remove unnecessary `Ember.` and `Ember.RSVP` prefixes
* Remove ignored closure parameters
* One-line adapater overrides when possible

[CLEANUP] Clean up adapter/find-all-test.js

---

addon/serializers/json-serializer.js

JSONSerializer#normalizeId seems to be unused, `extractId`/`coerceId` are used instead.
@wagenet is this something that can be just removed or needs a deprecation?
closes #3917

Remove JSONSerializer#normalizeId

---

addon/system/store/finders.js
tests/integration/adapter/find-all-test.js
tests/integration/adapter/find-test.js
tests/integration/store/json-api-validation-test.js

Currently, [Store._find][find] only asserts that the `adapterPayload` is
non-null (i.e. `{}` is a valid payload).
This commit forces the `adapterPayload` to be non-empty.
When TDDing with Mirage, `adapterPayload` is often `{}`, which sneaks
through the asserts and ends up as a non-descriptive:
```
Assertion Failed: You must include an 'id' for undefined in an object
passed to 'push'
```
Which is triggered in [Store._pushInternalModel][_pushInternalModel],
which is a few method invocations away from the source of the issue.
[_pushInternalModel]: https://github.com/emberjs/data/blob/f1ccad8ab9356dd51f44d63585c27d8bb4ec9c3a/packages/ember-data/lib/system/store.js#L1709
[find]: https://github.com/emberjs/data/blob/f1ccad8ab9356dd51f44d63585c27d8bb4ec9c3a/packages/ember-data/lib/system/store/fi …

`Store._find` asserts `adapterPayload` not empty

---

addon/serializers/json-api-serializer.js
tests/integration/serializers/json-api-serializer-test.js

Report better error when `type` is missing from a JSONApi response

---

addon/system/model/errors.js
addon/system/model/internal-model.js
addon/system/model/model.js
addon/system/model/states.js
tests/integration/records/save-test.js

Fixes issue #3851.  
Removes events from error class that was causing side effects.   I don't think the error class should be responsible for updating the model state.

fix transitioning into invalid state

---

addon/serializers/embedded-records-mixin.js

Reverts emberjs/data#3923
Seems to have broken the build. cc @locks

Revert "[DOC fix] Adds missing space before list"

---

addon/system/model/errors.js

For what I see, the `error` object is populated just when the status code is specifically `422`, and not for every code in the 400 family. I think it's worth having this information in the docs (as I spent some time trying to figure out why this was not working the way I was expecting).

[Doc] Specify the status code expected to populate the error object

---

addon/system/relationships/state/has-many.js
tests/integration/relationships/has-many-test.js

Fixes #2379 
cc/ @jcbvm @igorT

Directly reloading a hasMany with links should trigger only one request

---

addon/index.js
addon/serializers/embedded-records-mixin.js
addon/serializers/json-api-serializer.js
addon/serializers/json-serializer.js
addon/serializers/rest-serializer.js
addon/system/container-proxy.js
addon/system/many-array.js
addon/system/model/attributes.js
addon/system/model/errors.js
addon/system/model/internal-model.js
addon/system/model/model.js
addon/system/model/states.js
addon/system/promise-proxies.js
addon/system/relationships/belongs-to.js
addon/system/relationships/ext.js
addon/system/relationships/has-many.js
addon/system/relationships/state/belongs-to.js
addon/system/relationships/state/has-many.js
addon/system/relationships/state/relationship.js
addon/system/store.js
addon/system/store/finders.js
addon/system/store/serializer-response.js
addon/utils.js

By this, the calls to `assert`, `warn` etcetera are corectly stripped
when a new production build is created.
cc @fivetanley

[CLEANUP] use debug helpers from ember-data/debug

---

addon/system/relationships/ext.js

The variable was declared but never used in the documentation

Fix documentation to use "serializedHasManyName"

---

config/package-manager-files/bower.json
config/package-manager-files/component.json

From components/ember-data#33.
bower.json is missing the license field. If I'm not mistaken, Data uses the same license as Ember (MIT). https://github.com/components/ember/blob/master/bower.json#L3
Our automated external library requests service is blocking the import of Ember Data canary for this reason.
I've also positioned the license field in component.json to mirror that of Ember.

Add license field to bower.json

---

addon/adapters/rest-adapter.js
tests/integration/adapter/rest-adapter-test.js
tests/unit/adapters/rest-adapter/detailed-message-test.js

This is an initial PR to iterate on "friendly" (more detailed) error messages for Ember Data, as per [RFC101](https://github.com/emberjs/rfcs/pull/101)
(emberjs/rfcs#101)

Friendly Errors

---

.travis.yml
addon/features.js
config/environment.js
lib/enable-optional-features-via-url/index.js
lib/enable-optional-features-via-url/package.json
lib/javascripts.js
package.json
tests/test-helper.js

This re-enables testing feature flags and stripping disabled feature flags from production build (using [ember-cli/babel-plugin-feature-flags](https://github.com/ember-cli/babel-plugin-feature-flags)).
Feature flags are now possible within ember-data by using the following setup:
```js
import isEnabled from 'ember-data/features';
if (isEnabled("ds-my-feature")) {
// ...
}
```
The features need to be defined within `config/features.json`. Disabled feature flags are also stripped from production builds.
---
Running the tests with all optional feature flags enabled is possible via `ember test --environment=test-optional-features`. When the tests are run via `ember serve`, the optional feature flags can be enabled via a checkbox.
---
This addresses #3922.

Re-enable feature flags

---

addon/adapters/rest-adapter.js

_I might be missing something obvious, so feel free to close if this code was intended and I just missed the effect._
The conditional was checking if `error` was not an instance of `Error`, but it was initialized on the previous line, ensuring the conditional would always pass.

Remove extraneous conditional in ajax()

---

addon/-private/system/store.js

[internalModel.createSnapshot](https://github.com/HeroicEric/data/blob/use-create-snapshot-options/addon/-private/system/model/internal-model.js#L241-L250) already sets the `adapterOptions` on
the new snapshot the same way when `options` are provided.
Found this while working on https://github.com/emberjs/data/pull/3976 and figured that it would make sense to try to keep the logic for creating the snapshot in one place.

Rely on internalModel.createSnapshot to set adapterOptions

---

tests/integration/adapter/rest-adapter-test.js

- Replaces references to `find` with `findRecord`
- Replaces references to `create` with `createRecord`
- Replaces references to `update` with `updateRecord`
- Replaces references to `delete` with `deleteRecord`

Update adapter function references in test

---

FEATURES.md
addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/references.js
addon/-private/system/references/belongs-to.js
addon/-private/system/references/has-many.js
addon/-private/system/references/record.js
addon/-private/system/references/reference.js
addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/store.js
config/features.json
tests/integration/references/belongs-to-test.js
tests/integration/references/has-many-test.js
tests/integration/references/record-test.js
tests/integration/relationships/belongs-to-test.js
tests/unit/model-test.js

[Link to RFC](https://github.com/emberjs/rfcs/pull/57)

Implement RFC 57 - Reference Unification

---

FEATURES.md
addon/-private/adapters/rest-adapter.js
addon/-private/system/model/internal-model.js
addon/-private/system/record-arrays/record-array.js
addon/-private/system/snapshot-record-array.js
addon/-private/system/snapshot.js
config/features.json
tests/integration/adapter/rest-adapter-test.js
tests/integration/adapter/store-adapter-test.js
tests/unit/adapters/rest-adapter/ajax-test.js
tests/unit/adapters/rest-adapter/build-query-test.js

Related RFC: https://github.com/emberjs/rfcs/pull/99
These changes allow an `include` parameter to be specified when using
`store.findRecord` and `store.findAll`:
```javascript
store.findRecord('post', 123, { include: 'comments' });
store.findAll('post', { include: 'comments' });
```
The value for `include` is copied onto the `DS.Snapshot` or
`DS.SnapshotRecordArray` that is passed to the corresponding adapter
function. This value is then pulled from the snapshot and used as a
query parameter (`include`) when making an AJAX request via
`adapter.ajax`.
1. ~~Is it OK that the `include` option is copied into `adapterOptions` or should it be copied into `adapterOptions.query`. I originally copied it into `adapterOptions.query` but the code was a little uglier so I went with just copying it …

Allow `include` query parameter with store.findRecord & store.findAll

---

.travis.yml
bin/publish-builds

If I am not mistaken, it looks like the builds are not published on S3...
The `bin/publish-builds` script is inspired by [the one in the Ember.js repo](https://github.com/emberjs/ember.js/blob/fbab176eb41727dc6a4718ee3dfdc6490706b3b2/bin/publish_builds).

Re-enable pushing builds to S3

---

package.json

This package is needed within [`bin/publish-to-s3.js`](https://github.com/emberjs/data/blob/7a23274db30325549e3c13967f431ddffd8f0771/bin/publish-to-s3.js#L17).
---
This is a followup to #4000. Sorry @bmac, I missed that dependency...

Add ember-publisher to package.json

---

addon/-private/serializers/embedded-records-mixin.js
addon/-private/serializers/json-api-serializer.js
addon/-private/serializers/json-serializer.js
addon/-private/system/model/errors.js
addon/-private/system/model/internal-model.js
addon/-private/system/relationships/ext.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/store.js
addon/-private/system/store/finders.js

We shouldn't use array methods as they allocate and close over items that need to be GC'd. Memory preasure can be an issue and we should do everything to reduce that preasure.

[PERF] Don't use array methods

---

config/s3ProjectConfig.js

The generated files via `ember build --env=production` are located
inside the `dist/globals` directory.
---
This is yet another follow up for #4000, but when I am reading [the corresponding code in `ember-publisher`](https://github.com/rondale-sc/ember-publisher/blob/8bff5417cf94fced70fb50705f88a9563c7befff/index.js#L75-L81) correctly, this should finally work so the files - which are located inside `dist/globals/` and not just `dist/` - are uploaded to S3.

Fix paths to files which should be uploaded to S3

---

addon/-private/system/model/internal-model.js

Otherwise YUIDoc complains that those methods don't have an item type:
```
> ember build --environment=production
version: 1.13.12
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Building
info: YUIDoc Starting from: /home/travis/build/emberjs/data/addon,/home/travis/build/emberjs/data/node_modules/ember-inflector
warn: Missing item type:  /home/travis/build/emberjs/data/addon/-private/system/model/internal-model.js:300
warn: 		Checks if the attributes which are considered as changed are still
different to the state which is acknowledged by the server.
This method is needed when data for the internal model is pushed and the
pushed data might acknowledge dirty attributes as confirmed.
warn: …
```

[DOC beta] Mark comments as private

---

addon/-private/system/references/record.js
tests/integration/references/record-test.js

Since those properties are functions on a BelongsToReference and a
HasManyReference, they are changed for the RecordReference as well.
This makes it consistent.

[FEATURE ds-references] More conistency for RecordReference

---

tests/integration/relationships/belongs-to-test.js

To stay consistent with the usage elsewhere

[CLEANUP] Use `isEnabled` instead of `Ember.FEATURES` directly

---

addon/-private/core.js
addon/-private/system/model/internal-model.js

- add `@method` to comment so is processed correctly by YUIDoc
- remove obsolete comments
- remove obsolete `.gitkeep`

[CLEANUP] Update and remove obsolete comments

---

tests/unit/model-test.js

The tests for `Model#belongsTo()` and `Model#hasMany()` throwing an
error have been accidentally removed when the `ds-references` feature
has been implemented. This commit brings those tests back, so they are
run when the feature is not enabled.

[FEATURE ds-references] bring back accidentally removed tests

---

tests/integration/adapter/rest-adapter-test.js

`adapter.ajax` is setup before the tests, so a made AJAX call can be
asserted by checking `passedUrl`, `passedVerb` and `passedHash`. This
commit cleans up the tests so the existig setup is re-used.

[CLEANUP] re-use test setup to assert correct call to adapter.ajax

---

addon/-private/serializers/embedded-records-mixin.js
addon/-private/serializers/json-api-serializer.js
addon/-private/system/model/errors.js
addon/-private/system/model/internal-model.js
addon/-private/system/record-array-manager.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/store.js
addon/-private/system/store/finders.js
lib/jscs-rules/disallow-space-before-semicolon.js

Caching length of arrays in for loops isn't necessary and don't bring any (perf) benefits.
Also mentioned here by stef:
https://github.com/emberjs/data/pull/3988#issuecomment-165272429
https://github.com/emberjs/data/pull/3988/files#r47439430

[CLEANUP] Don't cache length in for loops

---

tests/unit/record-array-test.js

This is no more needed since Ember.js v1.11.0

[CLEANUP] Remove special logic for meta.descs in tests

---

addon/-private/system/store.js

`this._containerCache` has was added in 31583db and removed from the store in ee97760.

[CLEANUP] remove obsolete code within Store#willDestroy

---

tests/unit/utils-test.js

Since ember-data is a proper addon now, the utility functions in
`ember-data/-private/utils` can now be imported and invoked within the
tests.
`assertPolymorphicType()` is now tested directly instead of relying on
it being used within `Model.get('relationship').add()`.
`modelHasAttributeOrRelationshipNamedType` hasn't been tested since it
couldn't be imported in the tests.

[CLEANUP] use methods from utils module directly

---

addon/-private/serializers/embedded-records-mixin.js
tests/integration/serializers/embedded-records-mixin-test.js

This PR is related to https://github.com/ember-data/active-model-adapter/issues/74 .
It makes more sense to use `keyForReliationship` for relationships insteed of `keyForAttribute`.

Use keyForReliationship for belongsTo and hasMany

---

addon/-private/system/record-array-manager.js
tests/integration/record-array-manager-test.js

Although the result from `store.query` is intended to never be re-used
as we delegate to the server for the truth of a query, the user still
needs an escape hatch to destroy these AdapterPopulatedRecordArrays
created by query in order to prevent excessive memory.
Before, calling `destroy` on an AdapterPopulatedRecordArray (the type
returned from store.query), the logic in
RecordArrayManager#unregisterRecordArray did not account for adapter
populated record arrays resulting in a leak.
This commit changes the logic to search for the array in the
RecordArrayManager's AdapterPopulatedRecordArray collection when
unregistering a record array.
Fixes #4041

[BUGFIX beta] prevent calls to store.query leaking

---

addon/-private/system/record-arrays/record-array.js
addon/-private/system/store.js
tests/unit/adapter-populated-record-array-test.js

This is an updated version of https://github.com/emberjs/data/pull/3086/ by @vinilios.
permit for adapter populated record array contents to be updated by
calling `update` method.
refs #3082
cc @wecc @igorT

[BUGFIX beta] Functional update for adapter populated record arrays

---

addon/-private/system/coerce-id.js
addon/-private/system/many-array.js
addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/store.js
addon/-private/system/store/finders.js
tests/integration/adapter/find-test.js
tests/integration/adapter/json-api-adapter-test.js
tests/integration/adapter/record-persistence-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/adapter/store-adapter-test.js
tests/integration/debug-adapter-test.js
tests/integration/relationships/belongs-to-test.js
tests/integration/relationships/has-many-test.js
tests/integration/store/json-api-validation-test.js
tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
tests/unit/model/relationships/belongs-to-test.js

`store.find` has been deprecated in `1.13` and been officially removed in the `2.x` series. This updates all references in the public documentation to use `store.findRecord`. Also some tests were still using `store.find` (which is still available since it is needed in the `model()` hook of Ember, but it is private now).

Replace calls to store.find with store.findRecord

---

bower.json

See: http://benlimmer.com/2016/01/08/ember-jquery-dependancies/

[BUGFIX beta] pin jquery to 1.11.3 to fix broken build

---

index.js
lib/babel-build.js
lib/javascripts.js
lib/stripped-build.js
package.json

Currently the code of the `ember-data` addon is added to the app. This is problematic since the code contains `assert`, `debug`, etcetera calls and also no feature flag code is stripped.
This PR is my stab at fixing this, so only the stripped code is added via the `treeForAddon` hook in `index.js`.
This addresses #4047 and takes inspiration from [@fivetanley's gist](https://gist.github.com/fivetanley/1708106ba3372b41dc94).
---

Strip stuff from addon before it is added to app

---

addon/-private/system/model/internal-model.js

Currently the `referenceFor` function is added to the InternalModel's
prototype, regardless if the ds-references feature is enabled or not.

[FEATURE ds-references] Only add function to prototype if enabled

---

addon/-private/system/container-proxy.js
addon/-private/system/debug/debug-adapter.js
addon/-private/system/model/internal-model.js

It looks like marking classes as `@private` is not enough to hide them
from showing up in the API doc at http://emberjs.com/api/data/.
This commit changes the used comments to start with `/*`, which are
definitely ignored by JSDoc.

[DOC beta] Hide private classes from YUIDoc

---

index.js
node-tests/nodetest-runner.js
package.json

fixes #4044
I disagree with @rwjblue that this should be a silent error. I've found this same kind of error to be nice to see which plugin is throwing an error where, in case I need to debug it or a file an issue about it.

[BUGFIX beta] fail builds in ember-cli when ember-cli-shims isn't met

---

FEATURES.md

The feature is implemented in 266d3b0 as `ds-finder-include`, see [`addon/adapters/rest.js#L990`](https://git.io/vzYmN).
@HeroicEric should the feature be named `ds-finder-include` or `ds-find-include`?

Update name for feature in FEATURES.md

---

index.js

The code that gets compiled for the globals build is in a closure with
its own instance of `loader.js`, so the entries for ember-data don't end
up in ember-cli's instance of `loader.js`. The ember-data code does
include shims that end up in the app's instance of loader.js, so we
exclude the app code from running in this case.

[BUGFIX release] don't load "app" code when loading globals files

---

lib/ember/data/source.rb

Currently, global builds are placed into `./dist/globals`.
Related to https://github.com/emberjs/data/issues/4069

[BUGFIX release] Fix bundled source path for gem

---

addon/-private/system/store.js

- `Ember` is imported below so we don’t need the global :smile:
- The `eqnull:true` rule was originally added for
https://github.com/emberjs/data/commit/beb2f26 but was later added to the `.jshintrc` in
https://github.com/emberjs/data/commit/caa2753

[cleanup] Remove unnecessary inline JSHint config

---

addon/-private/system/record-arrays/adapter-populated-record-array.js
addon/-private/system/store.js
addon/-private/system/store/finders.js
addon/-private/system/store/serializer-response.js
tests/unit/adapter-populated-record-array-test.js

The previous implementation of inserting metadata from an ajax response
onto a record array used the store as temporary storage for the metadata
via `store._metadataFor` and `store._setMetadataFor`. Although rare, this could
store the wrong value on the record array due to a race condition, as
the metadata was stored based on the query's model's name. This moves
the storing of metadata to `AdapterPopulatedRecordArray.loadRecords`
since, at the time that that method is called, the payload is present,
so we don't have to use `store.{_setMetadataFor,_metadataFor}`.
`store._metadataFor` was only used in
`AdapterPopulatedRecordArray.loadRecords`, so it is no longer needed
with this new implementation.

[CLEANUP beta] Change the way metadata in response is stored on record array

---

app/initializers/data-adapter.js
app/initializers/injectStore.js
app/initializers/store.js
app/initializers/transforms.js

This PR adds missing initializers to keep backwards compatibility.
Fixes #4087

[BUFGIX release] Fix regression with missing initializers

---

blueprints/adapter/index.js
blueprints/model/files/__root__/__path__/__name__.js
blueprints/model/index.js
blueprints/serializer/files/__root__/__path__/__name__.js
blueprints/transform/files/__root__/__path__/__name__.js
node-tests/blueprints/adapter-test.js
node-tests/blueprints/model-test.js
node-tests/blueprints/serializer-test.js
node-tests/blueprints/transform-test.js

This does two things:
- Adds more tests to the adapter & model blueprints
- Updates blueprints to import modules directly rather than access them through `DS`
I originally added the extra tests to cover the existing behavior before I changed it. If you'd rather have those split out into a separate PR LMK.
- Imports `JSONAPIAdapter` module directly in blueprint
- Imports `JSONAPISerializer` module directly in blueprint
- Imports `Transform` module directly in blueprint
- Imports `attr` module directly in model blueprints when needed
- Imports `belongsTo` and `hasMany` modules directly in blueprints when needed

Update blueprints to import modules directly

---

addon/adapters/rest.js

This fixes some misleading docs for `DS.RESTAdapter.findBelongsTo` that
make it seems like it expects a JSON array rather than a JSON object in
the response.

[DOC] Fix misleading docs for `DS.RESTAdapter.findBelongsTo`

---

addon/-private/system/store.js

Replaces a reference to `DS.Store.find` in the docs for
`DS.Store.filter`

[DOC] Replace reference to DS.Store.find

---

lib/calculate-version.js
lib/version-replace.js

The change of version number format may break version checking from other libs.
Before:
``` js
DS.VERSION //=> "v2.3.2"
```
After:
``` js
DS.VERSION //=> "2.3.2"
```

[BUGFIX release] Remove 'v' prefix from `DS.VERSION`

---

addon/-private/system/store.js

`DS.Store.filter` was deprecated and moved to an addon in https://github.com/emberjs/data/pull/3364. 
It has not been available without using the addon since https://github.com/emberjs/data/pull/3778/files.
The addon can be found at https://github.com/ember-data/ember-data-filter.

[DOC] Mark `DS.Store.filter` as private

---

tests/integration/relationships/belongs-to-test.js

As the comment in the code says, this is no longer needed since
https://github.com/emberjs/ember.js/pull/10323 was merged in.

[cleanup] Remove unneeded `getComputedPropertyDesc` test helper

---

addon/-private/adapters/build-url-mixin.js
tests/integration/adapter/build-url-mixin-test.js

Fixes https://github.com/emberjs/data/issues/4105
I couldn't think of a better name for the test   ¯\_(ツ)_/¯

[BUGFIX beta] Fix `BuildUrlMixin.urlPrefix` regression when host=/

---

addon/adapters/rest.js

Allow for overriding of the `ajax` request by overriding
`RESTAdapter.ajaxRequest` instead of the `RESTAdapter.ajax`, which
perform promise wrapping and Ember Data specific errors

[BUGFIX beta] Move `jQuery.ajax` call to a method separate method

---

CONTRIBUTING.md

This prefills the tags with `ember.js` and `ember-data`.

Add ember.js and ember-data tags automatically to SO question

---

CHANGELOG.md

This also removes the entries for *Release 2.1.0-beta.1 (August 20,
2015)*, as those are already tracked in *Release 2.1.0*.

[ci skip] Sort CHANGELOG by version and not date of release

---

addon/-private/system/store.js
tests/integration/adapter/queries-test.js

Currently invoking `store.query('person')` will fail with an error
within `RESTAdapter#sortQueryParams`, which is not helpful.
This adds the following assertions to store#query():
- a type is passed to the query method
- a query hash is passed to the query method
---
Those two assertions are available on `store#queryRecord` so this PR aligns `store#query` so it has the same assertions.

Add assertions for store#query()

---

FEATURES.md
addon/attr.js
addon/serializers/json.js
config/features.json
tests/integration/serializers/json-serializer-test.js

This feature passes the options hash defined for an attribute to the
`serialize` and `deserialize` methods of `DS.Transform`:
```js
// app/models/post.js
export default Model.extend({
text: DS.attr('text'),
otherText: DS.attr('text', {
lowercaseInput: true,
uppercaseOutput: true
})
});
// app/transforms/text.js
export default DS.Tranform.extend({
serialize(value, options) {
if (options.uppercaseOutput) {
return value.toUpperCase();
}
return value;
},
deserialize(value, options) {
if (options.lowercaseInput) {
return value.toLowerCase();
}
return value;
}
});
```
---
This implements emberjs/rfcs#1.

[FEATURE ds-transform-pass-options] pass options to DS.Transform

---

FEATURES.md
addon/-private/system/store.js
addon/serializers/json-api.js
addon/serializers/rest.js
config/features.json
tests/unit/store/push-test.js

Changing `store.pushPayload` and `serializer.pushPayload` to return the "pushed value". Either a record or array of records.
You can see by the diff, this is actually a pretty trivial change and it would greatly benefit those of us using `pushPayload`. The only risk of breakage is if someone has overridden `pushPayload` in their serializer, the value may not be returned.
Addresses: #3576

[FEATURE ds-pushpayload-return] Change `pushPayload` to return a value.

---

addon/-private/adapters/errors.js
addon/adapters/rest.js
tests/unit/adapter-errors-test.js

There are `instanceof` checks for `AdapterError`; this removes it in favor of checking for a property on the error. `isAdapterError` appears on all errors that use `AdapterError` as the base.
This PR is looking to avoid the need to import private errors in fastboot to keep the same code flow in the ajax method used in node land, related PR: https://github.com/tildeio/ember-cli-fastboot/pull/95

[BUGFIX beta] Add ducktyping of `AdapterError`

---

lib/calculate-version.js
package.json

When repository URL is specified for ember-data in `package.json`, `DS.VERSION` should have git sha as suffix.
```
"ember-data": "git@github.com:emberjs/data.git"
```
Before:
After:

[BUGFIX beta] Add sha suffix to `DS.VERSION` for unreleased version

---

package.json

`lodash.assign` might be unused.

[BUGFIX beta] Remove unused dev-dependency module

---

addon/-private/debug.js
addon/-private/system/references/belongs-to.js
addon/-private/system/references/has-many.js
addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/has-many.js
addon/-private/utils.js
lib/stripped-build.js
tests/unit/utils-test.js

This assert statement checks if a record is of the expected polymporhic
type. Currently, this function is located in -private/utils and it is
not stripped from production builds. Since this function only contains
an `assert` (which gets stripped correctly), having this function in a
production build is not a severe issue.
Stripping it in production makes sense though since hereby we can get
rid of superfluous calls and it minifies the build size :hammer:

[BUGFIX beta] strip assertPolymorphicType in production builds

---

addon/-private/system/model/errors.js

This documents behavior added in https://github.com/emberjs/data/pull/3909.

[DOC] Document behavior of object level errors with JSON API

---

addon/-private/serializers/embedded-records-mixin.js
tests/integration/serializers/embedded-records-mixin-test.js

Closes #4068. This implements the same semantics for `key` that are used in JSONSerializer.

Fix key remapping for embedded belongsTo

---

addon/-private/utils/parse-response-headers.js
addon/adapters/rest.js
tests/unit/utils/parse-response-headers-test.js

Fixes https://github.com/emberjs/data/issues/4122
- Allows header field-value without preceding whitespace
- Removes leading/trailing whitespace from header field-names
- Removes leading/trailing whitespace from header field-values
- Moves `parseResponseHeaders` function out of `DS.RestAdapter` to its own module
The main reason for moving to a module was to make it easier to unit test in order to document current behavior before making the fix. Let me know if this is undesirable.

[BUGFIX beta] Allow optional spaces when parsing response headers

---

addon/-private/system/relationships/has-many.js

The global require in this file causes an error when using babel 6 with the transform-es2015-modules-amd plugin
fixes #4134

import require

---

tests/helpers/owner.js
tests/helpers/store.js
tests/integration/references/has-many-test.js

Closes #4151
It seems like some code was forgotten during the addonization.
Thanks to @rwjblue pointing it to me.

remove container related deprecation warnings

---

addon/-private/system/store.js

The method is marked as deprecated internally, but not in the docs.

[DOC] Mark store.filter as deprecated in JSDoc.

---

tests/integration/adapter/build-url-mixin-test.js
tests/integration/adapter/record-persistence-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/debug-adapter-test.js
tests/integration/record-array-manager-test.js
tests/integration/records/collection-save-test.js
tests/integration/records/delete-record-test.js
tests/integration/records/error-test.js
tests/integration/records/load-test.js
tests/integration/records/property-changes-test.js
tests/integration/records/reload-test.js
tests/integration/records/save-test.js
tests/integration/records/unload-test.js
tests/integration/relationships/has-many-test.js
tests/integration/relationships/many-to-many-test.js
tests/integration/relationships/one-to-many-test.js
tests/integration/relationships/one-to-one-test.js
tests/integration/relationships/polymorphic-mixins-belongs-to-test.js
tests/integration/relationships/polymorphic-mixins-has-many-test.js
tests/integration/store-test.js
tests/unit/many-array-test.js
tests/unit/model/relationships/belongs-to-test.js
tests/unit/model/relationships/has-many-test.js
tests/unit/store/has-record-for-id-test.js
tests/unit/store/peek-record-test.js
tests/unit/store/push-test.js

My string theory: the definitions for `toString` are a relict from the
pre-container era where this might have been needed. :barber:
This makes the recently failing builds for `master` green again. :green_apple: 
---
Note: the tests were failing since `2.3.1` ember seals `Mixin` so adding stuff
after `create` will error out: emberjs/ember.js#12612.

[CLEANUP] remove `toString` definitions for models in tests

---

addon/-private/system/relationships/state/has-many.js
tests/integration/relationships/has-many-test.js

calling reload multiple times on a has many triggers only one request

---

.travis.yml

This PR changes the TravisCI builds back to their containerized infrastructure and installs PhantomJS v2.1.1 manually. This should significantly reduce the TravisCI startup times since their containerized infrastructure boots much faster and more instances are available.
see 8011a0484f483cad26d7c2a1c5ba2774a24d0488 for the commit that originally changed this

TravisCI: Use PhantomJS v2.1.1

---

.travis.yml

This PR simplifies the PhantomJS installation on TravisCI by using the `phantomjs-prebuilt` NPM package.

Simplify PhantomJS installation on TravisCI

---

addon/-private/system/store.js

Removes a shim for `Ember.Service`.
This isn't needed anymore since Ember 2.x.x all have `Ember.Service` available.

[CLEANUP] Remove shim for Ember.Service

---

addon/-private/system/store.js

This shim was added a long while back when we could not rely on the version of Backburner that Ember was using to have the `join()` function.
Any currently supported version of Ember (2.x) should have this now.
Similarly, any currently supported (2.x) version of Ember also has `Ember._Backburner` available.
Shim was added in:
https://github.com/emberjs/data/pull/2608
`Backburner.join()` was added in:
https://github.com/ebryn/backburner.js/pull/119

[CLEANUP] Remove shim for Backburner.join

---

packages/ember-data/tests/integration/serializers/json-api-serializer-test.js

Backports https://github.com/emberjs/data/pull/3847 as a test for https://github.com/ember-data/active-model-adapter/issues/46.

[BUGFIX release-1-13] JSONAPI serializer not respecting 'attrs' hash

---

blueprints/test-framework-detector.js

This PR is changing the test framework detector of the blueprints to use `project.dependencies()` instead of `project.addonPackages`. This has the advantage of not requiring the test framework to actually be installed and will enable us to test the mocha blueprints properly.
see https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/28 for further information on this
/cc @rwjblue @trabus

blueprints: Use project.dependencies() to determine test framework

---

appveyor.yml

As a `npm install ember-data` on Windows will result in files with the original line endings (`\n`) we should also test in that configuration instead of using native line endings.

AppVeyor: Use same line endings as original files

---

FEATURES.md
addon/serializers/embedded-records-mixin.js
config/features.json
tests/integration/serializers/embedded-records-mixin-test.js

It is better explained with an example.
Lets say that that you have an error that contains many attachable items 
(`attachables: DS.hasMany(‘attachable’, { polymorphic: true })`) and the serializer looks like this:
```
export default ActiveModelSerializer.extend(DS.EmbeddedRecordsMixin, {
attrs: {
attachables: {
serialize: 'ids',
deserialize: 'ids'
}
}
});
```
At the moment the serialized json contains `attachables: [1,2,3, ...]` but that is useless for polymorphic relationships, the serialized array should contain `{id, type}` tuples (`attachables: [{type: 'pdf', id: 1}, {type: 'xls', id: 1}]`)

[BUGFIX] EmbeddedRecordMixin should include the type serializing hasMany as ids

---

CONTRIBUTING.md
README.md

Visting `http://localhost:4200` displays the dummy app's "Welcome to Ember" screen. The tests reside at `/tests`

Elaborate on running tests in browser

---

addon/-private/system/store.js

The type is only used for the warning message.

Don't resolve model name unless actually needed

---

addon/-private/system/many-array.js
tests/integration/relationships/has-many-test.js

This slightly restructures and adds more comments to a test, which fixed
a tricky bug which occurred while updating the canonical state of a
hasMany relationship in combination with locally created records.

Restructure and elaborate on test which fixes a tricky bug

---

index.js

Avoid errors when ember-cli-shims is not included.

---

lib/babel-build.js
package.json

* share the same algorithm ember.js uses
* path.join defaults to path[platform].join which results in path.win32.join on windows and path.posix.join on everything else.

[BUGFIX release] ensure import paths are resolved \w posix separators

---

lib/babel-build.js

This fixes the module name resolution. Currently production builds do
not resolve correctly as the dependencies of modules are being resolved
like the following.
```
define('ember-data/-private/system/references',
['exports',
'-private/system/references/record',
'-private/system/references/belongs-to',
'-private/system/references/has-many'],
function (exports, _privateSystemReferencesRecord, _privateSystemReferencesBelongsTo, _privateSystemReferencesHasMany) {...});
```
The module names should get resolved now. Such babel config.

Fix AMD dependencies

---

addon/adapters/rest.js
tests/unit/adapters/rest-adapter/build-query-test.js

From the commit message:
```
Before introducing a feature ds-finder-include it was possible to run
findRecord on an adapter without passing a snapshot. After introducing
the feature it's no longer possible even if the feature is disabled,
because some of the code was outsief of the flag check.
This commit fixes the code to work like before introducing the
ds-finer-include change.
```
I'm not 100% sure if this is public behaviour of `findRecord`, but it will cause regressions for people that use it. In case it's not an issue, I can also submit a PR to have a more meaningful error (like "You need to pass a snapshot to `findRecord`").

Fix RESTAdapter.findRecord without a snapshot

---

addon/-private/system/store.js
tests/unit/store/push-test.js

- wrap code inside runInDebug so it is stripped from production
- update checks so they work correctly with passed payload, which is
actually a JSON-API document

Strip code for DS_WARN_ON_UNKNOWN_KEYS warning in production

---

addon/-private/system/many-array.js
tests/integration/relationships/has-many-test.js

Addresses #3084
This is the simplest-possible-patch I could find to get around a real pain point for unloading records. It looks like you guys are doing more fundamental work to address this but I wonder if we could put a fix like this in place as a stopgap.
If it’s needless and the real fix is about to land, I totally understand. If you think it is worthwhile I’ll flesh it out and add tests.

[BUGFIX release] Guard against isDestroyed in ManyArray.flushCanonical

---

addon/-private/system/relationships/state/create.js

If the model explicitly [turns off inverse](https://guides.emberjs.com/v2.4.0/models/relationships/#toc_explicit-inverses), no work should be done to resolve this inverse.

Don't do inverse work if inverse is explicitly turned off

---

index.js

This is useful for blueprint testing scenarios of other Ember.js addons, where ember-cli-shims might be mentioned in bower.json but is not actually installed just for the blueprint testing. Example: https://github.com/ember-cli/ember-cli-legacy-blueprints/pull/4
This PR resolves part of https://github.com/ember-cli/ember-cli-blueprint-test-helpers/issues/33 and continues #4200 
/cc @rwjblue @trabus @marcoow

Only show ember-cli-shims errors if actually installed

---

addon/-private/system/store.js

`store.findAll` directly returns the result of `store._fetchAll`, which appears to return a promise. However, `store.findAll` is currently documented as returning an `AdapterPopulatedRecordArray`.

[DOC] Fix store.findAll return type

---

addon/-private/system/store.js
tests/integration/adapter/queries-test.js
tests/integration/store/query-record-test.js
tests/unit/store/asserts-test.js

Fixes #4170.
Are you alright with generated tests like this?
I wasn't quite sure where to put these. `serializerFor`, `createRecord`, and a few others have their own test files, but many of these didn't really seem to have a home. It also seems a small shame to split these tests up when they're almost exactly the same.

DS.Store type presence checks

---

CONTRIBUTING.md

Addresses point 4 in Issue #4238

Add note on `testInDebug`

---

FEATURES.md
addon/-private/transforms/boolean.js
config/features.json
tests/unit/model-test.js
tests/unit/transform/boolean-test.js

*NOTE:* this description is not completely accurate anymore, since the implementation changed so the `allowNull` flag needs to be passed to the options for the attribute. See discussion below for further context.
---
This feature allows `null` / `undefined` values for `DS.attr('boolean')`
attributes. Currently `DS.BooleanTransform` converts those values to
`false`; which means that a `DS.attr('boolean')` cannot be set to `null`
from the server. Other transforms (`string`, `number`) do allow `null`
values, so this is an inconsistency between the transforms.
The new feature `ds-boolean-transform-allow-null` changes this behavior
so `null` / `undefined` are converted to `null`. Since **this is a semver
breaking change**, a corresponding deprecation warning should be added
before this is …

[FEATURE ds-boolean-transform-allow-null] allow null for boolean

---

config/package-manager-files/package.json

having ember in the dependencies forces a npm install of this repo to have a duplicate install of ember. If someone is installing ember/ember-data via the components shim library, their package.json will have to look something like this
```
"components-ember": "https://github.com/components/ember/archive/2.4.2.tar.gz",
"components-ember-data": "https://github.com/components/ember-data/archive/2.4.0.tar.gz",
"ember": "https://github.com/emberjs/ember.js/archive/v2.4.2.tar.gz"
```

moves the ember dep in the package-manager package.json into optionalDependencies

---

addon/serializers/rest.js
tests/integration/serializers/rest-serializer-test.js

The code checked for a model using the possibly-overridden `modelNameFromPayloadKey` but didn’t use the override when getting the serialiser and model.
The test is really only verifying the `store.modelFor(this.modelNameFromPayloadKey(hash.type));` change, not the serialiser one, since I didn’t see any tests for custom serialisers in this file. Let me know if I should make a test for that regardless.

Use modelNameFromPayloadKey when type is given

---

FEATURES.md
addon/adapters/json-api.js
addon/adapters/rest.js
config/features.json
tests/integration/adapter/build-url-mixin-test.js
tests/integration/adapter/json-api-adapter-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/store-test.js
tests/unit/adapters/rest-adapter/ajax-test.js
tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
tests/unit/model/rollback-attributes-test.js

Though `ajax()` (and `ajaxOptions()`) of `DS.RESTAdapter` are marked as
private, they have been overwritten in many applications, since there is
currently no other way to customize the request.
This feature adds new public methods to `DS.RESTAdapter`, which allow to
customize the properties of a request:
- `methodForRequest` to get the HTTP verb
- `urlForRequest` to get the URL
- `headersForRequest` to get the headers
- `dataForRequest` to get the data (query params or request body)
The `params` hash passed to those methods has all the properties with
which the corresponding `find`, `createRecord`, `findQuery`, ...  call
have been invoked: store, type, snapshot(s), id(s) and query. The
`requestType` property indicates which method is requested; the possible
values are:
- `createRecord`
- …

[FEATURE ds-improved-ajax] Finer control over customizing a request

---

addon/-private/system/store/finders.js
tests/integration/adapter/rest-adapter-test.js

The origial intent was for a queryRecord with no response to reject the promise so it would act like a `findRecord` with a 404. This change introduced a regression that broke existing apps so it is going to be reverted.
Closes #4219

[BUGFIX release] Revert pr #3864

---

tests/integration/relationships/inverse-relationships-test.js

Ensures that if `inverse: null`, `inverseFor` is not called.
Test for https://github.com/emberjs/data/pull/4225. Addresses https://github.com/emberjs/data/issues/4236.
cc @krisselden @stefanpenner @pangratz

Add test asserting no unnecessary inverse work

---

addon/serializers/rest.js

See #4186.
Also, the `normalize` method was calling super with three parameters while it only receives two: http://emberjs.com/api/data/classes/DS.JSONSerializer.html#method_normalize

Solves #4186 and fixes `this._super` call within `normalize` method.

---

tests/helpers/setup-ember-dev.js

I've been helping to "addonify"® [ember-data-model-fragments](https://github.com/lytics/ember-data-model-fragments) which also uses the `ember-dev` test suite. I noticed that `expectNoDeprecations` was no longer working as expected. After investigating I discovered that because Ember no longer uses `Ember.deprecate` internally, overriding that has little effect. I checked to see how ember-data's test suite handled this and discovered you have the same problem. See: [setup-ember-dev.js#L7-L13](https://github.com/emberjs/data/blob/master/tests/helpers/setup-ember-dev.js#L7-L13).
This PR fixes that issue by using `ember-metal/debug` proper hooks. This PR is meant to keep backwards compatibility and work with older versions of ember which did not offer these hooks. If the feeling is that …

Modified the setup-ember-dev test helper to use `ember-metal/debug`s override hooks

---

CONTRIBUTING.md

2 questions:
- Does ember data use feature flags in the same way as ember.js?
- I left "submit your PR against `emberjs:master`", since people's remote in their `data` repo may be named `emberjs`. I could also change it to `data:master`

[DOC] Add section on commit tagging to CONTRIBUTING.md

---

addon/-private/system/model/errors.js
addon/adapters/rest.js
addon/serializers/json.js

Recently I was looking at how to get errors to work, and found the docs slightly confusing. I decided to give it a go and see if I could improve them in some way. This is what I got so far.
Does this make sense? I probably can add some other details and make corrections, but I wanted to fly this past you before spending more time on it. I'm happy to take any feedback you may have.
I removed the example provided at `addon/-private/system/model/errors.js` because I feel it can lead to confusion making people think `DS.Errors` actually expects responses in a specific format.
I think the docs at `addon/adapters/rest.js` need to be more explicit at to what exactly it expects.
I think the JSON example belongs in `addon/serializers/json.js`, with details of what keys are actually used. The …

Tweaks to docs on error responses

---

addon/serializers/json.js

As brought up [here](https://github.com/emberjs/data/issues/3882) the documentation for `extractMeta` was referring to a method which does not exist anymore.

[DOC canary] Update extractMeta documentation

---

addon/-private/system/store/finders.js
tests/integration/adapter/find-all-test.js
tests/integration/adapter/find-test.js

As explained [here](https://github.com/emberjs/data/issues/4217) the current assertion messages for finders are outdated because they are still accessing `typeClass.typeClassKey` which has been removed. This PR updates those messages to use `typeClass.modelName` instead, and updates the tests to be more specific.

[BUGFIX canary] Improve finders assertion messages

---

addon/-private/system/references/belongs-to.js
tests/integration/references/belongs-to-test.js
tests/integration/references/has-many-test.js

The documentation states that `null` is returned for `Reference#value()`,
when it is not yet loaded. This commit fixes the bug where `undefined`
has been returned for `BelongsToReference#value()`.

[BUGFIX beta] Ensure `null` is returned for Reference#value()

---

addon/serializers/json.js

This attempts to fix #2289, see my comments there.

Speed up JSONSerializer#applyTransforms

---

bin/start
package.json

Running `npm start` (which originally ran `ember serve`) before running `npm install` and `bower install` was confusing. This introduces `bin/start` which checks if `node_modules` or `bower_components` exists before trying to run `ember serve`.

Uses bin/start with friendly error message for npm start.

---

FEATURES.md
addon/adapters/errors.js
addon/adapters/rest.js
addon/index.js
config/features.json
tests/integration/adapter/rest-adapter-test.js
tests/unit/adapter-errors-test.js

This is going to help with questions like #3493 or #3491

[FEATURE ds-extended-errors] Make adapter error extendable and add more error types

---

FEATURES.md
addon/adapters/errors.js
addon/adapters/rest.js
addon/index.js
tests/integration/adapter/rest-adapter-test.js
tests/unit/adapter-errors-test.js

This is to align with `ember-ajax`

[FEATURE ds-extended-errors] add DS.ServerError

---

addon/adapters/rest.js
bower.json
package.json
tests/integration/adapter/rest-adapter-test.js

When the server returns an empty string for a response which doesn't
indicate that the content is empty, jQuery tries to parse the JSON which
results in an error, which is not very helpful at first:
JSON.parse("") === "SyntaxError: Unexpected end of input"
This change adds a custom warning when such a response is returned, so
the feedback is more valuable.
---
This addresses #4207

[BUGFIX beta] add custom warning when invalid JSON is returned

---

addon/serializers/rest.js

Hi! I was going through the docs and found an apostrophe(') mistaken for a back tick(`). Set that right.
You guys are doing some amazing work :clap:

[DOC release] Mistaken back tick.

---

addon/-private/adapters/build-url-mixin.js

I generated the docs from the source code to preview the API documentation and thus verify the typo is fixed.

[DOC] Fix typo in urlForFindBelongsTo adapter method

---

blueprints/adapter/index.js
blueprints/serializer/files/__root__/__path__/__name__.js
blueprints/serializer/index.js
lib/utilities/extend-from-application-entity.js
node-tests/blueprints/adapter-test.js
node-tests/blueprints/serializer-test.js

This is a followup PR, made due to [a comment](https://github.com/emberjs/data/pull/4019#issuecomment-166396159) by @igorT: currently a serializer generate via `ember generate ember-data:serializer foo` extends `DS.JSONAPIAdapter`, where it should extend the `ApplicationAdapter`. This behavior is already the case when an adapter is generated, so this PR aligns the behavior of the serializer blueprint to the one of the adapter blueprint.
---

Enhance blueprints

---

addon/-private/adapters/build-url-mixin.js
addon/adapters/rest.js
tests/integration/adapter/rest-adapter-test.js
tests/unit/adapters/build-url-mixin/build-url-test.js

See discussion: https://github.com/emberjs/data/issues/4302

pass DS.SnapshotRecordArray to build-url-mixin buildURL

---

.codeclimate.yml

That's why the codeclimate score hasn't been updated in a while.
Error in CodeClimate: `Unparsable .codeclimate.yml Configuration File`

[skip ci] fix invalid indentation in codeclimate.yml

---

addon/-private/adapters/build-url-mixin.js
addon/adapters/rest.js
tests/integration/adapter/rest-adapter-test.js
tests/unit/adapters/build-url-mixin/build-url-test.js

related to: https://github.com/emberjs/data/pull/4304

pass snapshot through to urlForFindHasMany and urlForFindBelongsTo

---

node-tests/blueprints/adapter-test.js
node-tests/blueprints/model-test.js
node-tests/blueprints/serializer-test.js
node-tests/blueprints/transform-test.js
package.json

This PR modifies the blueprint tests to use the new blueprint testing API introduced in https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/45.

Use new blueprint testing API

---

addon/serializers/rest.js
tests/integration/serializers/rest-serializer-test.js

Before, `_normalizeArray` would call `forEach` even if the object wasn't
an array. We guard against it by using `Ember.makeArray`.
fixes #3805
https://github.com/emberjs/data/issues/3805

[BUGFIX beta] convert single record sideloaded records to plural

---

tests/integration/serializers/rest-serializer-test.js

This flag has been used when transitioning from 1.13 to 2.0 and is no
more needed in 2.x
:checkered_flag: :wave:

[CLEANUP] remove reference to no more used isNewSerializerAPI flag

---

addon/-private/system/record-arrays/adapter-populated-record-array.js
addon/-private/system/record-arrays/record-array.js
addon/-private/system/store.js
tests/integration/adapter/queries-test.js

The `isUpdating` flag is not set to `true` when the `update()` method on
a `DS.AdapterPopulatedRecordArray` is invoked. As with the flag on
`DS.RecordArray`, this should be `true` until the update is finished and
the array contains the most reset result for the query, fetched from the
adapter.
---
The `[FEATURE]` commit DRY's up some code in the `DS.AdapterPopulatedRecordArray` and by this makes it easier to cherry-pick this bugfix into `beta` (where this feature is not yet available).

Fix `isUpdating` for DS.AdapterPopulatedRecordArray#update()

---

config/features.json
index.js
lib/javascripts.js
lib/stripped-build-plugins.js
lib/stripped-build.js

Prior to this:
* When used as an ember-cli addon, the feature flags would only be processed for `production` builds.
* When built for globals builds, the features flags would only be processed for `ember-data.prod.js` builds.
This is incorrect, they should be processed for all builds (for every environment) so that any features explicitly enabled or disabled in the version of Ember data being used are stripped properly.

Fixup feature flagging infrastructure.

---

index.js

`included` is called for each instance of `EmberApp` created within the consuming applicationm, which means that we would be adding the same plugins if the consuming application happened to be creating two `EmberApp` instances.
For example, ember-cli-fastboot currently uses this technique to build both for fastboot AND the normal build. I know of a few other applications that use similar techniques to build two versions of the same `EmberApp` (i.e. a mobile version and a desktop one).
This allows us to ensure that `this.options.babel` is only setup once (regardless of how many times `included` is being called).
Fixes #4322.

[BUGFIX release] Only setup babel options once.

---

index.js

Older versions of node can't use the concise method syntax.

[BUGFIX release] use es5 syntax for addon's index.js file

---

blueprints/model/HELP.md
blueprints/model/index.js
node-tests/blueprints/model-test.js

When a model is generated via `ember generate model` without attributes
and relationships, then it is not immediately clear from the generated
blueprint, on how to add attributes and relationships via importing
stuff from the modules.
This change adds the imports as comments, so uncommenting allows to
quickly add the imports without writing the import statement. So the
command `ember genrate model foo` now creates this file:
```js
import Model from "ember-data/model";
// import attr from "ember-data/attr";
// import { belongsTo, hasMany } from "ember-data/relationships";
export default Model.extend({
});
```
---
This has been raised in the `#-ember-data` slack channel, where it was confusing on how to add attributes and relationships, since there is no `import DS from "ember-data"` in the …

[BUGFIX beta] Overhaul attr/relationships imports in model blueprint

---

addon/-private/system/store.js
addon/adapter.js

Initial stab at adding better documentation for the reload and background reload behavior of `store.findRecord` and `store.findAll`. The behavior has been described in the [release blog post for `v.13`](http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_new-adapter-hooks-for-better-caching), but the API documentation currently lacks this information, which unfortunately caused some headaches (#4341, #4162, #4148, #3657, #3483).

[DOC beta] Overhaul documentation for reload / background reload

---

README.md

The link to the Customizing Adapters guide was hard-coded to point to the v2.3.0 docs. I updated the link so that it will redirect to the latest version's guide page instead.

[DOC] Fix hard-coded "Customizing Adapters" link

---

addon/-private/system/store.js
addon/-private/system/store/finders.js
addon/serializers/json-api.js
addon/serializers/rest.js
tests/integration/adapter/find-test.js
tests/integration/adapter/json-api-adapter-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/store-test.js

Currently the use case for `store.queryRecord` is not communicated very
well and there has been some confusion on what the expected server
response should look like (array, or an object).
There are several issues with the current code base:
- in general, if the serializer returns an array for the primary data
returned by `normalizeQueryRecordResponse`, then `store.queryRecord`
resolves with an array
- if rest serializer is used and an array is returned by the adapter,
then the first entry of the array is used as primary data and
`store.queryRecord` resolves with the first record
- if json-api serializer is used and the primary data is an array, then
`store.queryRecord` resolves with an array of the primary records
- the API documentation for `queryRecord` is similar to `query` and
doesn't …

[BUGFIX beta] Overhaul queryRecord

---

FEATURES.md
addon/serializers/embedded-records-mixin.js
config/features.json
tests/integration/serializers/embedded-records-mixin-test.js

This reverts commit 87e6e60e9b6266b27eceae17891839cf2b7a1787.
The cleanup for the ds-serialize-ids-and-types feature is made too
eagerly, since it hasn't been enabled in beta yet. This commit reverts
the cleanup so the functionality is still behind the (enabled) feature
flag. By this it can be tested via the beta channel.
Once the feature is go'ed in a release channel, this can be finally be
cleaned.
---
Cleanup happened to eagerly in #4349

Revert "[CLEANUP ds-serialize-ids-and-types]"

---

addon/serializers/embedded-records-mixin.js

The change replaces references to `snapshot.record.serialize()` with `snapshot.serialize()` in the `EmbeddedRecordsMixin` to ensure that the snapshot state is serialized rather than the current state of the record.

Fix #4366: EmbeddedRecordsMixin embeds the record, not the snapshot

---

addon/attr.js
tests/unit/model-test.js

Changing the value of an in-flight property, then changing back, had the
side effect that the record would be marked dirty once the save
completed.
`changedAttributes` would report that `name` had been changed from
'Thomas' to 'Thomas'
This is because the attr computed was only checking to see if the value
was being reset to the canonical value, not if it was being reset to the
in-flight value

[BUGFIX beta] Fix resetting of properties to in-flight values

---

blueprints/model/files/__root__/__path__/__name__.js

Addresses: https://github.com/emberjs/data/issues/4306
This ensures that if attrs are present when generating a model, we indent them properly.  If no attrs are present, there should be no trailing whitespace.

[BUGFIX beta] remove trailing whitespace from model blueprint

---

addon/-private/system/store.js
tests/integration/adapter/find-all-test.js

A regression for the `isUpdating` flag on the RecordArray returned for
`store.peekAll` has been introduced in #4316: the flag isn't set to true
anymore when records are reloaded or a background reloaded.
---
This closes #4339.

[BUGFIX release] `isUpdating` flag is set correctly for `store.findAll`

---

FEATURES.md
addon/serializers/json-api.js
addon/serializers/json.js
addon/serializers/rest.js
config/features.json
tests/integration/serializers/json-api-serializer-test.js
tests/integration/serializers/json-serializer-test.js
tests/integration/serializers/rest-serializer-test.js

The `modelNameFromPayloadKey` and `payloadKeyFromModelName` hooks on the
serializer allow to customize the mapping between the key of a JSON and
the corresponding name of the model. Consider the following payload:
```json
{
"blog/post": {
"id": 1
}
}
```
To map the "blog/post" key to the `post` model, the
`modelNameFromPayloadKey` hook is used:
```js
serializer.modelNameFromPayloadKey("blog/post")
```
---
There are some issues with the current code base, as the
`modelNameFromPayloadKey` and `payloadKeyFromModelName` hooks are also
used to map the "value" of a type from / to the payload. Consider the
following payload of a JSON-API document:
```json
{
"data": {
"id": 1,
"type": "API:V1::User"
}
}
```
To map the namespaced type to the model name ember-data is using,
currently the …

[FEATURE ds-payload-hooks] Add hooks to map type in payload to modelName

---

addon/serializers/json.js
tests/unit/model-test.js

A property lookup is used to speed up the hot path of applying transforms when normalizing data received from the server.
See discussion on #2289

Use property lookup in applyTransforms

---

addon/serializers/json-api.js
addon/serializers/json.js
addon/serializers/rest.js

This is a rebased version of pr https://github.com/emberjs/data/pull/4313

During normalization, use property lookup instead of hasOwnProp checks

---

addon/-private/ext/date.js
addon/-private/transforms/date.js
tests/unit/model-test.js
tests/unit/transform/date-test.js

This pr deprecates overriding `Date.parse` however it keeps the current behavior (and where it differs from the native date.parse) for the date transform.
This pr supersedes https://github.com/emberjs/data/pull/4231 and https://github.com/emberjs/data/pull/4275

Deprecate date parse

---

addon/-private/ext/date.js

currently Internet Explorer cannot parse dates like: 
2003-12-02T23:00:00.000+**0000**
it accepts only:
2003-12-02T23:00:00.000+**00**
I encountered this bug when I was using date transformer.

fixed date parsing in IE

---

FEATURES.md
addon/-private/system/references/belongs-to.js
addon/-private/system/references/has-many.js
config/features.json
tests/integration/references/belongs-to-test.js
tests/integration/references/has-many-test.js

`push()` for a belongs-to and has-many reference accepts weird formats,
where it basically should only support a JSON-API document. If this
feature is enabled, it adds deprecation messages if something different
than a JSON-API document is pushed.

[FEATURE ds-overhaul-references] Fix inconsistencies with Reference#push

---

addon/adapters/rest.js
tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js

When checking if the URL of a record is of the format
`...something/:id`, we need to decode the last part of the path before
comparing, since the part in the URL is encoded when the URL is
constructed within buildURL.
---
This fixes #4190.

[BUGFIX beta] Correctly coalesce URI encoded ids

---

addon/-private/system/relationships/ext.js

Corrected documentation regarding return values from the following methods/properties:
- DS.Model eachRelationship
- DS.Model relationshipsByName
Fixes #4388

Outdated documentation on DS.Model.eachRelationship and DS.Model.relationshipsByName return values

---

addon/-private/system/store.js
tests/integration/store-test.js

Just a small helpful improvement.
Could potentially save users tens of minutes finding the cause. :tada:
My original assumption was that a payload was not including an `id`.. then i discovered it was my `findRecord()` call

Small improvement for the badIdFormatAssertion

---

FEATURES.md
addon/serializers/json-api.js
addon/serializers/json.js
config/features.json
tests/integration/serializers/json-serializer-test.js

From https://github.com/emberjs/data/issues/2494

make shouldSerializeHasMany public #2494

---

addon/serializers/json-api.js
tests/integration/serializers/json-api-serializer-test.js

Since json serializer's serializeAttribute function is been overwritten in json api serializer, the feature to pass the options to the transform is not working when using the json api adapter. This fixes the problem.

[BUGFIX] Pass options to transform for serialization in json-api

---

blueprints/adapter-test/mocha-files/tests/unit/__path__/__test__.js
blueprints/model-test/mocha-files/tests/unit/__path__/__test__.js
blueprints/serializer-test/mocha-files/tests/unit/__path__/__test__.js
blueprints/transform-test/mocha-files/tests/unit/__path__/__test__.js

The `expr` rule should instead be deactivated in `tests/.jshintrc`.
see also https://github.com/ember-cli/ember-cli-legacy-blueprints/pull/33

Remove JSHint directives from Mocha test blueprints

---

tests/ember-data-initializers.js

remove DEPRECATION: Using the global version of DS is deprecated.
Imported DS explicitly in tests/ember-data-initializers.js.

remove DEPRECATION: Using the global version of DS is deprecated when running tests

---

FEATURES.md
addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
config/features.json
tests/unit/model-test.js

First pass at #3705 
First feature PR!
Is there any subtlety around in-flight records that I'm missing?

[FEATURE ds-rollback-attribute] Add rolling back of a single model attribute

---

addon/-private/core.js
addon/-private/ext/date.js
addon/-private/initializers/data-adapter.js
addon/-private/initializers/store-injections.js
addon/-private/initializers/store.js
addon/-private/initializers/transforms.js
addon/-private/instance-initializers/initialize-store-service.js

(they are showing up on the DS.Model class)
Add missing API docs for Ember.Date
Add minor doc update to the DS namespace API docs.

Remove initializer methods from the API docs

---

FEATURES.md
addon/serializers/embedded-records-mixin.js
config/features.json
tests/integration/serializers/embedded-records-mixin-test.js

This was originally found by looking into ember-data test deprecation warnings.  Then it was pointed out by @bmac that the feature actually shipped in 2.6, so now submitting a PR to remove the feature flag.

[CLEANUP beta] Remove feature flag for ds-serialize-ids-and-types (shipped in 2.6) #4416

---

.npmignore

This shaves 22MB off the size of the package installation

Add benchmarks directory to npmignore

---

addon/-private/system/relationships/state/belongs-to.js
tests/unit/model/relationships/belongs-to-test.js

If the response to a save of a model that includes a belongs to relationship is successful but that response contains data that sets the belongs to back to it's original value the change is not applied to the store. #4469

Belongs to not updating when response contains a change with the previous value

---

blueprints/adapter/index.js
blueprints/model/HELP.md
blueprints/model/files/__root__/__path__/__name__.js
blueprints/model/index.js
blueprints/serializer/index.js
blueprints/transform/files/__root__/__path__/__name__.js
lib/utilities/extend-from-application-entity.js
node-tests/blueprints/adapter-test.js
node-tests/blueprints/model-test.js
node-tests/blueprints/serializer-test.js
node-tests/blueprints/transform-test.js

cc @pangratz @HeroicEric @ebryn

[BUGFIX release] Revert blueprints to use the old import DS format

---

addon/adapter.js

[DOCS] No need to use Ember.run in succes and failure of wrapped getJSON

---

addon/serializers/embedded-records-mixin.js
tests/integration/serializers/embedded-records-mixin-test.js

Closes 4472. This implements the same semantics for `key` that are used
in JSONSerializer, for both belongsTo and hasMany records when
serialized as id/ids.

Fix key remapping for id/ids belongsTo with embedded-records-mixin

---

addon/-private/system/record-arrays/record-array.js
addon/-private/system/relationships/ext.js
addon/-private/system/store.js
package.json

This pr adds the
[ember-runtime-enumerable-includes-polyfill](https://github.com/rwjblue/ember-runtime-enumerable-includes-polyfill)
to add includes if the user's version of Ember doesn't support it.
cc @rwjblue

[BUGFIX beta] Prefer includes over contains

---

addon/-private/system/model/internal-model.js
tests/integration/references/belongs-to-test.js
tests/integration/references/has-many-test.js

Assertions are thrown when the specified relationship doesn't exist or
the passed type mismatches the one of the actual relationship.
---
This issue has been raised in the slack channel so adding assertions should help preventing this in the future.

[BUGFIX beta] add assertions for reference methods on DS.Model

---

addon/adapter.js

It was very unclear to me why the server was being hit when returning `false` from `shouldReloadRecord`. Upon digging through the tests, I finally realized that background reload was what was actually hitting the server.

Update docs for shouldReload* methods

---

addon/-private/system/model/model.js
tests/integration/store-test.js

In Ember 2.9, using an `Ember.computed.alias` or `Ember.computed.readOnly` automatically adds mandatory setter's getter/setter to the properties being watched, and defers reading the current value to the objects own meta.
This avoids creating an watcher for `_internalModel` and therefore prevents an error that ocurrs when we attempt to read from `meta` after the object has been destroyed.

[BUGFIX beta] Make `Model#data` a plain getter.

---

lib/javascripts.js

In [`ember-data.prod.js`](http://builds.emberjs.com/tags/v2.8.0/ember-data.prod.js), the Ember Data's initializers are missing since 2.8.0.
Without these initializes, `DS.Store` isn't setup for Ember application :<

[BUGFIX release] Include initializers for global production build

---

app/initializers/ember-data.js

`Ember.ArrayController` is deprecated since Ember 1.11.
ref: http://emberjs.com/deprecations/v1.x/#toc_arraycontroller

[DOC beta] Remove `Ember.ArrayController` from initializer example

---

addon/adapters/rest.js

[BUGFIX beta] Ember Data should not swallow exceptions from the run loop

---

addon/-private/system/store.js

[DOCS] Fix store.unloadAll modelName param type

---

addon/-private/transforms/date.js
tests/unit/transform/date-test.js

Invalid Date objects - such as `new Date("foo")` - are Date objects that
throw a `RangeError` when calling `date.toISOString()`. These are now
serialized like all other garbage-in inputs.

[BUGFIX beta] Correctly serialize invalid dates

---

addon/-private/system/record-arrays/record-array.js

In Ember 2.10+ objects that are in the middle of being destroyed no longer notify property changes on itself (or other destroying objects) to avoid wasted work.  This means that `set(this, 'content', undefined)` isn't enough to ensure that `Enumerable` mixin will `notifyPropertyChange(this, 'length')` (since its observers are not fired).
This change also sets `length` during cleanup so it properly resets to `0`.
This fixes the build against latest ember#canary.

[BUGFIX beta] Ensure record array length is reset during willDestroy.

---

addon/-private/system/model/internal-model.js

In future versions of Ember, the `Ember.GUID_KEY` property may not be the place that guids are stored per object (may be moving to a `WeakMap`).  This change keeps `this[GUID_KEY]` around for easier debugging (though it isn't _required_ per-se), and uses `Ember.guidFor` to get the guid and setup the object.
Related to conversation in https://github.com/emberjs/ember.js/pull/14383.

[BUGFIX beta] Use Ember.guidFor to set InternalModel's guid.

---

tests/integration/store-test.js

The find test was failing when run by itself as it wasn't setting up the
store correctly. It just happens to have worked on Travis due to us not
cleaning up the store

Properly cleanup store and env in store integration test

---

addon/-private/system/store.js
tests/integration/adapter/find-all-test.js

See https://github.com/emberjs/data/issues/4527 for jsbin
I think this was fixed incorrectly in https://github.com/emberjs/data/pull/4386 – `isUpdating` would be true on the returned cached array even if `backgroundReload` or `shouldBackgroundReloadAll` is false

isUpdating should be true only if a reload happens

---

addon/-private/system/store.js

This commit adds documentation on the use of the `include` query parameter in `DS.Store` methods `findRecord()` and `findAll()`. This feature allows records of models related to those requested to be retrieved from JSON API compliant server in a single request. This capability was added in https://github.com/emberjs/data/pull/3976 but is not currently documented.

[DOC] Update descriptions of findRecord() and findAll()

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/states.js
addon/-private/system/record-array-manager.js
tests/integration/filter-test.js

* remove unneeded reopens
* remove assert.wait, instead use the promise chaining
* consistent quotes
* remove unneeded promises
* some ES6

tidy up integration/filter-test

---

addon/-private/system/model/model.js
addon/-private/system/store.js
tests/unit/store/unload-test.js

**Issue:** https://github.com/emberjs/data/issues/4126
This is a work in progress to get conversation going on what the expectation should be. The test shows the issue where when you unload a record from the store, the observers on that object are not torn down. 
* Should `unloadRecord` set the object as destroyed?
* Should `unloadRecord` clear observers?

unloadRecord does not remove observers

---

addon/-private/system/model/model.js
addon/-private/system/store.js
tests/unit/store/unload-test.js

Reverts emberjs/data#4277
@ryanpatrickcook Looks like #4277 is not green on current master. Can you reopen a PR based on the latest `master`?

Revert "unloadRecord does not remove observers"

---

addon/-private/system/store/finders.js
tests/integration/adapter/find-test.js
tests/integration/relationships/belongs-to-test.js
tests/unit/store/adapter-interop-test.js

This addresses the problem stumbled over in #4414.
Basically we can't `assert` here as this would be a breaking change, since the bug mostly will not occur unless you try to reload the originally requested record again.
cc @igorT

Warn when findRecord returns a different id than the one requested

---

addon/-private/system/record-arrays/adapter-populated-record-array.js
addon/-private/system/store.js

[DOC] Add documentation for query#update() to refresh query

---

tests/dummy/app/serializers/application.js

We were not correctly deserializing relationships coming from the mock server,
because we try to dasherize by default.

Fix dummy app serializer

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/model/states.js
addon/-private/system/record-array-manager.js
addon/-private/system/store.js
ember-cli-build.js
lib/babel-build.js
lib/stripped-build-plugins.js
tests/unit/store/unload-test.js

Branches off of heimdall-instrumentation, so that should be merged fist ;)

[PERF] make internal model lazier

---

addon/-private/system/record-arrays/adapter-populated-record-array.js
addon/-private/system/references/belongs-to.js
addon/-private/system/store.js
addon/-private/system/store/finders.js
tests/unit/adapter-populated-record-array-test.js
tests/unit/record-arrays/adapter-populated-record-array-test.js
tests/unit/store/push-test.js

This adds a `store#_push` method which returns DS.InternalModel's
instead of materialized DS.Model instances. This allows us to defer the
materialization process of an InternalModel until the corresponding
record is actually needed.

[BUGFIX beta] Don't unnecessarily materialize records

---

addon/-private/system/relationships/state/belongs-to.js
tests/integration/records/relationship-changes-test.js

Don't notify belongsTo changes if nothing changed

---

tests/integration/filter-test.js

* use promises directly, rather then indirect async test helpers. QUnit now just supports them

tidy-up integration/filter-test

---

FEATURES.md
addon/serializers/json.js
config/features.json
tests/integration/serializers/json-serializer-test.js

[FEATURE ds-serialize-id] add serializeId to json-serializer

---

tests/integration/adapter/store-adapter-test.js

Followup to #4283 to add tests for asserting that `updateRecord` and `deleteRecord` exist.
cc @bmac

Test assertions when updateRecord & deleteRecord don't exist on adapter

---

addon/adapters/errors.js

This methods are already present on the `DS` namespace, so this change
marks the officially as public and adds documentation how they can be
used.

[DOC] Mark `errorsHashToArray` and `errorsArrayToHash` public

---

addon/serializers/json-api.js
tests/integration/serializers/json-api-serializer-test.js

Assert when original and not normalized key is found in payload

---

addon/adapters/errors.js

Adds documentation for `DS.AdapterError` and the sub-classes added in the `ds-extended-errors` feature.
Relates to #3586 and #3585 
@bmac have tried to add some example usages in as well. Not totally sure if this is what you have in mind, or if the usages are what Ember Data has in mind, so feel free to comment freely!!

[DOC ds-extended-errors] Add docs for extended errors

---

addon/-private/system/many-array.js

At one point, relationships were managed by the recordArrayManager, this is no longer true. But we still spuriously inform the manager when we flush a relationship

[PERF] HasMany doesn't need to inform RecordArrayManager

---

addon/-private/system/many-array.js

* ensure shape is stable
* use tidier ES6 syntax when appropriate

cleanup system/many-array

---

addon/-private/system/debug/debug-info.js
addon/-private/system/relationship-meta.js
addon/-private/system/relationships/belongs-to.js
addon/-private/system/relationships/has-many.js
tests/unit/debug-test.js

* allow other relationship types (extend the web/ember-data forward!) to be first-class and not crash the inspector
* improve tests

build ember-data attribute debug info dynamically

---

addon/-private/system/many-array.js
tests/unit/model/relationships/has-many-test.js

* no longer invalid relationships property when accessing it the first time #4649
* no longer duplicate  “notifyHasManyChange” when adding a record fixes #4648
No longer warn/error in glimmer 2 by accidentally causing duplicate work.

[BUGFIX #4649 #4648]

---

addon/-private/system/model/internal-model.js

given:
```js
let [a, b] = thing;
```
If it is not statically known to babel, it will assume an iterator may be present. At which the following code is omitted.
```js
var _changedAttributes$attribute = _slicedToArray(changedAttributes[attribute], 2);
var oldData = _changedAttributes$attribute[0];
var newData = _changedAttributes$attribute[1];
```
```js
var _slicedToArray = (function () {
function sliceIterator(arr, i) {
var _arr = [];var _n = true;var _d = false;var _e = undefined;try {
for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) {
_arr.push(_s.value);if (i && _arr.length === i) break;
}
} catch (err) {
_d = true;_e = err;
} finally {
try {
if (!_n && _i["return"]) _i["return"]();
} finally {
if (_d) throw _e;
}
}return _arr;
}return function (arr, …
```

[PERF] fix sub-optimal compiler output

---

addon/-private/system/model/internal-model.js

* [PERF] fix sub-optimal compiler output
given:
```js
let [a, b] = thing;
```
If it is not statically known to babel, it will assume an iterator may be present. At which the following code is omitted.
```js
var _slicedToArray = (function () {
function sliceIterator(arr, i) {
var _arr = [];var _n = true;var _d = false;var _e = undefined;try {
for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) {
_arr.push(_s.value);if (i && _arr.length === i) break;
}
} catch (err) {
_d = true;_e = err;
} finally {
try {
if (!_n && _i["return"]) _i["return"]();
} finally {
if (_d) throw _e;
}
}return _arr;
}return function (arr, i) {
if (Array.isArray(arr)) {
return arr;
} else if (Symbol.iterator in Object(arr)) {
return sliceIterator(arr, i);
} else {
throw new …
```

[PERF backport to beta] fix sub-optimal compiler output (#4655)

---

tests/integration/records/delete-record-test.js

Bumped into an edge case in our app and built this test as a sanity check, figured I'd leave it for us to have nice things.

Test for hasMany array removal on deletion

---

addon/-private/system/model/states.js

Replaced `isDirty` link for `hasDirtyAttributes` in the documentation of [DS.RootState](http://emberjs.com/api/data/classes/DS.RootState.html).

Fixed link

---

addon/-private/system/record-array-manager.js
addon/-private/system/store.js

Every call to `peekAll` currently forces us to completely rebuild the live array. This is a stop gap until recordArrayManager can be improved ( @stefanpenner and I have been brainstorming our way through how to improve it.).

dirty check to prevent liveRecordArrays being rebuilt too often

---

addon/-private/system/store.js
tests/unit/store/adapter-interop-test.js

I've been working in this file a lot and it got tedious needing to update just small parts of the code formatting each time, so I did a little bit more in bulk.

Code Cleanup for store.js

---

addon/adapters/rest.js

Document the  relationship serialized format in the RESTAdapter

---

FEATURES.md
addon/-private/system/model/model.js
addon/-private/system/store.js
config/features.json
tests/integration/relationships/belongs-to-test.js
tests/unit/store/serialize-test.js

This follows https://github.com/emberjs/data/pull/4637
cc @bmac

remove useless private api

---

addon/-private/system/model/model.js
addon/-private/system/references/belongs-to.js

Update API docs for BelongsToReference

---

addon/-private/system/store.js
tests/unit/model-test.js
tests/unit/store/asserts-test.js

It already just delegates to store.hasRecordForId

Deprecate store.recordIsLoaded

---

addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
addon/-private/system/store.js
tests/integration/relationships/belongs-to-test.js
tests/unit/store/push-test.js

This PR moves most of the code from `store.setupRelationships()` to `relationship.push()` to be able to set the `hasData` and `hasLoaded` flags correctly depending on both data and links in the payload.
`relationship.push()` will also allow us to push the contents from a relationship's self link in the future.
Fixes #3393

Don't warn for 'async: false' relationships with link + data

---

addon/serializers/json.js

I was not able to find any references to `normalizeAttribute`:
```
➜  frontend git:(master) ✗ grep 'normalizeAttributes' -R --exclude-dir tmp . | grep -v \.map
./dist/assets/vendor.js:      @method normalizeAttributes
./dist/assets/vendor.js:    normalizeAttributes: function normalizeAttributes(typeClass, hash) {
./node_modules/ember-data/addon/serializers/json.js:    @method normalizeAttributes
./node_modules/ember-data/addon/serializers/json.js:  normalizeAttributes(typeClass, hash) {
./node_modules/ember-data/CHANGELOG.md:* Moved several normalize helper methods to the JSONSerializer - Move `normalizeAttributes` to the `JSONSerializer` (mirrors `serializeAttributes`) - Move `normalizeRelationships` to the `JSONSerializer` - Move `normalizePayload` to the `JSONSerializer`
```

Remove unused helper function `normalizeAttributes`

---

addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/create.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js

Was spelunking about cleaning up our async story and fell into cleaning up this bit once I realized that `record` was meant to be `internalModel`.  Decided to go all the way and give us a fresh ES6 look.

Modernizes relationship containers

---

tests/dummy/config/environment.js
tests/helpers/setup-ember-dev.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/records/error-test.js
tests/integration/references/belongs-to-test.js
tests/integration/serializers/json-serializer-test.js
tests/integration/serializers/rest-serializer-test.js
tests/unit/model/errors-test.js
tests/unit/store/adapter-interop-test.js

Silence warnings and deprecations in the console during tests

---

FEATURES.md
addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
config/features.json
tests/unit/model-test.js

As discussed in the ember data weekly meeting, the initial thought of
naming the method `resetAttribute` introduces a new verb "reset" into
the ember data terminology, which is not ideal.
This renames the method to `rollbackAttribute` to be more consistent with
the current terminology.
---
This addresses https://github.com/emberjs/data/issues/3705#issuecomment-261467358

[FEATURE ds-rollback-attribute] rename ds-reset-attribute

---

addon/-private/system/model/model.js

It was not clear from reading the API documentation that this feature is hidden behind a feature flag. I think it will be helpful to include the following note to provide guidance to users.

update documentation for `resetAttribute`

---

config/features.json

As mentioned in https://github.com/emberjs/website/pull/2727, this feature will be disabled in favor of the corresponding [RFC#171](https://github.com/emberjs/rfcs/pull/171).

[FEATURE ds-improved-ajax] Disable feature

---

blueprints/adapter-test/mocha-0.12-files/tests/unit/__path__/__test__.js
blueprints/model-test/mocha-0.12-files/tests/unit/__path__/__test__.js
blueprints/serializer-test/mocha-0.12-files/tests/unit/__path__/__test__.js
blueprints/test-framework-detector.js
blueprints/transform-test/mocha-0.12-files/tests/unit/__path__/__test__.js
node-tests/blueprints/adapter-test.js
node-tests/blueprints/model-test.js
node-tests/blueprints/serializer-test.js
node-tests/blueprints/transform-test.js
node-tests/helpers/generate-fake-package-manifest.js

Resolves https://github.com/emberjs/data/issues/4689

[BUGFIX beta] Add blueprints for "ember-cli-mocha >= 0.12.0"

---

benchmarks/config.js
tests/dummy/app/routes/query/route.js

When benchmarking the micro queues for store._push I realized that I wasn't including related records in the payload anymore, this fixes that for the one scenario in the config but should be fixed for more of them long term.

include related record on the complex test

---

addon/-private/system/store.js

Notes:
- was split off from the micro-queue work in #4668 so we could benchmark separately
- Usage this replaces was a mis-use of run.join
- This fix doesn't show any improvement in benchmark range at a glance
- But the fix does tighten the cluster of values within the range in a good direction (so with proper outlier filtering we'd likely see a small gain)
- The fix cleans up timeline charts significantly by coalescing the related work underneath one run.join call instead of it being split across several, which is it's own win
- Benchmark is running in Chrome only, but this may improve Firefox more than Chrome.
Numbers are measuring `store._push` for `238` records of a single type, in milliseconds and from 35 runs comparing current master to this PR.
**current master**
```json
{
"min": …
```

[FIX backburner] Avoids spinning up unnecessary run loops via run.join

---

addon/-private/system/store/finders.js

use _push instead of mapping over push result to get internal models

Improved performance for findHasMany finder

---

addon/-private/system/relationships/state/create.js
addon/-private/system/store.js
addon/-private/system/store/common.js
addon/-private/system/store/finders.js

@stefanpenner and I were discussing how it's better to use a more specialized micro-queue than to push everything into backburner a few days ago. I was spelunking through a profile and noticed that pushing a bunch of records of one time wasn't batched even though I thought it should be, turns out the run.join + the excess calls to schedule were really hurting us.  In a few limited runs this seemed to help by as much as 30% on the time to push a bunch of records of the same type into the store.
**EDIT**
So upon request, I separated this out into two separate PRs (see #4698 for first change and numbers associated with it).  Here are the numbers for making "just this change" to current master:
Numbers are measuring store._push for 238 records: 34 primary records and 204 related records (6 …

[PERF] use micro-queue

---

addon/-private/system/identity-map.js
addon/-private/system/model/internal-model.js
addon/-private/system/record-array-manager.js
addon/-private/system/record-arrays/adapter-populated-record-array.js
addon/-private/system/record-arrays/filtered-record-array.js
addon/-private/system/record-arrays/record-array.js
addon/-private/system/record-map.js
addon/-private/system/store.js
addon/-private/system/store/finders.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/client-id-generation-test.js
tests/integration/record-array-manager-test.js
tests/integration/record-arrays/adapter-populated-record-array-test.js
tests/integration/records/collection-save-test.js
tests/unit/model/relationships/record-array-test.js
tests/unit/record-arrays/adapter-populated-record-array-test.js
tests/unit/record-arrays/filtered-record-array-test.js
tests/unit/record-arrays/record-array-test.js
tests/unit/store/adapter-interop-test.js
tests/unit/store/push-test.js

When pushing records into the store (no materialization), we only needed to load the associated modelClass for "key" purposes. This PR shifts ember-data to consistently using a normalized `modelName` as the key, making it possible to push internal models, assemble record arrays, and (potentially in the future) even make requests without any access to the modelClass.
Step two of this effort (a separate PR) will be to enable the parsing of `modelClass` to avoid needing to load the classes for related models.  Combined, this gives us a happy story for initial render in apps with pre-loaded data and complicated relationship graphs.
In addition, this paved an easier path forward for #4584
- (will be separate PR, but needed to complete this effort) refactor relationship setup to not need to …

Upgraded IdentityMap and RecordMap

---

addon/-private/system/store.js
addon/-private/system/store/finders.js

With #4698 having landed, it's potentially possible we can remove some if not all calls to `store._adapterRun`. This PR currently removes all calls, leading to a small handful of failed tests which I'm investigating.  I'll also run it against LI's test suite once those pass (if I can make them pass) to see if there are undocumented behaviors that this might break.
**Benefits**
- many fewer closures
- reduced overhead (one layer of abstraction fewer)
- easier to understand the data flow in `finders`
- simplifies the "async story" in ember-data, helping us find more avenues for improving our async data flow story in the future.
- gets us within a very very short step of removing backburner entirely. Only necessary thing would be for a true microtask based flush mechanism to be available.
cc …

Removes store._adapterRun

---

addon/-private/system/model/internal-model.js
addon/-private/system/record-arrays/record-array.js
addon/-private/system/store.js
addon/serializers/json-api.js
addon/serializers/rest.js

Needs benchmarking, review, may have been too aggressive in `_modelFor` use, dislike that `modelFactoryFor` is public, should discuss.
Also, one reason for WIP is that this builds off of #4664, may be easier to review once that lands and I rebase ;)

Factory cache

---

CONTRIBUTING.md

PR for #4238 
Created ember-twiddle versions for the reporting bug section of contributing.md.  The first two links are recreations of the existing js-fiddles, and the third is the one mentioned in #4362

[DOC canary] Updating CONTRIBUTING.md to use ember-twiddle as examples

---

addon/-private/system/relationships/state/create.js
tests/integration/relationships/inverse-relationships-test.js
tests/unit/debug-test.js

this is continuation of #4675 which is closed in favour of this one.
`2.6.0` [Introduced](https://github.com/asakusuma/data/blob/ced181ff68f87eecd149c6d15b1f8b6887f17142/addon/-private/system/relationships/state/create.js#L16) a bug such that for `{ inverse: null }` relationships the relationship target is not checked at model creation time. However without `{ inverse: null }` we would get an error when trying to create a model with relationship to another model that doesn't exist. This PR tries to bring in consistent behaviour for such cases - perform a check for model type during model creation and throw an error if the model is not present in the store.

[BUGFIX beta] Inverse null relationships should throw if model doesn't exist 3

---

addon/-private/system/model/model.js

just a couple of minor typos I spotted in the docs.

[DOC] fix a couple of typos in model class docs

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/states.js
addon/-private/system/record-array-manager.js
addon/-private/system/relationships/state/create.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
addon/-private/system/store.js
tests/dummy/app/routes/query/route.js
tests/unit/store/push-test.js

TL;DR spin up less, schedule less, batch more things, cleaner profiles :)
In a query returning 238 records 34 of which are primary records, this resulted in:
- ember’s run.schedule 105 times => 2x
- ember’s run.join 2 times => 1x
- ED’s schedule 274 times => 2x
- ED’s join 274 times => 2x
~~Right now this fails on the tests around support for preloading relationships when doing findRecord, digging in on that.~~
~~Also includes some additional instrumentation stuff that's part of a different PR + some additions to that instrumentation I'll need to back out.~~
~~I appear to have pushed this far enough we get failing tests around pushing hasMany's with invalid values. I think something likely just ended up dropping out of the same run loop, investigating.~~
~~There's still a little bit of …

Simplify Backburner Usage

---

addon/-private/system/snapshot.js

Was working on cleaning up some things and just felt this could use a facelift. This isn't for perf, but I'm going to try to isolate it in a profile anyway because I'm personally curious the overall effects of:
- not setting things on the prototype that we're just going to override in the constructor anyway
- (obvs babelified) es6 class definitions vs. prototype definition using the `Object.assign` pattern

converts Snapshot to an es6 class instead of using prototype assign

---

addon/adapters/json-api.js
addon/adapters/rest.js
addon/attr.js
addon/serializers/embedded-records-mixin.js
addon/serializers/json-api.js
addon/serializers/json.js
addon/serializers/rest.js

Minor clean up for linter issues.

[CLEANUP beta] Linter changes for addon, addon/adapters and addon/serializers

---

addon/-private/system/model/internal-model.js
addon/-private/system/record-array-manager.js
addon/-private/system/record-arrays/adapter-populated-record-array.js
addon/-private/system/record-arrays/record-array.js
addon/-private/system/store.js
tests/dummy/app/routes/query/route.js
tests/unit/record-arrays/record-array-test.js

There wasn't really a good reason for this singleton being an Ember.Object (it's not resolved / not in the container / no ember-y things in use), and converting it shaves 33% off it's instantiation time in addition to giving us nice es6 syntax (1.53ms => .97ms).
I additionally moved the instantiation of the `OrderedSet` used to track the `RecordArray`s for an `internalModel` into internal models directly instead of having the manager reach in.  I'm slightly conflicted on this because of the resulting double-underscore for the cached property, but I prefer to leave objects in control of their own properties.
**Before**
**After**

es6 RecordArrayManager

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/model/states.js
addon/-private/system/record-array-manager.js
addon/-private/system/record-map.js
addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
addon/-private/system/store.js
tests/integration/adapter/find-all-test.js
tests/integration/records/delete-record-test.js
tests/integration/records/load-test.js
tests/integration/records/rematerialize-test.js
tests/integration/records/unload-test.js
tests/integration/relationships/has-many-test.js
tests/integration/relationships/many-to-many-test.js
tests/integration/relationships/one-to-many-test.js
tests/integration/store-test.js
tests/unit/many-array-test.js
tests/unit/model/rollback-attributes-test.js
tests/unit/store/unload-test.js

`internalModel`s need to stay around as long as they're connected to a live record via relationships.  Once an entire subgraph is removed however, we can free all of it.
Also add a couple of "late private" fields to `internalModel`'s constructor for shape preservation.
Includes work from @igort and @sly7-7
[Fix #3296]
[Supercede #3301]

Free up `internalModel`s

---

README.md

This may be implied, but it does need to be done before running tests for the first time.

[DOC] - add bower install to README

---

addon/-private/system/store.js

According to docs (https://github.com/emberjs/ember.js/blob/v2.10.0/packages/ember-debug/lib/deprecate.js#L97) ember deprecate requires 3 arguments.

Update deprecate arguments

---

addon/-private/system/model/model.js

`store.unloadRecord` says that it's there for symmetry, meaning the model should have a similar public method.
cc @bmac

[DOC] Make model.unloadRecord public

---

addon/-private/adapters/build-url-mixin.js
addon/-private/ext/date.js
addon/-private/initializers/store-injections.js
addon/-private/initializers/store.js
addon/-private/instance-initializers/initialize-store-service.js
addon/-private/transforms/boolean.js
addon/-private/transforms/date.js
addon/-private/transforms/number.js
addon/-private/transforms/string.js
addon/-private/utils.js

Minor clean up for linter issues.

[CLEANUP Beta] Linter changes for addon/-private (not -private/system)

---

addon/-private/ext/date.js
tests/unit/transform/date-test.js

This fixes the case that a timestamp with a timezone offset matches the regex and correctly calls Date.UTC rather than native Date.parse.
See https://github.com/emberjs/data/issues/4764

[BUGFIX beta] Ensure ISO-8601 regex correctly matches timestamps 

---

.gitignore

Wanted to add these so I don't accidentally commit them.

Updating gitignore to remove .idea

---

addon/-private/instance-initializers/initialize-store-service.js
tests/integration/application-test.js

Deprecate unused initializers

---

addon/-private/utils.js

Do not access container if Ember.getOwner exists.

---

addon/-private/system/model/errors.js
addon/-private/system/model/model.js
addon/attr.js

This adds missing DS references to DS.Model implementation examples.
Locations affected:
1. http://emberjs.com/api/data/classes/DS.Errors.html
2. http://emberjs.com/api/data/classes/DS.Model.html#property_attributes
3. http://emberjs.com/api/data/classes/DS.Model.html#property_transformedAttributes
4. http://emberjs.com/api/data/classes/DS.Model.html#method_eachAttribute
5. http://emberjs.com/api/data/classes/DS.Model.html#method_eachTransformedAttribute
6. http://emberjs.com/api/data/classes/DS.Model.html#method_changedAttributes
7. http://emberjs.com/api/data/#method_attr

Added missing DS references to DS.Model implementation examples

---

addon/-private/system/store.js

With the upcoming `factory-for` work it is likely that mutating the result of `modelFactoryFor` will throw an error.  This is a minor refactoring to avoid needing to mutate the return value (since we can simply do the work before registering).
Addresses one of the issues mentioned in https://github.com/emberjs/data/issues/4807#issuecomment-281091810.

Avoid mutating model factory in _modelForMixin.

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/store.js
tests/integration/injection-test.js
tests/unit/model-test.js
yarn.lock

*note: this combined with embers factoryFor makes `MODEL_FACTORY_INJECTIONS` irrelevant.*
Fixes https://github.com/emberjs/data/issues/4807

[Fixes #4807] realize class + factory seperation

---

addon/-private/system/store.js
addon/-private/system/store/finders.js
addon/-private/system/store/serializers.js
tests/integration/adapter/find-all-test.js
tests/integration/adapter/find-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/store-test.js

* avoid needly internalModel -> type conversion, when the information is already present on the internalModel
* make asserts more consistent (ES6 interpolation etc)
* rename trueModelName to normalizedModelName

misc cleanup

---

addon/-private/system/store.js
addon/-private/system/store/finders.js

* remove more unnecessary modelClass reifications
cleanup
* remove unneeded method indirection `store._classKeyFor`
* improve some naming

More Cleanups

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/store.js
tests/integration/injection-test.js
tests/unit/model-test.js

backport of https://github.com/emberjs/data/pull/4810 to release
---
Lets see what CI thinks.

[Backport of #4810 to release]

---

app/initializers/ember-data.js

* DS object will always present fully. Today during initialization it remains partially initializers for a period (missing everything from https://github.com/emberjs/data/blob/master/addon/index.js#L91-L154)
* this also fixes the (unknown mixin) stuff for all DS classes
Although this does force the entire DS namespaces to be initialized immediately. This shouldn’t cause a performance issue, as it the full namespace was always initialized, just in two phases.

[BUGFIX] ensure all of DS is initialized together

---

addon/-private/system/store.js
addon/serializers/rest.js
tests/integration/serializers/rest-serializer-test.js
tests/unit/store/has-model-for-test.js

* when interacting with a user-provided modelName, always be sure to normalize it.

remove isPrimaryType’s reliance on modelName

---

addon/-private/system/store.js
tests/integration/adapter/rest-adapter-test.js
tests/unit/store/adapter-interop-test.js

* es6 cleanup
* promise cleanup
* remove dangling promises / errors
* throw useful error message when a payload does not include an expected record instead of `undefined`

cleanup + reject with useful reasons

---

tests/integration/debug-adapter-test.js
tests/integration/store/json-api-validation-test.js
tests/unit/many-array-test.js
tests/unit/model-test.js
tests/unit/model/lifecycle-callbacks-test.js

Noticed 8 containers leaked to the end of the test suite, this PR fixes 5 of them (2 of them are yet upstream). This leaves us with 1, and that one appears strange/tricky (will investigate next).
also found these leaks:
* https://github.com/tildeio/rsvp.js/pull/446 <-- caused us to leak 2 containers
* https://github.com/stefanpenner/es6-promise
---
The goal of this, is to be sure our own test suite can be used (at-least manually) to detect leaks/tests. So if we can have our test suite not leak, it will be easier to catch leaks going forward (like the 2 RSVP / ES6 promise leaks).

Stefs cleanup (and some test suite memory leak fixes)

---

addon/serializers/embedded-records-mixin.js

As mentioned in https://github.com/emberjs/data/issues/4575, the fact that embedded records rely on their own serializer can cause some confusion when using different serializers inside an application.
Suggestions for re-wording are welcome 😄 , see the above mentioned issue for more details.

[DOC release] Add note to embedded records mixin

---

addon/-private/system/model/model.js

```Represents the model's class name as a string. This can be used to look up the model's class name through DS.Store's modelFor method.```
This is wrong and should be `model's class name` since you don't look up the actual model but the name.

Fixed modelFor documentation. Look up model's class name

---

addon/-private/system/promise-proxies.js
addon/-private/system/relationships/state/has-many.js
tests/unit/model/relationships/has-many-test.js
tests/unit/promise-proxies-test.js

Stable has many promise proxy

---

addon/-private/system/identity-map.js
addon/-private/system/internal-model-map.js
addon/-private/system/record-array-manager.js
addon/-private/system/store.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/records/rematerialize-test.js
tests/integration/records/unload-test.js

* This was super confusing before
* This does not change any public APIs

Improve naming around internal constructs (record vs internal model)

---

addon/-private/system/model/internal-model.js

If the internal model has no record, we won't do anything with the changes, so let's not waste cycles calculating them.

Don't calculate `_changedKeys` pointlessly

---

addon/-private/system/diff-array.js
addon/-private/system/many-array.js
tests/integration/records/relationship-changes-test.js
tests/unit/diff-array-test.js

Diff many arrays properly to find the smallest contiguous block describing the change
Particularly important when polling server for changes with a repeating model.reload() or relationship.update()

Optimise has many notifications

---

addon/-private/system/clone-null.js
addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/relationships/state/create.js
addon/-private/system/snapshot.js
addon/-private/system/store.js
addon/-private/system/store/container-instance-cache.js
addon/-private/utils/parse-response-headers.js
tests/unit/utils/parse-response-headers-test.js

pending: https://github.com/emberjs/ember.js/pull/15002

[Fixes #4853] use Object.create(null) directly

---

index.js

I picked this back up today and got pretty confused by the conditionals here. I found that rewriting them with variable names actually helped my understanding quite a bit.

Refactor the detection / warnings around ember-cli-shims.

---

addon/-private/system/model/internal-model.js
addon/-private/system/record-array-manager.js
addon/-private/system/record-arrays/adapter-populated-record-array.js
addon/-private/system/record-arrays/record-array.js
addon/-private/system/store/finders.js
tests/dummy/app/routes/application/template.hbs
tests/dummy/app/routes/index/template.hbs
tests/integration/adapter/find-all-test.js
tests/integration/debug-adapter-test.js
tests/integration/filter-test.js
tests/integration/record-array-manager-test.js
tests/integration/record-array-test.js
tests/unit/debug-test.js
tests/unit/record-arrays/adapter-populated-record-array-test.js

Batch record arrays

---

addon/-private/utils/parse-response-headers.js

This aims to avoid the following overhead:
* forEach + closure  <-- this seems to be a-bit noisy on boot
* [field, …value] doesn’t really transpile nicely
More aggressive approach is possible, maybe someone else has time. This addresses the issues I noticed...

Tidy up parse-reponse-headers

---

index.js

make ES6.Classes loose
* makes profiling easier (methods are not called value)
* appears to be a slight performance improvement (although not the motivator)

Loose es6 class

---

lib/javascripts.js

Also addresses #4873
Canary version of #4875

[BUGFIX canary] ensure the globals build has the correct context in the iife.

---

lib/javascripts.js

The last PR used `)(this)` vs `).call(this)`, which is needed to set the context correctly.

[BUGFIX beta] ensure context is applied in iife

---

lib/javascripts.js

The last PR used `)(this)` vs `).call(this)`, which is needed to set the context correctly.

[BUGFIX canary] ensure context is applied in the iife

---

addon/-private/system/relationships/state/relationship.js

Fixes small typo: `intenralModel` -> `internalModel`

Fix internalModel typo

---

addon/-private/system/many-array.js

First pass at #4758 . Not sure that there's a commit prefix that is applicable here, it's more to help with debugging, and to provide some data points as to the prevalence of the problem.

Ember.warn when ManyArray.objectAt() is undefined

---

addon/-private/system/store.js

Prefixing the `buildInternalModel` private function with an underscore, based on this (slightly outdated) ticket [3250](https://github.com/emberjs/data/issues/3250).

Deprecate buildInternalModel, add _buildInternalModel.

---

addon/-private/system/model/internal-model.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js

Fixes https://github.com/emberjs/data/issues/4752
The semantics of destroy have changed since https://github.com/emberjs/data/commit/2f18405a4785486f3bd7c865ca1096ea44e2c184. This PR renames the method to convey better what it does.

[BUGFIX beta] Rename `relationship.destroy` to `removeInverseRelationships`

---

.travis.yml
addon/-private/system/model/internal-model.js
addon/-private/system/references/record.js
addon/-private/system/relationships/state/belongs-to.js
appveyor.yml
tests/unit/store/adapter-interop-test.js

This PR removes `get record` from InternalModel 'cause there is already a `getRecord` method.
Fixes #4756

[BUGFIX beta] Removes `get record` from InternalModel.

---

addon/-private/system/snapshot-record-array.js
addon/-private/system/snapshot.js
tests/integration/snapshot-test.js
tests/unit/system/snapshot-record-array-test.js

Make snapshot.type and snapshotRecordArray.type load classes lazily, so we don't pay the cost of loading the classes if we don't need to.

Lazy snapshot.type

---

addon/-private/system/store/finders.js
tests/unit/store/finders-test.js

There's no need to load serializers if and until the adapter fetch promise resolves.

Defer serializer loading

---

addon/-private/system/many-array.js
addon/-private/system/model/internal-model.js
addon/-private/system/references/belongs-to.js
addon/-private/system/relationships/belongs-to.js
addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
addon/-private/system/snapshot.js
addon/-private/system/store.js
tests/unit/model/relationships/has-many-test.js

Within relationships/state/* and many-array (as well as call sites).
Please note this is downstream of #4821 so do not merge (or even expect the diff to be easy to read) until #4821 lands.

Rename record[s] -> internalModel[s]

---

addon/-private/system/many-array.js

This reverts commit 44ffbff63e4cae33ab519b23d51394645d7ccab1.
More details: https://github.com/emberjs/data/pull/4896#issuecomment-291706797

Revert "Ember.warn when ManyArray.objectAt() is underfined"

---

addon/-private/system/store/container-instance-cache.js

don't prematurely nullify props on the container-instance-cache. the cache's `destroy` method is called during the store's `willDestroy` meaning it may still be required before the Application has completed cleanup.

[BUGFIX canary] don't prematurely nullify props

---

addon/-private/system/store.js
addon/-private/system/store/finders.js

Prefixing the didUpdateAll private function with an underscore, based on this (slightly outdated) ticket [3250](https://github.com/emberjs/data/issues/3250).

Deprecate didUpdateAll, add _didUpdateAll.

---

addon/adapters/rest.js

Updated the documentation to reflect the actual order of parameters, which is incorrectly rendered in the api documentation (see https://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_findHasMany).
I presume that the method signature shown in the doc (`findHasMany (store, snapshot, relationship, url)` for this method) is generated from these `@param` directives.  I copied the signature out of the doc and found myself confused by the parameter values.

[DOC] Fix findHasMany parameter order

---

addon/-private/system/model/internal-model.js

Without this, adding an internalModel to an orderd set will result in a new [GUID_KEY] prop being added, but using defineProperty https://github.com/emberjs/ember.js/blob/master/packages/ember-utils/lib/guid.js#L187. Both causing a shape change, and a potentially costly defProp.
Restoring this restores that, and addresses a category of OrderdSet related performance issues.
@rwjblue / @runspired

[BUGFIX release] restore internalModels GUID_KEY’s

---

addon/-private/adapters/build-url-mixin.js

[DOC release] Add missing ` in urlsForFindMany description

---

lib/transforms/babel-plugin-remove-imports.js

It is breaking `ember-cli-fastboot` tests. Fixes: #4927 
cc: @runspired @stefanpenner @hjdivad

Don't use `let` or `const`

---

addon/-private/system/model/model.js
addon/-private/system/relationship-meta.js
addon/-private/system/relationships/ext.js
tests/helpers/test-in-debug.js

`meta.parentType` (which is produced by) `didDefineProperty` is only required for development assertions. As development assertions are stripped in prod, this `didDefineProperty` can also be stripped

[PERF] Model.prototype.didDefineProperty only in dev

---

addon/-private/system/model/internal-model.js
addon/-private/system/store.js
tests/unit/model-test.js

* by the name Model.prototype.init is called, internal model’s data has been loaded
* do no emit extra change events during `createRecord` as the attributes are the initial state.

[BUGFIX beta] [fixes #4509] createRecord initializes correctly

---

package.json
yarn.lock

In ember-cli@2.13 we intend to ship only one version of babel by default (though having multiple versions does work perfectly fine).
These deps have just been released, the only breaking change (to them) was bumping the min engine version to Node 4 which we have already done here.
@bmac - Is it possible to land this into 2.13.0 before shipping it?

[BUGFIX beta] Update dependencies to use Babel 6.

---

addon/-private/system/store.js
addon/serializers/rest.js
index.js
lib/stripped-build-plugins.js
package.json
yarn.lock

This PR will fail to build until we have fixed all the locations in which our babel compilation step is producing sub-optimal output to handle `let` and `const` closures.
When this PR is green, we can merge it and gain perfs.
cc @stefanpenner

[PERF] Guard against poorly optimized babel output

---

addon/-private/instance-initializers/initialize-store-service.js

The argument passed into `instance-initializers` is _either_ an `Ember.ApplicationInstance` instance _or_ a `Ember.EngineInstance` instance. The `.application` property is only present on `Ember.ApplicationInstance`'s.
This change adds some inline comments around the various conditionals and swaps the logic to use `instance.base` when present and avoid erroring if neither `.base` or `.application` is present.
---
This mirrors the functionality changes made in #4969, but targets `release` branch.
Closes https://github.com/emberjs/data/pull/4968

[BUGFIX release] Ensure Engines can boot without error.

---

addon/instance-initializers/initialize-store-service.js

The argument passed into `instance-initializers` is _either_ an `Ember.ApplicationInstance` instance _or_ a `Ember.EngineInstance` instance. The `.application` property is only present on `Ember.ApplicationInstance`'s.
This change adds some inline comments around the various conditionals and swaps the logic to use `instance.base` when present and avoid erroring if neither `.base` or `.application` is present.
A follow up PR will be made targeting `release` branch (because this won't cherry-pick easily).
---
Also, note, the second commit is not _required_ but it does strip the deprecation related code in production builds which is kinda nice...
---
Addresses #4968

[BUGFIX beta] Ensure Engines can boot without error.

---

index.js

I was getting this error on a fresh install: 
```
Completed 500 Internal Server Error in 1038ms
ActionView::Template::Error (:frontend has failed to build: emberDataBower.satisifies is not a function
):
emberDataBower.satisifies is not a function
TypeError: emberDataBower.satisifies is not a function
at Class.init (frontend/node_modules/ember-data/index.js:72:60)
```

Fix typo in function call

---

addon/-private/system/references/has-many.js

The existing inline doc incorrectly marks the method name as
`remoteType`.

[DOC release] Document DS.HasManyReference.ids

---

addon/-private/system/references/belongs-to.js
addon/-private/system/references/has-many.js

Change the description of the DS.HasManyReference.meta to match the text for the DS.BelongsToReference.meta docs (incorrectly described returning link information before).
Fix a typo in return description for DS.BelongsToReference.meta

[DOC release] Docs for has-many, belongs-to ref meta

---

addon/-private/system/diff-array.js

- Fix method name from `diff-array` to `diffArray`
- This is not a public method

[DOC release] Fix doc for `diffArray`

---

addon/-private/index.js
tests/unit/private-test.js

I'm sure adding more things to the `-private` export is 😢 . Unfortunately we need access to this class in [ember-data-model-fragments](https://github.com/lytics/ember-data-model-fragments/blob/master/addon/ext.js#L331-L360). There was previously a discussion about alternative approaches, but we settled on monkey patching this class (https://github.com/lytics/ember-data-model-fragments/issues/224).

[BUGFIX BETA] Added `system/store/container-instance-cache` to the -private export

---

addon/transform.js

@stefanpenner made reference to this in the original PR (https://github.com/emberjs/data/commit/24f41209b7ab9978bcdf029e50e3e62564d0b50f#commitcomment-22121947), but I think it was just overlooked. Either way this created a regression for us when using: `import Transform from 'ember-data/transform';`.

[BUGFIX BETA]: Fixed export regression. `ember-data/transform` to be default.

---

addon/-private/system/model/internal-model.js
addon/-private/system/store.js
tests/integration/records/unload-test.js

The underlying issue was that the internalModel was not cleaning up it's `destroy` call and flags when being rematerialized immediately.

Fix and tests for unloadRecord => findRecord issue

---

addon/-private/system/store.js
tests/integration/records/delete-record-test.js

Fixes #4993 
Seems the regression was introduced with #4668, by refactoring from a `forEach` loop to a `for` loop, where we cannot simply `return` anymore: https://github.com/emberjs/data/commit/063b3e500e31a711d81253a893f8668558e86808#diff-fd4c34d9a34dfde73cd3413128a3c973R1866

[BUGFIX] Fix flushing of pending saves, that include a deleted record

---

app/initializers/ember-data.js

The global build of ember-data has been broken since https://github.com/emberjs/data/pull/4823.
When `ember-data.js` is loaded, the following error is occured:
```
Uncaught Error: Could not find module `ember-data/index` imported from `ember-data/initializers/ember-data`
```
A reproduction code is just simple:
```
<!DOCTYPE html>
<html>
<head>
<script src="http://builds.emberjs.com/tags/v2.13.1/ember.prod.js"></script>
<script src="http://builds.emberjs.com/tags/v2.14.3/ember-data.js"></script>
</head>
<body>
<h1>Hello, Ember!</h1>
</body>
</html>
```
The reason of this error is that the broccoli builds the module named "*/index" into `*` for global build.
But loader.js couldn't resolve `ember-data/index` as `ember-data`.
So the `ember-data/index` module should be to as just `ember-data` …

[BUGFIX release] Fix global build

---

tests/integration/adapter/build-url-mixin-test.js
tests/integration/adapter/find-all-test.js
tests/integration/adapter/find-test.js
tests/integration/adapter/json-api-adapter-test.js
tests/integration/adapter/queries-test.js
tests/integration/adapter/record-persistence-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/adapter/serialize-test.js
tests/integration/adapter/store-adapter-test.js
tests/integration/records/collection-save-test.js
tests/integration/records/load-test.js
tests/integration/relationships/belongs-to-test.js
tests/integration/relationships/has-many-test.js
tests/integration/relationships/many-to-many-test.js

- move away from `assert.wait` instead use promises and `return` directly
- other es6 and async cleanup

more cleanup

---

tests/integration/relationships/has-many-test.js
yarn.lock

add test for hasMany + addObject + destroyRecord

---

addon/-private/system/relationships/state/has-many.js
tests/integration/references/has-many-test.js

I believe this fixes #4845. The problem is that `setHasData` was only being called when at least one internal model was being added, which is not the case when the server returns an empty array.

[BUGFIX] has-many relationship: set hasData when fetching link

---

addon/-private/system/relationships/state/relationship.js
tests/unit/store/adapter-interop-test.js

See #5053 for a similar fix in the fetchLink case.  See #4845 for the initially reported bug.

Set hasData for preloaded empty hasMany

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/model/states.js
addon/-private/system/record-array-manager.js
addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
tests/integration/relationships/has-many-test.js
tests/unit/model/relationships/has-many-test.js

If this approach is deemed good, this should be backported to beta and release.
This addresses an issue uncovered by the work to improve relationships: deleting a relationship results in a call to `flushCanonical` which erases any other local changes made. We can prevent local edits being removed for the common case (delete returning no additional data).
cc @igorT @hjdivad @stefanpenner for review

[BUGFIX] keep local state after a deletion

---

addon/-private/system/store.js

- store#filter() is now [deprecated](https://github.com/emberjs/data/blob/master/addon/-private/system/store.js#L1785)
- Don't suggest it's usage

[DOC release] Update doc for deprecated function.

---

package.json

Resolves https://github.com/emberjs/data/issues/5080 and https://github.com/emberjs/data/issues/5024
/cc @stefanpenner @bmac @runspired

Convert "babel-plugin-transform-es2015-block-scoping" from dev to prod dependency

---

addon/-private/system/relationships/state/has-many.js
tests/unit/model/relationships/has-many-test.js

If a relationship was setup with duplicate entries, it would enter an
invalid state. Specifically, this.canonicalMembers and
this.canonicalState would be out of sync. Resulting in some sad things.
This was most likely introduced by https://github.com/emberjs/data/commit/f8304b23c792a1e74cefb63140e6ee1917cbdfa1#commitcomment-23256408

{release} [BUGFIX release] handle dupe relationship entries

---

addon/-private/system/relationships/state/has-many.js
tests/unit/model/relationships/has-many-test.js

If a relationship was setup with duplicate entries, it would enter an
invalid state. Specifically, this.canonicalMembers and
this.canonicalState would be out of sync. Resulting in some sad things.
This was most likely introduced by https://github.com/emberjs/data/commit/f8304b23c792a1e74cefb63140e6ee1917cbdfa1#commitcomment-23256408

{BETA} [BUGFIX release] handle dupe relationship entries

---

addon/-private/system/relationships/state/has-many.js
tests/unit/model/relationships/has-many-test.js

If a relationship was setup with duplicate entries, it would enter an
invalid state. Specifically, this.canonicalMembers and
this.canonicalState would be out of sync. Resulting in some sad things.
This was most likely introduced by https://github.com/emberjs/data/commit/f8304b23c792a1e74cefb63140e6ee1917cbdfa1#commitcomment-23256408

{MASTER} [BUGFIX release] handle dupe relationship entries

---

addon/-private/system/model/internal-model.js
addon/-private/system/relationships/state/create.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
tests/integration/records/rematerialize-test.js
tests/integration/relationships/has-many-test.js
tests/integration/store-test.js
tests/unit/model/relationships/has-many-test.js

For an async relationship [x, y] with x.unloadRecord(), now adjusts only the relationship’s currentState, leaving that relationship’s canonical state alone, ensuring the existing client-side delete semantics are preserved. But when that relationship is reloaded, the canonicalState consulted.
For sync relationship [x, y] with x.unloadRecord(), both currentState and canonical state are updated. This is to mirror the client-side delete semantics. But since we cannot reload a sync relationship we must assume this to be the new canonical state and rely on subsequent `push` or `adapterPayloads` or manual `store.push` to update.
This aims to:
* [FIX] hasMany arrays never contain dematerialized records (so they no longer become broken)
* [FIX] using unloadRecord as a type of client side delete
* …

[BUGFIX release] relationship [x, y] should not break on x.unloadRecord()

---

addon/-private/system/model/internal-model.js
addon/-private/system/store.js
tests/unit/store/unload-test.js

The following should be possible:
```js
const record = store.find(‘record’, 1);
record.unloadRecord();
store.createRecord(‘record’, 1);
```
before this commit, the `createRecord` would fail,
as the `record` would not yet be fully unloaded, 
and its ID would still be reserved.

[BUGFIX release] restore unloadRecord + createRecord

---

addon/-private/system/model/internal-model.js
addon/-private/system/store.js
tests/integration/records/unload-test.js

Given unloadRecord followed by a synchronous findRecord, we should be sure
any orphaned relationships are discarded.

[BUGFIX release] unloadRecord + findRecord + orphaned relationships

---

addon/-private/system/relationships/state/relationship.js
addon/-private/system/store.js
tests/integration/relationships/belongs-to-test.js
tests/integration/relationships/has-many-test.js

Fixes #4942.
Fixes #5023.
Fixes #5017.
I also took to the liberty of changing https://github.com/emberjs/data/compare/bugfix/4942?expand=1#diff-fd4c34d9a34dfde73cd3413128a3c973L2876 to be more explicit.
If this change is approved, we should reach out to people linking to this issue after a release is cut.

Don't notify relationships with links during initialization

---

.travis.yml
index.js
package.json
yarn.lock

This hook was added in [ember-cli/rfcs#90](https://github.com/ember-cli/rfcs/blob/master/complete/0090-addon-tree-caching.md), and essentially guarantees that a given tree returned by an addon is considered stable (or not).
In the case of Ember Data, we do not have different tree output based on our parent (project or addon).
Specifically, this implementation allows both an app _and_ a lazy engine to depend on `ember-data` without duplicating the `ember-data` assets in both the `assets/vendor.js` and `engine-dist/<engine-name>/assets/engine-vendor.js`.
Fixes https://github.com/ember-engines/ember-engines/issues/438.

[BUGFIX beta] Implement `cacheKeyForTree` hook.

---

addon/-private/system/store.js
tests/integration/records/unload-test.js

Add a failing test for https://github.com/emberjs/data/issues/5125 and make an attempt at fixing the issue.
It seems that internal models scheduled for destruction also need to be destroyed synchronously in didSaveRecord(), similar to as it's already done in createRecord().

Failing test for #5125 and attempted fix

---

.bowerrc
.travis.yml
addon/-private/system/model/internal-model.js
addon/-private/system/relationships/state/has-many.js
addon/-private/utils.js
appveyor.yml
bower.json
config/ember-try.js
index.js
package.json
tests/dummy/app/app.js
tests/helpers/model-factory-injection.js
tests/integration/injection-test.js
tests/integration/records/relationship-changes-test.js
tests/integration/relationships/belongs-to-test.js
tests/integration/relationships/has-many-test.js
tests/integration/relationships/polymorphic-mixins-belongs-to-test.js
tests/integration/relationships/polymorphic-mixins-has-many-test.js
tests/unit/model-test.js
tests/unit/promise-proxies-test.js
yarn.lock

Prior to this commit (since c2ca068) we were only testing ember-source@2.11. Even though we had a `config/ember-try.js` with many scenarios, none of them properly removed the `ember-source` version (even though ba7f46221 was specifically trying to do this :sob:).
The fundamental issue here is:
* `ember-try` supports removing packages, but requires that you specify them
in the `dependencies` or `devDependencies` objects.  Since my changes in
ba7f46221 added `"ember-source": null` to the root of the `npm` config
it was completely ignored :disappointed:.
* `ember-source` emits a warning to the console when it is present **and**
the bower package for `ember` is in use.  Unfortunately, this warning is
a bit misleading (it doesn't tell you that the `ember-source` from `npm`
will always win). …

Ensure we are properly testing multiple Ember versions.

---

addon/-private/system/relationships/state/has-many.js
tests/unit/model/relationships/has-many-test.js

When a many2many relationship exists and more than one related item is
included in the relationship ensure that both sides load completely.
This issue was introduced in e430edee24591afa562167c6f5775b61d1031b75
---
note: this is https://github.com/emberjs/data/pull/5142 with some simplification

[BUGFIX release] Load many2many relationships correctly

---

addon/-private/system/relationships/state/has-many.js
tests/unit/model/relationships/has-many-test.js

When a many2many relationship exists and more than one related item is
included in the relationship ensure that both sides load completely.
This issue was introduced in e430edee24591afa562167c6f5775b61d1031b75

{backport release} [BUGFIX release] Load many2many relationships correctly

---

addon/-private/system/relationships/state/has-many.js
tests/unit/model/relationships/has-many-test.js

When a many2many relationship exists and more than one related item is
included in the relationship ensure that both sides load completely.
This issue was introduced in e430edee24591afa562167c6f5775b61d1031b75

{backport beta} Beta backport 5144

---

addon/-private/system/relationships/relationship-payloads.js
tests/integration/relationships/nested-relationship-test.js

When relationship information is merged, the newest information should win.
Unfortunately prior to this PR, relationship containing only `link` information, would mistakenly purge any existing `data` information on that relationship.
1. Update One
```js
{
data: { /* existing data */ },
Link: { /* existing data */ },
}
```
2. Update Two
```js
{
Link: { /* new data */ },
}
```
Previously resulted in:
```js
{
link: { /* new data */ },
data: null // oops
}
```
But now (correctly) results in:
```js
{
link: { /* new data */ },
data: { /* existing data */ }
}
```

[BUGFIX release] fix relationship merging

---

addon/-private/system/relationships/relationship-payloads.js
tests/integration/relationships/nested-relationship-test.js

When relationship information is merged, the newest information should win.
Unfortunately prior to this PR, relationship containing only `link` information, would mistakenly purge any existing `data` information on that relationship.
1. Update One
```js
{
data: { /* existing data */ },
Link: { /* existing data */ },
}
```
2. Update Two
```js
{
Link: { /* new data */ },
}
```
Previously resulted in:
```js
{
link: { /* new data */ },
data: null // oops
}
```
But now (correctly) results in:
```js
{
link: { /* new data */ },
data: { /* existing data */ }
}
```

{backport beta} Beta fix relationship merging

---

addon/-private/adapters/build-url-mixin.js
addon/adapters/json-api.js
addon/serializers/json.js
tests/integration/adapter/build-url-mixin-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/serializers/rest-serializer-test.js

This PR backports https://github.com/emberjs/data/pull/5130 and https://github.com/emberjs/data/pull/5141 to the `release` branch to unblock https://github.com/emberjs/ember-inflector/pull/131
/cc @locks @rwjblue @stefanpenner

Backport `ember-inflector` imports

---

addon/-private/system/relationships/relationship-payloads.js
tests/integration/relationships/nested-relationship-test.js

When relationship information is merged, the newest information should win.
Unfortunately prior to this PR, relationship containing only `link` information, would mistakenly purge any existing `data` information on that relationship.
1. Update One
```js
{
data: { /* existing data */ },
Link: { /* existing data */ },
}
```
2. Update Two
```js
{
Link: { /* new data */ },
}
```
Previously resulted in:
```js
{
link: { /* new data */ },
data: null // oops
}
```
But now (correctly) results in:
```js
{
link: { /* new data */ },
data: { /* existing data */ }
}
```

{backport release} [BUGFIX release] fix relationship merging

---

addon/-private/system/model/internal-model.js
addon/-private/system/relationships/state/relationship.js
tests/integration/records/rematerialize-test.js
yarn.lock

In order to ensure symmetry between async and sync relationships,
on destroy/unload of a record we must remove it from existing hasManys
Prior to this it appears in the inverse async case accidentally removed the inverse of the inverse which is wrong, and may also not exist at that name. How this manifests

[BUGFIX release] ensure inverse async HasMany is correctly maintained

---

README.md

Looks like usage of bower was removed in #5122. This PR updates the README
to remove the mentions of both installing bower and running `bower install`.

[DOC] Remove mention of `bower install` from README

---

README.md

Changes step 3 of "Building Ember Data" to instruct using the npm script
"production" rather than "build:production", which doesn't exist.

[DOC] Update README build step script name

---

lib/transforms/babel-plugin-remove-imports.js

This file introduced let and const without strict mode, and is now failing on node 4.
cc @runspired

fix node 4

---

addon/-private/system/references/belongs-to.js

`BelongsToReference.prototype.value` does not appear to actually take any parameters.

[DOC] Remove parameter from BelongsToReference.value

---

addon/serializers/json-api.js
tests/integration/serializers/json-api-serializer-test.js

When the JSON API serializer encounters a resource with a type that doesn't resolve
to one of the application's Ember Data models, it replaces the object with `null` and
emits a warning. Prior to this commit, if that `null` was one of the sideloaded
(i.e. `included`) resources, the store would throw trying to ask for the `null`'s type.
This commit makes the serializer drop any nulls out of the list of included resources
to avoid this problem.
To summarize, if your API attempts to include resources that you don't have models for,
a warning will be emitted and they will be ignored.
Fixes #4568

Ignore included resources without that don't have a corresponding ember-data model

---

FEATURES.md
addon/-private/adapters/errors.js
addon/adapters/rest.js
addon/index.js
config/features.json
tests/integration/adapter/rest-adapter-test.js
tests/unit/adapter-errors-test.js

The feature was enabled in ember-data@2.13, the feature flagging can
now be removed.
This is a work around to a bug in the feature flagging system used
by ember-data, that will need to be fixed on master branch.

Remove feature flagging for ds-extended-errors.

---

lib/stripped-build-plugins.js

broccoli-babel-transpiler (which we use by way of ember-cli-babel) requires that all plugins have a `.baseDir` function which broccoli-babel-transpiler uses to ensure that it can properly invalidate the cached output of each transpiled file. If `.baseDir` is not present broccoli-babel-transpiler does the only "safe" thing and completely opts out of this caching system and prints a very loud warning message.
This commit ensures that the few custom plugins that we are using are properly setup with a `.baseDir`.
Fixes #5164

[BUGFIX beta] Avoid cache related warnings during builds.

---

lib/stripped-build-plugins.js

FastBoot builds are [breaking again](https://travis-ci.org/ember-fastboot/ember-cli-fastboot/builds/279059158?utm_source=github_status&utm_medium=notification). I will open a seperate issue to enable Node 4.x in travis in ember data and would be happy to spend cycles fixing anything in ember data to make it compatible with Node 4.x.
cc: @rwjblue @stefanpenner

Fix ember-data Node 4.x builds

---

lib/stripped-build-plugins.js

Latest ember-data@2.16 was still having "opting out of cache" warnings.
cc @rwjblue

[BUGFIX beta] Fix broccoli-babel-transpiler cache warnings

---

appveyor.yml
package.json

Appveyor seems to be getting stuck when ember try switches between scenarios. Lets try disabling it on appveyor (ember try scenarios will still always run on travis).

Skip ember try on appveyor

---

addon/-private/system/promise-proxies.js
tests/integration/store/query-test.js

This closes #5129.
I am unsure if this is the correct way to fix this or if something else is fishy...
Maybe it's because of this 🤔:
https://github.com/emberjs/data/blob/5fceead8acb53723bdf38daabad00aff093f390a/addon/-private/system/record-arrays/adapter-populated-record-array.js#L51-L52

[BUGFIX beta] proxy `meta` on PromiseArray

---

addon/-private/system/model/states.js
tests/unit/model-test.js

If an invalid property of an existing record is reset, it should transition the record back to the loaded state.
This closes #5201

[BUGFIX beta] invalid record becomes loaded when property is reset

---

addon/-private/system/references/record.js
tests/integration/references/record-test.js

[BUGFIX beta] RecordReference returns null when not yet loaded

---

addon/serializer.js

When rendered, this links to https://www.emberjs.com/api/ember-data/2.15/classes/DS.JSONSerializer.html - which 404's. Correct link doesn't have the `.html`.

Fix docs link in DS.Serializer

---

package.json

When I install my project dependencies with Yarn, I get the following warning:
```
warning "ember-data@2.16.2" has unmet peer dependency "ember-inflector@^2.0.0".
```
It looks like the ember-inflector peer dependency [was added to `package.json`](https://github.com/emberjs/data/commit/86a3f574a265b24efec6d9fc8dc4f2f349039031) back when it was a dev dependency. ember-inflector [has since been upgraded to a direct dependency](https://github.com/emberjs/data/commit/4fab9abac9e7f510a95c2a6ae8dd84a22b26f5a0), so it no longer needs to be listed as a peer dependency as consuming applications get it automatically when they install ember-data.

Remove (unnecessary) ember-inflector peer dependency

---

lib/stripped-build-plugins.js

On request, a PR, to fix the production like environment issue
#5233

Check if environment is production-like in stripped-build-plugins

---

index.js

Deprecate support for "production like" values in EMBER_ENV

---

tests/integration/adapter/json-api-adapter-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/polymorphic-belongs-to-test.js
tests/integration/records/save-test.js
tests/integration/relationships/inverse-relationships-test.js
tests/integration/store/query-test.js
tests/unit/diff-array-test.js
tests/unit/model-test.js
tests/unit/model/rollback-attributes-test.js
tests/unit/record-arrays/adapter-populated-record-array-test.js
tests/unit/record-arrays/filtered-record-array-test.js
tests/unit/record-arrays/record-array-test.js
tests/unit/store/adapter-interop-test.js
tests/unit/store/push-test.js
tests/unit/transform/boolean-test.js
tests/unit/transform/date-test.js
tests/unit/transform/number-test.js
tests/unit/transform/string-test.js

Does this make sense? Basically this is to prevent us from future :trollface:ing like reported in #5207. I am unsure if this is a good idea or if we should update the tests to use `assert.ok` / `assert.notOk` instead 🤔 . Basically just did a search and replace...

Update assert against nulls

---

addon/-private/system/store.js
tests/integration/record-array-test.js

Model names are normalized (so eg `store.peekRecord('fooBar',1) === store.peekRecord('foo-bar', 1)`) at most of the store API (`peekRecord`,`findRecord` &c.) but notably absent is `push`.
This adds back model name normalization to push

[BUGFIX beta] Normalize model names during `push`

---

addon/-private/system/store.js

The application serializer is used when a model name is not given. We already have one example where a model name is given and specify that the corresponding serializer will be used.

[DOC] Fixup DS.Store.pushPayload example

---

addon/-private/system/model/model.js
tests/integration/inverse-test.js

The old links won't hit the right sub-section in the Ember Guide.

[doc] Update links to Ember Guide

---

addon/-private/adapters/build-url-mixin.js

The argument order gets reversed internally, but that is currently left as an exercise to the reader to figure out ... 😛

[doc] Update urlForFindRecord example

---

addon/-private/system/record-arrays/adapter-populated-record-array.js
tests/unit/record-arrays/adapter-populated-record-array-test.js

- Allows properly using the `links` value of a json-api response.
- (clone of https://github.com/emberjs/data/pull/5240)

Update AdapterPopulatedRecordArray to use links if available otherwise return null

---

addon/-private/system/model/internal-model.js
tests/integration/adapter/client-side-delete-test.js

Previously relationships were only cleared for new records.  Now they
are cleared for destroyed records as well, allowing destroyed records to
be pushed back into the store and properly update their inverse
relationships.

Fix client-side delete + resurrection

---

addon/-private/system/model/model.js
tests/integration/relationships/inverse-relationships-test.js
tests/integration/serializers/json-serializer-test.js

While working on #5230 I discovered that our current resolution strategy for `inverseFor` would improperly allow relationships that specify `inverse: null` to still be matched.  This addresses that, adds a test, and fixes two tests that depended upon this bug.

[BUGFIX] inverseFor should respect inverse: null

---

ember-cli-build.js

@rwjblue would you mind reviewing this and confirming that adding this to `ember-cli-build.js` will only impact the test builds and not the builds of consumers of Ember Data?

Fix the ember-try canary scenario by polyfilling WeakMap

---

addon/serializers/json-api.js

In response to https://github.com/ember-learn/ember-api-docs/issues/399
`extractRelationship` has different args for `JSONAPISerializer` than `JSONSerializer`.  Since `JSONAPISerializer.extractRelationship` is not documented the apidocs show `JSONSerializer.extractRelationship` instead, leading to confusion.  This pr simply adds documentation reflecting correct arguments to `extractRelationship`, and also adds `extractRelationships` documentation (so source link goes to the correct implementation.

[doc beta]document extractRelationship in json-api.js

---

blueprints/test-framework-detector.js
node-tests/blueprints/adapter-test.js
node-tests/blueprints/model-test.js
node-tests/blueprints/serializer-test.js
node-tests/blueprints/transform-test.js
node-tests/fixtures/adapter-test/application-default.js
node-tests/fixtures/adapter-test/foo-default.js
node-tests/fixtures/adapter-test/foo-mocha-0.12.js
node-tests/fixtures/model-test/comment-default.js
node-tests/fixtures/model-test/foo-default.js
node-tests/fixtures/model-test/foo-mocha-0.12.js
node-tests/fixtures/model-test/post-default.js
node-tests/fixtures/serializer-test/application-default.js
node-tests/fixtures/serializer-test/foo-default.js
node-tests/fixtures/serializer-test/foo-mocha-0.12.js
node-tests/fixtures/transform-test/default.js
node-tests/fixtures/transform-test/mocha-0.12.js
node-tests/helpers/fixture.js

Making moving some of the assertion logic into files, and using strict mode so it's more in line with https://github.com/emberjs/ember.js/tree/master/node-tests
Will make https://github.com/emberjs/data/issues/5292 easier to implement

cleanup: node-tests cleanup 

---

blueprints/test-framework-detector.js
blueprints/transform-test/qunit-rfc-232-files/tests/unit/__path__/__test__.js
node-tests/blueprints/transform-test.js
node-tests/fixtures/transform-test/rfc232.js

`transform-test` & `test-framework.js` tasks from https://github.com/emberjs/data/issues/5292
Updates the `test-framework-detector` to be analagous to https://github.com/emberjs/ember.js/blob/master/blueprints/test-framework-detector.js

blueprints/transform-test: Add RFC232 variants

---

blueprints/adapter-test/qunit-rfc-232-files/tests/unit/__path__/__test__.js
node-tests/blueprints/adapter-test.js
node-tests/fixtures/adapter-test/rfc232.js

See https://github.com/emberjs/data/issues/5292

blueprints/adapter-test: Add RFC232 variants

---

blueprints/serializer-test/qunit-rfc-232-files/tests/unit/__path__/__test__.js
node-tests/blueprints/serializer-test.js
node-tests/fixtures/serializer-test/rfc232.js

See https://github.com/emberjs/data/issues/5292
Had questions on what we wanted the default to be so I implemented both 
@Turbo87 @bmac

blueprints/serializer-test: Add RFC232 variants

---

addon/serializers/json-api.js
tests/integration/serializers/json-api-serializer-test.js

Currently when saving a model with an unsaved `belognsTo` a null id is used in the JSON:API document. 
For example
```js
let user = this.store.createRecord('user');
let details = this.store.createRecord('user-details', { user });
user.save();
```
Generates this post payload:
```js
{
data: {
type: 'users',
id: '1',
relationships: {
user-details: {
data: {
type: 'user-details',
id: null
}
}
}
}
}
```
According to the spec this is an invalid payload:
This PR addresses this by not including the belongsTo that is unsaved in the relationship key.
I took this existing PR  and updated it to fit @wecc's comment: https://github.com/emberjs/data/pull/4500. Big thanks to @pangratz

Dont serialize new belongsTo records

---

addon/-private/system/store.js

`findRecord` calls `normalizeModelName` too

remove redundant `normalizeModelName`

---

addon/-private/system/model/internal-model.js
addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
tests/integration/records/rematerialize-test.js
tests/integration/records/unload-test.js
tests/integration/relationships/many-to-many-test.js

WIP client-side-delete semantics `unloadRecord`

---

tests/integration/relationships/has-many-test.js

Remove usages of enumerable observers and replace them with array observers.
Closes #5325.

Remove usages of enumerable observers

---

config/ember-try.js
package.json
yarn.lock

Stealing @rwjblue's magic from https://github.com/ember-cli/ember-cli/pull/7536
This pr also drops ember try tests for Ember 1.13, 2.4 and 2.8 which I think is ok since it targets Ember Data 3.0.

Avoid bower usage in config/ember-try.js

---

CHANGELOG.md

The release date for v2.11.0 (according to `npm info ember-data`) is '2017-01-09T20:44:27.764Z'.

[DOC] Fix Changelog release date for v2.11.0

---

index.js
lib/stripped-build-plugins.js

Previously production builds would fail to include `ember-data/-debug` when instrumentation is active; however, the `instrument` function helper is required in this case.

[DEV-BUGFIX] Fix instrumentation when running in production

---

addon/-private/system/relationships/ext.js
tests/integration/relationships/belongs-to-test.js

The previous implementation was intending to cache relationships when in the production environment, but avoid caching them in development.  Unfortunately, this code was factored in a way that relied on mutating internal private state of the underlying `Ember.ComputedProperty` instance when `Ember.testing` was true (which was used as a way to determine prod vs non-prod).
When this code was introduced (2014-12-02 in https://github.com/emberjs/data/pull/2530), setting `_cacheable` on a `ComputedProperty` instance would have worked as intended, however a refactor in Ember (ironically one day prior in https://github.com/emberjs/ember.js/pull/9489, but on Ember's canary channel) deprecated using `_cacheable` or `.cacheable()` (in favor of opting out of caching via `.volatile()`). Later support …

[BUGFIX beta] Fix development build relationship caching.

---

lib/stripped-build-plugins.js
package.json
yarn.lock

Prior to this, we used our ember-data's own dirname as the default `baseDir` for any of our custom babel plugins. This baseDir is used to traverse all JS files in all deps (recursively) and ensure that if any of them are changed, the transpilation cache is invalidated.
Once we swapped to using ember-source as an npm package this meant that we would be stating/hashing all files inside of `node_modules/ember-source/**`. When using `npm link ember-source` this leads to a JS max heap errors (because of `node_modules/ember-source/tmp/**` being _MASSIVE_).
This fixes that specific issue, by using the **correct** basedir for each individual plugin.
/cc @mmun

Prevent build issues when linking ember-source.

---

addon/-private/system/model/errors.js

In Ember 3.1+ any object that has an `unknownProperty` will throw an error if its `unknownProperty` returns any value other than `undefined` and the property is accessed via `obj.someProperty` (instead of `obj.get('someProperty')` or `Ember.get(obj, 'someProperty')`).

[BUGFIX beta] Update DS.Errors#unknownProperty to return `undefined`.

---

addon/-private/system/model/model.js

This just fixes the accessor. We should actually deprecate this though.

[BUGFIX] record.data is intimate API that we need to deprecate

---

tests/test-helper.js

This is part of the work for RFC 297, the deprecation of Ember.Logger

Removing reference to Ember.Logger

---

addon/-private/system/model/internal-model.js
addon/-private/system/store.js
tests/integration/relationships/one-to-many-test.js

Fixes #5359 and emberjs/ember.js#16258
Explained in #5364:
> Before this PR, it was possible to accidentally reify inverse relationships into an invalid state when combining createRecord with @each observers/CPs on an inverse relationship (see test). This would cause internalModel's getRecord to be called recursively with unexpected results. This problem became amplified in Ember 3.x because ArrayProxies now cache the result of objectAt, which lead us to caching the wrong invalid state.
This applies the workaround from https://github.com/emberjs/data/pull/5359#issuecomment-366880425 to create and cache the record _before_ setting any state which might update inverses.
cc @mmun

[BUGFIX beta] Fix createRecord creating two records

---

addon/-private/system/model/errors.js
addon/-private/system/model/internal-model.js
addon/-private/system/store/serializer-response.js
addon/transforms/number.js
tests/unit/model/rollback-attributes-test.js

`Ember.isEmpty` does **a lot of things**, there is no reason to use it when you are operating on known data types.
**_Use the platform..._**

[BUGFIX beta] Avoid `isEmpty` for known object types.

---

addon/-private/system/ordered-set.js
package.json
tests/integration/record-array-manager-test.js
yarn.lock

Ember will deprecate usage of `Ember.OrderedSet` (likely in 3.2 or 3.3), and as part of that process the implementation has been extracted to an addon `@ember/ordered-set`. The addon intelligently avoids shipping duplicated implementations, and is compatible with newer _and_ older Ember versions.
Closes https://github.com/emberjs/data/issues/5254

[BUGFIX beta] Use @ember/ordered-set to avoid deprecations.

---

addon/-private/system/relationships/state/relationship.js
tests/integration/records/unload-test.js

[bugfix beta] Invalidate link on inverse unload
Invalidates link promises when inverse records are unloaded.  Subsequent fetches of a `hasMany` unloaded in this way will load from the link again, rather than loading whatever ids were returned from the prior link load.

[bugfix beta] invalidate link promise on inverse unload

---

addon/-private/system/store.js
tests/integration/records/unload-test.js

When fetching records, cancel internal model destruction if it is
scheduled, ie if the model is dematerializing because it was unloaded.
It is not possible to construct snapshots for dematerializing internal
models.  Prior to this commit, this could happen when fetching a record
in the same runloop that it was unloaded.  A straightfoward way of
getting into this state was via
```
store.findRecord('book', 1).then(b => b.unloadRecord())
```
when the model is already cached in the store.  Under these conditions,
the fetch is scheduled, then the promise fulfills with the cached record
and is unloaded and *then* the scheduled fetch is flushed.
[fix #5343]

[bugfix beta] Fetch cancels unload

---

index.js

ember-cli no longer requires the modules directory to be used and will deprecate it soon
cc @rwjblue @kellyselden

Remove use of `modules` directory for ember-cli >= 3.0

---

addon/-private/system/store.js
addon/-private/system/store/finders.js
tests/integration/store-test.js

store promise with the exception.
Closes #4945
cc @runspired

Trap exceptions that are thrown from adapter methods and reject the

---

addon/-private/system/model/internal-model.js
addon/-private/system/record-array-manager.js
package.json
tests/helpers/watch-property.js
tests/integration/record-arrays/peeked-records-test.js
tests/integration/record-arrays/unload-peeked-records-test.js
yarn.lock

This PR resolves issues with ensuring that RecordArray is correctly synced for peekAll.
Resolves #5271 
Resolves #5167 
Resolves #5175
Resolves #5111 / #5157 
It also includes tests and a fix for #5350 and #5025 / #5095  wherein non-materialized records would remain in live-record-arrays and filtered record arrays upon unload.
Resolves #5025 
cc @tylerturdenpants @igorT @hjdivad @workmanw

[BUGFIX] resolve issues with RecordArray sync for peekAll

---

RELEASE.md

#5381 removed these lines prematurely.

[FIX release-guide] restore guidance to update default ember-cli blueprint

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/model-data.js
addon/-private/system/store.js
addon/-private/system/store/model-data-wrapper.js
tests/unit/model-test.js

This is small addition to the Model Data branch, which allows model datas to determine when they have received an ID from the server.
I've looked for tests to update, but it wasn't obvious where they should go. I'm looking for pointers in this regard.
cc @hjdivad @igorT

[Model Data] Introduce `setRecordId` function in place of `updateId`

---

addon/-private/system/store/finders.js

Currently the `if` statement always returns false because adapter#query is a wrappedFunction, which has length == 0.
This PR checks if the query is a wrappedFunction and if it is we'll check the length of that function.
I'm also wondering if we can get rid of the `if` statement and have the recordArray created and given to the query function in all cases. My guess is that the conditional guards around having to create and then later add models to the record array because there is a problem with the events that fire? @stefanpenner do you have any thoughts?

Check if adapter#query is a wrapped function

---

addon/-private/system/store.js
addon/-private/system/store/finders.js
tests/integration/adapter/store-adapter-test.js
tests/integration/record-arrays/adapter-populated-record-array-test.js

[BUGFIX #4497] query/queryRecord/filter now support adapter options

---

addon/-private/system/store.js

It was always private; so this is a cautious deprecation.

Deprecate `store.updateId`
