warp-drive-data/warp-drive

.travis.yml
appveyor.yml
package.json

* cleanup
* windows via appveyor
[fixes #2655]

build tool improvements

---

packages/ember-data/lib/serializers/embedded_records_mixin.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/serializers/embedded_records_mixin_test.js

Add support for embedded polymorphic belongsTo

---

Brocfile.js
packages/ember-data/lib/system/relationships/belongs_to.js
packages/ember-data/tests/integration/adapter/rest_adapter_test.js
packages/ember-data/tests/integration/filter_test.js
packages/ember-data/tests/integration/record_array_manager_test.js
packages/ember-data/tests/integration/relationships/belongs_to_test.js
packages/ember-data/tests/integration/relationships/has_many_test.js
packages/ember-data/tests/integration/relationships/inverse_relationships_test.js
packages/ember-data/tests/integration/serializers/embedded_records_mixin_test.js
packages/ember-data/tests/unit/debug_test.js
packages/ember-data/tests/unit/store/push_test.js
packages/ember-data/tests/unit/transform/number_test.js

Test suite should comply with JSHint standards and conventions

Run JSHint on Test Suite

---

.travis.yml
packages/ember-data/lib/system/record_array_manager.js

This replaces #2672
Fixes #2661

Remove use of private API to make tests pass again against Canary

---

README.md

Updating to use same style that Ember uses.

Update examples to use multi-var syntax

---

packages/ember-data/lib/system/record_array_manager.js
packages/ember-data/lib/system/record_arrays/record_array.js

Deprecate RecordArray.pushRecord()

---

packages/ember-data/lib/adapters/rest_adapter.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/store.js

Favor `object` over `hash` in public documentation and assertions

---

packages/ember-data/lib/system/store.js

I was trying to do some more sophisticated querying with `find` and the docs were not clear enough as to what exactly I should do. I ended up looking in the source code at the Store's `find` method to figure out what needed to be done. This is a PR to improve the docs so that others don't need to go into the source code to figure it out. 
I hope this helps. Please let me know if I could improve it in any way. Thanks.

add documentation for the Store's find method

---

packages/ember-data/lib/serializers/json_serializer.js

Would love to add a nice example of overriding this method as well. Suggestions?

Cleanup JSONSerializer#extract example

---

packages/ember-data/lib/adapters/rest_adapter.js
packages/ember-data/tests/integration/adapter/rest_adapter_test.js

Do not double include the host when it uses a protocol relative url.

---

.jshintrc

Enable 'nonbsp' JSHint option

---

packages/ember-data/lib/adapters/rest_adapter.js

Minor fix for JS code block at http://emberjs.com/api/data/classes/DS.RESTAdapter.html#property_coalesceFindRequests

Fix JS code block for coalesceFindRequests

---

CHANGELOG.md

Document that ManyArrays are no longer RecordArrays in the changelog.

---

packages/ember-data/lib/system/adapter.js

Update the generateIdForRecord docs to show it gets passed an Object

---

packages/ember-data/lib/system/record_arrays/many_array.js
packages/ember-data/lib/system/record_arrays/record_array.js
packages/ember-data/tests/unit/many_array_test.js

Added save() to ManyArray

---

README.md

Add es5-sham warning for IE8 support

---

appveyor.yml

Use node version specified in environment

Windows: Use latest node 0.10 release

---

packages/ember-data/tests/integration/relationships/has_many_test.js

Add adapter.hasMany unique IDs test

---

bower.json

upgrade qunit (now we can filter tests/modules)

---

bower.json

bump ember-inflector dependency for HTMLBars compat

---

packages/ember-data/lib/system/model/states.js
packages/ember-data/lib/system/relationships/state/has_many.js
packages/ember-data/tests/integration/adapter/rest_adapter_test.js
packages/ember-data/tests/integration/relationships/many_to_many_test.js
packages/ember-data/tests/unit/model_test.js

Includes @slindberg test case from #2759.
cc @igorT

Fix hasMany simultaneous adds and removes bug

---

packages/ember-data/tests/integration/adapter/rest_adapter_test.js

When a record with a `hasMany` relationship has a record removed and another added, then is persisted, the added record does not end up in the relationship's canonical list. Nearest I can tell, it's because [`ManyRelationship#computeChanges`](https://github.com/emberjs/data/blob/v1.0.0-beta.14.1/packages/ember-data/lib/system/relationships/state/has_many.js#L108-L142) performs a remove, but never adds new records. However, my attempts at adding the records there result in another test failing indicating that relationships are duplicated on record create.  :confused: 
Here's a [jsbin](http://jsbin.com/fetoqomopi/1/edit?html,js,output) that demonstrates the issue.
Possibly related to #2666

Added failing test for hasMany add/remove bug

---

packages/ember-data/lib/system/record_arrays/many_array.js

Further docs refining may be needed

(Docs) ManyArray is no longer a RecordArray

---

packages/ember-data/lib/adapters/fixture_adapter.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/adapter/fixture_adapter_test.js
packages/ember-data/tests/integration/adapter/rest_adapter_test.js
packages/ember-data/tests/unit/adapters/rest_adapter/group_records_for_find_many_test.js
packages/ember-data/tests/unit/store/adapter_interop_test.js

Warn when expected coalesced records are not found in the response

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/unit/model_test.js

Does the messages make sense? ping @ZenCocoon, @igorT 
Fixes #2829

Warn if calling attr, belongsTo or hasMany on model

---

packages/ember-data/tests/integration/store_test.js

Fix a test name and assertion message.

---

packages/ember-data/lib/system/serializer.js

update docs about `store` in serializer

---

packages/ember-data/lib/system/map.js
packages/ember-data/lib/system/ordered-set.js
packages/ember-data/lib/system/record_array_manager.js
packages/ember-data/lib/system/relationships/state/has_many.js
packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/tests/integration/snapshot_test.js

Have snapshots respect the order of items in hasMany relationships

---

packages/ember-data/lib/system/model/attributes.js

closes #2833
@yokree Does this address your concerns?

Add doc example for defaultValue as a function on DS.attr

---

packages/ember-data/lib/system/model/model.js

Add examples of how to use model.errors in a template

---

packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/system/adapter.js

server payload gets normalized.
Closes #2887
@atomkirk I'd like your feedback on these changes to the docs
<hr>

Update the InvalidError docs to make it more clear about where the

---

packages/ember-data/lib/system/many-array.js
packages/ember-data/tests/integration/relationships/has-many-test.js

Closes #2666
Thanks to @dwickern for the excellent test case. 
@igorT if you have time I'd love to get your eyes on this

Do not re-add deleted records to a hasMany relationship

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/store-test.js

Closes #2925
cc @igorT @jmurphyau

Allow the store to lookup the applicationAdapter using adapterFor

---

CONTRIBUTING.md

fixes JSBin link

---

packages/ember-data/lib/system/store.js

`DS.Store#findMany` returns Promise.

[DOC] Fix for DS.Store#findMany

---

README.md

`npm run dist` was `ember build --environment=production`.

Fix building steps in README

---

config/s3ProjectConfig.js
package.json

Update the s3ProjectConfig to upload tagged builds

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/unit/model-test.js

Do not assert reserved properties for static properties.

---

bower.json

:tada:
Remove `handlebars.js` dependency

Bump ember to `1.11.1`

---

packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/tests/unit/adapters/build-url-mixin/path-for-type-test.js

Somehow this was missing from BuildURLMixin :dizzy:

Add missing urlForUpdateRecord to BuildURLMixin

---

packages/ember-data/lib/system/model/model.js
packages/ember-data/tests/integration/records/reload-test.js

Reset Model#isReloading to false when request fails

---

packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/tests/unit/adapters/build-url-mixin/path-for-type-test.js

restore backwards compatibility of buildURL

---

packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/unit/model/merge-test.js

@igorT requested changes and test

minor adjustments and tests for snapshot creation refactor

---

packages/ember-data/tests/unit/store/get-by-id-test.js

Closes https://github.com/emberjs/data/issues/3161

add test for Store#getById

---

packages/ember-data/tests/unit/adapter-populated-record-array-test.js
packages/ember-data/tests/unit/record-arrays/filtered-record-array-test.js

add missing tests for record arrays

---

packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/lib/adapters/fixture-adapter.js
packages/ember-data/lib/adapters/rest-adapter.js
packages/ember-data/lib/serializers/embedded-records-mixin.js
packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/model/errors.js
packages/ember-data/lib/system/normalize-model-name.js
packages/ember-data/lib/system/record-array-manager.js
packages/ember-data/lib/system/record-arrays/record-array.js
packages/ember-data/lib/system/relationships/ext.js
packages/ember-data/lib/system/serializer.js
packages/ember-data/lib/system/snapshot.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/transforms/base.js

Fix JSDoc issues

---

packages/ember-data/lib/system/model/attributes.js
packages/ember-data/lib/system/model/model.js
packages/ember-data/lib/system/record-array-manager.js

Fix more JSDoc issues

---

packages/ember-data/tests/unit/model/relationships-test.js

* eachRelatedType()
* relationshipNames
fixes #3163

add missing tests DS.Model

---

packages/ember-data/tests/integration/adapter/serialize-test.js

This is a first stab at adding a test for DS.Adapter#serialize.
Would appreciate feedback on:
- is this the right place for the test? (did not find a good candidate in the existing files)
- am I testing at the right level? was not quite able to figure out how to unit-test this..
Closes https://github.com/emberjs/data/issues/3150

Add a test for DS.Adapter#serialize

---

packages/ember-data/lib/system/relationships/state/belongs-to.js
packages/ember-data/tests/integration/relationships/belongs-to-test.js

fix belongs-to when set with a resolved promise

---

packages/ember-data/lib/system/model/states.js
packages/ember-data/tests/unit/model/merge-test.js

This pr is a rebased version of https://github.com/emberjs/data/pull/2943

DirtyState.invalid handle pushedData event

---

packages/ember-data/lib/system/store.js

Fix doc for Store#findHasMany

---

packages/ember-data/lib/serializers/rest-serializer.js

fixes https://github.com/emberjs/data/issues/3231

Use dasherized modelName to fetch serializer

---

packages/ember-data/tests/integration/adapter/rest-adapter-test.js

http://stackoverflow.com/questions/30680516/ember-data-1-0-0-beta-19-store-find-returns-ds-internalmodel-instances

add test asserting findAll resolves with DS.Models

---

packages/ember-data/lib/system/store.js

Related to:
* https://github.com/emberjs/ember.js/pull/11366
* https://github.com/emberjs/ember.js/pull/11368

Use Ember._Backburner if present instead of Ember.Backburner.

---

CHANGELOG.md

Closes https://github.com/emberjs/data/issues/3256

Update changelog to mention new Instance Initializer

---

packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/serializer-response.js

Fix for passing json api objects into push

---

ember-data-source.gemspec

Close https://github.com/emberjs/data/issues/3252

Allow ember-source 2.x

---

README.md

Removed a lonely 'n' char from the first paragraph.

Fixed a small typo in readme.md

---

packages/ember-data/lib/system/store.js

cc/ @bmac, I think it was a small bad copy paste in https://github.com/emberjs/data/pull/3312/files#diff-1636bea36bbe333a834ea11fbfbde48dR569

Use 'findRecord' instead of 'find' in doc

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/integration/store-test.js

fix deprecation warning for store.fetch

---

packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/store.js
packages/ember-data/lib/system/store/serializer-response.js
packages/ember-data/tests/integration/store-test.js
packages/ember-data/tests/unit/model/lifecycle-callbacks-test.js
packages/ember-data/tests/unit/store/push-test.js

This is a rebased version of https://github.com/emberjs/data/pull/3272

Convert internal representation to JSONApi

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/tests/integration/store/query-record-test.js

Add hooks in serializer for queryRecord method

Add new normalizeQueryRecordResponse

---

packages/ember-data/lib/system/adapter.js
packages/ember-data/lib/system/snapshot-record-array.js
packages/ember-data/lib/system/store.js
packages/ember-data/tests/unit/store/adapter-interop-test.js

This will be moved into `shouldReloadAll` in Ember Data 2.0

Remove the logic to always fetch all the records the first time.

---

packages/ember-data/lib/system/adapter.js
packages/ember-data/tests/integration/adapter/find-test.js

Fix deprecation message for store.shouldReloadAll

---

packages/ember-data/lib/system/store.js
packages/ember-data/tests/unit/store/push-test.js

This fixes a regression that was introduces in eef10be

store.push should support arrays in the JSONAPI data property

---

package.json

There are some important fixes in 1.6.2
https://github.com/stefanpenner/ember-inflector/commits/master

update ember-inflector to 1.6.2

---

packages/ember-data/lib/system/adapter.js
packages/ember-data/tests/integration/adapter/find-test.js

Fix minor typo in deprecation warning

---

packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/tests/integration/adapter/json-api-adapter-test.js

[BUGFIX release] Correctly serialize type for hasMany relationships

---

CHANGELOG.md

The link to my github profile accidentally got part of the branch name in it.

Fix broken link

---

packages/ember-data/lib/system/model/errors.js

update errors.js docs to mirror new json api error specs

---

packages/ember-data/lib/system/model/internal-model.js

[DOC release] Fix documentation for DS.InternalModel#_changedKeys()

---

packages/ember-data/lib/system/store/finders.js
packages/ember-data/lib/system/store/serializer-response.js
packages/ember-data/lib/system/store/serializers.js
packages/ember-data/tests/integration/adapter/store-adapter-test.js

Fixes https://github.com/emberjs/data/issues/3427

[BUGFIX release] Do not assume the serializer is an Ember object.

---

packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/lib/serializers/json-serializer.js

This should take care of #3471 :)

Add modelClass argument to JSONSerializer.extractId

---

packages/ember-data/lib/system/record-arrays/filtered-record-array.js

https://github.com/emberjs/ember.js/commit/8ecc3bd04945be46873f734279f55034952f33f0

Reversed args in Ember.Observer

---

packages/ember-data/lib/adapters/build-url-mixin.js

Adding examples for URL methods

---

packages/ember-data/lib/system/snapshot-record-array.js

[DOC release] Adding documentation for SnapshotRecordArray

---

README.md

- Adds missing types for `DS.attr`s
- Use dasherized model names
- Use `store.findRecord` to fetch a single record

[DOC release] Update README examples

---

packages/ember-data/lib/system/serializer.js

[DOC release] make normalizeResponse show up in the API docs

---

packages/ember-data/lib/adapters/build-url-mixin.js
packages/ember-data/tests/unit/adapters/build-url-mixin/path-for-type-test.js

fixes https://github.com/emberjs/data/issues/3607
~~I wasn't sure which branch this should be opened against. What's the protocol when something needs to go into master as well as release?~~

[BUGFIX release] Add missing urlForFindQueryRecord to BuildUrlMixin

---

packages/ember-data/lib/adapters/build-url-mixin.js

[DOC release] fix urlForFindRecord documentation

---

package.json

botched other PR
https://github.com/stefanpenner/ember-inflector/pull/84

[BUGFIX release] Update ember-inflector to 1.9.0

---

bower.json
config/package-manager-files/bower.json

[BUGFIX beta] Update the dependencies for Ember 2.0

---

packages/ember-data/lib/adapters/rest-adapter.js

Proposing a change to decorator-style CPs in an example in the RESTAdapter api docs.

[DOC beta] Change to decorator-style CPs in RESTAdapter API doc samples

---

packages/ember-data/lib/system/model/internal-model.js
packages/ember-data/lib/system/model/model.js

cc @stefanpenner @igorT This fixes the two comments that were made on the PR after it was merged.

follow up fixes for #3701

---

package.json

This pulls in a much needed fix for older browsers (see: #3752 and stefanpenner/ember-inflector#89 ).
@bmac I wasn't sure if I should also issue the same PR against master or if you'd cherry-pick it over there. Happy to open the PR. Thanks again!

Bumped the ember-inflector version to 1.9.2. 

---

packages/ember-data/lib/serializers/json-serializer.js
packages/ember-data/lib/system/store.js

- Fixes [#3750](https://github.com/emberjs/data/issues/3750)

Remove normalizePayload, associated docs, and mention of functionality.

---

packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/tests/integration/serializers/json-api-serializer-test.js

[BUGFIX beta] JSONAPISerializer warns for unknown type

---

packages/ember-data/lib/system/relationships/state/belongs-to.js
packages/ember-data/lib/system/relationships/state/has-many.js
packages/ember-data/lib/system/relationships/state/relationship.js
packages/ember-data/tests/integration/relationships/belongs-to-test.js
packages/ember-data/tests/integration/relationships/has-many-test.js

This improves the way we fetch links depending on if we have local data or not.
Fixes #3380

[BUGFIX release] Improve links vs. local data for relationships

---

appveyor.yml

run optional feature tests on AppVeyor

---

CHANGELOG.md

This release is written at the above section.

Remove dup of release note for 2.0.1

---

packages/ember-data/lib/serializers/json-serializer.js

Fixes some minor syntax/grammar issues and things I found confusing in the docs.

[DOCS] Improve docs for JSONSerializer

---

tests/ember-configuration.js

This is the rebased version of #3233

raise errors on deprecation

---

packages/ember-data/lib/system/model/errors.js

Also added a link to the error object spec.

Fix DS.Errors summary and error object example

---

packages/ember-data/lib/adapters/errors.js

Credit to @wecc for noticing the issue

[DOC fix] errors pointers should start with a /

---

tests/integration/adapter/find-test.js

* Use ES6 `() =>` where applicable
* Remove unnecessary `Ember.` and `Ember.RSVP` prefixes
* Remove ignored closure parameters
* One-line adapater overrides when possible

[CLEANUP] `tests/integration/adapter/find-test.js`

---

addon/system/store.js

Mark `adapterFor` and `serializerFor` as public

---

lib/javascripts.js

refs https://github.com/components/ember-data/issues/32

[BUGFIX beta] create an empty sourcemap for bower users

---

addon/system/store.js

Just a small update to the new syntax.

[DOC beta] Use findRecord syntax in unloadRecord documentation

---

addon/serializers/embedded-records-mixin.js

[DOC fix] Adds missing space before list

---

addon/system/store/finders.js
tests/integration/store-test.js

Closes #3950 
cc @workmanw @wecc

Add a better error message when findRecord returns an array

---

addon/system/store.js

This is a rebased version of https://github.com/emberjs/data/pull/3854

Merge normalizeRelationships and setupRelationships methods in store

---

addon/serializers/json-serializer.js
addon/serializers/rest-serializer.js

This is a rebased version of https://github.com/emberjs/data/pull/3660

Added documentation to modify the hash by reference

---

packages/ember-data/tests/integration/records/error-test.js

This is a rebased version of https://github.com/emberjs/data/pull/3723. The original pr failed because of a jshint error.

tests for #3707

---

tests/integration/records/error-test.js

Also update test structure using `ember watson:upgrade-qunit-tests`.

[CLEANUP] move test file to correct location

---

tests/unit/store/create-record-test.js

Closes https://github.com/emberjs/data/issues/3969
This test has been obsolete since #3033

Remove duplicate createRecord test

---

package.json

Fixes bugs when pluralization involves floats.
See https://github.com/stefanpenner/ember-inflector/pull/97

[BUGFIX beta] bump ember-inflector

---

addon/-private/serializers/embedded-records-mixin.js

don't cache length in for loops

---

blueprints/adapter/index.js
blueprints/serializer/files/__root__/__path__/__name__.js
node-tests/blueprints/serializer-test.js

This addresses ember-cli/ember-cli#4787.

Use JSON-API adapter and serializer in blueprints

---

addon/-private/serializers/json-serializer.js
tests/integration/serializers/json-serializer-test.js

This is a rebased version of pr #3956

[BUGFIX beta] ignores keys that are not found in the map

---

LICENSE
generators/license.js

:fireworks: :tada: :fireworks:

Happy New Year!

---

appveyor.yml

Run optional feature tests and node tests (testing blueprints) on AppVeyor too, so we get some feedback if everything runs smoothly on Windows.
:trollface:

Run node tests and optional feature tests on AppVeyor

---

ember-data-source.gemspec

In favor of https://github.com/emberjs/data/issues/3650

Require ember-source 2.x

---

lib/calculate-version.js
lib/version-replace.js
lib/version.js
lib/yuidoc.js
package.json

Fixes https://github.com/emberjs/data/issues/4062.

Use correct version number when used as an addon.

---

ember-data-source.gemspec

This PR and https://github.com/emberjs/data/pull/4072 will fix https://github.com/emberjs/data/issues/4069.

[BUGFIX release] Add missing dist source to gem

---

addon/-private/serializers/embedded-records-mixin.js

keyForRelationship arguments are(key, typeClass, method)

Fix calls to keyForRelationship in embedded records

---

package.json
packages/ember-data/lib/serializers/json-api-serializer.js
packages/ember-data/lib/serializers/rest-serializer.js
packages/ember-data/lib/system/relationship-meta.js

Correcting the import usage fixes which resolver is used so users can provide their own inflections.
Fixes https://github.com/emberjs/data/issues/4142

[bugfix release-1-13] update ember-inflector and correct import usage

---

addon/adapters/rest.js

Based on this comment https://github.com/emberjs/data/pull/3930#discussion_r54583988

[DOC beta] Fix error message internal docs

---

lib/babel-build.js

seems to fix:
* https://github.com/ember-cli/ember-cli/issues/5638
not quite sure how https://github.com/emberjs/data/pull/4214 worked
cc @chadhietala

fix prod-build issue

---

addon/-private/system/model/internal-model.js
addon/-private/system/store/container-instance-cache.js
addon/serializers/json.js
tests/helpers/start-app.js

Closes https://github.com/emberjs/data/issues/4233.

[BUGFIX beta] Use Ember.assign when availability

---

addon/-private/system/store.js

The push method only accepts one parameter.

Fix example code on normalize method

---

tests/integration/adapter/rest-adapter-test.js

Change `precdence` to `precedence`

fix rest-adapter-test typo

---

CONTRIBUTING.md

Addresses the latest comment on https://github.com/emberjs/data/issues/4238#issuecomment-198482078 for adding feature-flags for new features

[DOC] Update CONTRIBUTING.md for feature flags

---

README.md

This PR improve ES6 syntax on [defining of model](https://github.com/emberjs/data#defining-your-models)

[DOC] Update README.md for improve ES6 syntax in example

---

addon/serializers/embedded-records-mixin.js

(will fix highlighting in docs)

[DOC] fix example syntax

---

FEATURES.md

This makes it easier to navigate to a feature to see its implementation
and additional context.

[DOC] Add link to PR's for every feature

---

addon/-private/system/store.js
tests/integration/store-test.js

Fixes https://github.com/emberjs/data/issues/3772
This adds support for controlling when records are reloaded in the
background to `store.findRecord()` and `store.findAll()`.
If you would like to force or prevent background reloading, you can set a
boolean value for `backgroundReload` in the options object for
`findRecord`.
```javascript
import Ember from 'ember';
export default Ember.Route.extend({
model: function(params) {
return this.store.findRecord('post', params.post_id, { backgroundReload: false });
}
});
```
If you would like to force or prevent background reloading, you can set a
boolean value for `backgroundReload` in the options object for
`findAll`.
```javascript
import Ember from 'ember';
export default Ember.Route.extend({
model: function() {
return …
```

Add `backgroundReload` option to `store.findRecord` & `store.findAll`

---

addon/-private/system/model/model.js
addon/-private/system/store.js

Closes https://github.com/emberjs/data/issues/4303

[BUGFIX beta] Document the adapterOptions property

---

tests/dummy/app/index.html

I kept getting confused between Ember Data's tests and an addon I had been testing.

Ember Data is no Dummy 😎

---

addon/adapters/rest.js
tests/integration/adapter/rest-adapter-test.js

[BUGFIX beta] Fixes issue with GET requests appending ?{} to url

---

blueprints/adapter/index.js
blueprints/model/files/__root__/__path__/__name__.js
blueprints/model/index.js
blueprints/serializer/files/__root__/__path__/__name__.js
blueprints/transform/files/__root__/__path__/__name__.js
node-tests/blueprints/adapter-test.js
node-tests/blueprints/model-test.js
node-tests/blueprints/serializer-test.js
node-tests/blueprints/transform-test.js

This commit is specifically targeting the 2.5 branch since changes
since 2.5 made it difficult to cherry-pick the changes from
https://github.com/emberjs/data/pull/4481 to this branch.
cc @pangratz

[BUGFIX release] Update the blueprints to import the DS namespace

---

addon/-private/system/store.js
addon/serializers/json-api.js
addon/serializers/rest.js

This updates the API docs to match the blueprints after https://github.com/emberjs/data/pull/4481

[BUGFIX beta] Update API docs to import DS from 'ember-data'

---

.npmignore

Adds `/bin` and `/docs` to .npmignore.

Addresses #4492

---

addon/adapters/rest.js
tests/integration/adapter/rest-adapter-test.js

This pr attempts to fix the issues identified in https://github.com/emberjs/data/issues/4488 by wrapping the ajax success/error code in a try/catch.
cc @stefanpenner @pangratz for review.

[BUGFIX beta] Fix Brittle Promise Usage

---

addon/-private/system/model/model.js
addon/-private/system/store.js

[DOC] clarify docs on Model#modelName and Store#modelFor

---

FEATURES.md

Spotted a small typo when looking through [Features](https://github.com/emberjs/data/blob/master/FEATURES.md)

[DOC] fix features response typo

---

addon/-private/system/store.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/adapter/store-adapter-test.js
tests/integration/client-id-generation-test.js
tests/integration/relationships/has-many-test.js
tests/integration/store-test.js
tests/unit/model-test.js

Revert "Log an assertion if the response from createRecord does not have an i…"

---

README.md

Believe this is out of date at this point

[DOC] Update Readme to reflect new default adapter

---

addon/serializers/json-api.js

Docs: typo

---

addon/-private/system/store.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/adapter/store-adapter-test.js
tests/integration/client-id-generation-test.js
tests/integration/relationships/has-many-test.js
tests/integration/store-test.js
tests/unit/model-test.js

New PR to replace https://github.com/emberjs/data/pull/4544

Improved null id assertions

---

addon/serializer.js

[DOC] Minor changes to addon/serializer.js

---

tests/unit/store/push-test.js

Assert that InternalModel is indeed not materialized on store._push

---

addon/-private/system/store.js

Fixes: https://github.com/emberjs/data/issues/4595

[DOC] #4595 revise unloadAll description

---

server/models/baz.js
server/models/complex.js
server/models/foo.js
server/models/heavy-baz.js
server/models/heavy-foo.js
server/models/heavy.js
server/models/simple.js
server/scenarios/default.js

My previous PR to update the mock server apparently missed a commit, leaving it broken and no one noticed until I ran new benchmarks :'( This fixes them.

fix mock server

---

tests/integration/records/delete-record-test.js

This slipped in https://github.com/emberjs/data/pull/4670

Fix typo in delete-record-test

---

addon/-private/system/model/states.js
addon/-private/system/store.js

store.reloadRecord => store._reloadRecord

Underscores the already private store.reloadRecord method

---

generators/license.js

Amend the generated license text to say "2017".
Also: Thanks for Ember Data.

License: 2017

---

addon/adapters/rest.js

https://github.com/emberjs/guides/pull/1770

Updates code sample to match Guides

---

addon/-private/system/store.js

Basing this on https://github.com/emberjs/data/blob/master/addon/-private/system/store/finders.js#L144
Would love feedback on how this could be better.

Document cache/request behavior of `query` #4733

---

addon/-private/system/store.js

See https://github.com/emberjs/data/pull/4765 for reference

[DOC] Update store.unloadRecord description

---

addon/-private/system/clone-null.js
addon/-private/system/debug/debug-adapter.js
addon/-private/system/empty-object.js
addon/-private/system/many-array.js
addon/-private/system/model/errors.js
addon/-private/system/ordered-set.js
addon/-private/system/promise-proxies.js
addon/-private/system/references/belongs-to.js
addon/-private/system/references/has-many.js
addon/-private/system/references/record.js
addon/-private/system/relationship-meta.js
addon/-private/system/relationships/belongs-to.js
addon/-private/system/relationships/ext.js
addon/-private/system/relationships/has-many.js
addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/relationship.js
addon/-private/system/store/finders.js
addon/-private/system/store/serializers.js

Linting changes for addon/-private/system

[CLEANUP Beta] Linter changes for addon/-private/system

---

tests/integration/relationships/has-many-test.js

This tests currently passes on master and 2.10 since the issue is fixed on those 2 branches. It fails on the `beta` and `release` branches.

Add a test for #4770

---

addon/-private/system/store.js

* findMany already returns Promise.all (which unwraps)

don’t create extra internal promise objects

---

tests/unit/adapters/build-url-mixin/path-for-type-test.js
tests/unit/adapters/json-api-adapter/ajax-test.js
tests/unit/adapters/rest-adapter/ajax-test.js
tests/unit/adapters/rest-adapter/build-query-test.js
tests/unit/adapters/rest-adapter/detailed-message-test.js
tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
tests/unit/model/errors-test.js
tests/unit/model/lifecycle-callbacks-test.js
tests/unit/model/merge-test.js
tests/unit/model/relationships-test.js
tests/unit/model/relationships/belongs-to-test.js
tests/unit/model/relationships/has-many-test.js
tests/unit/model/relationships/record-array-test.js
tests/unit/model/rollback-attributes-test.js
tests/unit/record-arrays/filtered-record-array-test.js
tests/unit/record-arrays/record-array-test.js

more test cleanup, specifically targetting:
* correct promise/run loop usage
* no dangling errors/promises
* consistent ES6 usage

Stefs cleanup

---

addon/-private/system/model/model.js

At http://emberjs.com/api/data/classes/DS.Model.html#method_inverseFor
Before:
After:

[DOC] Fix markup for example code of `DS.Model#inverseFor`

---

addon/-private/system/model/model.js

This is JoeTurbo crap, we can hopefully get rid of soon.

[PERF] let GUID_KEYS just be set on the model instances

---

addon/-private/system/many-array.js

The last call site of this private code was removed in 4de331554a02bd1a8f8c3f37cb78f2ea92f2467f.

Remove dead code

---

addon/-private/system/many-array.js
addon/-private/system/relationships/has-many.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js

More record -> internalModel fixes

---

lib/javascripts.js

Also addresses #4873
Canary version of #4875

[BUGFIX beta] ensure the globals build has the correct context in the iife.

---

lib/javascripts.js

[BUGFIX release] ensure the globals build has the correct context in the iife.

---

README.md

Fixes a typo in the README.md file - "First things first"

Fix readme typo - "First things first"

---

CONTRIBUTING.md

Closes https://github.com/emberjs/data/issues/4238 by tackling the last remaining item:

[DOCUMENTATION] Refer the RFC process for requesting new features

---

addon/-private/system/store.js

This just adds some documentation describing the caching behavior of `queryRecord`
Reference: https://github.com/emberjs/data/issues/4733

[DOC] Documents the caching behavior of queryRecord

---

addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js

Fixes https://github.com/emberjs/data/issues/4755

Remove unnecessary relationship guard

---

addon/-private/instance-initializers/initialize-store-service.js

Before we made three passes:
- map
- filter
- forEach
Now we make one.

[PERF] single-pass over the initializers array

---

addon/-private/system/store/container-instance-cache.js

[BACKPORT 4913] For release

---

addon/-private/system/relationships/ext.js

Remove no-longer-working private API usage.

---

tests/dummy/app/routes/query/route.js

dummy app routes should work with and without heimdall

---

index.js

[BUGFIX] remove forgotten broccoli-stew import

---

.travis.yml
package.json

(cherry picked from commit a36a44ff207a3167b0582ce20c15810126ef3676)

such travis

---

CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
FEATURES.md
README.md
addon/-private/system/model/model.js
addon/-private/system/relationships/belongs-to.js
addon/-private/system/store.js
addon/-private/system/store/finders.js
addon/serializers/json-api.js
blueprints/model/index.js
tests/integration/inverse-test.js

Now emberjs website is served via https. emberjs/website#2828

Use https in references to emberjs website

---

addon/-private/system/store.js

- store#filter() is now deprecated
- Don't suggest it's usage

[BACKPORT] Update doc for deprecated function.

---

addon/-private/system/model/internal-model.js
tests/integration/relationships/has-many-test.js

[BACKPORT 2 BETA] Beta fix unload after destroy

---

addon/-private/system/model/internal-model.js
tests/integration/relationships/has-many-test.js

[BACKPORT 2 release] Release fix unload after destroy

---

addon/-private/system/model/internal-model.js
addon/-private/system/relationships/state/create.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
tests/integration/records/rematerialize-test.js
tests/integration/relationships/has-many-test.js
tests/integration/store-test.js
tests/unit/model/relationships/has-many-test.js

https://github.com/emberjs/data/pull/5092 but for the beta branch

{BETA} unload fun

---

addon/-private/system/model/internal-model.js
addon/-private/system/store.js
tests/integration/records/unload-test.js

https://github.com/emberjs/data/pull/5102

{Beta} forward port

---

LICENSE

Update LICENSE through 2017

---

.travis.yml
appveyor.yml
node-tests/unit/babel-plugin-remove-imports-test.js
package.json
yarn.lock

add test coverage for more node versions (node 4)

---

addon/-private/system/model/errors.js
tests/integration/records/error-test.js

[BUGFIX beta] setProperties to clear errors works

---

addon/-private/system/references/belongs-to.js
addon/-private/system/references/has-many.js
addon/serializers/json-api.js

[DOC beta] update deprecation references

---

blueprints/model-test/index.js
blueprints/model-test/mocha-files/tests/unit/__path__/__test__.js
blueprints/model-test/qunit-files/tests/unit/__path__/__test__.js
blueprints/model-test/qunit-rfc-232-files/tests/unit/__path__/__test__.js
node-tests/blueprints/model-test.js
node-tests/fixtures/model-test/rfc232.js

See https://github.com/emberjs/data/issues/5292
Also updated `friendlyDescription` to `friendlyTestDescription` to match the other blueprints

bluepints/model-test: Add RFC232 variants

---

blueprints/model-test/qunit-rfc-232-files/tests/unit/__path__/__test__.js
node-tests/fixtures/model-test/rfc232.js

I missed this during review of #5297.

Fixup the RFC232 model-test files.

---

benchmarks/BenchmarkGuide.md
benchmarks/config.js
package.json
server/scenarios/default.js
yarn.lock

keeps it working and starts some docs

[CHORE] updates to benchmark harness

---

tests/integration/references/belongs-to-test.js

This is a failing test for #5134.
This is my first Contribution to ember-data. If I should change something please tell me!

failing test for reference when id is procided

---

addon/-private/system/model/model.js
addon/-private/system/relationships/ext.js

[BUGFIX] Object.values is not available in IE11 and some other random environments yet

---

tests/integration/relationships/one-to-many-test.js

Remove extra parameter from assert.equal that was causing issues on travis

Fix travis timeout issues on master branch

---

CONTRIBUTING.md

Fixes https://github.com/emberjs/data/issues/5358

Update ember twiddle links to working versions

---

addon/adapters/json-api.js
addon/adapters/rest.js

Remove $.parseJSON usage

---

tests/integration/adapter/rest-adapter-test.js

Remove jQuery usage from tests

---

addon/-private/system/model/states.js
tests/unit/model/rollback-attributes-test.js

Rebased version of https://github.com/emberjs/data/pull/4468

update states to trigger rollback. update tests.

---

addon/adapters/json-api.js
addon/adapters/rest.js

[CHORE] remove dead methods left behind from ff removal

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
tests/unit/model-test.js

Rebase of https://github.com/emberjs/data/pull/4949

remove `id` observer from DS.Model

---

.npmignore
.travis.yml

cc @rwjblue @kategengler @bmac

Fix npmignore and cleanup test artifacts before publishing

---

addon/-private/system/internal-model-map.js
tests/integration/records/unload-test.js
tests/unit/store/unload-test.js

also formats quotes for consistency
@runspired I rebased this but am also stealing your work :). I can submit the other branch to preserve attribution.

improve tests for unloading relationships

---

addon/-private/system/snapshot.js
tests/integration/snapshot-test.js

Cherry-pick #5428 to the beta branch: fixes https://github.com/emberjs/data/issues/5493.

[BUGFIX] make snapshot lazier and fix defaultValue

---

tests/integration/records/save-test.js

Adding a test to verify saving behavior: #3780

[BUGFIX] Adding tests to assert exception when saving unloaded record

---

package.json
yarn.lock

Fixes: #5529 
No changes required to `import` statements

[BUGFIX beta] Upgrading ember-inflector to v3.0.0

---

addon/serializers/json-api.js
tests/integration/serializers/json-api-serializer-test.js

Serialize empty hasMany relationships

---

addon/-legacy-private/system/many-array.js
addon/-legacy-private/system/model/states.js
addon/-legacy-private/system/references/belongs-to.js
addon/-legacy-private/system/references/has-many.js
addon/-legacy-private/system/store.js
addon/-private/adapters/build-url-mixin.js
addon/-private/adapters/errors.js
addon/-private/system/model/errors.js
addon/-private/system/references/record.js
addon/-record-data-private/system/many-array.js
addon/-record-data-private/system/model/states.js
addon/-record-data-private/system/references/belongs-to.js
addon/-record-data-private/system/references/has-many.js
addon/-record-data-private/system/store.js
addon/adapter.js
addon/adapters/json-api.js
addon/adapters/rest.js
addon/serializers/embedded-records-mixin.js
addon/serializers/rest.js
addon/transforms/boolean.js
addon/transforms/transform.js

I went through the documentation and fixed typos, grammar errors and tried to make spelling a bit more consistent.

Grammar fixes

---

addon/adapters/rest.js

[BUGFIX] use xhr.textStatus not xhr.statusText

---

addon/-private/system/store.js

Please see #5467  for further details.

[BUGFIX Backport] #5467 to 2.18

---

.travis.yml
RELEASE.md
package.json
yarn.lock

[FEAT #5607] Improve Travis Config to help keep Release branches stable

---

.travis.yml
appveyor.yml
config/ember-try.js
package.json
testem.js
yarn.lock

[FEAT #5607] ensure release builds only perform necessary jobs

---

addon/-private/system/model/internal-model.js
addon/-private/system/snapshot.js
addon/-private/system/store.js
tests/helpers/deep-copy.js
tests/integration/adapter/build-url-mixin-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/store-test.js
tests/unit/system/relationships/polymorphic-relationship-payloads-test.js

Port this commit: 23a87e8e7a7cd39e33ef877148f7d9e8f103c2ab

Backport copy usage removal to 3.1

---

.travis.yml
addon/-private/system/model/internal-model.js
addon/-private/system/ordered-set.js
appveyor.yml
tests/dummy/config/targets.js
tests/integration/store-test.js
tests/unit/model-test.js
tests/unit/model/rollback-attributes-test.js

Port #5557 to release branch 3.3
Related issue here #5576

Backport @ember/ordered-set fix to 3.3

---

.travis.yml
addon/-private/system/model/internal-model.js
addon/-private/system/ordered-set.js
tests/dummy/config/targets.js
tests/integration/store-test.js
tests/unit/model-test.js
tests/unit/model/rollback-attributes-test.js

Port #5557 to release branch 3.2
Related issue here #5576

Backport @ember/ordered-set fix to 3.2

---

.travis.yml

[CHORE] improve CI time by optimizing job order

---

node-tests/blueprints/adapter-test.js

I accidentally committed this with #5654 🤕

remove .only

---

addon/serializers/json.js

Resolves #5623 
Added check for polymorphic relationship.

Added check to extract polymorphic relationship for hasMany (#5623)

---

addon/-private/system/store.js

update/remove rails/backend references in documentation

---

addon/-private/system/model/record-data.js

remove old feature-flag

---

tests/integration/peek-all-test.js

[CHORE tests] modernize integration/peek-all-test

---

tests/integration/client-id-generation-test.js

[CHORE tests] modernize integration/client-id-generation-test

---

addon/-private/attr.js
addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/relationship-meta.js
addon/-private/system/relationships/belongs-to.js
addon/-private/system/relationships/ext.js
addon/-private/system/relationships/has-many.js
tests/unit/model-test.js
tests/unit/model/lifecycle-callbacks-test.js

[BUGFIX CHORE tests] modernize unit/model-test (and some fixes that it uncovered)

---

tests/integration/inverse-test.js
tests/integration/relationships/inverse-relationships-test.js

[CHORE tests] modernize integration/inverse-test

---

addon/-private/attr.ts
addon/-private/index.js
addon/-private/system/many-array.js
addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/model/record-data.js
addon/-private/system/record-data-for.js
addon/-private/system/references/belongs-to.js
addon/-private/system/references/has-many.js
addon/-private/system/references/reference.ts
addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/relationship.js
addon/-private/system/snapshot.js
addon/-private/system/store.js
tests/integration/records/record-data-test.js
tests/integration/records/unload-test.js
tests/integration/relationships/belongs-to-test.js
tests/integration/relationships/has-many-test.js
tests/unit/model-test.js

isolate accessing recordData and relationships in tests

---

addon/-private/system/relationships/belongs-to.js
addon/serializers/embedded-records-mixin.js
addon/serializers/json-api.js

It fixes the broken `toc_` links. 
_Note: I haven't reviewed other type of links._

[DOC beta] Fix broken links

---

addon/-private/system/identity-map.ts
addon/-private/system/internal-model-map.ts
package.json
types/dummy/index.d.ts
yarn.lock

// ... please delete this default text after reading
If this is your first PR to `ember-data`, you may want to read our [Contributor Guide](https://github.com/emberjs/data/blob/master/CONTRIBUTING.md).

[CHORE ts] A couple of dabblings to start us down the road

---

addon/-private/system/identity-map.ts
addon/-private/system/internal-model-map.ts
addon/-private/types.ts

Address late feedback from #5727

---

.npmignore

Revert "Add *.ts to `.npmignore`"

---

addon/-private/system/model/internal-model.js
tests/integration/records/record-data-test.js

[BUGFIX beta] backport #5767 Make _recordData lazy

---

addon/serializers/json.js

[DOC] link to JSON API error specs

---

addon/serializers/embedded-records-mixin.js

Reverts emberjs/data#5874
cc @yusufsagdic didn't realize this was a PR against `release`, could you please make this PR against the master branch?

Revert "[DOC serializeHasMany ] Fixed import ember-data lines"

---

addon/-private/system/model/model.js
addon/adapter.js

Fixes emberjs#5803
Missing type param in generateIdForRecord api doc

[DOCS] [BUGFIX] generateIdForRecord api doc 

---

addon/-private/system/references/record.ts

Fixes #5808
Added type to push data with value "user"

[DOCS] [BUGFIX] recordRef push param must be with type

---

addon/-private/system/store/finders.js
tests/integration/relationships/inverse-relationship-load-test.js

fix: ensure missing resource linkage isn't normalized incorrectly

---

addon/-private/system/store/finders.js
tests/integration/adapter/find-test.js

see https://github.com/emberjs/data/pull/5901 for details

fix: coerce ids before warning for mismatch

---

index.js

// ... please delete this default text after reading
If this is your first PR to `ember-data`, you may want to read our [Contributor Guide](https://github.com/emberjs/data/blob/master/CONTRIBUTING.md).

glob is wasteful, simply capture the one directory we want.

---

addon/adapters/rest.js
tests/integration/adapter/rest-adapter-fetch-test.js

[BUGFIX useFetch] clean up the WTFs

---

package.json

As it doesn't seem to be used 😄
Supersedes https://github.com/emberjs/data/pull/5939

[chore] Remove semver dependency

---

.eslintignore
.eslintrc.js
.gitignore
.npmignore
CONTRIBUTING.md
README.md
testem.js

This PR modernizes slightly a few doffiles.

[chore] Run a `ember init`

---

packages/adapter/addon/json-api.js

Please, find additional info here: https://github.com/emberjs/data/commit/f26d07b62e4240f723a822b73d5a196ebee8de22

[fix] Add json:api header on every requests

---

.travis.yml

see https://github.com/emberjs/data/pull/6018

Adjust travis CI on release / lts

---

packages/-ember-data/tests/integration/adapter/queries-test.js
packages/-ember-data/tests/integration/adapter/rest-adapter-fetch-test.js
packages/-ember-data/tests/integration/debug-adapter-test.js
packages/-ember-data/tests/integration/records/relationship-changes-test.js
packages/-ember-data/tests/unit/record-arrays/record-array-test.js

Some misc lint and assertion cleanup I've extracted from a different PR where it just adds noise.

[CHORE tests] misc test cleanup

---

packages/-ember-data/tests/helpers/public-props.js
packages/-ember-data/tests/integration/record-data/record-data-test.ts
packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts

Add tests for custom RecordData relationship handling.

RecordData Relationship Tests

---

addon/-private/adapters/errors.js

[BUGFIX lts] Fix this.stack assignement in AdapterError

---

addon/adapters/rest.js

[BUGFIX jQuery] avoid jQuery deprecation notice for intentional use

---

packages/store/addon/-private/system/record-arrays/record-array.js

Fix the issue https://github.com/ember-learn/ember-api-docs/issues/591

Fix broken ArrayProxy link on api docs

---

.github/PULL_REQUEST_TEMPLATE.md

Using HTML comments here mean they don't need to delete anything
and simplifies the process a tad bit...

Use HTML comments in PR template.

---

packages/-ember-data/tests/unit/adapters/json-api-adapter/ajax-test.js
packages/-ember-data/tests/unit/adapters/json-api-adapter/fetch-test.js
packages/adapter/addon/json-api.js

[BUGFIX fetch] prevent Accept & ContentType header overwriting (#6062)

---

azure-pipelines.yml
packages/-ember-data/config/ember-try.js
packages/-ember-data/package.json
packages/adapter/addon/-private/index.js
packages/adapter/addon/-private/utils/determine-body-promise.ts
packages/adapter/addon/-private/utils/fetch.ts
packages/adapter/addon/-private/utils/serialize-query-params.ts
packages/adapter/addon/rest.js
yarn.lock

Backport of #6077 to beta branch.
(cherry picked from commit 83c5ee09e18b900cbdc32dcbfd7031df09a9660f)

[BUGFIX release] Remove ember-fetch dependency.

---

packages/adapter/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json

Set repository url for packages

---

index.js

[BUGFIX release] Fix rollup warnings for require as an external module

---

packages/-ember-data/tests/unit/model/relationships-test.js

Converts `unit/model/relationships-test.js` to the new qunit style test format.

[CHORE] Modernize unit/model/relationships-test.js test

---

packages/-ember-data/tests/unit/adapters/build-url-mixin/path-for-type-test.js
packages/-ember-data/tests/unit/adapters/json-api-adapter/ajax-test.js
packages/-ember-data/tests/unit/adapters/json-api-adapter/fetch-test.js
packages/-ember-data/tests/unit/adapters/rest-adapter/ajax-test.js
packages/-ember-data/tests/unit/adapters/rest-adapter/build-query-test.js
packages/-ember-data/tests/unit/adapters/rest-adapter/detailed-message-test.js
packages/-ember-data/tests/unit/adapters/rest-adapter/fetch-test.js
packages/-ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
packages/-ember-data/tests/unit/model/errors-test.js
packages/-ember-data/tests/unit/model/init-properties-test.js
packages/-ember-data/tests/unit/model/lifecycle-callbacks-test.js
packages/-ember-data/tests/unit/model/merge-test.js
packages/-ember-data/tests/unit/model/relationships/belongs-to-test.js
packages/-ember-data/tests/unit/model/relationships/has-many-test.js
packages/-ember-data/tests/unit/model/relationships/record-array-test.js
packages/-ember-data/tests/unit/model/rollback-attributes-test.js
packages/-ember-data/tests/unit/record-arrays/adapter-populated-record-array-test.js
packages/-ember-data/tests/unit/record-arrays/record-array-test.js
packages/-ember-data/tests/unit/store/adapter-interop-test.js
packages/-ember-data/tests/unit/store/create-record-test.js
packages/-ember-data/tests/unit/store/finders-test.js
packages/-ember-data/tests/unit/store/has-model-for-test.js
packages/-ember-data/tests/unit/store/has-record-for-id-test.js
packages/-ember-data/tests/unit/store/model-for-test.js
packages/-ember-data/tests/unit/store/peek-record-test.js
packages/-ember-data/tests/unit/store/push-test.js
packages/-ember-data/tests/unit/store/serializer-for-test.js
packages/-ember-data/tests/unit/store/unload-test.js
packages/-ember-data/tests/unit/system/snapshot-record-array-test.js
packages/-ember-data/tests/unit/utils/parse-response-headers-test.js

Used https://github.com/ember-codemods/ember-qunit-codemod for unit tests.

[CHORE] Converting unit tests to new qunit syntax

---

packages/serializer/addon/-private/embedded-records-mixin.js
packages/serializer/addon/json-api.js
packages/serializer/addon/json.js
packages/serializer/addon/rest.js
packages/serializer/addon/serializer.js
packages/serializer/addon/transforms/boolean.js
packages/serializer/addon/transforms/date.js
packages/serializer/addon/transforms/number.js
packages/serializer/addon/transforms/string.js
packages/serializer/addon/transforms/transform.js

Backport beta/6139

---

packages/adapter/addon/-private/build-url-mixin.js
packages/adapter/addon/adapter.js
packages/adapter/addon/error.js
packages/adapter/addon/json-api.js
packages/adapter/addon/rest.js

Use the @ember-data packages in the adapter API docs (#6138)

---

.gitignore
packages/-ember-data/yuidoc.json

* [CHORE] Igore docs folder
* [DOC @ember-data packages] fix yuidoc generation
backports #6153

Fix yuidoc setup to support the split packages (#6153)

---

packages/store/addon/-private/system/model/model.js

Docs: fixing request->record typo

---

packages/-build-infra/src/addon-build-config-for-data-package.js
packages/-build-infra/src/debug-macros.js
packages/-build-infra/src/features.js
packages/canary-features/.npmignore
packages/canary-features/.watchmanconfig
packages/canary-features/LICENSE.md
packages/canary-features/README.md
packages/canary-features/addon/index.js
packages/canary-features/index.js
packages/canary-features/package.json
packages/store/package.json
yarn.lock

initial support for feature flagging 

---

packages/-ember-data/package.json
packages/-ember-data/stripped-types.d.ts
packages/adapter/package.json
packages/adapter/stripped-types.d.ts
packages/model/package.json
packages/model/stripped-types.d.ts
packages/serializer/package.json
packages/serializer/stripped-types.d.ts
packages/store/package.json
packages/store/stripped-types.d.ts

chore: avoid publishing types

---

packages/-ember-data/package.json
packages/-ember-data/stripped-types.d.ts
packages/adapter/package.json
packages/adapter/stripped-types.d.ts
packages/model/package.json
packages/model/stripped-types.d.ts
packages/serializer/package.json
packages/serializer/stripped-types.d.ts
packages/store/package.json
packages/store/stripped-types.d.ts

chore: avoid publishing types (#6186)

---

packages/-build-infra/src/features.js
packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
packages/canary-features/addon/index.js
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/model/model.js
packages/store/addon/-private/system/model/record-data.ts
packages/store/addon/-private/system/store.js
packages/store/addon/-private/system/store/record-data-store-wrapper.ts
packages/store/addon/-private/ts-interfaces/record-data-store-wrapper.ts
packages/store/addon/-private/ts-interfaces/record-data.ts
packages/store/types/ember/index.d.ts

Record Data State

---

.gitignore

ignore lerna debugging files

---

packages/-build-infra/package.json
packages/-build-infra/src/features.js
packages/canary-features/addon/default-features.js
packages/canary-features/addon/index.js
yarn.lock

See discussion in https://github.com/emberjs/data/pull/6228#issuecomment-509637960.

Use @ember-data/canary-features/default-features module as single source of truth for feature flags

---

azure-pipelines.yml
packages/-ember-data/package.json

Make canary features tests work on Windows

---

packages/adapter/index.js

Fixes https://github.com/emberjs/data/issues/6218

[BUGFIX release] Fix rollup warning for ember-inflector.

---

packages/store/addon/-private/system/store.js

These methods are never referenced from anywhere

chore: eliminate dead code

---

bin/sync-dev-dependency
package.json
packages/-build-infra/package.json
packages/adapter/package.json
packages/canary-features/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json
yarn.lock

chore: ensure * deps are hoisted

---

packages/-ember-data/testem.js

[BETA RELEASE] remove disable-gpu from testem

---

bin/-tarball-info.js
packages/adapter/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json

[CHORE] Release Improvements - no package path, dont add to packages

---

azure-pipelines.yml
packages/-ember-data/tests/unit/model/rollback-attributes-test.js

[CHORE] ensure lint errors are reported correctly on azure

---

packages/store/addon/-private/ts-interfaces/identifier.ts

[CHORE] update identifers cache comment to latest method names

---

packages/serializer/addon/rest.js

Revert "[CHORE] Use model name instead of store in isPrimaryType"

---

packages/-ember-data/tests/integration/records/collection-save-test.js
packages/-ember-data/tests/integration/records/delete-record-test.js
packages/-ember-data/tests/integration/records/error-test.js
packages/-ember-data/tests/integration/records/property-changes-test.js
packages/-ember-data/tests/integration/records/relationship-changes-test.js
packages/-ember-data/tests/integration/records/rematerialize-test.js
packages/-ember-data/tests/integration/records/save-test.js

Part of https://github.com/emberjs/data/issues/6166
This replaces usage of the `setupStore` helper for `tests/integration/records/*`.
cc @runspired

[CHORE tests] Replace setupStore for records integration tests

---

packages/-ember-data/tests/helpers/store.js
packages/-ember-data/tests/integration/references/belongs-to-test.js
packages/-ember-data/tests/integration/references/has-many-test.js
packages/-ember-data/tests/integration/references/record-test.js
packages/-ember-data/tests/integration/relationships/belongs-to-test.js
packages/-ember-data/tests/integration/serializers/json-serializer-test.js
packages/-ember-data/tests/integration/store-test.js
packages/-ember-data/tests/integration/store/query-record-test.js
packages/-ember-data/tests/integration/store/query-test.js

[CHORE tests] Remove explicit -default serializer registration in tests

---

packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts

[CHORE]: add relationshipReferenceFor tests

---

packages/-ember-data/tests/unit/model-test.js
packages/-ember-data/tests/unit/model/relationships-test.js
packages/model/addon/-private/attr.js
packages/model/addon/-private/belongs-to.js
packages/model/addon/-private/has-many.js
packages/model/addon/-private/util.ts
packages/model/package.json

(cherry picked from commit aa05d928737a2832051c8ffd1882d44db399794c)

[BUGFIX beta] Adds support for parenless attr, belongsTo, and hasMany (#6339)

---

bin/-tarball-info.js

[BUGFIX] ensure commit based versioning passes semver

---

bin/publish.js

Also needs backported to BETA, already on `release` where I needed this change to be able to publish.

[BUGFIX] ensure we publish all packages regardless of changes

---

packages/adapter/addon/-private/utils/fetch.ts

resolves #6326 
resolves #6380

[BUGFIX BETA RELEASE] make fetch function JIT

---

packages/adapter/addon/-private/utils/fetch.ts

Backports #6430 to release
* [BUGFIX BETA RELEASE] make fetch function JIT
* ensure pretender can hijack the fetch fn

[BUGFIX RELEASE] make fetch function JIT (#6430)

---

bin/-tarball-info.js
bin/add-dev-dependency
bin/lint-js
bin/packages-for-commit.js
bin/publish.js
bin/sync-dev-dependency
bin/test-external-partner-project.js
package.json

[CHORE] Update execa to v2

---

packages/-build-infra/package.json
packages/-build-infra/src/utilities/edition-detector.js
packages/-test-infra/package.json
packages/-test-infra/src/node-test-helpers/setup-test-environment.js
packages/adapter/package.json
packages/model/blueprints/model/index.js
packages/model/package.json
yarn.lock

(cherry picked from commit 396ae0aabe707247e4da05756d17873d727adbc2)

[BUGFIX beta] Backport: Update edition detection logic.

---

packages/store/addon/-private/identifiers/utils/uuid-v4.ts

Backport crypto fix to beta

---

.github/workflows/main.yml

Make sure lint and basic tests pass before starting other jobs

---

.eslintrc.js
packages/-ember-data/tests/integration/serializers/json-serializer-test.js
packages/-serializer-encapsulation-test-app/.eslintrc.js
packages/model/addon/-private/belongs-to.js
packages/store/addon/-private/system/model/states.js

[CHORE] Fix eslint no-prototype-builtins

---

packages/store/addon/-private/system/references/reference.ts

[DOC] Fix meta example in reference.ts

---

packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/model/shim-model-class.ts
packages/store/addon/-private/system/snapshot.js

[FEATURE] attributesDefintionFor and relationshipsDefinitionFor accept identifiers

---

packages/-serializer-encapsulation-test-app/tests/integration/requests-test.js

[TEST] Complete requests-test for serializer encapsulation

---

packages/-serializer-encapsulation-test-app/tests/integration/relationships-test.js

[TEST] requests relationships tests for serializer encapsulation

---

packages/-serializer-encapsulation-test-app/tests/integration/errors-test.js

For #6460 
Depends on #6451 (fails on serializeIntoHash otherwise) (will have to rebase after that is merged)
Update: Rebased!

Encapsulate serializer errors test

---

packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
packages/adapter/addon/-private/index.js
packages/adapter/addon/-private/utils/serialize-into-hash.js
packages/adapter/addon/json-api.js
packages/adapter/addon/rest.js
packages/store/addon/-private/identifiers/cache.ts
packages/store/addon/-private/system/fetch-manager.ts
packages/store/addon/-private/system/identity-map.ts
packages/store/addon/-private/system/internal-model-map.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/store.ts
packages/store/addon/-private/ts-interfaces/ember-data-json-api.ts
packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts
packages/store/addon/-private/ts-interfaces/utils.ts

[DOC serializer] implements MinimumSerializerInterface (#6451)

---

CHANGELOG.md
packages/adapter/addon/-private/build-url-mixin.js
packages/adapter/addon/rest.js
packages/model/addon/-private/belongs-to.js
packages/serializer/addon/-private/embedded-records-mixin.js
packages/serializer/addon/-private/transforms/boolean.js
packages/serializer/addon/-private/transforms/date.js
packages/serializer/addon/-private/transforms/number.js
packages/serializer/addon/-private/transforms/string.js
packages/serializer/addon/json-api.js
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/model/states.js
packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js

[DOCS] Fix some links

---

.travis.yml
azure-pipelines.yml
packages/-ember-data/config/ember-try.js

Question: Should we also test against Ember 3.12 LTS with jquery?

[TEST BETA CANARY] Test against Ember 3.12 LTS

---

packages/-serializer-encapsulation-test-app/tests/integration/create-record-test.js

[TEST] createRecord test for serializer encapsulation side quest

---

packages/store/addon/-private/system/model/internal-model.ts

Verifies the trigger is a function.  I noticed a couple tests failed but they also failed without the additional guard added. Fixes #6504

Improved guarding in _triggerDeferredTriggers()

---

packages/-ember-data/tests/integration/identifiers/cache-test.ts

Apologies for the mutliple PRs. This is https://github.com/emberjs/data/pull/6488 last follow-up

[CHORE/TESTS] Switch notEqual with strictNotEqual

---

.travis.yml
azure-pipelines.yml
packages/-ember-data/config/ember-try.js

Backport Test against Ember 3.12 LTS (#6502)

---

packages/-serializer-encapsulation-test-app/tests/integration/update-record-test.js

[TEST] updateRecord test for serializer encapsulation side quest

---

packages/-serializer-encapsulation-test-app/tests/integration/serialize-test.js

[TEST] serialize test for serializer encapsulation side quest

---

packages/-serializer-encapsulation-test-app/tests/integration/delete-record-test.js

[TEST] deleteRecord test for serializer encapsulation side quest

---

.yarnrc

https://twitter.com/yarnpkg/status/1177988164432093184

[CHORE] Update yarn policy

---

packages/-serializer-encapsulation-test-app/package.json
packages/-serializer-encapsulation-test-app/tests/integration/delete-record-test.js
packages/-serializer-encapsulation-test-app/tests/integration/normalize-test.js
packages/store/addon/-private/system/core-store.ts

For #6460 
I noticed the error message for when you don't define serializer#normalize is confusing and seems like an Ember-Data internal error rather than a user error, so added an assertion.

[TEST] normalize test for serializer encapsulation side quest

---

package.json
packages/-adapter-encapsulation-test-app/package.json
packages/-debug-encapsulation-test-app/package.json
packages/-ember-data/package.json
packages/-fastboot-test-app/package.json
packages/-model-encapsulation-test-app/package.json
packages/-record-data-encapsulation-test-app/package.json
packages/-serializer-encapsulation-test-app/package.json
packages/adapter/package.json
packages/debug/package.json
packages/model/package.json
packages/record-data/package.json
packages/serializer/package.json
packages/store/package.json
yarn.lock

[CHORE] Remove ember-cli-htmlbars-inline-precompile

---

packages/-serializer-encapsulation-test-app/tests/helpers/test-in-debug.js
packages/-serializer-encapsulation-test-app/tests/integration/normalize-test.js
packages/-serializer-encapsulation-test-app/tests/integration/push-payload-test.js
packages/store/addon/-private/system/core-store.ts

[CHORE] pushPayload test for serializer encapsulation side quest

---

azure-pipelines.yml

This reverts commit 66e5a6bf633e48ae95250d85ee4a53a623bd8191.
Bring back Azure for now due to Github actions instability

Revert "chore(ci): Remove Azure Pipelines configuration"

---

packages/-ember-data/tests/dummy/app/models/foo.js

Discovered this: https://github.com/babel/babel/issues/10264#issuecomment-516297942

[CHORE] fix babel warning emitted due to anonymous class

---

packages/-ember-data/tests/integration/adapter/find-test.js

Attempt to help to modernize the tests.
* Remove run(() => { }) when possible.
* Setup test information in the same test to ease reviews and have all the context required within the test.
* Use const when possible.

[CHORE]: Refactor integration/adapter/find-test.js

---

packages/adapter/addon/index.js
packages/serializer/addon/index.js
packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts

Fixes markup issues and improves readability of the documentation for @ember-data/serializer
This should be backported to LTS, Release, and Beta.

[FIX DOCS] cleanup serializer documentation

---

packages/-ember-data/tests/unit/adapters/rest-adapter/ajax-options-test.js
packages/adapter/addon/rest.js

[BUGFIX]: Fix problem with headers precedence #6588

---

packages/-ember-data/addon/-private/index.js
packages/model/addon/-private/errors.js
packages/model/addon/-private/index.ts
packages/model/addon/-private/model.js
packages/store/addon/-private/index.ts

This was approved by @rwjblue in #6669 but that PR was closed due to a github service outage.
The issues with Asset Size Check are resolved by #6676

[CHORE] move Errors into @ember-data/model #6669

---

packages/-ember-data/tests/helpers/deprecated-test.js
packages/-ember-data/tests/helpers/qunit-asserts/assert-assertion.ts
packages/-ember-data/tests/helpers/qunit-asserts/assert-deprecation.ts
packages/-ember-data/tests/helpers/qunit-asserts/assert-warning.ts
packages/-ember-data/tests/integration/application-test.js
packages/-ember-data/tests/integration/lifecycle-hooks-test.js
packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/-ember-data/tests/integration/request-state-service-test.ts
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/-ember-data/tests/test-helper.js
packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
packages/-ember-data/tests/unit/model-test.js
packages/-ember-data/tests/unit/model/lifecycle-callbacks-test.js
packages/-ember-data/tests/unit/model/rollback-attributes-test.js
packages/-ember-data/tests/unit/record-arrays/adapter-populated-record-array-test.js
packages/-ember-data/tests/unit/store/adapter-interop-test.js
packages/-ember-data/tests/unit/store/push-test.js
packages/-ember-data/tests/unit/store/serializer-for-test.js

Builds on #6627 #6626 #6625 
Fixes all tests, turns on the assertion infra to protect against regressions.

[CHORE] test fixes for deprecations, enables asserting all deprecations

---

packages/debug/tsconfig.json
packages/record-data/tsconfig.json

clean old package folders

---

CHANGELOG.md
package.json
packages/-adapter-encapsulation-test-app/package.json
packages/-ember-data/package.json
packages/-fastboot-test-app/package.json
packages/-serializer-encapsulation-test-app/package.json
packages/adapter/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json
yarn.lock

3.14.0 Changelog

---

packages/store/addon/-private/identifiers/utils/uuid-v4.ts

[BUGFIX 3.13 RELEASE BETA CANARY] Better fastboot crypto error message

---

packages/-ember-data/tests/integration/store-test.js

[CHORE]: refactor: Remove run loops from find-record module inside store integration test

---

packages/adapter/addon/rest.js

[LTS] Warn about changing header precedence in lts

---

packages/store/addon/-private/identifiers/utils/uuid-v4.ts

Backport #6692 to 3.13

---

packages/store/addon/-private/identifiers/utils/uuid-v4.ts

Backport #6692 to release

---

packages/store/addon/-private/identifiers/utils/uuid-v4.ts

Backport #6692 to beta

---

packages/store/addon/-private/system/core-store.ts
packages/unpublished-adapter-encapsulation-test-app/tests/integration/reload-test.js

[BUGFIX TEST] reloading tests for adapter encapsulation side quest - shouldBackgroundReloadAll

---

packages/store/addon/-private/system/core-store.ts
packages/unpublished-adapter-encapsulation-test-app/tests/integration/reload-test.js

[BUGFIX TEST] reloading tests for adapter encapsulation side quest - shouldBackgroundReloadRecord

---

packages/unpublished-relationship-performance-test-app/ember-cli-build.js

necessary for landing tracerbench work

[CHORE] turn off fingerprinting in the perf app

---

packages/debug/addon/index.js

[CHORE] documentation for @ember-data/debug package

---

packages/private-build-infra/src/features.js

 [BUGFIX] only allow feature flag alterations in canary

---

packages/model/addon/-private/errors.js

[DOC] Fix typo

---

packages/-ember-data/tests/integration/store/model-name-test.js
packages/store/addon/-private/system/store.ts

Backports https://github.com/emberjs/data/pull/6746

[BUGFIX] ensure MandatorySetter does not trigger for modelName

---

packages/model/addon/-private/errors.js
packages/unpublished-adapter-encapsulation-test-app/tests/integration/mutations-test.js

[TEST] mutations tests for adapter encapsulation side quest

---

packages/store/addon/-private/system/model/shim-model-class.ts
packages/store/addon/-private/ts-interfaces/ds-model.ts
packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts

cc @chriskrycho this is part of the next steps we previously discussed due to issues with being able to type DS.Model

[CHORE] introduce static ModelSchema interface

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/record-data.js
tests/unit/model-test.js

https://github.com/emberjs/data/pull/6775

Set IDs on Record Data when mutating DS Model

---

packages/model/addon/-private/model.js
packages/model/addon/-private/system/relationships/ext.js
packages/store/addon/-private/index.ts

From #6166 : move -private/system/relationships/ext.js in @ember-data/store into the Model package

[CHORE] Move -private/system/relationships/ext from store to model

---

CHANGELOG.md

Changelog for 3.12.5

---

packages/unpublished-adapter-encapsulation-test-app/tests/integration/coalescing-test.js

[TEST] coalescing tests for adapter encapsulation side quest

---

packages/-ember-data/tests/integration/adapter/queries-test.js
packages/-ember-data/tests/integration/store-test.js

[CHORE] refactor: Update tests for integration/adapter/query

---

packages/model/addon/-private/index.ts
packages/model/addon/-private/system/model-for-mixin.ts
packages/store/addon/-private/system/schema-definition-service.ts

[CHORE] Move _modelForMixin to Model package

---

packages/store/addon/-private/system/core-store.ts
packages/unpublished-adapter-encapsulation-test-app/tests/integration/belongs-to-test.js
packages/unpublished-adapter-encapsulation-test-app/tests/integration/coalescing-test.js
packages/unpublished-adapter-encapsulation-test-app/tests/integration/has-many-test.js
packages/unpublished-adapter-encapsulation-test-app/tests/test-helper.js

[BUGFIX TEST] relationships tests for adapter enapsulation side quest

---

packages/-ember-data/tests/test-helper.js
packages/model/addon/-private/model.js
packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts

[CHORE] Fix deprecation warnings; improve tooling

---

.github/workflows/asset-size-check.yml
.github/workflows/main.yml
.github/workflows/relationship-performance-check.yml

[FIX CI] fetch full history for checks against master

---

yarn.lock

[CHORE] Update yarn.lock for latest backports

---

package.json
yarn.lock

[FIX release] install local lint rules using link instead of a version

---

.eslintrc.js

[CHORE] Enabled eslint-plugin-qunit

---

package.json
yarn.lock

fix release and install by using a link instead of a version (#6967)

---

bin/asset-size-tracking/src/post-comment.sh

https://github.com/koalaman/shellcheck/wiki/SC1114
~~just curious if this fixes any stdio issue~~
This is just for correctness 🥇

remove leading whitespace per shellcheck

---

packages/unpublished-model-encapsulation-test-app/ember-cli-build.js
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-model-encapsulation-test-app/tests/integration/model-for-test.js

[BUFGIX BETA] dont run canary model tests in beta

---

packages/canary-features/addon/default-features.ts

turn on FULL_LINKS_ON_RELATIONSHIPS

---

packages/unpublished-model-encapsulation-test-app/ember-cli-build.js
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-model-encapsulation-test-app/tests/integration/model-for-test.js

[BUFGIX BETA] dont run feature flag model tests in beta

---

package.json
packages/-ember-data/package.json
packages/adapter/package.json
packages/canary-features/package.json
packages/debug/package.json
packages/model/package.json
packages/private-build-infra/package.json
packages/record-data/package.json
packages/serializer/package.json
packages/store/package.json
packages/unpublished-fastboot-test-app/package.json
packages/unpublished-test-infra/package.json
yarn.lock

Bump ember-cli-typescript

---

bin/publish.js

(cherry picked from commit 2955e2cf7c142147f0baf31def48e65e03f4afb2)

Make execa use compatible with volta

---

packages/adapter/addon/index.js
packages/serializer/addon/index.js
packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts

Backports [FIX DOCS] cleanup serializer documentation #6575 for LTS 3.12

[Backport] cleanup serializer documentation (#6575)

---

packages/-ember-data/tests/helpers/create-tracking-context.js
packages/-ember-data/tests/integration/references/has-many-test.js
packages/store/addon/-private/system/references/has-many.js

Resolves #7100 
Surfaced #7102

[BUGFIX] dont use Ember.get on internals

---

packages/-ember-data/tests/integration/adapter/client-side-delete-test.js
packages/unpublished-relationship-performance-test-app/app/routes/application.js

[CHORE]: refactor: Remove usage of runloop in integration test for clientSideDelete

---

packages/-ember-data/tests/integration/adapter/record-persistence-test.js

[CHORE]: refactor: Update record persisting tests to remove run loop usage

---

package.json
packages/-ember-data/package.json
packages/adapter/node-tests/blueprints/adapter-test.js
packages/adapter/package.json
packages/debug/package.json
packages/model/blueprints/model/index.js
packages/model/node-tests/blueprints/model-test.js
packages/model/package.json
packages/private-build-infra/src/utilities/edition-detector.js
packages/record-data/package.json
packages/serializer/node-tests/blueprints/serializer-test.js
packages/serializer/node-tests/blueprints/transform-test.js
packages/serializer/package.json
packages/store/package.json
packages/unpublished-adapter-encapsulation-test-app/package.json
packages/unpublished-debug-encapsulation-test-app/package.json
packages/unpublished-fastboot-test-app/package.json
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-record-data-encapsulation-test-app/package.json
packages/unpublished-relationship-performance-test-app/package.json
packages/unpublished-serializer-encapsulation-test-app/package.json
packages/unpublished-test-infra/package.json
packages/unpublished-test-infra/src/node-test-helpers/setup-test-environment.js
yarn.lock

fix: blueprint tests for classic

---

.github/workflows/main.yml
azure-pipelines.yml
packages/-ember-data/config/ember-try.js

chore: update lts tests

---

packages/-ember-data/tests/integration/identifiers/cache-test.ts
packages/store/addon/-private/identifiers/cache.ts
packages/store/addon/-private/system/store/internal-model-factory.ts

Backport of https://github.com/emberjs/data/pull/7182

Cache identifiers

---

CHANGELOG.md

Update Changelog for v3.16.6

---

packages/serializer/addon/json-api.js

[DOC] Use native syntax in JSONAPISerializer documentation

---

packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts

For https://github.com/ember-learn/ember-api-docs/issues/672

[DOCS] fix links on @ember-data/store package intro

---

bin/relationship-performance-tracking/src/tracerbench.js
packages/unpublished-relationship-performance-test-app/app/adapters/application.js
packages/unpublished-relationship-performance-test-app/app/models/child.js
packages/unpublished-relationship-performance-test-app/app/models/parent.js
packages/unpublished-relationship-performance-test-app/app/router.js
packages/unpublished-relationship-performance-test-app/app/routes/add-children.js
packages/unpublished-relationship-performance-test-app/app/routes/destroy.js
packages/unpublished-relationship-performance-test-app/app/routes/materialization.js
packages/unpublished-relationship-performance-test-app/app/routes/unload.js
packages/unpublished-relationship-performance-test-app/app/utils/create-parent-payload.js

Extra performance tests for #7090 and #7096

Add extra performance tests

---

.github/workflows/main.yml

[INFRA]: test against Node.js 10 and 14

---

packages/-ember-data/config/ember-try.js
packages/unpublished-fastboot-test-app/config/ember-try.js

See error here:
https://github.com/emberjs/data/pull/7234/checks?check_run_id=969258442
Fix here: 
https://github.com/ember-cli/ember-fetch/pull/552

[Infra]: Fix "fetch is not defined - maybe your browser targets are not covering everything you need"

---

CHANGELOG.md

[LTS]: 3.20.2

---

.github/workflows/main.yml
CHANGELOG.md
azure-pipelines.yml
package.json
yarn.lock

- Min LTS 3.16
- CHANGELOG additions
- ember-source 3.20

[RELEASE]: 3.21.0

---

packages/-ember-data/tests/acceptance/tracking-model-id-test.js

`exists()` is a function, not a getter.

Invoke function typo

---

.github/workflows/main.yml
CHANGELOG.md
RELEASE.md
package.json
packages/-ember-data/config/ember-try.js
packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/model/package.json
packages/record-data/package.json
packages/serializer/package.json
packages/store/package.json
packages/unpublished-adapter-encapsulation-test-app/package.json
packages/unpublished-debug-encapsulation-test-app/package.json
packages/unpublished-fastboot-test-app/package.json
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-record-data-encapsulation-test-app/package.json
packages/unpublished-relationship-performance-test-app/package.json
packages/unpublished-serializer-encapsulation-test-app/package.json
packages/unpublished-test-infra/package.json
yarn.lock

[DOCS]: Changelog additions and improvements to RELEASE.md

---

packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts

https://github.com/emberjs/ember.js/blob/master/packages/@ember/debug/index.ts

Chore: fix deprecate import path to @ember/debug

---

.github/workflows/main.yml

https://github.com/actions/checkout
https://github.com/actions/setup-node
https://github.com/actions/upload-artifact

[CI]: update github actions to v2

---

packages/model/blueprints/model/HELP.md

Command `ember g model` emits native class syntax so this brings example in pair with actual output.

[DOC model] Convert model blueprint HELP.md to native class syntax

---

packages/model/addon/-private/system/many-array.js
packages/record-data/addon/-private/relationships/state/belongs-to.ts
packages/record-data/addon/-private/relationships/state/create.ts
packages/record-data/addon/-private/relationships/state/has-many.ts
packages/record-data/addon/-private/relationships/state/relationship.ts
packages/store/addon/-private/system/references/belongs-to.js

Changes pulled from https://github.com/emberjs/data/pull/7287

[Cleanup]: relationship push method does not need `initial` argument

---

packages/private-build-infra/src/deprecations.js
packages/private-build-infra/src/features.js
packages/private-build-infra/src/packages.js

Release target: [Build]: disable esm cache (#7322)

---

packages/private-build-infra/src/deprecations.js
packages/private-build-infra/src/features.js
packages/private-build-infra/src/packages.js

Avoid issues found in #7221 and others

[Build]: disable esm cache (#7322)

---

packages/serializer/addon/-private/embedded-records-mixin.js
packages/serializer/addon/-private/transforms/boolean.js
packages/serializer/addon/-private/transforms/date.js
packages/serializer/addon/-private/transforms/number.js
packages/serializer/addon/-private/transforms/string.js
packages/serializer/addon/-private/transforms/transform.js
packages/serializer/addon/index.js
packages/serializer/addon/json-api.js
packages/serializer/addon/json.js
packages/serializer/addon/rest.js

Updated serializer examples - reference #7256.

[DOC serializer] convert api examples to native classes/Octane

---

packages/-ember-data/tests/unit/store/finders-test.js

[Chore]: Update finders-test to modern @ember-data imports

---

packages/-ember-data/tests/integration/model-errors-test.ts
packages/model/addon/-private/errors.js

[Bug]: errors `remove` to accurately update in template

---

packages/adapter/addon/index.js

Add adapterOptions parameter to documentation of adapters query() and queryRecord() functions

---

packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json
yarn.lock

close #5967 
Reimplementation of above PR to see if tests will pass.  Added a few other modules that need the explicit dep install.

[Deps]: add `@ember/string` dependency in preparation of deprecation

---

.github/workflows/asset-size-check.yml
.github/workflows/nightly.yml
.github/workflows/relationship-performance-check.yml
bin/asset-size-tracking/generate-diff.js

[CI]: bump failure asset size to 75 bytes

---

packages/-ember-data/package.json
packages/record-data/package.json
yarn.lock

[CHORE] Bump @ember/ordered-set

---

packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/adapter/addon/-private/utils/determine-body-promise.ts

backport of https://github.com/emberjs/data/pull/7372

Fix for empty payloads

---

CHANGELOG.md

Update Changelog for v3.24.0-beta.0

---

packages/adapter/addon/-private/build-url-mixin.js

[DOC adapter] fix parent class invocation syntax

---

CHANGELOG.md

Update CHANGELOG master

---

.github/workflows/relationship-performance-check.yml
package.json
yarn.lock

close #7403 
Need to downgrade.
https://github.com/TracerBench/tracerbench/blob/v3.1.2/packages/core/src/index.ts#L13
Happy to follow up with an upgrade.

[Perf]: fix tracerbench runs

---

packages/store/addon/-private/system/promise-proxies.js

Update link in PromiseObject documentation

---

packages/store/addon/-private/system/core-store.ts

[Task]: remove meaningless assertion

---

package.json

chore: remove unneeded tracerbench dep

---

packages/record-data/addon/-private/relationships/state/belongs-to.ts
packages/record-data/addon/-private/relationships/state/has-many.ts
packages/record-data/addon/-private/relationships/state/relationship.ts

chore: relationships should use declare for fields

---

packages/record-data/addon/-private/record-data.ts
packages/record-data/addon/-private/relationships/state/create.ts

similar to the other PRs but also improves a couple of type usages and updates argument usage within the relationship create code path to prepare for a cleaner refactor.

chore: use declare for Relationships class and improve typing and encapsulation

---

bin/asset-size-tracking/generate-diff.js

chore: small improvements to the asset-size report output

---

.github/workflows/alpha-release.yml

Fixing typo where it should be deployment

chore: fix alpha-release.yml typo for environment

---

package.json
yarn.lock

chore: remove unneeded har-remix dep

---

packages/serializer/addon/json.js

Revert "Docs: normalizeArray -> normalizeArrayResponse"

---

packages/serializer/addon/json.js

Dup of #7495 but on the correct master branch

[DOC] normalizeArray -> normalizeArrayResponse

---

.github/workflows/alpha-release.yml
.github/workflows/asset-size-check.yml
.github/workflows/nightly.yml
.github/workflows/perf-check.yml
bin/perf-tracking/create-comment.js

- Fixes issue causing the asset-size comment to not get posted recently.
- Brings back and improves performance monitoring comment.
- Restores all the other performance scenarios
- Cuts fixture generation time out of the part of the report we care about for materialization
- Adds artifact uploading for the performance report
Requires #7499

chore: improved monitoring

---

packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js

chore: modernized build-url-mixin-test with dot notation (.get)

---

packages/adapter/addon/index.ts

fix adapter doc example

---

packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js

updated IDs from num to string

---

packages/-ember-data/addon/index.js
packages/-ember-data/tests/integration/debug-adapter-test.js
packages/-ember-data/tests/unit/debug-test.js
packages/private-build-infra/src/packages.js

As per discussion with @runspired, I understood it is a temporary fix, and ideally we should use the `HAS_DEBUG_PACKAGE` flag from build-infra.

check debug package presence before import Fix #7053

---

packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js

chore: build-url-mixin | replaced comment.reopen with individual definitions per test

---

packages/serializer/addon/json.js

[DOC] Updates this._super in native classes to native class super

---

packages/model/addon/-private/model.js
packages/store/addon/-private/system/deprecated-evented.js

Closes https://github.com/ember-learn/ember-api-docs/issues/759

Fixes `DeprecatedEvented` link

---

packages/-ember-data/tests/integration/adapter/store-adapter-test.js

chore: store-adapter-test | removed run loop where possible

---

packages/-ember-data/tests/integration/adapter/rest-adapter/find-record-test.js
packages/-ember-data/tests/integration/identifiers/cache-test.ts
packages/-ember-data/tests/integration/identifiers/configuration-test.ts
packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
packages/-ember-data/tests/integration/references/record-test.js
packages/-ember-data/tests/unit/store/asserts-test.js
packages/-ember-data/tests/unit/store/peek-record-test.js
packages/store/addon/-private/identifiers/cache.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/snapshot.ts
packages/store/addon/-private/system/store/internal-model-factory.ts
packages/store/addon/-private/ts-interfaces/ember-data-json-api.ts
packages/store/addon/-private/ts-interfaces/store.ts
packages/store/addon/-private/utils/construct-resource.ts

ref https://github.com/emberjs/rfcs/pull/521

[FEAT] RFC-521 Accept Identifiers for store methods

---

CONTRIBUTING.md

Add labeling guidance to contributing guide

---

packages/-ember-data/tests/integration/references/record-test.js
packages/store/addon/-private/system/core-store.ts

Follow up: store identifier #7104

---

packages/model/package.json
packages/private-build-infra/src/addon-build-config-for-data-package.js
yarn.lock

* Use patched ember-cached-decorator-polyfill
* Simplify `@cached` transpilation
* Use meber-cached-decorator-polyfill 0.1.4

@ember-data/model: Simplify @cached transpilation (#7599)

---

.github/workflows/alpha-release.yml
.github/workflows/asset-size-check.yml
.github/workflows/main.yml
.github/workflows/nightly.yml
packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts

ref https://www.npmjs.com/package/semver

Nightly test: beta and canary fail b/c semver comparison

---

packages/model/addon/-private/attr.js

[DOC] Fix transform example not using native class syntax

---

lerna.json
packages/-ember-data/package.json
packages/adapter/package.json
packages/canary-features/package.json
packages/debug/package.json
packages/model/package.json
packages/private-build-infra/package.json
packages/record-data/package.json
packages/serializer/package.json
packages/store/package.json
packages/unpublished-adapter-encapsulation-test-app/package.json
packages/unpublished-debug-encapsulation-test-app/package.json
packages/unpublished-eslint-rules/package.json
packages/unpublished-fastboot-test-app/package.json
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-record-data-encapsulation-test-app/package.json
packages/unpublished-relationship-performance-test-app/package.json
packages/unpublished-serializer-encapsulation-test-app/package.json
packages/unpublished-test-infra/package.json

We should have published v4.0.0 instead of v3.29.

Update version on master to v4.0.0-alpha.1

---

packages/-ember-data/tests/unit/model-test.js
packages/-ember-data/tests/unit/model/attr-test.js
packages/model/addon/-private/attr.js
packages/model/addon/-private/belongs-to.js
packages/model/addon/-private/has-many.js
packages/model/addon/-private/model.js

Revert "[BUGFIX Model] assert when 'content' is used as a property on a record (#7545)"
This reverts commit 1d1496d73d21b3fd32ae10e6a41fa23a5287e0d4.

Revert "[BUGFIX Model] assert when 'content' is used as a property on a record (#7545)"

---

packages/-ember-data/addon/setup-container.js
packages/-ember-data/app/initializers/ember-data.js
packages/-ember-data/tests/integration/injection-test.js
packages/unpublished-fastboot-test-app/app/routes/index.js
packages/unpublished-fastboot-test-app/app/routes/person/new.js
packages/unpublished-relationship-performance-test-app/app/routes/add-children.js
packages/unpublished-relationship-performance-test-app/app/routes/destroy.js
packages/unpublished-relationship-performance-test-app/app/routes/materialization.js
packages/unpublished-relationship-performance-test-app/app/routes/unload.js
packages/unpublished-relationship-performance-test-app/app/routes/unused-relationships.js

Released as part of our 4.0 release series.
ref: https://github.com/emberjs/ember.js/pull/19680
ref: https://github.com/emberjs/ember.js/pull/19358

[cleanup]: Remove implicit store injection slated for Ember v4.0.0

---

.github/workflows/asset-size-check.yml
scripts/asset-size-tracking/src/create-comment-text.js

Remove IE11 asset size checks

---

packages/-ember-data/tests/unit/transform/custom-test.js
packages/serializer/addon/-private/transforms/boolean.js
packages/serializer/addon/-private/transforms/date.js
packages/serializer/addon/-private/transforms/number.js
packages/serializer/addon/-private/transforms/string.js
packages/serializer/addon/-private/transforms/transform.js

[Chore]: Convert transforms to class syntax

---

packages/-ember-data/node-tests/fixtures/expected.js
packages/-ember-data/tests/unit/model-test.js
packages/model/addon/-private/model.js

Remove deprecated toJSON on model instance

---

packages/-ember-data/tests/integration/records/unload-test.js
packages/-ember-data/tests/integration/store-test.js
packages/store/addon/-private/system/core-store.ts

Remove delete and unload record deprecations in core-store

---

packages/-ember-data/tests/integration/application-test.js
packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/-ember-data/tests/unit/store/peek-record-test.js
packages/adapter/addon/rest.ts
packages/canary-features/addon/index.ts
packages/record-data/addon/-private/record-data.ts
packages/record-data/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
packages/serializer/addon/json.js
packages/store/addon/-private/identifiers/cache.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/record-array-manager.js
packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
packages/store/addon/-private/system/snapshot.ts
packages/store/addon/-private/system/store/finders.js
packages/unpublished-test-infra/addon-test-support/public-props.js

Backport of https://github.com/emberjs/data/pull/7722

Fix deprecated assign usage from @ember/assign (#7722)

---

packages/-ember-data/tests/integration/store-test.js
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/fetch-manager.ts
packages/store/addon/-private/ts-interfaces/fetch-manager.ts
packages/store/addon/-private/ts-interfaces/store.ts

ref https://github.com/emberjs/data/pull/7702

[bug]: findRecord should not cache if includes differ (#7702)

---

packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/record-data/addon/-private/graph/operations/replace-related-records.ts

add test and fix push of duplicate identifiers to a relationship

---

packages/-ember-data/tests/unit/utils/serialize-query-params-test.js
packages/adapter/addon/-private/utils/serialize-query-params.ts

close https://github.com/emberjs/data/issues/7824

Fix bug with encoding space characters when serializing query params

---

packages/-ember-data/tests/integration/records/create-record-test.js
packages/model/addon/-private/model.js
packages/store/addon/-private/system/ds-model-store.ts

cherry-pick https://github.com/emberjs/data/commit/959fa04c9cc73231796d40bf24beb5970d567c04

Fix: assign unknown properties in init after initialization is finished to ensure proper setup timing (#7771)

---

.eslintrc.js

Some of these config lines were not needed or unnecessarily disabled.

Simplify import linting

---

packages/adapter/blueprints/adapter-test/mocha-rfc-232-files/__root__/__path__/__test__.js
packages/adapter/blueprints/adapter-test/qunit-files/__root__/__path__/__test__.js
packages/adapter/node-tests/fixtures/adapter-test/application-default.js
packages/adapter/node-tests/fixtures/adapter-test/foo-default.js
packages/adapter/node-tests/fixtures/adapter-test/mocha-rfc232.js
packages/adapter/node-tests/fixtures/adapter-test/rfc232.js
packages/model/blueprints/model-test/mocha-rfc-232-files/__root__/__path__/__test__.js
packages/model/blueprints/model-test/qunit-files/__root__/__path__/__test__.js
packages/model/node-tests/fixtures/model-test/comment-default.js
packages/model/node-tests/fixtures/model-test/foo-default.js
packages/model/node-tests/fixtures/model-test/mocha-rfc232.js
packages/model/node-tests/fixtures/model-test/post-default.js
packages/model/node-tests/fixtures/model-test/rfc232.js
packages/serializer/blueprints/serializer-test/mocha-rfc-232-files/__root__/__path__/__test__.js
packages/serializer/blueprints/serializer-test/qunit-files/__root__/__path__/__test__.js
packages/serializer/blueprints/transform-test/mocha-rfc-232-files/__root__/__path__/__test__.js
packages/serializer/blueprints/transform-test/qunit-files/__root__/__path__/__test__.js
packages/serializer/node-tests/fixtures/serializer-test/application-default.js
packages/serializer/node-tests/fixtures/serializer-test/foo-default.js
packages/serializer/node-tests/fixtures/serializer-test/mocha-rfc232.js
packages/serializer/node-tests/fixtures/serializer-test/rfc232.js
packages/serializer/node-tests/fixtures/transform-test/default.js
packages/serializer/node-tests/fixtures/transform-test/mocha-rfc232.js
packages/serializer/node-tests/fixtures/transform-test/rfc232.js

RFC PR: https://github.com/emberjs/rfcs/pull/637
Corresponding PR in `ember-cli`: https://github.com/ember-cli/ember-cli/pull/9803
Corresponding PR in `ember-source`: https://github.com/emberjs/ember.js/pull/19981

[RFC 637] Customizable test setups

---

CHANGELOG.md

Changelog 4.1.0

---

.github/workflows/asset-size-check.yml
.github/workflows/perf-check.yml

allows us to not clone the entire repo

chore: faster checks by cloning less

---

packages/store/addon/-private/system/store/finders.js

Fix typo in DEPRECATE_RSVP_PROMISE message

---

packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
packages/model/addon/-private/system/promise-many-array.ts

fix for #7904 computed chains not updated for async hasMany loading

---

packages/-ember-data/tests/index.html
packages/adapter/tests/index.html
packages/model/tests/index.html
packages/record-data/tests/index.html
packages/serializer/tests/index.html
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/tests/index.html
packages/unpublished-adapter-encapsulation-test-app/tests/index.html
packages/unpublished-debug-encapsulation-test-app/tests/index.html
packages/unpublished-fastboot-test-app/tests/index.html
packages/unpublished-model-encapsulation-test-app/tests/index.html
packages/unpublished-record-data-encapsulation-test-app/tests/index.html
packages/unpublished-relationship-performance-test-app/tests/index.html
packages/unpublished-serializer-encapsulation-test-app/tests/index.html
packages/unpublished-test-infra/tests/index.html

some small cleanups and fix test container

---

packages/-ember-data/tests/integration/adapter/find-all-test.js

[CHORE]: Modernize find-all-test

---

packages/-ember-data/tests/integration/adapter/queries-test.js

[CHORE]: Modernize queries-test

---

packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js
yarn.lock

[CHORE]: Modernize build-url-mixin-strict-equal

---

packages/-ember-data/addon/index.js

chore: remove unneeded version code in ember-data package

---

packages/-ember-data/tests/integration/adapter/serialize-test.js

[CHORE]: Modernized serialize-test

---

packages/-ember-data/tests/integration/adapter/find-test.js

[CHORE]: Modernize Find-Test

---

.github/workflows/main.yml
packages/-ember-data/tests/integration/store-test.js
packages/private-build-infra/package.json
yarn.lock

Cherry pick https://github.com/emberjs/data/pull/7559 to fix https://github.com/babel/ember-cli-babel/issues/419#issuecomment-971787156

Cherry pick: chore(deps): bump broccoli-rollup from 4.1.1 to 5.0.0

---

.github/workflows/perf-check.yml

Deactivate Perf Benchmarks until Fixed

---

packages/unpublished-fastboot-test-app/package.json
yarn.lock

Revert "chore(deps): update dependency ember-simple-tree to ^0.8.3"

---

.github/PULL_REQUEST_TEMPLATE.md

Adding these sections to the Pull Request Template would help the learning team and other volunteers to write release blog posts.

[DOC] update pull request template

---

packages/-ember-data/tests/integration/adapter/rest-adapter-test.js

test: defined post model individually per test

---

packages/private-build-infra/src/utilities/require-module.js

fix earlier versions of node-14

---

packages/-ember-data/tests/integration/references/autotracking-test.js
packages/model/addon/-private/references/belongs-to.ts
packages/model/addon/-private/references/has-many.ts
packages/store/addon/-private/managers/record-notification-manager.ts

Clear subscriptions once unsubscribed, don't unnecessarily churn on subscriptions

---

ember-data-types/q/schema-definition-service.ts

No release note needed. This is a typo fix in some docs.

[DOC] typo fix

---

ember-data-types/q/identifier.ts

Minor typo in documentation
This PR does not need to be described in release blog

[DOC] typo in identifier initializer documentation

---

packages/private-build-infra/src/utilities/require-module.js

fix earlier versions of node-14 (#8108)

---

packages/store/addon/-private/identifier-cache.ts
packages/store/addon/-private/utils/uuid-polyfill.ts

fix: uuid polyfill logic

---

packages/-ember-data/ember-cli-build.js
packages/private-build-infra/src/addon-build-config-for-data-package.js

should resolve https://github.com/rust-lang/crates.io/issues/5254#issuecomment-1264487638

fix: thread config from host to nested deps

---

packages/private-build-infra/src/addon-build-config-for-data-package.js

[backport release-prev] fix: thread polyfillUUID config through nested deps

---

packages/private-build-infra/src/addon-build-config-for-data-package.js

[Backport Release]: fix: thread polyfillUUID config through nested deps

---

packages/debug/addon/setup.js

fix: inspector type detection #8205

---

.github/renovate.json

chore: improve renovate experience

---

packages/private-build-infra/src/addon-build-config-for-data-package.js
packages/private-build-infra/src/debug-macros.js
packages/private-build-infra/src/debugging.js
packages/private-build-infra/src/deprecations.js
packages/private-build-infra/src/packages.js
packages/private-build-infra/src/transforms/babel-plugin-convert-existence-checks-to-macros/index.js
packages/private-build-infra/src/transforms/package.json
packages/private-build-infra/src/utilities/require-module.js

Convert existence checks to Embroider Macros

Convert existence checks to macros (take 2)

---

CHANGELOG.md
RELEASE.md
lerna.json
packages/-ember-data/package.json
packages/adapter/package.json
packages/canary-features/package.json
packages/debug/package.json
packages/model/package.json
packages/private-build-infra/package.json
packages/record-data/package.json
packages/serializer/package.json
packages/store/package.json
packages/tracking/package.json
packages/unpublished-eslint-rules/package.json
packages/unpublished-test-infra/package.json
pnpm-lock.yaml
scripts/publish.js
tests/adapter-encapsulation/package.json
tests/blueprints/package.json
tests/debug-encapsulation/package.json
tests/docs/package.json
tests/fastboot/package.json
tests/full-data-asset-size-app/package.json
tests/graph/package.json
tests/main/package.json
tests/model-encapsulation/package.json
tests/performance/package.json
tests/record-data-encapsulation/package.json
tests/serializer-encapsulation/package.json

Update changelog for 4.8.0

---

.gitignore
packages/tracking/addon-main.js
packages/tracking/package.json
pnpm-lock.yaml

related but does not address #8296

fix: prepack addon tree for embroider

---

README.md

It seems `@ember-data/tracking` is required now, so we add it to the readme under "Advanced Installation"

add @ember-data/tracking to Advanced Installation

---

packages/record-data/addon/-private/record-data.ts
packages/store/addon/-private/store-service.ts
tests/main/tests/integration/records/save-test.js

fix: add meaningful error and proper rejection for id assertion during createRecord commit

---

packages/store/addon/-private/caches/instance-cache.ts
packages/store/addon/-private/store-service.ts
tests/main/tests/integration/records/load-test.js

fix: assign preload data always

---

tests/main/tests/unit/model-test.js

resolves #5882 by expanding tests to show the format works

test: show #5882 is no longer the case

---

packages/model/addon/-private/system/many-array.js

Notify on length when notifying that many-array has changed

---

packages/-ember-data/package.json
packages/adapter/addon/error.js
packages/adapter/package.json
packages/debug/package.json
packages/model/index.js
packages/model/package.json
packages/serializer/package.json
packages/store/index.js
packages/store/package.json
pnpm-lock.yaml
tests/adapter-encapsulation/package.json
tests/debug-encapsulation/package.json
tests/embroider-basic-compat/package.json
tests/fastboot/package.json
tests/full-data-asset-size-app/package.json
tests/graph/package.json
tests/main/package.json
tests/main/tests/unit/adapter-errors-test.js
tests/model-encapsulation/package.json
tests/performance/package.json
tests/record-data-encapsulation/package.json
tests/request/package.json
tests/serializer-encapsulation/package.json

resolves https://github.com/emberjs/data/issues/8393 and https://github.com/emberjs/data/issues/8404 for 4.10/4.11
the @ember/string fix will also need to be applied to master for 4.12(5.0)+

fix @ember/error and @ember/string deprecations

---

packages/private-build-infra/src/transforms/babel-plugin-convert-existence-checks-to-macros/index.js
packages/private-build-infra/src/transforms/babel-plugin-transform-has-debug-package/index.js
packages/store/addon/-private/legacy-model-support/schema-definition-service.ts
packages/store/addon/-private/network/fetch-manager.ts
packages/store/addon/-private/store-service.ts

resolves embroider issues for 4.8 lts

fix: embroider compat

---

packages/private-build-infra/src/transforms/babel-plugin-convert-existence-checks-to-macros/index.js
packages/private-build-infra/src/transforms/babel-plugin-transform-has-debug-package/index.js
packages/store/src/-private/legacy-model-support/schema-definition-service.ts
packages/store/src/-private/network/fetch-manager.ts
packages/store/src/-private/store-service.ts

ensures we properly code-strip

fix: use macroCondition with all strippable checks

---

packages/model/addon/-private/model.js
packages/record-data/addon/-private/graph/graph.ts
packages/record-data/addon/-private/graph/index.ts
packages/record-data/addon/-private/record-data.ts
packages/store/addon/-private/caches/instance-cache.ts
packages/store/addon/-private/caches/record-data-for.ts
packages/store/addon/-private/index.ts
packages/store/addon/-private/proxies/promise-proxies.ts
pnpm-lock.yaml
tests/main/package.json
tests/main/tests/unit/model-test.js

- perf: fix: eliminate SSR/Test memory leak (#8436)
- fix: de-cycle ember-concurrency access of promise (#8435)

Backport EmberConcurrency and Memory Leak Fixes

---

packages/store/src/-private/record-arrays/identifier-array.ts

chore: fix ArrayLike.setObjects deprecation message

---

ember-data-types/q/cache.ts
packages/json-api/src/-private/cache.ts
packages/store/src/-private/caches/instance-cache.ts
packages/store/src/-private/managers/cache-manager.ts
tests/docs/fixtures/expected.js
tests/main/tests/integration/record-data/record-data-errors-test.ts
tests/main/tests/integration/record-data/record-data-state-test.ts
tests/main/tests/integration/record-data/record-data-test.ts
tests/main/tests/integration/record-data/store-wrapper-test.ts
tests/main/tests/integration/record-data/unloading-record-data-test.js

Implements Cache.upsert from v2 spec

feat: rename cache.pushData to cache.upsert

---

ember-data-types/cache/aliases.ts
ember-data-types/cache/cache.ts
ember-data-types/cache/change.ts
ember-data-types/cache/identifier.ts
ember-data-types/cache/mutations.ts
ember-data-types/cache/operations.ts
ember-data-types/cache/relationship.ts
ember-data-types/cache/validation-error.ts
ember-data-types/q/cache-store-wrapper.ts
ember-data-types/q/cache.ts
packages/-ember-data/addon/index.js
packages/graph/package.json

chore: port types from #8315

---

tests/fastboot/config/fastboot-testing.js
tests/fastboot/config/fastboot.js
tests/fastboot/tests/fastboot/index-test.js

fix fastboot testing

---

tests/main/tests/unit/model/relationships/has-many-test.js

chore: fixup some tests

---

docs-generator/compile-docs.js
tests/docs/index.js

fix: docs generation should maintain a stable relative path

---

packages/store/src/-private/legacy-model-support/record-reference.ts
packages/store/src/-private/managers/notification-manager.ts
packages/store/src/-private/managers/record-array-manager.ts
tests/main/tests/acceptance/concurrency-test.js

fix: NotificationManager should only invoke resource/document callbacks owned by the originating store (#8649)

---

packages/adapter/package.json
packages/graph/package.json
packages/json-api/package.json
packages/legacy-compat/package.json
packages/model/package.json
packages/request/package.json
packages/serializer/package.json
packages/store/package.json
packages/tracking/package.json
pnpm-lock.yaml

chore: bump @embroider/addon-dev

---

packages/graph/src/-private/graph/graph.ts
packages/model/src/-private/legacy-relationships-support.ts
packages/model/src/-private/many-array.ts
packages/store/src/-private/managers/record-array-manager.ts
packages/store/src/-private/record-arrays/identifier-array.ts
packages/store/src/-private/store-service.ts
tests/main/tests/integration/record-array-manager-test.js
tests/main/tests/integration/records/new-record-unload-test.js
tests/main/tests/integration/records/save-test.js
tests/main/tests/integration/records/unload-test.js

- resolves #8700 
- Also fixes isDestroyed flag on RecordArrays (resolves #8707)
- Also fixes an edge case with sync unload right after a save completes (resolves #8709 )

fix: catch errors during didCommit in DEBUG

---

packages/request-utils/src/index.ts

A small util for helping consumers make nice urls

feat: filterEmpty for query params

---

package.json
pnpm-lock.yaml

We don't actually have control over RSVP atm, and the ember-source and typescript versions need to be allowed to float freely for scenario-testing.
<details><summary>now</summary>
```
packages/-ember-data
├─┬ @ember-data/adapter 5.3.0-alpha.8
│ └── ✕ missing peer @ember/string@^3.1.1
├─┬ @ember-data/debug 5.3.0-alpha.8
│ └── ✕ missing peer @ember/string@^3.1.1
├─┬ @ember-data/model 5.3.0-alpha.8
│ └── ✕ missing peer @ember/string@^3.1.1
├─┬ @ember-data/serializer 5.3.0-alpha.8
│ └── ✕ missing peer @ember/string@^3.1.1
└─┬ @ember-data/store 5.3.0-alpha.8
└── ✕ missing peer @ember/string@^3.1.1
Peer dependencies that should be installed:
@ember/string@">=3.1.1 <4.0.0-0"  
packages/unpublished-test-infra
└─┬ ember-resolver 10.1.1
└── ✕ missing peer @ember/string@^3.0.1
Peer dependencies that …
```

Make the pnpm i --resolution-only output more meaningful

---

package.json
packages/-ember-data/package.json
packages/unpublished-test-infra/package.json
pnpm-lock.yaml
tests/blueprints/package.json
tests/builders/package.json
tests/debug-encapsulation/package.json

Peer problems now don't exist when running `pnpm i` / `pnpm i --resolution-only`

Solve all peer problems reported by pnpm

---

package.json
packages/-ember-data/package.json
packages/unpublished-test-infra/package.json
packages/unpublished-test-infra/tests/dummy/config/environment.js
pnpm-lock.yaml
tests/adapter-encapsulation/config/environment.js
tests/blueprints/package.json
tests/builders/config/environment.js
tests/builders/package.json
tests/debug-encapsulation/config/environment.js
tests/debug-encapsulation/package.json
tests/embroider-basic-compat/config/environment.js
tests/fastboot/config/environment.js
tests/full-data-asset-size-app/config/environment.js
tests/graph/config/environment.js
tests/json-api-encapsulation/config/environment.js
tests/json-api/config/environment.js
tests/main/config/environment.js
tests/model-encapsulation/config/environment.js
tests/performance/config/environment.js
tests/performance/ember-cli-build.js
tests/performance/package.json
tests/request/config/environment.js
tests/serializer-encapsulation/config/environment.js

At some point in the update to 5.x it broke :(

chore: fix peers and get perf-test-app running again

---

packages/model/src/-private/belongs-to.js
packages/model/src/-private/has-many.js
packages/model/src/-private/util.ts
packages/private-build-infra/virtual-packages/deprecations.d.ts
packages/private-build-infra/virtual-packages/deprecations.js
packages/serializer/package.json
packages/serializer/rollup.config.mjs
packages/serializer/src/-private.ts
packages/serializer/src/-private/utils.ts
packages/serializer/src/json-api.js
packages/serializer/src/json.js
packages/serializer/src/rest.js
packages/store/src/-private/caches/identifier-cache.ts
packages/store/src/-private/utils/coerce-id.ts
packages/store/src/-private/utils/normalize-model-name.ts
pnpm-lock.yaml
tests/main/tests/integration/backwards-compat/non-dasherized-lookups-test.js
tests/main/tests/integration/client-id-generation-test.js
tests/main/tests/integration/record-array-test.js
tests/main/tests/integration/references/record-test.js

associated RFCs:
- https://github.com/emberjs/rfcs/pull/739
- https://github.com/emberjs/rfcs/pull/740

feat: Implement Strict Types and Id Deprecations

---

ember-data-types/cache/cache.ts
ember-data-types/q/cache.ts
packages/json-api/src/-private/cache.ts
packages/json-api/src/-private/serialize.ts

Adds general purpose serialization utils for JSON:API

feat: JSON:API serialization utils

---

packages/debug/package.json
packages/graph/src/-private/graph/graph.ts
packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
packages/model/src/-private/many-array.ts
packages/store/src/-private/managers/record-array-manager.ts
packages/store/src/-private/record-arrays/identifier-array.ts
packages/store/src/-private/store-service.ts
tests/adapter-encapsulation/tests/integration/coalescing-test.js
tests/graph/tests/integration/graph/unload-test.ts
tests/main/tests/integration/record-array-manager-test.js
tests/main/tests/integration/records/new-record-unload-test.js
tests/main/tests/integration/records/save-test.js
tests/main/tests/integration/records/unload-test.js

Bringing #8703 #8704 #8705 and #8708 into the main branch.

Forward fixes from 3.12.x into main

---

packages/graph/src/-private/graph.ts

allows cheaper access to metas without instantiating an edge

chore: refactor metas into separate cache

---

packages/-ember-data/tests/unit/store/create-record-test.js

chore: add test to demonstrate create props work as expected

---

tests/fastboot/config/fastboot-testing.js

wooot for things being the same config now :)

chore: fix fastboot-testing deprecation

---

ember-data-types/q/fetch-manager.ts
ember-data-types/q/identifier.ts
packages/graph/src/-private/operations/update-relationship.ts
packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
packages/store/src/-private/caches/identifier-cache.ts
packages/store/src/-private/network/request-cache.ts
packages/store/src/-private/utils/identifier-debug-consts.ts

probably not an optimization that does much, but an idea I wanted to run the suite on.
If nothing else, it gets us closer to nicer debugging / a setup that might work better for forked stores.

perf: stash idea around faster lookup

---

packages/graph/src/-private/graph.ts
packages/graph/src/-private/operations/update-relationship.ts

- changes from a Set to a counter for transaction tracking
- changes the remote update buffer into a two layer Map. Which may regress perf but should allow us to make updates lazily computed in a future PR

chore: simpler graph transactions

---

tests/main/tests/integration/relationships/one-to-many-test.js

chore: remove runloop usage

---

tests/main/tests/integration/records/unload-test.js

test: confirm records unload properly for #8863

---

tests/main/tests/integration/relationships/has-many-sort-order-test.js

adds additional testing around sort order preservation

chore: add tests for sort-order

---

tests/main/tests/acceptance/relationships/has-many-test.js

rewrites the test to be less brittle.

chore: fix flaky test

---

packages/store/src/-private/managers/record-array-manager.ts
tests/main/tests/integration/records/unload-all-test.js

fix: live-array delete sync should not clear the set on length match

---

tests/request/tests/integration/stateful-handler-test.ts

We should add the service pattern to the README/overview guides too

test: show stateful / DI based handler pattern

---

packages/diagnostic/src/styles/dom-reporter.css

chore: test-harness improvements

---

packages/active-record/package.json
packages/adapter/package.json
packages/diagnostic/package.json
packages/graph/package.json
packages/holodeck/package.json
packages/json-api/package.json
packages/legacy-compat/package.json
packages/model/package.json
packages/request-utils/package.json
packages/request/package.json
packages/rest/package.json
packages/schema-record/package.json
packages/serializer/package.json
packages/store/package.json
packages/tracking/package.json
pnpm-lock.yaml

bumps us to rollup v4, requires bumping additional deps to satisfy peers

chore: rollup v4

---

package.json

all for the want of a missing filter

chore: fix development test command

---

packages/diagnostic/README.md

chore: add @warp-drive/diagnostic docs

---

packages/eslint-plugin-ember-data/package.json

chore: update eslint plugin name

---

packages/json-api/src/-private/cache.ts
tests/main/tests/integration/records/concurrent-save-test.ts

fix: make willCommit slightly safer when race conditions occur

---

.gitignore
package.json
packages/-ember-data/package.json
packages/active-record/package.json
packages/adapter/package.json
packages/core-types/package.json
packages/diagnostic/package.json
packages/graph/package.json
packages/holodeck/package.json
packages/json-api/package.json
packages/legacy-compat/package.json
packages/model/package.json
packages/request-utils/package.json
packages/request/package.json
packages/rest/package.json
packages/schema-record/package.json
packages/serializer/package.json
packages/store/package.json
packages/tracking/package.json
turbo.json

fixes #9040 
Most of the remaining time is #9039

chore: reduce number of things turbo builds for build

---

.gitignore

Git-ignore .prettier-cache

---

packages/diagnostic/package.json
packages/holodeck/package.json

TS doesn't use the browser ones 🙃

Add import types

---

@types/ember-data-qunit-asserts/index.d.ts
packages/diagnostic/package.json
packages/unpublished-test-infra/addon-test-support/asserts/assert-all-deprecations.ts
packages/unpublished-test-infra/addon-test-support/asserts/assert-notification.ts
packages/unpublished-test-infra/addon-test-support/asserts/index.ts
packages/unpublished-test-infra/addon-test-support/test.ts
packages/unpublished-test-infra/package.json
packages/unpublished-test-infra/tsconfig.json
pnpm-lock.yaml
tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
tests/main/tests/integration/cache-handler/store-package-setup-test.ts
tests/main/tests/integration/record-data/record-data-errors-test.ts
tests/main/tests/integration/record-data/record-data-state-test.ts
tests/main/tests/integration/record-data/record-data-test.ts

Add type-checking for packages/unpublished-test-infra

---

packages/request/src/-private/context.ts
packages/request/src/-private/debug.ts
packages/request/src/-private/future.ts
packages/request/src/-private/manager.ts
packages/request/src/-private/utils.ts
packages/request/src/fetch.ts

Backports all changes to the `@ember-data/request` package from 5.x as of tag `5.5.0-alpha.11`
related to #9013

feat: backport changes in request package from 5.x

---

packages/json-api/src/index.ts
packages/json-api/src/request.ts

docs: update links

---

package.json
packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/graph/package.json
packages/json-api/package.json
packages/legacy-compat/package.json
packages/model/package.json
packages/private-build-infra/package.json
packages/request/package.json
packages/schema-record/package.json
packages/serializer/package.json
packages/store/package.json
packages/tracking/package.json
packages/unpublished-test-infra/package.json
pnpm-lock.yaml
tests/ember-data__graph/package.json
tests/ember-data__json-api/package.json
tests/main/package.json

chore: bump @embroider/macros

---

packages/request/src/fetch.ts

Port https://github.com/emberjs/data/pull/9199 to release

fix: Fetch handler hacks for Mirage (release)

---

guides/requests/examples/0-basic-usage.md
guides/requests/examples/1-auth.md

Working on guides here 
Auth Handler guides section

Add auth handler guides

---

packages/serializer/src/json-api.js
tests/main/tests/integration/serializers/json-api-serializer-test.js

normalization in json-api serializer preserves lid #7956

---

release/core/publish/steps/generate-tarballs.ts

fix: update line when removing declare statements

---

release/core/publish/steps/generate-tarballs.ts

fix: use npm pack instead of pnpm pack to respect .npmignore rules

---

packages/graph/src/-private/operations/merge-identifier.ts

resolves issue reproduced here https://github.com/Eredrim/emberdata-polymorphic/

fix: set localState to latest identifier in belongsTo when merging identifiers

---

guides/requests/examples/1-auth.md
guides/requests/index.md
guides/requests/overview/0-intro.md
guides/requests/overview/1-request-management.md
guides/terminology.md

fills out additional terminology in the new guide

docs: add requests guide

---

packages/request/src/fetch.ts

Mirage's fake Responses do not support most web standards, including body, getReader, streams etc.

fix: mirage does not support anything

---

packages/request/README.md

removes a duplicate line in request readme

docs(request): remove duplicate line in readme

---

guides/requests/index.md

doc: remove reference to unexisting ESA auth handler

---

packages/ember/src/-private/await.gts
packages/ember/src/-private/request.gts

fix: @warp-drive-ember, dont leak empty slot

---

packages/model/src/-private/references/belongs-to.ts
packages/store/package.json
packages/store/src/-private/store-service.ts
packages/store/src/-private/store-service.type-test.ts
packages/store/src/-types/q/store.ts
pnpm-lock.yaml
tests/main/.eslintrc.cjs
tests/main/tests/integration/record-data/record-data-test.ts

improves types for store methods

feat: better types for legacy store methods

---

packages/model/src/index.ts

use a better name for the type

types: ManyArray => HasMany

---

packages/schema-record/src/record.ts
tests/warp-drive__schema-record/tests/legacy/create/basic-fields-test.ts
tests/warp-drive__schema-record/tests/legacy/reactivity/basic-fields-test.ts

completes the support matrix for legacy Model

feat: make @id editable and reactive

---

packages/build-config/src/deprecation-versions.ts
packages/request-utils/src/deprecation-support.ts

fix: update deprecation language for ember-inflector deprecation

---

packages/tracking/package.json
pnpm-lock.yaml

somehow we got a non-workspace dev-dep version, this fixes that

chore: fixup dev deps

---

packages/-ember-data/package.json
packages/adapter/package.json
packages/model/package.json
packages/serializer/package.json

Trying to fix issue with latest ember-learn/super-rentals-tutorial

Add export point for direct export of blueprints

---

config/vite/config.js
packages/build-config/src/-private/utils/features.ts
packages/build-config/vite.config-cjs.mjs
packages/build-config/vite.config.mjs

fix: windows builds

---

packages/schema-record/src/-private/compute.ts
packages/schema-record/src/-private/managed-array.ts
packages/schema-record/src/-private/managed-object.ts
packages/schema-record/src/record.ts
tests/warp-drive__schema-record/tests/reactivity/object-test.ts
tests/warp-drive__schema-record/tests/reactivity/schema-object-test.ts
tests/warp-drive__schema-record/tests/reads/schema-array-test.ts
tests/warp-drive__schema-record/tests/reads/schema-object-test.ts
tests/warp-drive__schema-record/tests/writes/schema-object-test.ts

feat(schema-record): handle nested objects for schema-object and schema-array

---

packages/core-types/src/schema/fields.ts
packages/schema-record/src/-private/compute.ts
packages/schema-record/src/-private/managed-object.ts
packages/schema-record/src/record.ts
tests/warp-drive__schema-record/tests/reads/alias-test.ts
tests/warp-drive__schema-record/tests/writes/object-test.ts

also fixes several issues around writes with SchemaObject and ManagedObject, and improves some factoring

feat: adds AliasField to allowed schema fields

---

packages/schema-record/src/-private/compute.ts
packages/schema-record/src/-private/managed-array.ts
packages/schema-record/src/-private/managed-object.ts
packages/schema-record/src/record.ts

pass editable and legacy so that we can properly manage editable state.

pass editable and legacy through to ManagedObject and ManagedArray

---

packages/debug/package.json
packages/debug/src/_app_/data-adapter.js
packages/debug/vite.config.mjs

fix: use an explicit re-export file for the data-adapter

---

packages/-ember-data/README.md
packages/-ember-data/src/index.ts

fix: cleanup stale config documentation

---

tests/main/tests/unit/adapter-errors-test.js
tests/main/tests/unit/debug-test.js
tests/main/tests/unit/many-array-test.js
tests/main/tests/unit/model-test.js
tests/main/tests/unit/promise-proxies-test.js
tests/main/tests/unit/utils/determine-body-promise-test.js

Check that the main/tests/unit/utils and top-level are in-sync with main

---

tests/main/tests/unit/store/adapter-interop-test.js
tests/main/tests/unit/store/asserts-test.js
tests/main/tests/unit/store/create-record-test.js
tests/main/tests/unit/store/finders-test.js
tests/main/tests/unit/store/model-for-test.js
tests/main/tests/unit/store/push-test.js
tests/main/tests/unit/store/unload-test.js
tests/main/tests/unit/system/relationships/polymorphic-relationship-payloads-test.js

Sync main/tests/unit/{system,store} w/ main

---

tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
tests/main/tests/unit/legacy-compat/formatted-id-test.js
tests/main/tests/unit/legacy-compat/formatted-type-test.js
tests/main/tests/unit/legacy-compat/is-equiv-id-test.js
tests/main/tests/unit/legacy-compat/is-equiv-type-test.js
tests/main/tests/unit/model/relationships/belongs-to-test.js
tests/main/tests/unit/model/relationships/has-many-test.js
tests/main/tests/utils/schema.ts

Legacy compat tests + finish unit/model folder

---

tests/main/tests/integration/records/collection-save-test.js
tests/main/tests/integration/records/concurrent-save-test.ts
tests/main/tests/integration/records/create-record-test.js
tests/main/tests/integration/records/delete-record-test.js
tests/main/tests/integration/records/error-test.js
tests/main/tests/integration/records/load-test.js
tests/main/tests/integration/records/new-record-unload-test.js
tests/main/tests/integration/records/polymorphic-find-record-test.ts
tests/main/tests/integration/records/property-changes-test.js
tests/main/tests/integration/records/relationship-changes-test.js
tests/main/tests/integration/records/reload-test.js
tests/main/tests/integration/records/rematerialize-test.js
tests/main/tests/integration/records/save-test.js
tests/main/tests/integration/records/unload-test.js

update integration/records tests

---

.github/workflows/compat-tests.yml
.github/workflows/docs-and-blueprint-tests.yml
.github/workflows/enforce-pr-labels-canary.yml
.vscode/settings.json
config/eslint/typescript.js
package.json
packages/tracking/src/-private.ts

various changes on the v4-main branch that should be brought forward to main

chore: updates to match v4 main

---

.github/workflows/asset-size-check.yml
.github/workflows/main.yml
.github/workflows/perf-check.yml
.github/workflows/perf-over-release.yml

Enable more workflows on v4-main

---

guides/typescript/0-installation.md
guides/typescript/1-configuration.md
guides/typescript/index.md

mainly working to clear up confusion now that more versions ship their own types

chore: misc updates to TS guide

---

packages/tracking/README.md

Fix tracking README

---

packages/build-config/src/debugging.ts
packages/graph/src/-private/-diff.ts
packages/graph/src/-private/-utils.ts
packages/graph/src/-private/edges/collection.ts
packages/graph/src/-private/edges/resource.ts
packages/graph/src/-private/graph.ts
packages/graph/src/-private/operations/add-to-related-records.ts
packages/graph/src/-private/operations/merge-identifier.ts
packages/graph/src/-private/operations/remove-from-related-records.ts
packages/graph/src/-private/operations/replace-related-record.ts
packages/graph/src/-private/operations/replace-related-records.ts
packages/graph/src/-private/operations/update-relationship.ts
packages/model/src/-private/references/has-many.ts
packages/store/src/-private/managers/notification-manager.ts
tests/docs/fixtures/expected.js
tests/main/tests/integration/references/autotracking-test.js
tests/main/tests/integration/relationships/rollback-test.ts
tests/performance/app/routes/relationship-materialization-complex.js
tests/performance/ember-cli-build.js

perf: reduce notifications during first-load

---

packages/store/src/-private/managers/notification-manager.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-test-infra.ts
tests/main/tests/unit/model/relationships/has-many-test.js

A few TODO tests needed to be guarded

chore: fixup deprecation-removed test variants

---

.github/workflows/perf-check.yml
.github/workflows/perf-over-release.yml
packages/graph/src/-private/-diff.ts
tests/performance/app/routes/relationship-materialization-complex.js

Add perf info for re-materialization

---

packages/core-types/src/request.ts
packages/request/src/-private/debug.ts

Fix: support all known http methods

---

packages/schema-record/README.md

chore: fixup SchemaRecord readme

---

.github/workflows/perf-check.yml
.github/workflows/perf-over-release.yml
tests/performance/app/router.js
tests/performance/app/routes/update-with-same-state.js
tests/performance/app/templates/application.hbs

Add perf test for replacing state with new state that matches local state

---

tests/performance/vite.config.mjs

enable minification and splitting

chore: fixup vite config for perf

---

.github/workflows/perf-check.yml
.github/workflows/perf-over-release.yml

Actually add the m2m test case to the perf test output

---

package.json
packages/build-config/src/debugging.ts
tests/docs/fixtures/expected.js
tests/performance/app/routes/update-with-same-state-m2m.js
tests/performance/ember-cli-build.js
tests/performance/fixtures/index.js
tests/performance/vite.config.mjs

separates harness fixes from #9702 so we can get the delta appropriately

chore: update perf suite

---

packages/-ember-data/app/initializers/ember-data.js

FIX: Add request-utils/deprecation-support import to ember-data initializer

---

packages/graph/src/-private/-diff.ts
packages/graph/src/-private/operations/replace-related-records.ts

Don't overnotify for updates to added state that match local updates

---

packages/build-config/vite.config.mjs
packages/core-types/src/-private.ts
packages/core-types/src/runtime.ts
packages/core-types/vite.config.mjs
packages/graph/src/-private/-diff.ts
packages/request/src/index.ts
packages/store/src/-private/managers/notification-manager.ts
packages/store/src/-private/store-service.ts
packages/unpublished-test-infra/src/test-support/asserts/assert-notification.ts
packages/unpublished-test-infra/src/test-support/asserts/index.ts
tests/ember-data__graph/ember-cli-build.js
tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
tests/warp-drive__schema-record/tests/polaris/basic-fields-field-read-test.ts

fix: better reordering detection when remoteClearsLocal is true

---

package.json
packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/legacy-compat/package.json
packages/model/package.json
packages/schema-record/package.json
packages/serializer/package.json
patches/ember-source@3.28.12.patch
patches/ember-source@4.4.5.patch
pnpm-lock.yaml
tests/blueprints/package.json
tests/builders/package.json
tests/ember-data__graph/package.json
tests/ember-data__json-api/package.json
tests/ember-data__model/package.json
tests/ember-data__request/package.json
tests/ember-data__serializer/package.json
tests/embroider-basic-compat/package.json
tests/example-json-api/package.json
tests/fastboot/package.json
tests/full-data-asset-size-app/package.json
tests/main/config/ember-try.js
tests/main/package.json
tests/performance/package.json
tests/vite-basic-compat/package.json
tests/warp-drive__ember/package.json
tests/warp-drive__experiments/package.json
tests/warp-drive__schema-record/package.json

see [ember-test-waiters#](https://github.com/emberjs/ember-test-waiters/issues/515) for motivation on patches

chore: update test-waiters to v4

---

packages/serializer/src/rest.js

fix: make warnMessageNoModelForKey safe in prod

---

packages/build-config/src/debugging.ts
packages/build-config/src/index.ts

- If this PR updates API docs, preview them by running `bun preview-api-docs`

docs: add more to the debugging guide

---

packages/core-types/src/request.ts
packages/request-utils/package.json
packages/request-utils/src/-private/handlers/auto-compress.ts
packages/request-utils/src/handlers.ts
packages/request-utils/tsconfig.json
packages/request-utils/vite.config.mjs
packages/request/src/-private/debug.ts
pnpm-lock.yaml
tests/docs/fixtures/expected.js
tests/ember-data__request/package.json
tests/ember-data__request/tests/request-utils/handlers/auto-compress-test.ts
tests/ember-data__request/tests/test-helper.ts

This adds a new handler utility to `@ember-data/request-utils` that will compress request payloads.

feat: AutoCompress handler

---

docs-viewer/docs.warp-drive.io/.vitepress/config.mts
docs-viewer/package.json
docs-viewer/src/site-utils.ts
docs-viewer/typedoc.json
pnpm-lock.yaml

- If this PR updates API docs, preview them by running `bun preview-api-docs`

docs: programatically build guides nav, begin work on api doc extraction

---

guides/concepts/requests.md

removed extra `)`
---
If this PR updates API docs, preview them by:
- run `pnpm install` in the root (if needed)
From inside the `<root>/docs-viewer` directory
- start sync for guides with `bun ./src/start-guides-sync.ts`
- build/rebuild the API docs with `pnpm typedoc` (rerun as needed)
- start the server with `pnpm dev`, visit the site url
---

docs(concepts/requests): fix glimmer-ts code example

---

packages/json-api/package.json
packages/json-api/src/index.ts
packages/json-api/tsconfig.json
pnpm-lock.yaml
warp-drive-packages/json-api/package.json
warp-drive-packages/json-api/src/-private/cache.ts
warp-drive-packages/json-api/src/-private/validate-document-fields.ts
warp-drive-packages/json-api/src/-private/validator/1.1/7.1_top-level-document-members.ts
warp-drive-packages/json-api/src/-private/validator/1.1/7.2_resource-objects.ts
warp-drive-packages/json-api/src/-private/validator/1.1/links.ts
warp-drive-packages/json-api/src/-private/validator/index.ts
warp-drive-packages/json-api/src/-private/validator/utils.ts
warp-drive-packages/json-api/src/index.ts
warp-drive-packages/json-api/tsconfig.json
warp-drive-packages/utilities/src/-private/json-api/-utils.ts
warp-drive-packages/utilities/src/-private/json-api/find-record.ts
warp-drive-packages/utilities/src/-private/json-api/find-record.type-test.ts
warp-drive-packages/utilities/src/-private/json-api/query.ts
warp-drive-packages/utilities/src/-private/json-api/query.type-test.ts
warp-drive-packages/utilities/src/-private/json-api/save-record.ts
warp-drive-packages/utilities/src/-private/json-api/serialize.ts
warp-drive-packages/utilities/src/json-api.ts
warp-drive-packages/utilities/tsconfig.json
warp-drive-packages/utilities/vite.config.mjs

```
Migration Status
@warp-drive/core
- ✅ core-types
- ✅ request
- ✅ store
- ✅ request-utils (LRUCache, dasherize)
- ✅ request-utils (CachePolicy)
- ✅ graph
- ✅ tracking (integration hooks)
- ❌ build-config
- ❌ schema-record
@warp-drive/utilities
- ✅ request-utils
- ❌ rest
- ❌ active-record
- ✅ json-api (builders)
@warp-drive/json-api
- ✅ json-api (cache)
@warp-drive/experiments
- ❌ update to consume core dep
@warp-drive/ember
- ✅ tracking (ember integration)
- ❌ update to consume core dep
@warp-drive/legacy
- ❌ model
- ❌ adapter
- ❌ serializer
- ❌ legacy-compat
```

feat: @warp-drive/json-api

---

docs-viewer/docs.warp-drive.io/.vitepress/config.mts
docs-viewer/typedoc.config.mjs

feat: split API Docs in sidebar

---

packages/diagnostic/src/runners/dom.ts
tests/warp-drive__ember/app/app.ts
tests/warp-drive__ember/ember-cli-build.js
warp-drive-packages/core/src/store/-private.ts
warp-drive-packages/core/src/store/-private/new-core-tmp/request-subscription.ts
warp-drive-packages/ember/src/-private/request.gts

Extracts the guts of the request component for easy re-use across frameworks

feat: RequestSubscription

---

tests/warp-drive__schema-record/tests/polaris/schema-object-field-reactivity-test.ts
tests/warp-drive__schema-record/tests/polaris/schema-object-field-read-test.ts
tests/warp-drive__schema-record/tests/polaris/schema-object-field-write-test.ts
warp-drive-packages/core/src/reactive/-private/fields/compute.ts
warp-drive-packages/core/src/reactive/-private/fields/get-field-key.ts
warp-drive-packages/core/src/reactive/-private/fields/many-array-manager.ts
warp-drive-packages/core/src/reactive/-private/record.ts
warp-drive-packages/core/src/reactive/-private/schema.ts
warp-drive-packages/core/src/store/-private/record-arrays/many-array.ts
warp-drive-packages/core/src/store/-types/q/schema-service.ts
warp-drive-packages/core/src/types/schema/fields.ts
warp-drive-packages/json-api/src/-private/cache.ts
warp-drive-packages/legacy/src/model/migration-support.ts

feat: sourceKey for api fields

---

guides/1-configuration/2-setup/1-universal.md
guides/1-configuration/2-setup/2-ember.md
guides/1-configuration/4-legacy-package-setup/2-setup/1-universal.md
guides/1-configuration/4-legacy-package-setup/2-setup/2-ember.md

If this PR updates API docs, preview them by:
- install [bun](https://bun.sh/docs/installation) (if needed)
- install [volta](https://docs.volta.sh/guide/getting-started) and configure it for [pnpm](https://docs.volta.sh/advanced/pnpm) (if needed)
- run `pnpm install` in the root (if needed)
- run `pnpm preview` in the root
---

Fix some docs inaccuracies

---

tests/builders/tests/integration/create-record-test.ts
tests/builders/tests/integration/delete-record-test.ts
tests/builders/tests/integration/update-record-test.ts
tests/warp-drive__schema-record/tests/edit-workflow-test.ts
warp-drive-packages/core/src/reactive.ts
warp-drive-packages/core/src/reactive/-private/record.ts
warp-drive-packages/core/src/reactive/-private/symbols.ts
warp-drive-packages/core/src/types/-private.ts
warp-drive-packages/core/src/types/cache.ts
warp-drive-packages/json-api/src/-private/cache.ts

This one is for you @gitKrystan

feat: smoother checkout process

---

packages/-ember-data/app/services/store.js
packages/-ember-data/app/transforms/boolean.js
packages/-ember-data/app/transforms/date.js
packages/-ember-data/app/transforms/number.js
packages/-ember-data/app/transforms/string.js
packages/store/src/index.ts

Fix deprecation handling for blueprint/tutorial

---

packages/diagnostic/server/bun/fetch.js
pnpm-lock.yaml
tests/ember-data__graph/package.json
tests/ember-data__json-api/package.json
tests/ember-data__model/package.json
tests/ember-data__request/package.json
tests/ember-data__serializer/package.json
tests/example-json-api/package.json
tests/full-data-asset-size-app/package.json
tests/main/package.json
tests/warp-drive__ember/package.json
tests/warp-drive__experiments/package.json
tests/warp-drive__react/README.md
tests/warp-drive__react/babel.config.mjs
tests/warp-drive__react/diagnostic.js
tests/warp-drive__react/eslint.config.mjs
tests/warp-drive__react/index.html
tests/warp-drive__react/package.json
tests/warp-drive__react/tests/integration/request-component-test.tsx
tests/warp-drive__react/tests/test-helper.ts
tests/warp-drive__react/tsconfig.json
tests/warp-drive__react/vite.config.mjs
tests/warp-drive__schema-record/package.json
tests/warp-drive__schema/package.json

we can do roughly this for vue/svelte etc as well.

chore: add react test-app

---

config/vite/config.js
pnpm-lock.yaml
tests/warp-drive__react/babel.config.mjs
tests/warp-drive__react/package.json
tests/warp-drive__react/tests/integration/reactive-context-test.tsx
tests/warp-drive__react/tests/test-helper.ts
tests/warp-drive__react/tsconfig.json
tests/warp-drive__react/vite.config.mjs
warp-drive-packages/build-config/src/debugging.ts
warp-drive-packages/core/src/store/-private.ts
warp-drive-packages/core/src/store/-private/new-core-tmp/reactivity/internal.ts
warp-drive-packages/core/src/store/-private/new-core-tmp/reactivity/signal.ts
warp-drive-packages/react/babel.config.mjs
warp-drive-packages/react/package.json
warp-drive-packages/react/src/-private/reactive-context.tsx
warp-drive-packages/react/src/index.ts
warp-drive-packages/react/src/install.ts
warp-drive-packages/react/tsconfig.json
warp-drive-packages/react/vite.config.mjs

will form the basis of Request and Await

feat: react signals

---

warp-drive-packages/core/src/request/-private/context.ts
warp-drive-packages/core/src/request/-private/manager.ts
warp-drive-packages/core/src/store/-private/managers/cache-manager.ts

chore: dont use JS private fields

---

docs-viewer/docs.warp-drive.io/.vitepress/config.mts
docs-viewer/tsconfig.json
warp-drive-packages/core/src/reactive/-private/document.ts
warp-drive-packages/core/src/request/-private/context.ts
warp-drive-packages/core/src/store/-private/managers/cache-manager.ts
warp-drive-packages/core/src/store/-private/managers/notification-manager.ts
warp-drive-packages/core/src/store/-private/managers/record-array-manager.ts
warp-drive-packages/core/src/store/-private/network/request-cache.ts
warp-drive-packages/core/src/store/-private/new-core-tmp/request-state.ts
warp-drive-packages/core/src/store/-private/new-core-tmp/request-subscription.ts
warp-drive-packages/legacy/src/compat/legacy-network-handler/snapshot.ts
warp-drive-packages/legacy/src/model/-private/legacy-relationships-support.ts
warp-drive-packages/legacy/src/model/-private/schema-provider.ts

continued work to make mirror and non-mirror types compatible

chore: remove more private types from published output

---

pnpm-lock.yaml
tests/framework-svelte/babel.config.mjs
tests/framework-svelte/diagnostic.js
tests/framework-svelte/eslint.config.mjs
tests/framework-svelte/index.html
tests/framework-svelte/package.json
tests/framework-svelte/start.ts
tests/framework-svelte/tests/request-component.spec-test.ts
tests/framework-svelte/tsconfig.json
tests/framework-svelte/vite.config.mjs
warp-drive-packages/svelte/package.json
warp-drive-packages/svelte/src/lib/install.svelte.ts

If this PR updates API docs, preview them by:
- install [bun](https://bun.sh/docs/installation) (if needed)
- install [volta](https://docs.volta.sh/guide/getting-started) and configure it for [pnpm](https://docs.volta.sh/advanced/pnpm) (if needed)
- run `pnpm install` in the root (if needed)
- run `pnpm preview` in the root
---

Add svelte test app

---

specs/src/await-component.spec.ts
specs/src/get-promise-state.spec.ts
tests/framework-react/tests/await-component.spec-test.tsx
warp-drive-packages/core/src/reactive.ts
warp-drive-packages/core/src/store/-private.ts
warp-drive-packages/ember/src/-private/await.gts
warp-drive-packages/ember/src/index.ts

move to final home and expose union types

docs: fixup PromiseState

---

warp-drive-packages/json-api/src/-private/validator/1.1/7.2_resource-objects.ts
warp-drive-packages/json-api/src/-private/validator/utils.ts

Fix validator fields parsing for Nick

---

guides/the-manual/schemas/object-schemas.md
guides/the-manual/schemas/simple-fields.md

This PR adds two new docs pages: ObjectSchemas and SimpleFields.

add(doc): ObjectSchema and Fields documentation
