addon/-private/system/store.js
tests/unit/model-test.js

On Ember 3.2 and higher, Ember uses "real" inheritance when an `Ember.Object` is `.extend()`ed. This means that in 3.2 and higher the `ModelClassHere.modelName` property is now being inherited (where previously each `.extend()` reset the value to `null`).
The fix here ensures that each `ModelClass.extend()` gets its own `modelName`...

[BUGFIX release] Fix `Model.modelName` inheritance with Ember 3.2+.

---

addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js

Maybe I'm missing something, but it seems weird for a relationship to be polymorphic by default, right ?

fix initial polymorphic attribute

---

tests/integration/store-test.js

Added this test as a sanity check that `_loadingPromise` isn't kicking us back early and that `PromiseProxy` isn't exposing data it shouldn't be when `findRecord` is used with `{ reload: true }`.

adds a more robust test around reload

---

addon/-private/system/model/states.js
tests/unit/model-test.js

resolves #4995
replaces #5231 
**Problem**
Records in the `root.deleted.saved` state currently error if new data is received from the server for the record while the record is still in the store.
For instance, a user may desire the following flow, which is now possible with this PR:
```
=> signal deletion (send actual `DELETE` request)
=> update ui state to isDeleting
=> receive notice of actual deletion
=> update ui state to isDeleted
=> unload
```
**Use Case**
Sometimes deletions are "soft deletes", and sometimes deletions may be queued on the server and the deleted state not reflect immediately in other requests.
**2.13 Regression**
Prior to 2.13 we would unload records whose deletion had been persisted. While this enabled folks to push server updates back into the store for either use …

[FEAT BUGFIX] enable canonical state updates to deleted records

---

addon/serializers/json-api.js
tests/integration/serializers/json-api-serializer-test.js
yarn.lock

Similar to #5317 but for hasMany.
Currently when saving a model with an unsaved `hasMany` a null id is used in the JSON:API document. 
For example
```js
let company = this.store.peekRecord('company', 1);
let user = this.store.createRecord('user');
company.get('users').addObject(user);
company.save();
```
Generates this post payload (note that we're using serializer option `attrs.users.serialize = true`)
```js
{
data: {
type: 'company',
id: '1',
relationships: {
users: [
data: {
type: 'users',
id: null
}
]
}
}
}
```
This is an invalid payload. To fix this, we'll filter out new records from using in the serialized belongsTo.

Don't serialize new has many relationships

---

addon/-private/system/model/internal-model.js
addon/-private/system/model/model.js
addon/-private/system/model/states.js
addon/-private/system/store.js
tests/integration/records/reload-test.js

[FEAT BUGFIX] adds adapterOptions ability to model.reload()

---

addon/-private/system/many-array.js
addon/-private/system/model/internal-model.js
addon/-private/system/relationships/belongs-to.js
addon/-private/system/relationships/has-many.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/snapshot.js
addon/-private/system/store.js
addon/attr.js
tests/integration/relationships/has-many-test.js
tests/integration/relationships/one-to-many-test.js
tests/integration/snapshot-test.js
tests/unit/model-test.js
tests/unit/model/init-properties-test.js
tests/unit/store/create-record-test.js

This restores the changes from #4931 that were removed by #5369, ensuring that in as many cases as possible we "do the expected thing" and give access to properties in `init`.
Historically, so long as `_internalModel` has data, any available record-data is available in `init`. This PR ensures that the same is true for properties passed to `createRecord`.
We achieve this by buffering the changes for dirty-state sent to `ManyArray`.  In the process, we also cleanup the responsibilities of `attr` `belongsTo` and `hasMany` descriptors who previously were responsible for the tricky logic of where to find state and how to set state on internal-model. This should help inform and improve the APIs of https://github.com/emberjs/rfcs/pull/293

[BUGFIX] Fix availability of properties in createRecord init

---

addon/-private/system/model/internal-model.js
addon/-private/system/promise-proxies.js
addon/-private/system/references/has-many.js
addon/-private/system/relationships/relationship-payloads.js
addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
addon/-private/system/snapshot.js
tests/integration/adapter/json-api-adapter-test.js
tests/integration/records/rematerialize-test.js
tests/integration/relationships/belongs-to-test.js
tests/integration/relationships/has-many-test.js
tests/integration/relationships/json-api-links-test.js
tests/integration/relationships/many-to-many-test.js
tests/integration/relationships/nested-relationship-test.js
tests/integration/relationships/one-to-many-test.js
tests/integration/snapshot-test.js
tests/unit/model/relationships/has-many-test.js
tests/unit/system/relationships/relationship-payloads-test.js

**Description**
This PR includes two fixes for links and a suite of new tests to accompany them.
The first addresses a shortcoming of the lazy-relationships work which caused `meta` and `links` information to be lossy. We now "merge forward" meta and links information on relationship payloads when necessary.  We also now handle data for `has-many` relationships discovered via their inverse in a special way (see `_partialData`). This avoids us losing information about whether the membership should be considered complete or not. 
The second addresses the situation in which both `data` and `links` are present for a relationship. We now ALWAYS prefer to fetch/re-fetch relationship data via a link if present.  To achieve this, we now do a minimal amount of book-keeping on whether the …

[FEAT BUGFIX] resolves issues with links and data in relationships

---

addon/-private/system/snapshot.js
tests/integration/snapshot-test.js

Resolves #5426 
Resolves #5419 
Adds tests for
- 1. test that a record is not materialized (e.g. internalModel.hasRecord is false) when calling `findRecord` for the very first time
- 2. test that defaultValues provided to a model reflect on attributes on snapshots (both function based and value based)
- 3. test that non-materialized records generate attributes for snapshots lazily
- 4. test that materialized records generate attributes for snapshots greedily
- 5. unskips the test for snapshots not greedily causing model classes to be looked up

make snapshot lazier and fix defaultValue

---

addon/attr.js

Due to the indentation in the description of the `defaultValue` bullet point, our markdown renderer is considering it to be a code block. I did a quick patch, but haven't verified how it renders yet.
Repro: https://www.emberjs.com/api/ember-data/3.0/classes/DS/methods/attr?anchor=attr

[DOC release] Fix documentation syntax in attr

---

addon/-private/system/model/internal-model.js
addon/-private/system/snapshot.js
addon/-private/system/store.js
tests/helpers/deep-copy.js
tests/integration/adapter/build-url-mixin-test.js
tests/integration/adapter/rest-adapter-test.js
tests/integration/records/rematerialize-test.js
tests/integration/relationships/json-api-links-test.js
tests/integration/store-test.js
tests/unit/system/relationships/polymorphic-relationship-payloads-test.js

Adds a test utility for `deepCopy` where we needed it, uses `Object.assign` everywhere else.

[CHORE] remove all usage of Ember.copy

---

addon/-private/system/model/internal-model.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/store.js
tests/integration/records/unload-test.js

resolves #5424
**Bug**
Unloading the record from a hasMany relationship immediately prior to pushing that same record with that same relationship state back into the store results in a disconnected internal-model being left behind in the has-many relationship.
**Root Cause**
When the unload and push are in the same run loop, we were calling `destroySync` to complete the destroy and before giving the user a new `InternalModel` instead of `cancelDestroy`.  Because a deletion was not signaled, `destroySync` did not remove the `InternalModel` from relationships.  This is semantically what we expect from destroy, minus the return of a brand new internal-model.
**Background**
The `destroySync` logic branch was added to support `unloadRecord` being immediately followed by `createRecord` for a …

[BUGFIX] ensure destroy-sync cleanup is correct

---

addon/-private/system/store.js
tests/integration/adapter/rest-adapter-test.js
tests/unit/model-test.js

Fastboot Shoebox rehydration works at the adapter level, waiting until `afterRender` to flush fetches means that we can't rehydrate properly on the initial render. This fixes that for the common case of routes, but likely does not fix anything for components that fetch data.
cc @krisselden

[FEAT] FASTBOOT SHOEBOX - Use actions queue so rehydration works

---

addon/-private/system/model/model.js
tests/unit/model-test.js

This changes the dreaded `(unknown mixin)` to something like `model:person`.
This will make things like this error much more useful:
> Error: Assertion Failed: You defined the 'run' relationship on (unknown mixin), but multiple possible inverse relationships of type (unknown mixin) were found on (unknown mixin). Look at http://emberjs.com/guides/models/defining-models/#toc_explicit-inverses for how to explicitly specify inverses

Give Model a static toString method

---

addon/-private/system/diff-array.js
addon/-private/system/relationships/state/has-many.js
tests/integration/records/relationship-changes-test.js
tests/unit/diff-array-test.js
tests/unit/model/relationships/has-many-test.js

resolves #4150
On master:
With 5000 records, adding 1000 on the end with a `store.push` takes 250ms in `has-many.computeChanges`
Removing them again takes another 250ms
With this PR:
adding takes 37ms
removing takes 9ms

[PERF] optimize updates to hasMany state

---

addon/-private/system/model/internal-model.js
addon/-private/system/record-arrays/record-array.js
addon/-private/system/relationships/relationship-payloads-manager.js
addon/-private/system/store.js
addon/serializers/json-api.js
addon/serializers/rest.js
tests/integration/injection-test.js
tests/unit/model-test.js
tests/unit/store/asserts-test.js
tests/unit/system/relationships/relationship-payload-manager-test.js

Resolves #4711
Resolves an issue with `createRecord` failing when being called for a non-existent model
Fixes an issue found with `toString` implementation in #5117 
Example Fail case prior to this PR:
```
let person = run(() => store.push({
data: {
type: 'person',
id: '1'
}
}));
person.constructor.modelName; // will be unset
```
Previously, we had overly complicated the process of looking up a model with a mixture of public and private and public-looking but private methods.  This complexity resulted in there being multiple code-paths by which a `ModelClass` could be looked up without a `modelName` or in which no factory for the `ModelClass` would be found but we would still attempt to `create` an instance from a missing factory.
Much of this complexity stemmed from the desire to check …

[CLEANUP BUGFIX] fix model and factory lookup

---

addon/-private/system/diff-array.js
addon/-private/system/relationships/state/has-many.js
tests/integration/records/relationship-changes-test.js
tests/unit/diff-array-test.js
tests/unit/model/relationships/has-many-test.js

This reverts commit 34aef620f6dc8a4e133da2968fbb2b2325e10a9a.
@hjdivad noted several concerns in his review of a second stage in #5269 that lead me to believe we should revert this until
- after RecordData has landed
- after further cleanup has occurred

Revert "Optimise has many notifications (#4850)"

---

addon/-private/system/relationships/state/belongs-to.js
tests/integration/relationships/belongs-to-test.js

resolves #5452 
replaces #5457 
This adds a failing test that a relationship should disassociate records
on both sides of the relationship when a payload explicitly returns null
for the data of that relationship.
`'book removed from author'` is the assertion that fails here. e.g. the record is not removed on the hasMany side.

[BUGFIX] update content of proxy for async belongs-to relationships when null data received

---

addon/-private/system/store.js

[BUGFIX] don't cause unnecessary work during destroy

---

addon/serializers/json-api.js
tests/integration/serializers/json-api-serializer-test.js

This is a fix for the issue [reported here](https://github.com/emberjs/data/pull/5324#issuecomment-386028562). We will now serialize an empty list when the relationship has no records.
This PR removes the `if (nonNewHasMany.length > 0) {` guard and restructures some of the code.

Serialize empty hasMany relationships

---

addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/store.js
addon/-record-data-rfc-private/system/model/model-data.js
tests/integration/relationships/belongs-to-test.js
tests/integration/relationships/has-many-test.js

Previously pushing an invalid relationship payload from a `has-many` would not error while a `belongs-to` would but was untested. Added tests for both.

[FEAT] improved assertions for invalid relationship payloads

---

addon/-legacy-private/system/many-array.js
addon/-legacy-private/system/relationships/state/has-many.js
addon/-legacy-private/system/relationships/state/relationship.js
package.json
tests/helpers/todo.js
tests/integration/records/relationship-changes-test.js
tests/integration/relationships/many-to-many-test.js
tests/unit/model/relationships/has-many-test.js
yarn.lock

This PR extracts the non-diff changes from #5269. In general this is just a nice cleanup PR.
It ideally would include a test to show the issue with ManyArray losing sync that it addresses; however, because we do not currently correctly diff when flushing canonical state (thereby losing local changes), this out-of-sync issue is very hard to manifest as in most scenarios we would be in the same incorrect state even though we were drawing our state from the incorrect source.  To be out-of-sync required the currentState to be different from canonicalState post flushCanonical for more changes than just `isNew` records.
I've taken the opportunity to port the tests from #5269 and converted them to `todo`. While fixing the ManyArray state won't resolve those tests, it will move our ability to fix …

[BUGFIX] ensure ManyArray state is in-sync with relationship state

---

addon/-private/utils/parse-response-headers.js
tests/unit/utils/parse-response-headers-test.js

On nix systems the headers will be delimited with only a newline (`\n`) character.
This PR changes the split to `\r?\n`, which will work for all fastboot environments as well as browsers.

Update parseResponseHeaders to work in fastboot.

---

addon/-legacy-private/system/many-array.js
addon/-legacy-private/system/model/internal-model.js
addon/-legacy-private/system/model/model.js
addon/-legacy-private/system/relationships/state/belongs-to.js
addon/-legacy-private/system/relationships/state/has-many.js
addon/-record-data-private/system/model/internal-model.js
addon/-record-data-private/system/model/model.js
addon/-record-data-private/system/relationships/state/belongs-to.js
addon/-record-data-private/system/relationships/state/has-many.js
addon/-record-data-private/system/relationships/state/relationship.js
addon/-record-data-private/system/store.js
addon/-record-data-private/system/store/model-data-wrapper.js
tests/integration/records/create-record-test.js
tests/integration/relationships/one-to-many-test.js
tests/integration/relationships/one-to-one-test.js

Added tests to cover creating and unloading an owner with associated pet, and creating and unloading a pet with associated owner
see #5472 for motivation

Add tests for createRecord+unloadRecord

---

addon/-private/system/relationship-meta.js
tests/unit/model/relationships-test.js

Given these models:
```ruby
const User = DS.Model.extend({
userProfile: DS.belongsTo(),
streamItems: DS.hasMany()
});
const UserProfile = DS.Model.extend({
user: DS.belongsTo()
});
const StreamItem = DS.Model.extend({
user: DS.belongsTo()
});
```
The inferred model type of `User.streamItems` will be `stream-item` while the type of `User.userProfile` will be `userProfile`.
This goes against the concept of all model types being dasherized.
With this change, `User.userProfile` will be converted into `user-profile`.
I'm not exactly sure where this kind of thing should be tested. It seems like it belongs in same place that the `hasMany` model type normalization tests reside, but I'm having trouble finding that place!

[BUGFIX] normalize model name for belongs to relationships

---

addon/-legacy-private/system/store.js
addon/-private/system/store/common.js
addon/-private/system/store/finders.js
addon/-record-data-private/system/store.js

The test waiter is prone to pwn-ing folks with the current implementation. New implementation to follow.

remove test waiter

---

addon/-record-data-private/system/model/internal-model.js

Use of `Object.assign` isn't supported in IE. Change to use Ember's polyfilled `assign`

[BUGFIX beta] Replace Object.assign with Ember polyfill assign

---

package.json
tests/acceptance/relationships/has-many-test.js
tests/integration/records/create-record-test.js
tests/integration/records/edit-record-test.js
tests/integration/records/load-test.js
yarn.lock

With prettier v1.14 release, the way decorators should be formated has changed a bit. Let's update ember-data's Prettier version + apply the new fomatting.
As a result [this kind of failure](https://travis-ci.org/emberjs/data/jobs/410439133) won't happen anymore.
You may want to have a look to this [prettier release note](https://prettier.io/blog/2018/07/29/1.14.0.html#javascript).

Fix `floating dependencies` test suite

---

.travis.yml
addon/-legacy-private/system/model/internal-model.js
addon/-private/system/ordered-set.js
addon/-record-data-private/system/model/internal-model.js
tests/dummy/config/targets.js
tests/integration/store-test.js
tests/unit/model-test.js
tests/unit/model/rollback-attributes-test.js

The first commit here, demonstrates the failure reported in #5556 by running the test suite in "Chrome only" mode.
Follow up commits clean things up, and ensure we test both transpiled maximally (down to IE11) and minimally.

Fixup transpilation issues with @ember/ordered-set.

---

addon/-legacy-private/system/relationships/state/relationship.js
addon/-record-data-private/system/relationships/state/relationship.js

While our `relationship.push` method is sync, we do not wait for the end of the method to `notifyPropertyChange`. This causes issues with observers which then trigger in a broken intermediate state. Here, I've fixed this for notifying that a relationship is stale after receiving a new `link`; however, it is still possible for this to go wrong for folks when new data is pushed in. In a happier future, we ought to have a better setup to ensure we always buffer ui notifications and flush after state is settled.

[BUGFIX] fix timing of ui notification to avoid trolling observers

---

package.json
yarn.lock

This does't really change much, we are still testing 2.16, 2.18, release, beta, and canary branches in CI. It just changes the default version of Ember used when you `ember test --server` in the project...

Bump default scenario ember-source version.

---

addon/-legacy-private/system/relationships/state/belongs-to.js
addon/-record-data-private/system/store.js
tests/integration/relationships/belongs-to-test.js

Will need backported to 3.2/3.3 in addition to landing in a new 3.4 beta.
This resolves an issue that @wagenet and I debugged wherein async belongsTo relationships would not wait for `internalModels` that are loading. The eager resolve would then leave the relationship in a state that appeared to be empty.
[WIP] Working on adding a test still.

[BUGFIX] use internalModel promise if already loading

---

tests/acceptance/relationships/belongs-to-test.js

This is a revisit of #5534 which I was unable to push updates to. (Many thanks to @selvaa89 for getting this going).
**Note: we need to follow up on both this and the `hasMany` acceptance test to make them work for `RecordData` as well.**

Acceptance Tests for belongsTo

---

README.md

It seems that the README contained a broken link to the Ember guides.

Updated broken link to Ember guides

---

addon/-legacy-private/system/relationships/state/belongs-to.js
addon/-legacy-private/system/relationships/state/has-many.js
addon/-legacy-private/system/store.js
addon/-private/system/store/common.js
addon/-record-data-private/system/relationships/state/belongs-to.js
addon/-record-data-private/system/relationships/state/has-many.js
addon/-record-data-private/system/store.js
tests/integration/store-test.js
tests/unit/store/async-leak-test.js

This feature enables app developers to better use `async ... await` while simultaneously detecting asynchronous test leaks in their data layer.  It is best paired with [ember-qunit's `setupTestIsolationValidation` feature](https://github.com/emberjs/ember-qunit/blob/master/addon-test-support/ember-qunit/index.js#L276).
When running an `ember-cli` application in non-production environments, this feature adds a test-waiter per-store instance that works with the [`settled()` test-helper](https://github.com/emberjs/ember-test-helpers/blob/master/API.md#settled). This test-waiter does not cause waiting by default, in order to prevent immediately breaking any apps that upgrade to this version of ember-data that do have test leaks without warning.
This feature comes with two feature flags, only …

[FEAT] TrackableRequests for when async leakage is detected

---

addon/-record-data-private/system/store.js

Issue: https://github.com/emberjs/data/issues/4761
This PR adds documentation for the `preload` param in `findRecord`.

Fixes #4761: Add doc param for preload on findRecord

---

addon/serializers/embedded-records-mixin.js

The current link to "defining relationships" returns a 404. This fixes the issue mentioned here: https://github.com/emberjs/website/issues/3504

Fixed broken link to defining relationships in guides

---

addon/adapters/rest.js

There was a [broken link](https://emberjs.com/api/ember-data/3.3/classes/DS.JSONAPIAdapter/properties/headers?anchor=headers).

fix broken link because the new API website does not support the anchor

---

.travis.yml
addon/-private/system/relationships/state/relationship.js

Per #5580 we're backporting #5537 to 3.2

[BUGFIX Backport] fix createRecord re-fetch

---

.travis.yml
addon/-private/system/relationships/state/relationship.js
appveyor.yml

Per #5580 we're backporting #5537 to 3.3

[BUGFIX Backport 3.3] fix createRecord re-fetch

---

addon/-private/system/relationships/state/belongs-to.js

Changes from #5562
Fixes #5579
This is super lazy, I couldn't get the new tests in that PR working. The testing model seems to have changed a bit between `release` and `master`. There were also changes in ` addon/-record-data-private/system/store.js`, but I think that is new code that is only in `master`.  If tests are required to merge this let me know and I will keep digging, but I thought maybe the fix was enough for a backport given the relatively small change.

[BUGFIX] backport use internalModel promise if already loading

---

addon/-legacy-private/system/relationships/state/belongs-to.js
addon/-legacy-private/system/relationships/state/has-many.js
addon/-legacy-private/system/relationships/state/relationship.js
tests/acceptance/relationships/belongs-to-test.js
tests/acceptance/relationships/has-many-test.js
tests/integration/records/create-record-test.js
tests/integration/records/reload-test.js

resolves #5548 
should possibly be backported to 3.2/3.3

[BUGFIX] Reference.reload should not cause sync-relationship assertion

---

addon/-private/system/relationships/state/belongs-to.js
addon/-private/system/relationships/state/has-many.js
addon/-private/system/relationships/state/relationship.js
tests/acceptance/relationships/has-many-test.js
tests/integration/records/reload-test.js

backport of #5582 to `3.2` release for #5595

[BUGFIX 3.2] Reference.reload should not cause sync-relationship assertion

---

addon/-legacy-private/system/relationships/state/belongs-to.js
addon/-legacy-private/system/relationships/state/has-many.js
addon/-legacy-private/system/relationships/state/relationship.js
tests/acceptance/relationships/belongs-to-test.js
tests/acceptance/relationships/has-many-test.js
tests/integration/records/create-record-test.js
tests/integration/records/reload-test.js

backport of #5582 to `3.4` release for #5595

[BUGFIX release] Reference.reload should not cause sync-relationship assertion

---

.travis.yml
addon/-private/system/store.js
appveyor.yml
package.json
tests/integration/records/unload-test.js
tests/unit/model-test.js
yarn.lock

backports fix for `modelClass.modelName` from #5406  to `2.18` to resolve #5577

Backport modelName fix from #5406 to 2.18

---

.travis.yml
addon/-private/system/store.js
appveyor.yml
package.json
tests/unit/model-test.js
yarn.lock

backports fix for modelClass.modelName from #5406 to `3.0` to resolve #5577

Backport modelName fix from #5406 to 3.0

---

addon/-private/system/store.js
tests/unit/model-test.js
yarn.lock

backports fix for modelClass.modelName from #5406 to 3.0 to resolve #5577

Backport modelName fix from #5406 to 3.1

---

addon/-legacy-private/system/store.js
addon/-record-data-private/system/store.js
tests/unit/store/asserts-test.js

Previously, it was possible to call many of these methods (perhaps accidentally) after the store was already destroyed or in the process of being destroyed. Attempting to update the state of data in a destroyed store, or add/remove data from a destroyed store is an error. Previously these errors would be difficult to diagnose, along the lines of `cannot call X of undefined`, or would simply result in strange state.
This PR will help folks detect other async and teardown timing issues in their applications and test suites in a friendlier way.
Replaces #5282 
cc @danwenzel. Many thanks for bringing this to our attention!

[FEAT] assert when methods are called on a destroyed store instance

---

addon/-legacy-private/system/relationships/state/belongs-to.js
tests/acceptance/relationships/belongs-to-test.js
tests/integration/relationships/belongs-to-test.js

Additional test coverage for async belongsTo mutation

---

addon/-legacy-private/system/store.js
addon/-record-data-private/system/store.js
tests/unit/store/asserts-test.js

Toggle `store.shouldAssertMethodCallsOnDestroyedStore = true;` To turn these deprecations into assertions.

[FEAT] deprecate instead of assert method calls on a destroyed store instance

---

addon/-legacy-private/system/relationships/relationship-payloads.js

I was mucking about with google-closure-compiler and it tripped up on these deletes that are not for properties. Looking at the blame, looks like they may have been left over from some find/replacing.

remove deletes

---

addon/-private/system/record-arrays/adapter-populated-record-array.js

In my experimentation, I've discovered that though the promise returned from `store.query()` does have array-like methods on it, the actual `AdapterPopulatedRecordArray` is what the promise *resolves to*. The promise does not behave like a proxy (or what I think Ember Proxies do...). The documentation for `store.query` states this plainly, but the documentation here misrepresented that.
For example, the original code actually would behave like this:
```javascript
// GET /users?isAdmin=true
var admins = store.query('user', { isAdmin: true });
admins.then(function() {
console.log(admins.get("length")); // Throws: "admins.get" is not a function
});
```

[DOC release] Change misleading documentation for AdapterPopulatedRecordArray

---

.eslintrc.js
addon/-legacy-private/system/many-array.js
addon/-legacy-private/system/references/belongs-to.js
addon/-legacy-private/system/references/has-many.js
addon/-legacy-private/system/relationships/state/belongs-to.js
addon/-legacy-private/system/relationships/state/has-many.js
addon/-legacy-private/system/relationships/state/relationship.js
addon/-legacy-private/system/store.js
addon/-private/system/store/finders.js
addon/-record-data-private/system/many-array.js
addon/-record-data-private/system/model/internal-model.js
addon/-record-data-private/system/promise-proxies.js
addon/-record-data-private/system/references/belongs-to.js
addon/-record-data-private/system/references/has-many.js
addon/-record-data-private/system/store.js
tests/integration/references/belongs-to-test.js
tests/integration/references/has-many-test.js

Addressing this comment: https://github.com/emberjs/data/issues/3700#issuecomment-379246701

[FEAT adapterOptions] Ensure adapterOptions use is possible throughout

---

appveyor.yml

Set the node version to be inline with `package.json`
This would fix the CI pipeline build.
I don't know why travis build is not triggered.

Update appveyor config for release branch 3.3

---

addon/-private/system/model/internal-model.js
addon/-private/system/ordered-set.js
package.json
tests/dummy/config/targets.js
tests/integration/filter-test.js
tests/integration/store-test.js
tests/unit/model-test.js
tests/unit/model/rollback-attributes-test.js
yarn.lock

Port #5557 to release branch 3.1
Related issue here https://github.com/emberjs/data/issues/5576

Backport @ember/ordered-set fix to 3.1

---

addon/adapters/rest.js
tests/integration/adapter/rest-adapter-test.js

Currently the `AbortError ` does not have any context about the request/response.
This PR adds the request method, url and error if available...
```
error.message
"The adapter operation was aborted"
error.errors[0].title
"Adapter Error"
error.errors[0].detail
"Request failed: GET http://localhost:4200/api/v1/reports"
error.errors[0].status
0
```
The problem is that when you have this error there is no related info captured to identify why the adapter aborted. For example, using a service like bugsnag or raygun, the error may not have any information to help reproduce the problem in your application.

Include request/response info with Abort error

---

lib/scripts/test-external.js

Turns out we weren't symlink-ing from within the external project directory and so we haven't been testing external partners correctly. We have work to do.

[BUGFIX] ensure external-partner tests correctly symlink

---

.travis.yml

Needed for external partner ilios-frontend where Firefox is the CI
browser of choice. The alias 'latest' refers to the [most recent released
version](https://docs.travis-ci.com/user/firefox/#version-aliases)
As I mentioned in https://github.com/emberjs/data/pull/5386#issuecomment-420745846 ilios-frontend tests have become flaky recently and the reason seems to be an issue with the shared memory allocation for [Chrome in Travis](https://github.com/testem/testem/issues/1021). New versions if Ilios will use Firefox to run tests and hopefully this will resolve the testing issues here as well.

Add firefox addon to Travis config

---

.github/ISSUE_TEMPLATE/bug.md
.github/PULL_REQUEST_TEMPLATE/first-time-contributor.md
.npmignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md

We haven't updated much of our contributor language and some time, this begins some work on that. Note, we need to update the `teams` section on `emberjs.com`

[CHORE] update contribution guidelines

---

index.js
lib/cli-flags.js
lib/stripped-build-plugins.js
tests/dummy/config/environment.js

This simplifies and reorganizes the process.argv processing that needs to be done for the two flags that we support.
This commit migrates the instrument flag handling to a single file (`lib/heimdall-utils.js`) and uses that single exported function throughout the rest of the code. It also removes the reliance on `process.env` string coercion (which apparently _can_ be broken when you've reassigned `process.env`).
It also changes around the details of the previous `--record-data-rfc-build` flag. Instead, we add a `--disable-record-data-rfc-build` flag (because as of 3.5 beta's the record data code is enabled by default). During this refactor, the `config` hook was migrated into the dummy app itself, so that ember-data no longer adds that flag to all consuming app's runtime config.

Refactor argument parsing for --instrument and --record-data-rfc-build

---

blueprints/transform-test/qunit-files/__root__/__path__/__test__.js
node-tests/fixtures/transform-test/default.js
node-tests/fixtures/transform-test/rfc232.js

fix(blueprints): remove second string argument from transform tests

---

blueprints/adapter-test/mocha-rfc-232-files/__root__/__path__/__test__.js
blueprints/test-framework-detector.js
node-tests/blueprints/adapter-test.js
node-tests/fixtures/adapter-test/mocha-rfc232.js

https://github.com/emberjs/data/issues/5292 added blueprints for RFC232 qunit tests, this PR is a starting point for adding them for Mocha.  If the direction of this PR seems satisfactory I could pretty quickly follow on with the necessary model/serializer/transform tests.

 add mocha rfc232 blueprints

---

lib/scripts/test-external.js
package.json

The Ilios-frontend tests run very long and often fail to finish before
the Travis 50 minutes timeout. Skipping the smoke tests at least ensures
that passing builds pass. Failing builds will need to be investigated
separately to ensure that smoke tests are not failing as well.

[CHORE] Allow skipping of smoke tests in long running partner tests

---

addon/adapters/rest.js
tests/integration/adapter/rest-adapter-test.js

`#5639 Include request/response info with Abort error` was released with v3.5, would be great to have this on the LTS version as well.
See PR #5639

Cherry-pick Include request/response info with Abort error

---

addon/-private/system/store.js
tests/unit/model/relationships/belongs-to-test.js

In order to ensure coalesceFindRequests works for this case.
Without this, it would trigger one find-request per belongsTo relationship, instead of correctly coalescing them together.
I have stumbled over this while trying to debug something else, and was pretty puzzled as to why it wasn't working as expected. Changing this fixed the issue for me - not sure if there is something I'm not seeing there, though.

Use _scheduleFetch instead of _fetchRecord for belongsTo relationship

---

tests/integration/relationships/inverse-relationship-load-test.js

we do not need to await synchronous `get` and `peek` calls

cleanup unnecessary await

---

addon/-private/system/store.js
tests/integration/records/load-test.js
tests/integration/store/adapter-for-test.js
tests/unit/store/lookup-test.js

Also fixes a bug with `adapterFor` that the expanded test coverage caught.
This was split out from #5708

[CHORE tests] modernize integration/store/adapter-for-test

---

addon/-private/system/many-array.js
tests/unit/model/lifecycle-callbacks-test.js
tests/unit/model/relationships/has-many-test.js

Fixes: https://github.com/emberjs/data/issues/5720
Assert that `objects` is an array or has array-like methods and return a more meaningful message when that condition is not met.

[BUGFIX 5720] - assert that replacing has-many with non-array throws assertion

---

tests/unit/model/lifecycle-callbacks-test.js

[CHORE tests] modernize unit/model/lifecycle-callbacks-test

---

CHANGELOG.md
addon/-private/system/many-array.js
addon/-private/system/model/errors.js
addon/-private/system/model/model.js
addon/-private/system/promise-proxies.js
addon/adapter.js
addon/serializer.js

As I was working on ember-api-docs I noticed some small missmatches between ED Api-docs and the actual implementation. Also EmberObject should also be referenced without a dot. I did fix these.

Fixed small Docs and Code mismatches

---

addon/-private/adapters/errors.js
addon/-private/system/references/reference.ts

As mentioned in a previous [PR](https://github.com/emberjs/data/pull/5729) this fixes some missing Docs.
Should the Reference Doc somehow be rewritten?

[DOC] Add Reference doc and AdapterError uses

---

addon/-private/system/debug/debug-adapter.js
tests/integration/debug-adapter-test.js

Fixed formatting of column desc to support many words. It used to replace only the first underscore with space and leave the rest.

[BUGFIX inspector] Fix columns names in debug-adapter

---

addon/-private/system/relationships/belongs-to.js
addon/-private/system/relationships/has-many.js

Initially, I could not find the documentation about how `async: false` relationship work. 
I found a few posts about the topic [embermap](https://embermap.com/notes/83-the-case-against-async-relationships) and [discuss](https://discuss.emberjs.com/t/what-is-an-async-relationship-async-true-vs-async-false/4107) and finally #5548 that provides the explanation about the expected behavior.
I have written some initial docs based on the mentioned github issue.

[DOC beta] Add doc for `async: false`

---

.npmignore

Don't publish .ts files in order to not make them public api until
we are confident in our typings.

Add *.ts to `.npmignore`

---

addon/-private/system/model/internal-model.js
tests/integration/records/record-data-test.js

In particular, do not instantiate them for `findRecord`

Make _recordData lazy

---

addon/-private/system/model/errors.js
tests/integration/records/error-test.js
tests/unit/model/errors-test.js

Replaces #5705 following discussion on the [RFC](https://github.com/emberjs/rfcs/pull/384) in which we decided to simply eliminate the warning vs proceeding with a deprecation.

[FEAT errors] eliminate the call to warn for add/remove/clear

---

addon/-private/system/model/errors.js

Issue  #5817 mentions two cases of deprecation warnings, changing usage of merge is being fixed in #5812, but the second case needs fixing, so here is a quick fix for it

[BUGFIX deprecation] stop calling A as constructor - partial fix for #5817

---

addon/-private/system/many-array.js

Related to #5849.
cc @rwjblue & @runspired

[BUGFIX canary] Use `filter` instead of `find` due to IE11

---

index.js

Fixes #5799 
This PR suppresses those benign-but-annoying circular dependency warnings from rollup. It's a sledgehammer-style fix where a scalpel is probably more appropriate, but I figure it's worth the PR anyway so it's a button press away if y'all decide to go this route. If not, no worries.
No tests (yet?) 'cause I'm frankly not sure how to go about writing a test for this kind of build-time thing.

[BUGFIX build] suppress circular dependency warning from rollup

---

addon/-private/system/references/record.ts

this is what was erroring during `ts:precompile` preventing `npm publish`, seems `tsc` runs with slightly different (and more aggressive) settings during precompile.

[BUGFIX tsc] ts:precompile needs RSVP Promise not native promise to be documented

---

addon/serializers/json.js

Fixes #5819
Adding type in the normalize example of app serializer
fields.forEach should have field as the second param

[DOCS] [BUGFIX] Adding type to forEach app serializer

---

addon/-private/system/store.js

After fixes in snapshots, we no longer need to do this

Stop resurecting internalModels while fetching

---

.eslintignore
blueprints/adapter/index.js
blueprints/adapter/native-files/__root__/__path__/__name__.js
blueprints/edition-detector.js
blueprints/model/files/__root__/__path__/__name__.js
blueprints/model/index.js
blueprints/model/native-files/__root__/__path__/__name__.js
blueprints/serializer/index.js
blueprints/serializer/native-files/__root__/__path__/__name__.js
blueprints/transform/index.js
blueprints/transform/native-files/__root__/__path__/__name__.js
node-tests/blueprints/adapter-test.js
node-tests/blueprints/model-test.js
node-tests/blueprints/serializer-test.js
node-tests/blueprints/transform-test.js
node-tests/helpers/setup-test-environment.js

Part of the Octane Tracking issue. 
Atm, the blueprints will only generate Native Classes if the env `EMBER_VERSION` is equal to `OCTANE`; the [octane-blueprints](https://github.com/ember-cli/ember-octane-blueprint) will set the variable.
It follows the same implementation than the Ember repo https://github.com/emberjs/ember.js/pull/17621

Update blueprints to use native JS classes

---

addon/-private/system/model/record-data.js
addon/-private/system/relationships/state/relationship.js
tests/unit/store/push-test.js

This PR changes the known to be empty behavior. It allows a second payload push without included data to keep any relationship data that the model knows about.
Related issue: https://github.com/emberjs/data/issues/5866

Don't reset sync relationship

---

package.json
yarn.lock

According to RELEASE.md, release is not done with this tool's help. Let's
remove it, as it triggers a long list of warnings.

Remove ember-cli-release

---

tests/integration/adapter/client-side-delete-test.js
tests/integration/application-test.js
tests/integration/debug-adapter-test.js
tests/unit/store/push-test.js

I noticed there were a handful of tests, one written by me!, that were failing in 2.18. This is causing the travis badge to say "build failing".
This PR updates those tests to pass in 2.18, which should get the travis to green.
Here's what I did:
* Wrapped `application.boot` in `run` for initializer tests.
* Wrapped `unloadRecord` in `run`
* Used `.get` instead of ES getter for computeds

Fix 2.18 tests for Travis/CI

---

addon/-debug/index.js
tests/integration/relationships/inverse-relationships-test.js
tsconfig.json

This PR adds a test to verify that a missing `inverse` on a one-sided association results in the same situation as having an `inverse: null`. Closes #5538.
Two questions; in the original issue, it was mentioned this behaviour ought to be deprecated. If so, where in the docs would you like to indicate this? Then I'll make that change, too. Finally, is there any reason `"experimentalDecorators": true` isn't set in `tsconfig.json`? The decorators are causing VSCode to report code everywhere. If this is something you'd like to see, I'd be more than willing to add it.

Implicit null inverse test.

---

addon/adapters/json-api.js
addon/adapters/rest.js
config/ember-try.js
package.json
tests/unit/adapters/json-api-adapter/fetch-test.js
tests/unit/adapters/rest-adapter/fetch-test.js
yarn.lock

This just rebases @tchak's work from here: https://github.com/emberjs/data/pull/5386

Rebase tchack use fetch

---

.travis.yml
package.json

This adds a script to `package.json` to run our feature linting script via `yarn lint:features` rather than using `./bin/lint-features` directly.
This makes it easier to run the script from the root package after converting to a monorepo like in https://github.com/emberjs/data/pull/5919

Add `yarn lint:features` script

---

.travis.yml

Fixes the command meant to install bower globally during CI runs.
Currently we are using `yarn add global bower`, which actually installs the packages `global` and `bower` locally rather than installing the `bower` package globally.
> Note: Unlike the `--global` flag in npm, `global` is a command which must
> immediately follow `yarn`. Entering `yarn add global package-name` will add
> the packages named `global` and `package-name` locally instead of adding
> package-name globally.
https://yarnpkg.com/lang/en/docs/cli/global/#toc-yarn-global
---
I noticed this while working on https://github.com/emberjs/data/pull/5919, where the following error was starting to show up in CI after converting to use yarn workspaces:
```
yarn add v1.13.0
error Running this command will add the dependency to …
```

Fix bower global install command for CI

---

addon/adapters/rest.js
tests/unit/adapters/rest-adapter/fetch-test.js

**Description**
This PR fixes https://github.com/emberjs/data/issues/5918. 
Appears that:
1. The fetch promise was not being returned
2. Premature error handling using `.catch` meant that the success `.then` handlers would also fire.

[RFC] Return promise in _fetchRequest

---

addon/-private/system/model/model.js
tests/unit/model-test.js

Our check for `recordData` isn't viable in the native class world because we are reserving a prop that we don't actually use yet. This leads to us having no good way to test that the prop isn't what we expect.
This said, with the direction the `custom-class` RFC have taken and the intent to introduce a non reserved-prop based lookup for the `RecordData` of an instance (which we already do internally), there is no reason to reserve this prop at all.
Note: There is still an outstanding question around why the defaultValue for this `attr` was not being returned. That case should be covered by other tests and may have simply been a timing issue with where our check is, but we should follow up with a new test for defaultValue on native classes attrs.

[BUGFIX canary] eliminate recordData prop restriction

---

addon/adapters/json-api.js

This should fix many of the partner addon issues.

[BUGFIX canary] Fix options assignment in json-api adapter

---

addon/-private/adapters/errors.js

When consuming ember@<3.8, an app would run into `error is undefined`.
This should fix the last failing job.

[BUGFIX canary] Fix this.stack assignement in AdapterError

---

.travis.yml
appveyor.yml
config/ember-try.js
lib/scripts/test-external.js
node-tests/nodetest-runner.js

Bower is still referenced in the test suite (for the external partners tests). But all the projects against which ember-data is tested have dropped Bower. 🎉

[chore] Drop references to Bower

---

addon/transforms/transform.js

Reading the [API information about transforms](https://api.emberjs.com/ember-data/release/classes/DS.Transform), the order seemed a little off. First, we indicate a basic example for transforms, and the usage that makes reference (`app/transforms/temperature`) is at the end of this section, after an option slightly more advanced.
This change moves the usage snippet right after the example.

Change order of transform usage

---

tests/unit/transform/boolean-test.js
tests/unit/transform/date-test.js
tests/unit/transform/number-test.js
tests/unit/transform/string-test.js

* instantiates the transforms for the tests via container lookup instead of the new keyword
* ports tests to modern test format
* addresses lack of assertion messages in the boolean test (others still require this fix)

[FIX transforms] don't instantiate via `new`

---

.travis.yml

In the past, this job has been used to publish to Bower registry and to S3. The S3 build has been used to build ember-data API section in emberjs doc at some time. Now, ember-data doc is fetched from npm release to build emberjs guides.
As this job is not publishing anything anymore, it sounds safe to remove it.
https://github.com/emberjs/data/pull/5602
cc @igorT

[chore] Remove Publish job from CI

---

.travis.yml
packages/-ember-data/config/ember-try.js
packages/-ember-data/tests/integration/record-array-test.js
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/adapter/README.md
packages/model/README.md
packages/serializer/README.md
packages/store/README.md
packages/store/addon/-private/system/model/model.js

This will allow some modernizations in the test suite.
LTS support has ended last February for ember-source@2.18 (https://emberjs.com/releases/).

Drop ember-source 2.18 compatibility

---

packages/-ember-data/lib/scripts/test-external.js

To create the `__external-test-cache` directory out of this repository
scope, the file hierarchy has to be climbed two steps further.

[chore] Adjust external tests cache path

---

.travis.yml
CHANGELOG.md
bin/changelog
lerna.json
package.json
packages/-ember-data/config/ember-try.js
yarn.lock

* prepare for release
* update ember-source
* filter out dependabot
* dependabot has a user and a bot :scream:
* changelog should include labeled commits
* Release Ember Data 3.9.0
* bump version

[CHORE release] backport fixes from release branch for releasing

---

index.js
package.json

This is an attempt to fix the issue with fastboot on newly generated ember apps on version 3.9.0
We have discussed this solution at length in the #fastboot channel on the Ember Community Discord and this was one of the quicker ways to fix the issue and the one that required the least amount of up-front work.
Essentially the problem arises from the fact that ember-cli-fastboot should be walking the tree of addons and finding all addons that add things to the manifest using `updateFastBootManifest()` but it currently does not 😞 
As ember-data has now added ember-fetch as a dependency, we need to include the manifest information from ember-fetch for any app that uses ember-data to be able to use fastboot.
If my explanation of this doesn't seem right please feel free to correct me 😂 
Fixes …

ember-fetch fastboot passthrough

---

packages/store/addon/-private/system/record-array-manager.js

Perf 🔥 🔥 🔥 
Previously we were failing to clear the scheduled flush because we were trying to delete the wrong thing, which led to us having a double flush in a large number of common scenarios.

[FIX recordArrayManager] removes an extraneous flush

---

packages/store/addon/-private/system/model/errors.js

Deprecation id: computed-property.override
https://deprecations.emberjs.com/v3.x/#toc_computed-property-override
This PR doesn't change [the actual computed property](https://github.com/CvX/data/blob/713d640e6d5395da7ff654f246b0969595e98f4a/packages/store/addon/-private/system/model/errors.js#L151-L158), but maybe it would be a good idea to modify that instead, since it is effectively used just as a kind of a lazy initialized property?
A possible alternative to this PR:
```diff
/**
@property content
@type {Array}
@private
*/
-  content: computed(function() {
-    return A();
-  }),
+  get content() {
+    let _content = get(this, '_content');
+
+    if (_content) {
+      return _content;
+    }
+
+    return set(this, '_content', A());
+  },
+
+  set content(value) {
+    return …
```

[CHORE] Fix the computed-property.override deprecation

---

CONTRIBUTING.md

Contributing currently says to use `ember test`, but that results in `No ember-cli-build.js found.`.
The correct command is `yarn test`.

[DOC contributing.md] | Clarifying that yarn should be used to run tests

---

packages/adapter/addon/rest.js

Uses global `jQuery` when available to avoid the deprecation on `Ember.$`. This may result in some apps using a different version of `jQuery` than expected if global `jQuery` and `Ember.$` are different versions of `jquery` (e.g. `no-conflict` mode).
cc @wagenet

[BUGFIX jQuery] avoid jQuery deprecation notice for intentional use

---

appveyor.yml
packages/-build-infra/package.json
packages/-ember-data/node-tests/fixtures/addon/package/package.json
packages/-ember-data/node-tests/fixtures/app/package/package.json
packages/-ember-data/package.json
packages/adapter/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json

[CHORE node] bump to LTS node 8

---

packages/-ember-data/tests/integration/records/edit-record-test.js
packages/store/addon/-private/system/model/record-data.ts
packages/store/addon/-private/system/relationships/state/relationship.ts

Bug wherein changing the parent of a child then unloading the original parent sets the child association to `null`.
Setup:
```js
// This is the association set up
class Child extends DS.Model {
@belongsTo('parent')
}
class Parent extends DS.Model {
@hasMany('child')
}
```
```js
// Assume here that `child` is already associated to Parent 1
const parent1 = this.store.peekRecord('parent', 1)
const child = this.store.peekRecord('child', 1)
const parent2 = this.store.peekRecord('parent', 2)
set(child, 'parent', parent2) // We are not commiting to the database yet at this point
// Delete Parent 1
parent1.unloadRecord()
child.parent // Returns null. Parent 2 is expected
```
Current work around:
```js
// Assume here that `child` is already associated to Parent 1
const parent1 = …
```

Add failing test when changing parent and unloading original parent

---

packages/-ember-data/blueprints/model/index.js
packages/-ember-data/node-tests/blueprints/model-test.js

Addresses issue https://github.com/emberjs/data/issues/5937
I suspect this may not be how you want to fix this problem - as otherwise you'd have done it by now. However, it just cost me an hour or so stepping through the code wondering what was going on, which not everyone is going to do.  Seems better to 'fix' the blueprint, and then go back to remove the parentheses if ED is updated to detect the `@attr` without them.

Add paranthesis to the Octane attr decorator when there is no data type

---

.travis.yml

* Disable `external partner tests`, `Linting`, `Enabled In-Progress Features`, `Ember Release`, `Ember Beta` & `Ember Canary` tests on tag push.
Fixes https://github.com/emberjs/data/issues/6049
You can see in my fork that all the mentioned tests do run on master: https://travis-ci.com/mbinet/data/builds/109345304
but not when I push a tag: https://travis-ci.com/mbinet/data/builds/109345324
@runspired You don't ask for it in the issue but I removed `Linting` & `Enabled In-Progress Features` as well, what do you think about that?

Ignore unneeded jobs on tag push

---

packages/-ember-data/tests/unit/adapters/json-api-adapter/ajax-test.js
packages/-ember-data/tests/unit/adapters/json-api-adapter/fetch-test.js
packages/adapter/addon/json-api.js

Fixing the bug that caused overwriting of "Accept" header in "ajaxOptions" method of the adapter. This is for addressing the issue #6058 
Change description:
1. Updated the code in "packages\adapter\addon\json-api.js". If the input hash contains value for "Accept" header, it should not be overwritten by the default "application/vnd.api+json" string.
2. Added unit tests for checking this flow.
Fixes https://github.com/emberjs/data/issues/6058

[BUGFIX release] Fixing adapter "Accept" header overwriting issue.

---

azure-pipelines.yml
packages/-ember-data/config/ember-try.js
packages/-ember-data/package.json
packages/adapter/addon/-private/index.js
packages/adapter/addon/-private/utils/determine-body-promise.ts
packages/adapter/addon/-private/utils/fetch.ts
packages/adapter/addon/-private/utils/serialize-query-params.ts
packages/adapter/addon/rest.js
yarn.lock

This change removes ember-fetch as a direct dependency of ember-data, and allows for this dependency to be provided by the host application or for users to directly use native fetch.
Having `ember-fetch` as a direct dependency of ember-data has proven troublesome. There are issues using ember-fetch as a nested dependency (these are documented in the ember-fetch README), but it is also quite difficult for ember-data to ensure that the versions of `ember-fetch` provided will actually include the correct version (duplicated addon merging in the ember-cli addon space is complicated and error prone).
This change moves the `determineBodyPromise` and `serializeQueryParams` helper functions directly into `@ember-data/adapter`. A future version of ember-fetch will drop these utilities (as well as …

[BUGFIX release] Remove ember-fetch dependency.

---

addon/adapters/rest.js

The prior detection of when to use fetch vs when to use jQuery was not properly accounting for the `fastboot` case when `ember-fetch` is not present and a `fetch` global is not present. In that scenario, `najax` would be present (provided by `fastboot` itself).
We already had the correct logic in `_ajax`, however the `useFetch` computed was returning `true` which prevented the `najax` supported branch from being used.

[BUGFIX release] Fix fetch detection in FastBoot.

---

packages/-ember-data/index.js

Fixes issue mentioned by @turbo87 in https://github.com/emberjs/data/pull/6077#issuecomment-490006581

[BUGFIX release] Fix rollup warnings for require as an external module.

---

packages/adapter/addon/rest.js

The prior detection of when to use fetch vs when to use jQuery was not properly acounting for the `fastboot` case when `ember-fetch` is not present and a `fetch` global is not present. In that scenario, `najax` would be present (provided by `fastboot` itself).
We already had the correct logic in `_ajax`, however the `useFetch` computed was returning `true` which prevented the `najax` supported branch from being used.
Note: This is https://github.com/emberjs/data/pull/6092 updated for `master` / `beta` branches.

[BUGFIX beta] Fix fetch detection.

---

packages/-build-infra/src/cli-flags.js

Works on https://github.com/emberjs/data/issues/6009
Moves away from using command flags when building eg
`yarn build --instrument` to `INSTRUMENT=true yarn build` and `ENABLE_IN_PROGRESS=true yarn build`

[CHORE] Use env variables instead of command flags

---

.eslintrc.js
.travis.yml
azure-pipelines.yml
bin/lint-js
package.json
yarn.lock

This addresses #6090 by adding the eslint plugin. Event though the actual lint rule doesn't enforce having a label for assertions (https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/assert-args.md) I feel like this could still be worthwhile to have.

[FEAT] Adding eslint-plugin-qunit

---

package.json
packages/-build-infra/node-tests/unit/babel-plugin-remove-imports-test.js

chore: remove co usage

---

bin/-tarball-info.js
bin/packages-for-commit.js
bin/test-external-partner-project.js

Resolves the "portability" requirements of #6119 
The tarballs now include the commit `SHA` in their version number, and they are placed together in a directory named via that same `SHA` (this both makes it a bit easier to quickly grab them but also helps us avoid accidentally using stale tarballs).
The script also now helpfully outputs information that can be used for quickly grabbing / making use of these tarballs, and comes with two flags that allow configuration of the generated tarballs for `local|hosted|registry` usage. These flags alter how the produced tarballs refer to the other produced tarballs in their `dependencies`.
**Building for Local Usage**
`node ./bin/packages-for-commit.js`
**Building for Hosted Tarballs**
`node ./bin/packages-for-commit.js …

[CHORE packaging] enable tarballs to be installed elsewhere

---

.travis.yml
azure-pipelines.yml
package.json

emberaddons.com is no longer maintained and the website has been taken down: https://github.com/gcollazo/ember-cli-addon-search/issues/109

[CHORE partner-tests] remove emberaddons.com

---

.gitignore
packages/-ember-data/yuidoc.json

When trying to view the latest doc changes on the API docs app, I noticed that the setup is borked.
With these changes, you can view the latest docs from this branch by following the instructions in https://github.com/ember-learn/ember-jsonapi-docs#generating-api-documentation-and-testing-api-docs-locally.
This is for https://github.com/emberjs/data/issues/6016

Fix yuidoc setup to support the split packages

---

packages/adapter/addon/-private/utils/fetch.ts
packages/adapter/addon/rest.js

We're not sure how to test this change. We'd welcome any advice 😄 (@rwjblue?)
We also added some errors for the situation where `fetch` could not be found as a module **or** on the global. We weren't sure where people would prefer to put this error (and whether it would be a problem to throw during module evaluation). We're open to any feedback on this 😄

Improve fetch

---

packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
packages/-ember-data/tests/acceptance/relationships/has-many-test.js
packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/-ember-data/tests/integration/relationships/unload-new-record-test.js
packages/store/addon/-private/system/many-array.js
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/promise-proxies.js
packages/store/addon/-private/system/references/belongs-to.js
packages/store/addon/-private/system/relationships/state/relationship.ts
packages/store/addon/-private/system/store.js
packages/store/addon/-private/system/store/record-data-store-wrapper.ts
packages/store/addon/-private/ts-interfaces/record.ts

This PR unskips tests skipped for landing RecordData and fixes regressions introduced around relationship fetching in 3.5
cc @code0100fun please confirm this resolves #5814 et al.

[BUGFIX relationships] fix infinite retry bug for failed relationship fetches

---

packages/store/addon/-private/system/store.js
packages/store/addon/-private/system/store/finders.js

Since an unknown time many many (many) years ago, `findAll` has not supported use of a `sinceToken`, even though the adapter API still has a slot for it in the arguments passed to `Adapter.findAll`.
This PR removes a bit of infra that attempted to pull an always missing sinceToken from an always empty cache attached to the InternalModel cache where we were never stashing one to begin with.
If this is a feature we wish to support, we should design a mechanism through which consuming applications can retrieve and update the sinceToken.

chore: remove dead sinceToken code

---

packages/adapter/addon/adapter.js
packages/adapter/addon/rest.js

See https://github.com/emberjs/data/pull/6163/files
and #6164.

remove remaining sinceToken and update docs

---

packages/store/addon/-private/system/model/model.js

The way this was phrase implies the exactly wrong thing. `unloadRecord` is *definitely not* about "destroying" anything.

Docs update for unloadRecord

---

.gitignore

make sure that the tarballs we produce while publishing aren't checked in

chore: ignore local tarballs

---

packages/-build-infra/src/debug-macros.js
packages/-build-infra/src/features.js
packages/canary-features/addon/environment/global.js
packages/canary-features/addon/environment/index.js
packages/canary-features/addon/index.js
packages/store/addon/-private/system/model/internal-model.ts

Topic feature flag env var

---

packages/-ember-data/tests/helpers/deprecated-test.js
packages/-ember-data/tests/integration/lifecycle-hooks-test.js
packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/-ember-data/tests/unit/model-test.js
packages/-ember-data/tests/unit/model/errors-test.js
packages/-ember-data/tests/unit/model/merge-test.js
packages/store/addon/-private/system/deprecated-evented.js
packages/store/addon/-private/system/many-array.js
packages/store/addon/-private/system/model/errors.js
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/model/model.js
packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
packages/store/addon/-private/system/record-arrays/record-array.js

Deprecating Evented for various ember-data classes.

[CHORE] RFC-0329 - adding deprecation about using evented in ember-data

---

package.json
yarn.lock

We seem to be getting lots of churn with prettier changes, so we should be deliberate about when and how we upgrade. I set the value to what is currently in the lock file
@runspired @rwjblue

lock prettier version

---

packages/store/addon/-private/system/references/has-many.js
packages/store/addon/-private/system/store.js

eliminates a private method that only had one usage

chore: eliminate store._getInternalModelForRecordData

---

packages/store/addon/-private/system/store.ts
packages/store/addon/-private/utils/promise-record.ts

tiny bit of cleanup to the `store.js` file as we prepare to refactor it more

chore: refactor promiseRecord

---

packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
packages/store/addon/-private/system/store/finders.js

This addresses the issue described in #6232. The arity check that decides whether to create a record array and pass options to adapter.query when the adapter extends `EmberObject`.
The solution suggested by @runspired is to remove the arity check completely, so I took a stab at doing that.

[BUGFIX query] Remove arity check for adapter.query

---

packages/-ember-data/.npmignore

The `.npmignore` file entry that includes the `data.json` file generated by yuidoc doesn't seem to work after the package movement. I used `yarn pack` to verify that this includes the file as a part of the published package.
We need a patch release of 3.11 with this commit.

[BUGFIX] Includes yuidoc's output data.json to published package

---

packages/-build-infra/.npmignore
packages/-ember-data/.npmignore
packages/-ember-data/package.json
packages/-ember-data/stripped-types.d.ts
packages/adapter/.npmignore
packages/adapter/package.json
packages/adapter/stripped-types.d.ts
packages/canary-features/.npmignore
packages/model/.npmignore
packages/model/package.json
packages/model/stripped-types.d.ts
packages/serializer/.npmignore
packages/serializer/package.json
packages/serializer/stripped-types.d.ts
packages/store/.npmignore
packages/store/package.json
packages/store/stripped-types.d.ts

Updates how we guard against stripping types by:
- not running `ts:precompile`
- ignoring any `.d.ts` files in our `.npmignore`
- ignoring the `/types/` directory in each package where overrides live
See https://typed-ember.github.io/ember-cli-typescript/versions/master/docs/ts-guide/with-addons#publishing

[BUGFIX release] fix type overrides

---

bin/publish.js
packages/-ember-data/.npmignore
packages/adapter/.npmignore
packages/model/.npmignore
packages/serializer/.npmignore
packages/store/.npmignore

The previous fix in #6252 didn't work properly with `npm` pack which does not run `prepublishOnly`. Incidentally this means we've not been running our `prepublishOnly` script with previous releases, and `ts:precompile` which it contained does not currently work. #6256 removes this command anyway so I've also gone ahead and removed it here to ensure we build properly.
I added the new `.npmignore` rules and made sure we do a production build for each individual package. At a glance, it appears that the `data.json` file produced in the `-ember-data` package is the only such file and contains the docs from the other packages.
cc @sivakumar-kailasam

[BUGFIX docs] ensure we publish docs

---

.travis.yml
azure-pipelines.yml
packages/-ember-data/blueprints/adapter-test/index.js
packages/-ember-data/blueprints/adapter/index.js
packages/-ember-data/blueprints/model-test/index.js
packages/-ember-data/blueprints/model/index.js
packages/-ember-data/blueprints/serializer-test/index.js
packages/-ember-data/blueprints/serializer/index.js
packages/-ember-data/blueprints/transform-test/index.js
packages/-ember-data/blueprints/transform/index.js

In 3.11 ember-data migrated its blueprints to belong to the specific packages that they operate on. Unfortunately, ember-cli (at least as of 3.12) only supports discovering blueprints from addons that are direct dependencies or devDependencies of the project.
This adds re-exports for each of the blueprints from the top level `ember-data` package in order to make `ember g model` (and friends) work properly when the project depends on `ember-data` and not the individual `@ember-data/*` packages themselves.

[BUGFIX release] Add blueprints to ember-data package.

---

.travis.yml
azure-pipelines.yml
bin/publish.js
packages/-build-infra/.npmignore
packages/-ember-data/.npmignore
packages/-ember-data/blueprints/adapter-test/index.js
packages/-ember-data/blueprints/adapter/index.js
packages/-ember-data/blueprints/model-test/index.js
packages/-ember-data/blueprints/model/index.js
packages/-ember-data/blueprints/serializer-test/index.js
packages/-ember-data/blueprints/serializer/index.js
packages/-ember-data/blueprints/transform-test/index.js
packages/-ember-data/blueprints/transform/index.js
packages/-ember-data/package.json
packages/-ember-data/stripped-types.d.ts
packages/adapter/.npmignore
packages/adapter/package.json
packages/adapter/stripped-types.d.ts
packages/model/.npmignore
packages/model/package.json
packages/model/stripped-types.d.ts
packages/serializer/.npmignore
packages/serializer/package.json
packages/serializer/stripped-types.d.ts
packages/store/.npmignore
packages/store/package.json
packages/store/stripped-types.d.ts

backports #6256 and #6257 to release

Backport fixes for release

---

package.json
packages/-ember-data/tests/helpers/store.js
packages/-ember-data/tests/integration/adapter/queries-test.js
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/references/record.ts
packages/store/addon/-private/system/store.ts
packages/store/addon/-private/system/store/finders.js
packages/store/addon/-private/ts-interfaces/ember-data-json-api.ts
yarn.lock

`Service.extend` forces us to move all properties onto the prototype in order for them to be type checked, the syntax does not allow for method overloads, and TS struggles to flow expected types through the store methods.
This PR refactors the store into a native class, giving us much improved type checking and allowing us to use method overloads.
It surfaced one issue where we expect folks to be able to overwrite `adapter` as a property on the store when extending; however, when using babel+typescript and a class this is transpiled with an automatic initializer to `void 0` that overwrites anything set via `create` or `extend`. We worked around this by not declaring that particular property and using a (nasty) type cast in the two locations we access it. @rwjblue does not believe this …

chore: refactor store to class

---

.travis.yml
azure-pipelines.yml
packages/-build-infra/src/utilities/edition-detector.js
packages/-build-infra/src/utilities/test-framework-detector.js
packages/adapter/blueprints/adapter-test/index.js
packages/adapter/blueprints/adapter/index.js
packages/model/blueprints/model-test/index.js
packages/model/blueprints/model/index.js
packages/serializer/blueprints/serializer-test/index.js
packages/serializer/blueprints/serializer/index.js
packages/serializer/blueprints/transform-test/index.js
packages/serializer/blueprints/transform/index.js

This fixes unable to generate models, adapters, serializers, and transforms.
Note: This is my first attempt to commit to ember-data.
Also fixes #6263 
Please note that we could not just override `path` or `filesPath` because `path` gets overwritten on `init` and `filesPath` is patched from outside the blueprints object.
Update: Rebased against master

[BUGFIX RELEASE] Fix generating from blueprints

---

packages/canary-features/addon/default-features.js

#6272 accidentally left these two flags on while debugging a test failure. This turns them back off until we explicitly turn them on later.

[BUGFIX canary] turn off identifiers until we explicitly PR the flag on

---

.travis.yml
azure-pipelines.yml
packages/-ember-data/config/ember-try.js

EmberData's LTS support policy is for two previous LTS releases of Ember. Since master is currently targeting 3.13 and since 3.12 will be an LTS release, this means that on master we no longer need to support 3.4.
Once 3.12 LTS is released we will need to add that into the test configuration.

[CHORE ci] Remove 3.4 LTS scenario for 3.13

---

packages/-ember-data/testem.js

`disable-gpu` is breaking headless chrome

[BETA RELEASE] remove disable-gpu from testem

---

bin/publish.js

resolves #6297 (for originally reported issue)
There is a separate issue affecting 3.11 (and soon 3.12) in which transforms are not being re-exported in `-ember-data/addon/transforms/*` for legacy path support for folks previously extending these transforms.

[BUGFIX beta] ensure produced artifacts correctly lock with each other

---

packages/-ember-data/tsconfig.json

Need to set `allowJs` to false becuase of codedoc comments which conflict with typescript usage.
discussed this over slack with @mike-north Eventually we might want to redo the jsdoc comments, but I think in practice we will end up typing the remaining js files before that.

fix ts package resolution

---

bin/publish.js

https://github.com/emberjs/data/commit/2bd02463315871ab5fb4060d813f944d24d5aa58 introduced a change to bin/publish.js that failed linting, this fixes it.

[BUGFIX BETA] Fix linting issue in bin/publish.js

---

packages/store/addon/-private/system/model/model.js

Extracted from https://github.com/emberjs/data/pull/6098
Fixes the following warning:
```
'@ember-data/store' is imported by -private/system/model/model.js, but could not be resolved – treating it as an external dependency
```
I'm not sure I understand why but it seems like Rollup does not like the other style of import.
This also resolves an issue with the external partner tests for ember-observer. You can see an example of what happens without this at https://dev.azure.com/ember-data/emberjs/_build/results?buildId=962

[BUGFIX beta] Fix Rollup warning about unresolved dependency

---

.travis.yml
azure-pipelines.yml
package.json
packages/-ember-data/package.json
packages/store/addon/-private/system/store.ts

This updates the CI config to fail the build if TypeScript compilation
fails.
This also fixes the following existing TypeScript compilation error:
```
../store/addon/-private/system/store.ts:19:24 - error TS2305: Module '"../../../../../../../../../../Users/eric/code/emberjs/data/node_modules/@types/ember__debug"' has no exported member 'deprecate'.
```

Fail CI when TypeScript errors

---

packages/-build-infra/src/addon-build-config-for-data-package.js

This allows us to:
* Gather data about size per `-private` module
* Gather usage details about each `-private` module (via Chrome's coverage stats)
* Test the overall application performance impact of doing the `rollup` stages (do we still need them? how much impact does it have?)

[BETA] Add environment variable to opt-out of rolling up `-private`

---

packages/-ember-data/tests/integration/adapter/find-all-test.js
packages/-ember-data/tests/integration/record-array-test.js
packages/-ember-data/tests/unit/model/rollback-attributes-test.js

Some operations in Ember Data flush using `run.join`. This will flush
_synchronously_ if no runloop or autorun currently exists, but will
join the existing runloop otherwise, making the scheduled task
effectively asynchronous.
With the tracked properties feature flag enabled, the way we've
scheduled autoruns has changed. A few Data tests were failing because
they were expecting an operation to flush synchronously, but it flushed
asynchronously due to an existing autorun. This PR adds appropriate
`await settled();` statements in these cases.

[BUGFIX] Await potentially async operations

---

packages/store/addon/-private/identifiers/utils/uuid-v4.ts

@HeroicEric discovered that storefront tests fail when accessing `crypto` without `window`. We are still looking into the underlying causes

[BUGFIX] Fix crypto to `window.crypto`

---

packages/store/addon/-private/system/store.ts

We can't use @computed because we can't rely on consumer apps having the computed class polyfill

[BUGFIX BETA CANARY] remove decorator CP usage from es6 classes

---

packages/-ember-data/tests/unit/model/rollback-attributes-test.js

Mostly reverts https://github.com/emberjs/data/commit/bde7c386c29c7675cde27e00dcbc847050b2e2ce due to further changes to observer behavior in https://github.com/emberjs/ember.js/commit/e9714186c4954d10fac

[CHORE] fix test observers to match ember canary changes

---

packages/-build-infra/package.json
packages/model/package.json

@ember-data/-build-infra directly requires `@ember-data/canary-features` (in `packages/-build-infra/src/features.js`), but without a dependency on it directly we can't ensure that it is present.

[BUGFIX release] Add @ember-data/canary-features dependency where used.

---

packages/-ember-data/tests/unit/debug-test.js
packages/store/addon/-private/system/model/model.js

This fixes a bug in inspector where the groups are named the model name instead of the relationship type.

Set group name to relationship.kind

---

packages/-ember-data/tests/helpers/store.js
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/unit/store/adapter-interop-test.js

This PR is meant to eliminate `-rest` usage as described in #6166. 
Follow up:
- drop `-rest` from `createStore` && `setupStore`
- if using RestAdapter, also register RestSerializer explicitly in test
- drop `-default` from `createStore` && `setupStore` and instead register `application`.  Don't set this adapter on store in these helpers
...
Ref https://github.com/emberjs/data/issues/6166

[INTERNAL]: replace -rest adapter usage in tests

---

packages/-ember-data/addon/-private/system/debug/debug-adapter.js

This will be useful for debugging in the future when developers are stepping through both this `debug-adapter` and the `m3` `debug-adapter`.

[DOC debug-adapter]: Add comments for each method in debug-adapter

---

packages/serializer/addon/rest.js

Update rest serializer `isPrimaryType` to not use store anymore. 
Closes #5809

[CHORE] Use model name instead of store in isPrimaryType

---

packages/-ember-data/tests/integration/adapter/find-all-test.js
packages/-ember-data/tests/integration/application-test.js
packages/-ember-data/tests/integration/debug-adapter-test.js
packages/-ember-data/tests/integration/inverse-test.js
packages/-ember-data/tests/integration/lifecycle-hooks-test.js
packages/-ember-data/tests/integration/polymorphic-belongs-to-test.js
packages/-ember-data/tests/integration/record-array-manager-test.js
packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
packages/-ember-data/tests/integration/snapshot-test.js

Updating a few tests at the top level of the integration directory...more to come but wanted to get something up to make sure i'm on the right track.
@runspired

[CHORE] Modernize integration/ tests and remove run loop calls

---

packages/-ember-data/package.json
packages/-ember-data/tests/unit/model-test.js
packages/-ember-data/tests/unit/model/relationships-test.js
packages/model/addon/-private/attr.js
packages/model/addon/-private/belongs-to.js
packages/model/addon/-private/has-many.js
packages/model/addon/-private/util.ts
packages/model/package.json

This will only be added in modern Ember versions that support decorators. I tried to figure out how to write better tests, but I couldn't find basic unit tests to emulate, will definitely take pointers if anyone has any!

[FEAT] Adds support for parenless attr, belongsTo, and hasMany

---

packages/-ember-data/addon/setup-container.js
packages/-ember-data/tests/helpers/store.js
packages/-ember-data/tests/integration/serializers/json-serializer-test.js
packages/-ember-data/tests/unit/store/adapter-interop-test.js

This PR allows for more incremental migration away from `createStore` and `setupStore` to modern test syntax.
Specifically it
- ensures that we aren't registering anything unneeded for tests currently
- provides a path for registering a serializer for use with the test
- encourages use of "application" adapter/serializer
cc @pete-the-pete @snewcomer

[CHORE tests] simplify setupStore registrations

---

packages/-ember-data/tests/unit/adapter-errors-test.js
packages/-ember-data/tests/unit/debug-test.js
packages/-ember-data/tests/unit/diff-array-test.js
packages/-ember-data/tests/unit/many-array-test.js
packages/-ember-data/tests/unit/modules-test.js
packages/-ember-data/tests/unit/private-test.js
packages/-ember-data/tests/unit/promise-proxies-test.js
packages/-ember-data/tests/unit/states-test.js
packages/-ember-data/tests/unit/system/relationships/polymorphic-relationship-payloads-test.js
packages/-ember-data/tests/unit/utils-test.js

Converts the remaining QUnit modules that are using the non-nested syntax to the nested syntax.
This will help reduce noise in diffs for further work to modernize the test suite to use things like the `setupTest` helper from `ember-qunit`.
**Highly recommend hiding whitespace changes while reviewing**

[CHORE tests] Convert non-nested QUnit modules to nested

---

packages/-build-infra/src/utilities/extend-from-application-entity.js
packages/adapter/blueprints/adapter/index.js
packages/adapter/node-tests/blueprints/adapter-test.js
packages/model/blueprints/model/files/__root__/__path__/__name__.js
packages/model/blueprints/model/index.js
packages/model/blueprints/model/native-files/__root__/__path__/__name__.js
packages/model/node-tests/blueprints/model-test.js
packages/serializer/blueprints/serializer/index.js
packages/serializer/blueprints/transform/files/__root__/__path__/__name__.js
packages/serializer/blueprints/transform/native-files/__root__/__path__/__name__.js
packages/serializer/node-tests/blueprints/serializer-test.js
packages/serializer/node-tests/blueprints/transform-test.js

This updates all the blueprints to use the namespaced package imports from https://github.com/emberjs/rfcs/blob/master/text/0395-ember-data-packages.md
Blueprints updated for:
- adapters
- serializers
- models
- transforms

[CHORE blueprints] Update blueprints to use package imports

---

packages/-ember-data/addon/setup-container.js
packages/-ember-data/app/serializers/-default.ts
packages/-ember-data/app/serializers/-json-api.ts
packages/-ember-data/app/serializers/-rest.ts
packages/-ember-data/app/transforms/boolean.ts
packages/-ember-data/app/transforms/date.ts
packages/-ember-data/app/transforms/number.ts
packages/-ember-data/app/transforms/string.ts
packages/-ember-data/tests/helpers/store.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/-ember-data/tests/unit/store/adapter-interop-test.js
packages/adapter/types/require/index.d.ts
packages/serializer/tsconfig.json
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/store/serializers.js
packages/store/index.js
packages/store/types/require/index.d.ts

**Default Serializers**
Previously several `-json` and `-defaults` serializers corresponding to the `JSONSerializer` and `JSONAPISerializer` were added to applications via `inject`. These are now added via a re-export in the `app/` directory, making them overrideable and easier to drop.
**Transforms**
The RFC for packages intentionally did not provide import paths for the transforms we provide (`date`, `number` `boolean` `string`). A more ideal location for these transforms would be for them to exist in the `app/transforms` directory as overridable defaults; however, in order to continue supporting the legacy import locations in the `ember-data` package they continue to live in`@ember-data/serializer/-private` from whence they are re-exported.
Once the deprecation lifecycle is complete …

[FEAT serializers] clean up packages organization

---

packages/-ember-data/tests/helpers/store.js
packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
packages/-ember-data/tests/integration/record-arrays/peeked-records-test.js
packages/-ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
packages/-ember-data/tests/unit/debug-test.js
packages/-ember-data/tests/unit/model/lifecycle-callbacks-test.js
packages/-ember-data/tests/unit/model/merge-test.js
packages/-ember-data/tests/unit/store/adapter-interop-test.js
packages/-ember-data/tests/unit/store/create-record-test.js
packages/-ember-data/tests/unit/store/has-model-for-test.js
packages/-ember-data/tests/unit/store/unload-test.js
packages/-ember-data/tests/unit/system/relationships/polymorphic-relationship-payloads-test.js

From https://github.com/emberjs/data/issues/6166
This refactors some tests so that they don't rely on the `createStore` test helper.
`createStore` was helpful in the past but is less so now that we have [nice APIs for dependency injection](https://guides.emberjs.com/release/applications/dependency-injection/).
---
One test was removed from `unit/store/adapter-interop - Store working with a Adapter` because I don't think it was correct.
Here was the test:
https://github.com/emberjs/data/blob/39182f324d5777e4a75c4a582f0791631e37d8de/packages/-ember-data/tests/unit/store/adapter-interop-test.js#L28-L32
This test was, at one time, testing that it was possible to pass a factory as the `adapter` property to `Store`. This feature was removed in https://github.com/emberjs/data/pull/3191 but the …

[CHORE] Refactor away from `createStore` test helper

---

packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/-ember-data/tests/integration/relationships/many-to-many-test.js
packages/-ember-data/tests/integration/relationships/nested-relationship-test.js
packages/-ember-data/tests/integration/relationships/one-to-many-test.js
packages/-ember-data/tests/integration/relationships/one-to-one-test.js
packages/-ember-data/tests/integration/relationships/polymorphic-mixins-belongs-to-test.js
packages/-ember-data/tests/integration/relationships/polymorphic-mixins-has-many-test.js

Part of https://github.com/emberjs/data/issues/6166
Follow up to https://github.com/emberjs/data/pull/6347
This replaces usage of the `setupStore` helper for `tests/integration/relationships/*`.
cc @runspired

[CHORE tests] Replace setupStore for relationship integration tests

---

packages/-ember-data/tests/integration/adapter/client-side-delete-test.js
packages/-ember-data/tests/integration/adapter/find-test.js
packages/-ember-data/tests/integration/adapter/json-api-adapter-test.js
packages/-ember-data/tests/integration/adapter/queries-test.js
packages/-ember-data/tests/integration/adapter/record-persistence-test.js
packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/-ember-data/tests/integration/adapter/serialize-test.js
packages/-ember-data/tests/integration/adapter/store-adapter-test.js

Part of https://github.com/emberjs/data/issues/6166
This replaces usage of the `setupStore` helper for `tests/integration/adapter/*`.
cc @runspired

[CHORE tests] Replace setupStore for adapter integration tests

---

packages/-ember-data/tests/helpers/async.js

Fixes the following deprecation that is triggered via the `asyncEqual`
custom QUnit assertion:
```
assert.push is deprecated and will be removed in QUnit 3.0. Please use assert.pushResult instead (https://api.qunitjs.com/assert/pushResult).
```
For reference:
- [QUnit.assert.pushResult() docs](https://api.qunitjs.com/assert/pushResult)
- [QUnit.push() docs](https://api.qunitjs.com/config/QUnit.push)

[CHORE tests] Fix QUnit.assert.push() deprecation

---

packages/-ember-data/tests/unit/adapters/json-api-adapter/ajax-options-test.js
packages/-ember-data/tests/unit/adapters/rest-adapter/ajax-options-test.js
packages/adapter/addon/json-api.js
packages/adapter/addon/rest.js

Piggybacked off of #6169 with some tests and default content type header
close #6341 #6167

[BUGFIX]: set Content-Type for non GET requests only

---

packages/-ember-data/tests/helpers/store.js
packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js
packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/-ember-data/tests/integration/serializers/rest-serializer-test.js
packages/-ember-data/tests/integration/store-test.js
packages/-ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
packages/-ember-data/tests/unit/model/rollback-attributes-test.js

[RFC-522](https://github.com/emberjs/rfcs/pull/522) will deprecate the `-rest` serializer and usage of the `adapter.defaultSerializer` fallback which for the RESTAdapter is set to `-rest`. This PR entirely removes our reliance on this fallback from our own test suite.
cc @pete-the-pete for RFC-522
cc @HeroicEric towards efforts on eliminating setupStore

[CHORE tests] eliminates usage of -rest serializer fallback in tests

---

packages/-ember-data/tests/helpers/store.js
packages/-ember-data/tests/integration/adapter/find-all-test.js
packages/-ember-data/tests/integration/adapter/json-api-adapter-test.js
packages/-ember-data/tests/integration/adapter/queries-test.js
packages/-ember-data/tests/integration/client-id-generation-test.js
packages/-ember-data/tests/integration/lifecycle-hooks-test.js
packages/-ember-data/tests/integration/record-array-test.js
packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
packages/-ember-data/tests/integration/records/unload-test.js
packages/-ember-data/tests/integration/snapshot-test.js
packages/-ember-data/tests/unit/model-test.js

The intent of this PR is to mirror #6368 but for -json-api fallback behavior.
[RFC-522](https://github.com/pete-the-pete/rfcs/blob/master/text/0000-default-serializers-and-adapters.md#deprecate-storedefaultadapter--json-api-and-the--json-api-adapter-fallback-behavior) will deprecate the -json-api serializer and usage of the adapter.defaultSerializer fallback which for the JSONAPIAdapter is set to -json-api. This PR entirely removes our reliance on this fallback from our own test suite.
Part of https://github.com/emberjs/data/issues/6166
Co-Authored-By: Eric Kelly <heroiceric@gmail.com> @HeroicEric

[CHORE tests] Added explicit -json-api serializer registration in tests

---

packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
packages/store/addon/-private/system/record-data-for.js
packages/store/addon/-private/system/relationships/state/relationship.ts

This results for us in a large memory leak: our application has a small set of long living records and during the lifetime it receives a large number of records (those records will be deleted after a while) that has a belongsTo (with implicit inverse) reference to the records in the first set.

Clean up inverse implicit relationships, when record is destroyed.

---

packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/adapter/addon/-private/utils/determine-body-promise.ts
packages/adapter/addon/rest.js

Fixes #6083 
The issue wasn't pretender after all. ember-fetch overrides ajaxError so we have to move the debugging code.

Make rest adapter test pass for fetch

---

.eslintrc.js
packages/-ember-data/tests/unit/model-test.js
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/model/model.js

- Related RFC: https://github.com/emberjs/rfcs/blob/master/text/0329-deprecated-ember-evented-in-ember-data.md
- Original PR: https://github.com/emberjs/data/pull/6059
- Fixes bugs with deprecation logic for `Model` lifecycle event methods
- Adds URL to deprecation guide
- Adds tests for `Model` lifecycle event method deprecations
---
Deprecations were added for the following model lifecycle events `becameError`, `becameInvalid`, `didCreate`, `didDelete`, `didLoad`, `didUpdate`, `ready`, `rolledBack` in https://github.com/emberjs/data/pull/6059.
There was a discussion on the PR that suggested adding an additional check to make sure that that the deprecations were only triggered for instances of Ember Data's `Model` class https://github.com/emberjs/data/pull/6059#discussion_r284921979
This …

[BUGFIX release beta canary] Fix Model lifecycle event deprecations

---

.eslintrc.js
azure-pipelines.yml
bin/publish.js
packages/-build-infra/src/addon-build-config-for-data-package.js
packages/-ember-data/tests/integration/adapter/find-all-test.js
packages/-ember-data/tests/integration/record-array-test.js
packages/-ember-data/tests/unit/model-test.js
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/model/model.js
packages/store/addon/-private/system/store.ts

`bc0cb5d`: `id setting` was erroneously not tagged as needing to be backported to beta, and it needs to be because it fixes intimate api breakage for addons

Backporting beta fixes

---

packages/-build-infra/src/utilities/extend-from-application-entity.js
packages/-build-infra/src/utilities/module-unification.js
packages/-test-infra/src/node-test-helpers/setup-test-environment.js
packages/adapter/blueprints/adapter-test/index.js
packages/adapter/blueprints/adapter/index.js
packages/adapter/node-tests/blueprints/adapter-test.js
packages/model/blueprints/model-test/index.js
packages/model/blueprints/model/index.js
packages/model/node-tests/blueprints/model-test.js
packages/serializer/blueprints/serializer-test/index.js
packages/serializer/blueprints/serializer/index.js
packages/serializer/blueprints/transform-test/index.js
packages/serializer/blueprints/transform/index.js
packages/serializer/node-tests/blueprints/serializer-test.js
packages/serializer/node-tests/blueprints/transform-test.js

This experiement has been disabled in Ember, meaning it can't be used anymore (starting from `ember-source@v3.12.0-beta.1`).

Remove module-unification blueprints

---

packages/store/addon/-private/system/references/has-many.js

I think this was missing. This should also fix: https://github.com/ember-learn/ember-api-docs/issues/630.

[DOC HasManyReference] Indicate that HasManyReference extends Reference

---

packages/store/addon/-private/system/references/belongs-to.js
packages/store/addon/-private/system/references/has-many.js
packages/store/addon/-private/system/references/record.ts

Some minor things I noticed when reading the `RecordReference`, `BelongsToReference` and `HasManyReference` docs.

Improve RecordReference, BelongsToReference and HasManyReference docs

---

bin/-tarball-info.js
bin/publish.js

At some point recently `npm` installs began semver validating package versions. The versions we were producing for builds for individual commits failed validation because we required a `-` or ` +` before the sha.
Based on the precedence rules outlined here: https://github.com/semver/semver/blob/master/semver.md
I've updated our versioning from `x.x.x.<SHA>` to `x.x.x+sha.<SHA>`
for beta/canary branches the `-beta` and `-alpha` pre-release identifier will already be present

[BUGFIX BETA RELEASE] ensure commit based versioning passes semver

---

packages/store/addon/-private/ts-interfaces/utils/brand.ts
packages/store/addon/-private/ts-interfaces/utils/symbol.ts

Port https://github.com/emberjs/data/pull/6389 to 3.12
This solves will close https://github.com/emberjs/data/pull/6389
~~🚧 We have to re-target this PR against a `release-3.12` branch, that need to be created. ⚠️~~ EDIT: done

[BUGFIX 3.12] Backport Symbol fix

---

bin/sync-dev-dependency
package.json
packages/-ember-data/package.json
yarn.lock

Noticed thisi issue while working on #6373
Prevents sync-dev-dependency from hoisting @ember-data/-test-infra
Also ensures newline at end of files in accordance with .editorconfig
Also runs sync-dev-dependency script

[BUGFIX] sync-dev-dependency should not hoist @ember-data/-test-infra

---

packages/adapter/addon/-private/utils/fetch.ts

Backports #6430 to beta
* [BUGFIX BETA RELEASE] make fetch function JIT
* ensure pretender can hijack the fetch fn

[BUGFIX BETA] make fetch function JIT (#6430)

---

packages/store/addon/-private/system/fetch-manager.ts
packages/store/addon/-private/system/request-cache.ts
packages/store/addon/-private/ts-interfaces/utils/brand.ts
packages/store/addon/-private/ts-interfaces/utils/symbol.ts

Backports #6389 to beta
* Add a Symbol-like symbol (thank you glimmer-vm)
This is similar to what is implemented here:
https://github.com/glimmerjs/glimmer-vm/blob/72718d0d6ebb2614ec984f51435a44830d410e4c/packages/%40glimmer/reference/lib/validators.ts
* Replace `Symbol`s that may be iterable by `symbol`s
These occurences of Symbol might be replaced by this `symbol`, similar
but different in the sense it is iterable.

fix: Strip Symbol from production builds (#6389)

---

packages/-build-infra/package.json

[BUGFIX RELEASE] Fix missing @babel/plugin-transform-block-scoping dependency (#6432)

---

packages/-ember-data/tests/integration/identifiers/cache-test.ts
packages/store/addon/-private/identifiers/cache.ts
packages/store/addon/-private/identifiers/is-stable-identifier.ts
packages/store/addon/-private/ts-interfaces/identifier.ts

This is an attempt at removing the last `Symbol`s from master. The goal is to fix IE compatibility regarding Symbol support, as detailed in this issue: https://github.com/emberjs/data/issues/6380. 
It won't have to be backported. Indeed, the Identifier feature has been turned on in https://github.com/emberjs/data/pull/6366 and included in a tag for the first time in `v3.14.0-alpha.2`.
Thank you for pointing me to that solution @rwjblue (https://github.com/emberjs/data/pull/6389).
With the implementation I've done, I'm concerned by the fact:
- it kind of changes the `StableIdentifier` interface
- the `isStableIdentifier` signature is modified
But as it is still on canary, it might be fine?
Is the `symbol` fix good enough? It has been suggested it could be replaced by the WeakMap fix every …

[BUGFIX canary]: Remove the last Symbols

---

packages/-build-infra/package.json
packages/-build-infra/src/utilities/edition-detector.js
packages/-test-infra/package.json
packages/-test-infra/src/node-test-helpers/setup-test-environment.js
packages/adapter/package.json
packages/model/blueprints/model/index.js
packages/model/package.json
yarn.lock

[@ember/edition-utils](https://github.com/emberjs/ember-edition-utils)
was created to make it easier to both set and retrieve the current
edition information.

[BUGFIX beta] Update edition detection logic.

---

packages/serializer/addon/rest.js

Maybe this deprecation should be removed altogether (and throw some kind of error) since we've passed 3.0?

[DOC] Added URL to `queryRecord` deprecation warning

---

packages/-serializer-encapsulation-test-app/.eslintrc.js
packages/-serializer-encapsulation-test-app/.template-lintrc.js
packages/-serializer-encapsulation-test-app/app/app.js
packages/-serializer-encapsulation-test-app/app/router.js
packages/-serializer-encapsulation-test-app/config/targets.js
packages/-serializer-encapsulation-test-app/ember-cli-build.js
packages/-serializer-encapsulation-test-app/package.json
packages/-serializer-encapsulation-test-app/tests/integration/requests-test.js
packages/store/package.json
yarn.lock

First Test for #6460 
Also fixes linting in new serializer-encapsulation-test-app package

[TEST] First encapsulation test

---

.github/workflows/main.yml

Without this change, all pushed tags will *not* do a CI build (because there must be at least one positive match if any filtering is done).

Ensure tags start a CI job.

---

packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
packages/store/addon/-private/system/model/internal-model.ts

This fixes an error with async `belongsTo` relationships throwing an error like:
```
Cannot read property 'isDestroying' of null
```
This happens when the relationship fetch fails the first time and is then accessed again later.

[BUGFIX relationships] fix proxy isDestroying error

---

packages/-ember-data/tests/unit/model-test.js
packages/store/addon/-private/system/deprecated-evented.js

In #6059 deprecation warnings for Evented usage we added. This PR adds a URL to the deprecation documentation for the console warnings.
**before**
**after**

[DOC] Added documentation URL to evented deprecation warnings

---

packages/-ember-data/tests/integration/identifiers/cache-test.ts

Instead of the more permissive `assert.equal`.
This is a follow-up of https://github.com/emberjs/data/pull/6428

[CHORE/TESTS] Use strictEqual for identifiers/cache test

---

.github/workflows/main.yml
packages/-ember-data/config/ember-try.js

written by @HeroicEric (don't want to put words in @runspired's mouth 😄)
---
This supersedes https://github.com/emberjs/data/pull/6098 but with [GitHub actions](https://help.github.com/en/articles/about-github-actions) rather than Azure Pipelines.
Part of https://github.com/emberjs/data/issues/6282
Closes https://github.com/emberjs/data/pull/6443
Closes https://github.com/emberjs/data/pull/6455
Closes https://github.com/emberjs/data/pull/6098
I think we should continue running Travis CI alongside this for a little while to make sure everything is working correctly but we should remove the Azure Pipelines config.
- This GitHub version runs much faster because we're given more resources to run jobs concurrently.
- The syntax is also nicer, which is my opinion of course but it seems to be …

Use GitHub Actions for CI

---

README.md

Part of https://github.com/emberjs/data/issues/6282
Replaces the Travis CI build status badge in the README with the one for GitHub Actions.
[Preview README with new badge](https://github.com/emberjs/data/blob/411db0bbee6149dbe1acabe40f9f7eba42297c6d/README.md)

[CHORE] Replace Travis CI badge with GitHub CI badge

---

packages/-ember-data/addon/-private/system/debug/debug-adapter.js
packages/-ember-data/addon/setup-container.js
packages/-ember-data/app/debug-adapter.js
packages/debug/README.md

Provides the DataAdapter for the ember-inspector

[CHORE] Use `ember-data` without `@ember-data/debug`

---

packages/-build-infra/src/addon-build-config-for-data-package.js
packages/-ember-data/index.js
packages/-ember-data/package.json
packages/adapter/index.js
packages/debug/index.js
packages/model/index.js
packages/record-data/index.js
packages/serializer/index.js
packages/store/index.js

Previously we were adding version to the tree in every package (whoops!)
This also ensures that version is always included in the output regardless of whether shouldRollupPrivate is used.
Resolves #6219

[FIX] only include version in ember-data output

---

.github/workflows/main.yml
.travis.yml
azure-pipelines.yml

This adds the [`--frozen-lockfile`](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install) flag to our CI scripts where we are `yarn install`ing dependencies.
This flag will cause the script to exit with an error if the committed `yarn.lock` is not up to date.
This makes sure we our `yarn.lock` file is always up to date.

[CHORE] Fail CI build if `yarn.lock` is out of date

---

.eslintignore
.eslintrc.js

Cleans up our ESLint config to be more close to the ember-cli addon blueprints.
- Uses more consistent ignore pattern style
- Removes some unnecessary ESLint rule declarations that are already set via the latest `eslint:recommended` in 6.x.x
- Re-enables some rules for linting bin scripts that no longer need to be disabled

[CHORE] Cleanup ESLint config

---

.github/workflows/main.yml

Adds Ember LTS 3.12 to the GitHub Actions LTS test matrix.
Same as https://github.com/emberjs/data/pull/6502 but for our GitHub Actions CI config.

[CHORE ci] Add Ember LTS 3.12 to GitHub Actions test matrix

---

packages/-ember-data/testem.js

We're frequently seeing an error about testem failing to connect to the browser (Chrome) within the 30 second default timeout in our CI builds.
This increases the timeout from 30 seconds to 120 seconds in an effort to at least diagnose whether the timeout is just too short or if there is another problem causing these timeouts.
There is a pretty long related issue on the testem repo that suggests that this may help our issue: https://github.com/testem/testem/issues/1021
This is what the error looks like:
```
Built project successfully. Stored in "/tmp/tests-dist-2019911-2914-80vil9.m6t3n".
F
1 tests complete (30770 ms)
1) [Chrome] error
Error: Browser failed to connect within 30s. testem.js not loaded?
```
Some sample runs that include the browser timing out:
- …

chore(ci): Increase browser start timeout

---

packages/-ember-data/addon/adapters/errors.js

embroider flagged `export 'AdapterError' was not found in '@ember-data/adapter/error'`.
turns out `AdapterError` is the default export, not a named export.

[BUGFIX] fix AdapterError reexport

---

packages/-ember-data/tests/unit/adapters/rest-adapter/fetch-options-test.js
packages/adapter/addon/rest.js

Landed some fixes to `ember-fetch` in [PR #174](https://github.com/ember-cli/ember-fetch/pull/174) to correctly support POST `body`s other than objects. These fixes came after these utils were added to ED.
Also added several tests from ember-fetch to increase coverage for this util, some of which pertain to this change.

[BUGFIX fetchOptions] fix fetchOptions to support POST body of all valid types

---

packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/store/finders.js

**Description By @runspired **
Most new data enters the cache via `store._push` which ensures that all operations on state internally occur within one ED runloop. An exception is when fetching relationships via links, where in addition to calling `_push` we make a call to `internalModel.linkWasLoadedForRelationship`. Since this call is not within the call to `_push` we were accidentally spinning up thousands of run loops for hasMany relationships.
Here we ensure that this loading always has an outer run loop so that scheduled work is appropriately batched internally.
**EDIT**
After reflection, @runspired realized that the call to `linkWasLoadedForRelationship` was especially odd. After digging it, it became apparent that this was only necessary to forward links and meta to the …

[BUGFIX links] relationship setup for link fetch should batch

---

packages/-ember-data/tests/helpers/watch-property.js
packages/-ember-data/tests/integration/store-test.js
packages/-ember-data/tests/unit/store/peek-record-test.js
packages/record-data/addon/-private/coerce-id.ts
packages/store/addon/-private/system/coerce-id.ts

Happen to run into this typo. Been using Ember for years, love your work! Good luck!
Co-authored-by: igorT <terzicigor@gmail.com>

[CHORE] fix Typo

---

package.json
packages/-ember-data/package.json
packages/-ember-data/tests/helpers/qunit-asserts/assert-assertion.ts
packages/-ember-data/tests/helpers/qunit-asserts/assert-deprecation.ts
packages/-ember-data/tests/helpers/qunit-asserts/assert-warning.ts
packages/-ember-data/tests/helpers/qunit-asserts/check-matcher.ts
packages/-ember-data/tests/helpers/qunit-asserts/index.ts
packages/-ember-data/tests/helpers/qunit-asserts/utils/is-thenable.ts
packages/-ember-data/tests/integration/relationships/inverse-relationship-load-test.js
packages/-ember-data/tests/test-helper.js
packages/-serializer-encapsulation-test-app/package.json
packages/-serializer-encapsulation-test-app/tests/integration/normalize-test.js
packages/-serializer-encapsulation-test-app/tests/integration/push-payload-test.js
packages/-test-infra/package.json
packages/store/addon/-private/system/store/finders.js
packages/store/types/qunit/index.d.ts
yarn.lock

Depends on #6625 for tsconfig fixes
This:
- Allows us to remove more run loops.
- Gives us the ability to expand how we handle managing deprecations (done in a follow up commit)
It introduces:

[CHORE] adds infra for testing calls to Ember warn|deprecate|assert

---

packages/-ember-data/tests/integration/multiple-stores-test.js

* Remove run(() => { }) when possible.
* Use const when possible.

[CHORE] Refactor integration/multiple-stores-test.js in order to remove run loop usage

---

packages/-ember-data/tests/unit/promise-proxies-test.js
packages/store/addon/-private/system/promise-proxies.js

#6012 Issue to add test for meta property for PromiseBelongsTo.
I think i also found a bug in the assertion because internal model is not present on the object, just originatingInternalModel, so i changed it to modelName. I need confirmation that this is the intended behaviour.

ISSUE-6012: test: added test for meta property and bug fix.

---

packages/-build-infra/src/features.js
packages/-ember-data/tests/acceptance/relationships/has-many-test.js
packages/-ember-data/tests/integration/adapter/record-persistence-test.js
packages/-ember-data/tests/integration/relationships/relationship-links-test.js
packages/canary-features/addon/default-features.ts
packages/canary-features/addon/index.ts
packages/canary-features/package.json
packages/record-data/addon/-private/record-data.ts
packages/record-data/addon/-private/relationships/state/belongs-to.ts
packages/record-data/addon/-private/relationships/state/has-many.ts
packages/record-data/addon/-private/relationships/state/relationship.ts
packages/store/addon/-private/system/many-array.js
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/promise-proxies.js
packages/store/addon/-private/system/references/reference.ts
packages/store/addon/-private/system/store/finders.js

In [RFC 332](https://github.com/emberjs/rfcs/blob/master/text/0332-ember-data-record-links-and-meta.md) we assumed that the full `links` object was supported for relationships. However, our implementation restricted access to just the `related` link and discarded all other links.
This PR
- Preserves all existing behaviors attached to the `related` link
- Adds `reference.links()` for accessing links
- Adds `HasMany.links` and `PromiseHasMany.links` for accessing links
- Ensures that we return links from the cache in whichever format the user supplied us (`{ href }` or `string`).
While the PR is non-breaking it does introduce some new APIs. I would argue given past promises in the linked RFC and around links more generally that this is "API backfill"  that does not require a new RFC, but I …

[FEAT links] ensures full links object support for relationships

---

packages/-fastboot-test-app/app/router.ts
packages/-fastboot-test-app/app/routes/person/new.js
packages/-fastboot-test-app/app/templates/person/new.hbs
packages/-fastboot-test-app/package.json
packages/-fastboot-test-app/tests/fastboot/person/new-test.js
packages/store/addon/-private/identifiers/utils/uuid-v4.ts
packages/store/types/fastboot/index.d.ts

Changes the V4 UUID generation to leverage `FastBoot.require` when possible.
This currently requires that the host application add the following to their `package.json`:
```json
{
"fastbootDependencies": [
"crypto"
]
}
```
Fixes #6563

[BUGFIX release] Enable `store.createRecord` in FastBoot

---

packages/-ember-data/tests/helpers/deprecated-test.js
packages/-ember-data/tests/helpers/qunit-asserts/assert-deprecation.ts
packages/-ember-data/tests/helpers/test-in-debug.js
packages/-ember-data/tests/test-helper.js

turned off until we fix tests in follow up PR, but have written all necessary test fixes locally already.
This gives us guarantees we don't regress on our own deprecations
It introduces: 
There's a LOT more we can do from here for things like asserting encountered deprecations have `url` and `until` attached to them for instance, or making a report that errors if we have deprecations coming from `Ember` itself.
I also think we should wrap the deprecation and warning helpers in `if (DEBUG)` and make them pass in prod automatically to reduce the number of tests that require `testInDebug`.

[CHORE] allow asserting all tests for deprecations

---

packages/store/addon/-private/system/snapshot-record-array.js

This has been broken for a few releases & this PR fixes the messed up code block in the API docs.

[DOC] Close code block in the description

---

.eslintrc.js
.github/workflows/asset-size-check.yml
.gitignore
bin/asset-size-tracking/generate-analysis.js
bin/asset-size-tracking/generate-diff.js
bin/asset-size-tracking/print-analysis.js
bin/asset-size-tracking/src/create-comment-text.js
bin/asset-size-tracking/src/get-built-dist.js
bin/asset-size-tracking/src/library.js
bin/asset-size-tracking/src/parse-modules.js
bin/asset-size-tracking/src/post-comment.sh
package.json
yarn.lock

Before running these commands you will want to run
```
yarn workspace ember-data ember b -e production
```

[CHORE] adds asset reporting infra

---

packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
packages/record-data/addon/-private/relationships/state/belongs-to.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/model/shim-model-class.ts
packages/store/addon/-private/system/schema-definition-service.ts
packages/unpublished-model-encapsulation-test-app/app/app.js
packages/unpublished-model-encapsulation-test-app/tests/integration/model-for-test.js

While working to encapsulate some Model related things I noticed that there are some unintentional changes in the custom-model-class feature flag branch.

[BUGFIX] modelFor should return a stable ShimModelClass

---

.github/workflows/main.yml
packages/-ember-data/config/ember-try.js

Backporting #6472 into beta branch per #6282 
----
This supersedes https://github.com/emberjs/data/pull/6098 but with
[GitHub
actions](https://help.github.com/en/articles/about-github-actions)
rather than Azure Pipelines.
I think we should continue running Travis CI alongside this for a little
while to make sure everything is working correctly but we should remove
the Azure Pipelines config.
Why?
- This GitHub version runs much faster because we're given more
resources to run jobs concurrently.
- The syntax is also nicer, which is my opinion of course but it seems
to be shared by others.
Stages
The jobs are configured to run in three stages, each only running once
all of the jobs in the previous stage have passed:
1. lint & basic-tests
1. floating-dependencies, lts, releases, …

Backport #6472: Use GitHub Actions for CI (#6472)

---

packages/-fastboot-test-app/app/router.ts
packages/-fastboot-test-app/app/routes/person/new.js
packages/-fastboot-test-app/app/templates/person/new.hbs
packages/-fastboot-test-app/package.json
packages/-fastboot-test-app/tests/fastboot/person/new-test.js
packages/adapter/addon/index.js
packages/serializer/addon/index.js
packages/store/addon/-private/identifiers/utils/uuid-v4.ts
packages/store/addon/-private/system/fetch-manager.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/store.ts
packages/store/addon/-private/system/store/finders.js
packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts
packages/store/types/fastboot/index.d.ts
yarn.lock

* Add FastBoot test for store.createRecord
Fails at the moment.
* Enable store.createRecord in FastBoot
Changes the V4 UUID generation to leverage `FastBoot.require` when
possible. This currently requires that the host application add the
following to their `package.json`:
```
"fastbootDependencies": [
"crypto"
]
```
* fix types

Backport release

---

packages/-ember-data/tests/unit/store/asserts-test.js
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/model/states.js
packages/store/addon/-private/system/record-array-manager.js

We deprecated filters ages ago and completed killing them off after 3.4. This is the scheduled removal of some secret notification infra we had left in place to keep them working a tad longer if needed.
**⚠️ WARNING**
This infrastructure had the unintended bug of making us notify array `length` and `[]` over-eagerly.
Due to this, the change **MAY** break apps that were using observers or computed properties on the `length` or `[]` properties of `RecordArray`s when intending to observe changes to properties on records inside these arrays.
For such cases there is an easy refactor to more standard Ember computed property usage ala `allRecords.@each.{aProp,bProp}`. This risk may be lower in versions of Ember in which @tracked is in use.

[BREAKING BUGFIX] eliminate infrastructure for filter record arrays

---

packages/store/addon/-private/system/core-store.ts
packages/unpublished-adapter-encapsulation-test-app/app/services/store.js
packages/unpublished-adapter-encapsulation-test-app/tests/integration/reload-test.js

For #6666 
It additionally contains fixes for when adapters do not implement `shouldReloadAll` and `shouldBackgroundReloadAll`

[BUGFIX TEST] reloading tests for adapter encapsulation side quest - shouldReloadAll

---

packages/-ember-data/tests/integration/store-test.js

[CHORE] refactor: Remove runloop usage in integration/store-tests module deleteRecord

---

packages/store/addon/-private/system/core-store.ts
packages/unpublished-adapter-encapsulation-test-app/tests/integration/reload-test.js

[BUGFIX TEST] reloading tests for adapter encapsulation side quest - shouldReloadRecord

---

packages/debug/index.js

Part of #6166 , the debug package is included based on a config setting in `environment.js`.
This relies on the `isEnabled` hook of the debug package's index.js. I manually ran yarn build in the following scenarios with the following outcomes:
1. in debug package -> not included
2. in the main addon -> included
3. in the main added with `ENV.includeDebug = false;` in environment.js -> not included
I used the environment.js settings to hold the potential config value, but this is mostly a POC, please let me know if there is a better location, name, etc.

Using a config to include ember-data/debug in the build

---

packages/-ember-data/tests/integration/store-test.js

[CHORE] refactor: Remove runloop usage in integration tests for store/ find All module

---

packages/private-build-infra/src/features.js

Also changes `isCanary` to not be a function and fixes the bug with the function not being invoked

Strip FeatureFlagged code in non canary builds

---

packages/-ember-data/tests/integration/store/model-name-test.js
packages/store/addon/-private/system/schema-definition-service.ts

resolves #6143 
Users who extend a model from another model (not constrained to polymorphism) will encounter a potential race condition when upgrading to ember-source 3.13 or later.
- If the model being extended is looked up prior to the model doing the extending
- and if the model being extended has it's modelName accessed in a manner that would install a MandatorySetter prior to the lookup of the model doing the extending
Then setting the static modelName property of the extended class would error.
We should attempt to backport the fix as far as possible; however, due to file re-arrangements and refactoring while the fix will remain the same the location is likely to change for 3.12 and again for 3.8.

[BUGFIX] ensure MandatorySetter does not trigger for modelName

---

.github/workflows/main.yml
.travis.yml
azure-pipelines.yml
package.json
packages/-ember-data/package.json
packages/private-build-infra/src/features.js

Previously once we turned a feature flag on we would stop running any tests against the "off" state. This makes reverting the state of a feature flag once "on" risky.
This reduces that risk by ensuring we always run the tests at least once with all flags off.

[CHORE] feature flag reversal test

---

packages/unpublished-adapter-encapsulation-test-app/tests/integration/queries-test.js
packages/unpublished-adapter-encapsulation-test-app/tests/integration/reload-test.js

For #6666 
This also exposes, but does not fix, a bug where the payload object is unexpectedly mutated if IDENTIFIERS is turned on. See issue #6758 
This also goes back and cleans up the transform code needed previously to avoid a deprecation warning.

[TEST] queries tests for adapter encapsulation side quest

---

packages/-ember-data/tests/integration/relationships/polymorphic-mixins-has-many-test.js
packages/store/addon/-debug/index.js

resolves #6728 
Ports the test from #6727 and adds a fix

[BUGFIX] fix detect usage for native class polymorphism

---

.github/ISSUE_TEMPLATE.md

The change to the command will output all of the `@ember-data` packages in addition to `ember-data` so we can see if any conflicts exist including in nested dependencies.

[CHORE issue-template] capture nested package deps in cli output

---

packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/references/record.ts
packages/store/addon/-private/system/store/internal-model-factory.ts
packages/store/addon/-private/ts-interfaces/ds-model.ts
packages/store/addon/-private/ts-interfaces/record-instance.ts
packages/store/addon/-private/ts-interfaces/record.ts

[CHORE] rename Record to RecordInstance

---

package.json
yarn.lock

Cleaned up version of https://github.com/emberjs/data/pull/6542

Backport @babel/plugin-transform-block-scoping fix to 3.8.0

---

packages/-ember-data/index.js
packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
packages/private-build-infra/src/addon-build-config-for-data-package.js
packages/record-data/addon/-private/record-data.ts
packages/record-data/addon/-private/ts-interfaces/relationship-record-data.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/record-data-for.ts
packages/store/addon/-private/system/store/record-data-store-wrapper.ts
packages/store/addon/-private/ts-interfaces/record-data-record-wrapper.ts
packages/store/addon/-private/ts-interfaces/record-data.ts

[BUGFIX] cleanup rollup warnings

---

bin/-tarball-info.js
bin/test-external-partner-project.js
package.json

Since we wrote this script, yarn has improved and we might now be able to rely on its use of resolutions. Resolutions seems to be the only way to force partners that have addons with dependencies on ember-data to use the version we want, otherwise things like `ember-cli-addon-docs` install a stable release as well.

[FIX] improve tarball insertion

---

packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts

I saw in the [documentation](https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fserializer) the example code for the `serialize` method and it shows the `snapshot.id` property as a function instead of a string. I [double checked it](https://github.com/emberjs/data/blob/master/packages/store/addon/-private/system/snapshot.js#L65) to be sure it is just a string :) I hope this is the right place to make the fix to the documentation.

fixed serialize example

---

.github/workflows/asset-size-check.yml
.github/workflows/relationship-performance-check.yml
bin/asset-size-tracking/src/post-comment.sh
bin/relationship-performance-tracking/src/create-comment-text.js

This PR
- changes the comment-bot to update existing comments instead of deleting old comments
- fixes the bug that was preventing deletion of old comments
- fixes the performance analysis script to also post a comment correctly (it's been failing to do so although trying for some time)
You can see the effects of the updates (edit history on the pr comments) within this PR. Overall it seems like a good change, although I dislike how the comment time stamp remains the time of the very original comment instead of showing the time edited. This makes it harder to judge quickly if it is the most recent analysis, although checking the commit sha that is printed will verify.

[CHORE] improve comment bot

---

packages/debug/index.js
packages/private-build-infra/src/addon-build-config-for-data-package.js
packages/unpublished-test-infra/index.js

Refactor to use _findHost and provide a shared mechanism for accessing `EmberData` config.
Also removes test-infra's VERSION module from our production output if we aren't in a testing environment.

[CHORE] cleanup build

---

bin/asset-size-tracking/src/post-comment.sh
bin/test-external-partner-project.js
package.json

Our recent upgrade to the partner tests was primarily to use yarn + resolutions while avoiding the cache. If a partner uses yarn and had a lock file we can very likely still trust it and so continuing to use it will reduce the potential for unexpected failures due to drift (such as we are currently seeing with ilios and storefront).

[FIX] comment-bot, partner-tests: use yarn lock-file when we can

---

packages/unpublished-adapter-encapsulation-test-app/tests/integration/generate-id-test.js

[TEST] generateIdForRecord tests for adapter encapsulation side quest

---

bin/asset-size-tracking/generate-diff.js
bin/asset-size-tracking/src/library.js

We've been compressing at max because the default brotli setting is 11, but this makes it explicit just in case that default is ever different.
It also tidies up a bit how we do our compression math, which makes it easier to improve our diff.
We improve our diff by adjusting the formula for how we calculate the delta in compression.
Before, the delta for individual modules and packages was calculated like this:
```
LibraryDelta = NewLibraryCompressedSize - OldLibraryCompressedSize;
CompressedSizeInitial = OldSize / OldLibrarySize * OldLibraryCompressedSize;
CompressedSizeFinal = NewSize / NewLibrarySize * NewLibraryCompressedSize;
CompressionDelta = CompressedSizeFinal - CompressedSizeInitial;
```
While on the surface this equation seems to make sense, because compression is not directly …

[CHORE] 11!

---

packages/-ember-data/index.js
packages/private-build-infra/src/addon-build-config-for-data-package.js

currently the process env conditional is incorrect, and turning off rollup errors for some packages due to lack of a _super assignment. This fixes the conditional and lets us turn off rollup if we desire again.
specifically we are working around this: https://github.com/ember-cli/core-object/blob/master/lib/assign-properties.js#L48

[BUGFIX] fix no-rollup check

---

.github/workflows/asset-size-check.yml
bin/asset-size-tracking/generate-analysis.js
bin/asset-size-tracking/generate-diff.js
bin/asset-size-tracking/print-analysis.js
bin/asset-size-tracking/src/create-comment-text.js
bin/asset-size-tracking/src/library.js

**IE11!**
Our targets for builds of `ember-data` are set by the dummy app in tests since we are an addon here: https://github.com/emberjs/data/blob/master/packages/-ember-data/tests/dummy/config/targets.js
Previously we weren't building for IE11 outside of the max transpilation test (I'd assumed we were since often IE11 is the default for production).
This fixes that and takes the opportunity to split out our asset monitoring to monitor BOTH IE11 and No-IE11 sizes (e.g. `latest chrome|safari|firefox`).
Fortunately our delta here wasn't so big (17kb uncompressed, 1kb compressed) so likely our use of rollup and aggressive optimization have already eliminated a lot of the low-hanging fruit of getting off of IE11.
I would expect IE11 support to turn into a more obviously large portion of our …

[CHORE] AssetSize check for both modern and IE11 builds

---

.github/workflows/main.yml
bin/test-external-partner-project.js
package.json
packages/canary-features/addon/index.ts

resolves #6825 
This PR
- Fixes our YML so that we actually run tests on all the Operating Systems we'd specified (they were all running ubuntu before)
- Adds timeouts to our jobs so that they don't hang for hours (the default timeout is 6 hours)
- Uploads artifacts from failed partner-test runs so that we can debug them better
- Fixes the bug it enabled debugging that was causing EmberObserver to fail
This turned out to be a canary-only dev-build-only transpilation bug that only affects partners transpiling for IE11 in their tests.
The primary difference between Travis/Azure and Github Actions is that in Github Actions we correctly set `env` to include `CI=true`. This causes ember-observer to target `ie11`, which
introduces a transpilation bug when using `typeof`.
Our code in …

[CHORE] Fix workflow and enable partner test debugging

---

.eslintrc.js
.github/workflows/main.yml
packages/-ember-data/testem.js
packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
packages/-ember-data/tests/integration/record-data/record-data-test.ts
packages/-ember-data/tests/integration/relationships/inverse-relationship-load-test.js
packages/-ember-data/tests/integration/request-state-service-test.ts
packages/-ember-data/tests/integration/store-test.js
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/model-name-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/-ember-data/tests/test-helper.js
packages/store/addon/-private/identifiers/cache.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/fetch-manager.ts
packages/store/addon/-private/system/request-cache.ts
packages/store/addon/-private/ts-interfaces/utils/symbol.ts
packages/unpublished-test-infra/addon-test-support/public-props.js
packages/unpublished-test-infra/addon-test-support/todo.js
packages/unpublished-test-infra/addon-test-support/watch-property.js

We're still a ways (if ever) from being able to run the full test suite in IE11 https://github.com/emberjs/data/pull/6830/checks?check_run_id=327832618
But this lets us run the production tests.
The small number of changes to EmberData itself are mostly for dev-time support of IE11 (which I got pretty far with but ultimately the widespread lack of support for IE11 at dev time in Ember itself prevents us from getting any further).
Some of the changes will affect prod builds but only once feature flags are turned on (request-state cache for instance).

[CHORE] IE11 Testing

---

packages/serializer/addon/rest.js

Reverts deprecating isPrimaryType in #6835

Revert deprecation of isPrimaryType

---

packages/-ember-data/tsconfig.json
packages/adapter/tsconfig.json
packages/debug/tsconfig.json
packages/model/tsconfig.json
packages/record-data/tsconfig.json
packages/serializer/tsconfig.json
packages/store/tsconfig.json
packages/unpublished-test-infra/tsconfig.json

These configs simply re-export our root config, which doesn't provide any value over just having the root config but does introduce the risk that we make config edits in some packages we don't intend.
tsc uses our root config and vscode will always find it there as well. ember-cli-typescript likely doesn't need it at all but if it does we can point it to the right place.

[CHORE] remove unneeded configs

---

.github/workflows/main.yml
packages/unpublished-fastboot-test-app/testem.js

A few of our jobs are timing out, this addresses that.
For some the issue is the testem timeout needs to be lengthened (our basic tests already do this but fastboot still needed it).
For others it's the job timeout being hit. I'd intentionally set aggressive timeouts for our github actions recently to be sure we weren't spending needless time waiting for them (we had jobs going for 6 hours), so one or two more tweaks may occur in the near future but overall they seem to be settling into a good set of budgets.

[CHORE CI] fix timeout issues

---

.github/workflows/nightly.yml
packages/-ember-data/testem.js
packages/-ember-data/tests/dummy/config/environment.js
packages/-ember-data/tests/test-helper.js
packages/unpublished-adapter-encapsulation-test-app/tests/test-helper.js
packages/unpublished-debug-encapsulation-test-app/tests/test-helper.js
packages/unpublished-model-encapsulation-test-app/tests/test-helper.js
packages/unpublished-record-data-encapsulation-test-app/tests/test-helper.js
packages/unpublished-serializer-encapsulation-test-app/tests/test-helper.js
packages/unpublished-test-infra/addon-test-support/assert-all-deprecations.js
packages/unpublished-test-infra/addon-test-support/async.js
packages/unpublished-test-infra/addon-test-support/legacy.js
packages/unpublished-test-infra/addon-test-support/testem/custom-qunit-adapter.js
packages/unpublished-test-infra/package.json
packages/unpublished-test-infra/src/testem/custom-dot-reporter.js
yarn.lock

[CHORE] Cron job to check for external deprecations

---

.github/workflows/nightly.yml
packages/unpublished-adapter-encapsulation-test-app/testem.js
packages/unpublished-debug-encapsulation-test-app/testem.js
packages/unpublished-fastboot-test-app/testem.js
packages/unpublished-model-encapsulation-test-app/testem.js
packages/unpublished-record-data-encapsulation-test-app/testem.js
packages/unpublished-relationship-performance-test-app/testem.js
packages/unpublished-serializer-encapsulation-test-app/testem.js

I wish I could figure out how to test this.

fix nightly.yml

---

packages/-ember-data/node-tests/docs/test-coverage.js
packages/-ember-data/node-tests/fixtures/expected.js
packages/-ember-data/yuidoc.json
packages/private-build-infra/addon/index.ts

[DOCS] fix inclusion of docs for deprecation and canary features

---

packages/adapter/addon/-private/build-url-mixin.js

While the example provided is valid, I think a slightly more fleshed out
example of usage might be more helpful for newcomers.

[DOC] improve urlForFindAll example

---

package.json
packages/-ember-data/package.json
packages/private-build-infra/package.json
yarn.lock

All of these depencencies dropped support for Node 8 in their most recent major version bump:
* broccoli-concat@4
* broccoli-funnel@3
* broccoli-merge-trees@4
Unfortunately, the PR's didn't properly fail CI because we use the latest LTS for running all of our CI jobs.

Revert dependency updates requiring Node 10+.

---

package.json
packages/-ember-data/tests/integration/snapshot-test.js
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/fetch-manager.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/snapshot.ts
packages/store/addon/-private/ts-interfaces/ds-model.ts
packages/store/addon/-private/ts-interfaces/identifier.ts
yarn.lock

Will be used by the minimum-adapter-interface so typing it makes that type more robust

[CHORE ts] type Snapshot

---

packages/-ember-data/tests/integration/adapter/json-api-adapter-test.js

Remove usage of run function in `integration/adapter/json-api-adapter-test.js` and use `async/await` syntax.

[CHORE]: refactor: Remove usage of run function and use async/await syntax

---

packages/-ember-data/tests/integration/adapter/handle-response-test.js
packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/-ember-data/tests/unit/utils/determine-body-promise-test.js
packages/adapter/addon/-private/index.ts
packages/adapter/addon/-private/utils/continue-on-reject.ts
packages/adapter/addon/-private/utils/determine-body-promise.ts
packages/adapter/addon/rest.js
packages/unpublished-test-infra/addon-test-support/testem/custom-qunit-adapter.js
yarn.lock

[BUGFIX] ensure handleResponse always called in rest adapter

---

packages/-ember-data/tests/integration/identifiers/polymorphic-scenarios-test.ts
packages/store/addon/-private/identifiers/cache.ts

This is a failing test for the polymorphic association and identifiers. @runspired 
This happens in my app when using 3.14.beta0: 
A record of type `company` is a subclass of `party` and it is first loaded as a `company` within a `belongsTo` relation, then a `findRecord` is done on `party` with the same id.
This PR is a failing test that is a direct reference to the RFC#403 section on single-table polymorphism and identifier: 
```
For instance, when using single-table polymorphism (in which ferrari and bmw extend car and share a common id space) then ferrari:1 and bmw:2 are the same vehicles as car:1 and car:2.
```

[BUGFIX] fix single-table polymorphism when IDENTIFIERS is ON

---

README.md

The link now resolves correctly!

[DOCS] Fix link for API Documentation

---

bin/relationship-performance-tracking/generate-analysis.sh

Per some discussion in discord we'll probably standardize using JS
for internal scripts. Until then, remind consumers of this script to
install the required binaries.

validate perf related binaries are installed

---

packages/unpublished-relationship-performance-test-app/PERFORMANCE_BENCHMARKING.md

I removed `php` server recommendation since we can use ember-cli's
server.
Is there a specific reason we pin tracerbench to 2.3?
/cc @skaterdav85 @runspired

improve performance app documentation

---

bin/relationship-performance-tracking/generate-analysis.sh

This ensures we checkout whatever branch the user had when they launched the script.
Further improvements would be to bail if there are staged changes since they could violate the principles of reproducible measurements. I'm waiting to do those since we are considering migrating this script to JS for consistency.

restore inital checkout when running perf analysis

---

packages/-ember-data/tests/integration/adapter/find-test.js

Remove usage of run loop in `packages/-ember-data/tests/integration/adapter/find-test.js` after updates to qunit assertions.

chore: refactor: Remove last usages of run in adapter find tests

---

.eslintignore
packages/-ember-data/addon/index.js
packages/record-data/addon/-private/ts-interfaces/relationship-record-data.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts
packages/unpublished-relationship-performance-test-app/app/routes/application.js

Fixes issue spotted by partner tests for Storefront/Observer/Travis-web
This fix will need to be back ported alongside the fix for `RecordData not implemented` to 3.16 beta and 3.15 release
Also fixes (separate commit) lint issue that crept in and a lint perf issue where we would attempt lint the dists created for the performance checks.

[FIX] RecordData is not a constructor

---

packages/-ember-data/tests/integration/relationships/one-to-many-test.js

~~Test is automatically re-enabled for 3.17.x~~.  We can re-enable it once
the upstream failure (glimmerjs/glimmer-vm#1010) is resolved and into
ember-source.

Disable known failure for 3.16.x

---

packages/-ember-data/tests/integration/adapter/handle-response-test.js
packages/adapter/addon/rest.js

[BUGFIX] fix jsonapi error handling when not using jquery 

---

packages/-ember-data/node-tests/fixtures/expected.js
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/ts-interfaces/minimum-adapter-interface.ts

Prior to this change, adapters and serializers were never destroyed.  Commonly (and anecdotally) this is "fine" (heck this is the first report of the issue in years!), but it is pretty common for adapters to do async of their own (e.g. tracking adapter responses, exponential backoffs, etc) and without `.destroy()` being called on them there is no way for those adapters/serializer to ensure that async is canceled appropriately.
Fixes #7018

Ensure adapters and serializers are destroyed upon store destruction.

---

packages/-ember-data/tests/integration/relationships/one-to-many-test.js

This reverts commit 10ad35fa55acebdb9f64175c0d3bbcfdf8e97bf5.

Revert "Disable known failure for 3.16.x"

---

packages/adapter/addon/error.js

[DOC] modernize TimeoutError example code

---

packages/-build-infra/package.json

This is already a de-facto dep as it's required by `features.js`.
Adding it as an explicit dep to deal with dependency issues.

Add @canary-features as -build-infra dep

---

packages/serializer/addon/-private/embedded-records-mixin.js

Adding documentation on the embedded records mixin explaining that it does not work with JSONAPISerializer. This should be noted more prominently rather than in a passive warning message (which might get buried under a sea of deprecation warnings in the test suite).

[DOC] Update embedded-records-mixin.js

---

packages/-ember-data/tests/integration/adapter/handle-response-test.js
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/adapter/addon/rest.js
packages/store/addon/-private/system/core-store.ts

Backports the following PRs to the release branch:
- [Ensure adapters and serializers are destroyed upon store destruction.](https://github.com/emberjs/data/pull/7020)
- This is backported with the caveat that it does not include the changes to `MinimumAdapterInterface` because it does not exist in the release branch. Let me know if you think this is a problem. The `MinimumAdapterInterface` was added in https://github.com/emberjs/data/pull/6643
- [[BUGFIX] fix jsonapi error handling when not using query](https://github.com/emberjs/data/pull/6941)

Release backports

---

packages/-ember-data/node-tests/fixtures/expected.js
packages/-ember-data/tests/integration/adapter/handle-response-test.js
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/adapter/addon/rest.js
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/ts-interfaces/minimum-adapter-interface.ts

Backports the following PRs to the beta branch:
- [Ensure adapters and serializers are destroyed upon store destruction.](https://github.com/emberjs/data/pull/7020)
- [[BUGFIX] fix jsonapi error handling when not using query](https://github.com/emberjs/data/pull/6941)

Beta backports

---

CONTRIBUTING.md

Briefly document how to link ember data in your application. Came up as a result of someone wanting to helpfully test an outstanding PR.

[DOC] create a howto for testing pull requests

---

CHANGELOG.md

This fixes the changelog by moving the changelog entries originally
intended for 3.16.1 to the section for 3.16.2.
For some more context, due to an unfortunate mishap by yours truly,
3.16.1 was never actually published to NPM. Instead, 3.16.2 was
published with what should have been 3.16.1. NPM does not support any
way to remedy this after the fact (and with good reason), but it would
still be nice for the changelog to be correct for anyone viewing it via
GitHub.

Fix changelog for v3.16.2

---

packages/-ember-data/tests/integration/snapshot-test.js
packages/store/addon/-private/system/snapshot.ts

Backports [BUGFIX] Fix #7015 - calling changedAttributes for non instantiated r… #7080 for beta

Backport #7080 for beta

---

packages/-ember-data/tests/integration/snapshot-test.js
packages/store/addon/-private/system/snapshot.ts

Backports [BUGFIX] Fix #7015 - calling changedAttributes for non instantiated r… #7080 for release

Backport #7080 for release

---

packages/-build-infra/package.json
packages/-build-infra/src/features.js

Backports the following PRs to the current LTS branch (lts-3-12):
- [BUGFIX] only allow feature flag alterations in canary #6738 
- Add @canary-features as -build-infra dep #7067

Backport #6738 & #7067 for LTS

---

packages/adapter/addon/rest.js

Ember Observer was failing due to their headers set to null. This original warning did not come with a test, so unfortunately this PR doesn't either.

[BUGFIX] Fix headers precedence warning for null headers object

---

packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/adapter/addon/index.js
packages/store/addon/-private/system/store.ts

Backports Ensure adapters and serializers are destroyed upon store destruction. #7020 for LTS 3.12
This required a few changes:
- The [changes to packages/-ember-data/node-tests/fixtures/expected.js](https://github.com/emberjs/data/pull/7020/files#diff-90207ce76d6fc168c717eecca7fd82a5R148-R154) were not included because that test file does not exist in the branch
- the documentation for `Adapter#destroy()` was added to the base `Adapter` class rather than the `MinimumAdapterInterface` because that interface did not yet exist

Backport #7020 for LTS

---

.github/workflows/nightly.yml

cron * 14 means every minute of the 14th hour.  GitHub Actions will
limit this to the minimum of every 5 minutes, although it didn't
actually run 12 times presumably because of the length of the jobs
themselves.
Fix the cron schedule so the job only runs once per night.

Fix nightly run

---

packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
packages/record-data/addon/-private/record-data.ts

While investigating memory usage of our application, where we load a large amount of data and afterwards destroy/unload it again, I noticed that the `recordData` objects are not destroyed and kept consuming memory. I tracked it down to `Relationships` not being cleared during unload.

clear relationships during delete

---

packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/model/addon/-private/system/many-array.js

In our application we have long living objects with a large collection of children. During the lifetime of our application these children get destroyed, but the `has-many` relationship on the parent still keeps track of these children in the `initialState` property. This property is only used during the initial construction of the `has-many` relationship. So, it can easily be cleared after `init`.
This solves a large memory leak in our application.

clear initialState after construction

---

packages/-ember-data/tests/integration/store/store-creation-recursion-test.js
packages/store/addon/-private/system/core-store.ts

Lazily create transforms in core-store constructor by checking for factoryFor, instead of lookup

fix creation recursion with ember-data-model-fragments

---

bin/relationship-performance-tracking/generate-analysis.sh
bin/relationship-performance-tracking/src/har-remix.js
bin/relationship-performance-tracking/src/tracerbench.js
packages/unpublished-relationship-performance-test-app/PERFORMANCE_BENCHMARKING.md
packages/unpublished-relationship-performance-test-app/app/router.js
packages/unpublished-relationship-performance-test-app/app/routes/materialization.js
packages/unpublished-relationship-performance-test-app/app/utils/end-trace.js
packages/unpublished-relationship-performance-test-app/config/environment.js

Add support for multiple routes in the relationship performance test application

Support for multiple routes in performance-test-app

---

packages/-ember-data/package.json
packages/-ember-data/tests/integration/store/model-name-test.js
packages/unpublished-test-infra/addon-test-support/deprecated-test.js
packages/unpublished-test-infra/index.js
packages/unpublished-test-infra/package.json

close #7072
This PR allows a developer to execute `yarn start` and run the tests in the browser.
We add the `/version` file with some tag/sha information at build time iff `EMBER_CLI_TEST_COMMAND` is set by Node on the global variable `process.env` at runtime.  
Another option is to be more specific in the if conditional by allowing only development or test.  However, if this module is excluded from production, then this may be sufficient in its current state.

[BUGFIX]: Fix errors while running yarn start

---

packages/-ember-data/tests/integration/serializers/json-api-serializer-test.js
packages/serializer/addon/json-api.js

Use of EmbeddedRecordsMixin and JSONAPISerializer together asserts instead of warns. Allows for setting "isEmbeddedRecordsMixinCompatible" on the serializer for when parts of the API are compatible.
Closes #6991

[DOC EmbeddedRecordsMixin] Assert from JSONAPISerializer

---

packages/-ember-data/tests/integration/identifiers/cache-test.ts
packages/store/addon/-private/identifiers/cache.ts
packages/store/addon/-private/system/store/internal-model-factory.ts

Add a caching layer to Identifiers that is not type specific.

Cache identifiers

---

.dependabot/config.yml

Running dependabot too often creates a lot of noise in the commit logs, making it nearly useless to track actual progress.
Running it less often would reduce this problem (security updates still running immediately).

Reduce dependabot frequency

---

packages/model/addon/-private/attr.js

Updates some of the language around how defaultValue behaves.

[DOC] Update documentation around behavior of attr

---

.github/workflows/main.yml

`test-infra` was timing out midrun https://github.com/emberjs/data/runs/741935013 Exteded all of the times by 30-50%, and doubled test-infra

[INFRA] Extend github actions timeouts to prevent CI failures

---

package.json
packages/-ember-data/package.json
packages/adapter/package.json
packages/canary-features/package.json
packages/debug/package.json
packages/model/package.json
packages/private-build-infra/package.json
packages/record-data/package.json
packages/serializer/package.json
packages/store/package.json
packages/unpublished-adapter-encapsulation-test-app/package.json
packages/unpublished-debug-encapsulation-test-app/package.json
packages/unpublished-fastboot-test-app/package.json
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-record-data-encapsulation-test-app/package.json
packages/unpublished-relationship-performance-test-app/package.json
packages/unpublished-serializer-encapsulation-test-app/package.json
packages/unpublished-test-infra/package.json
yarn.lock

**NOTE:** Targets the 3.16 branch (as this no longer affects the current release).
`@ember-data/store@3.16` introduced new typescript syntax that is not guaranteed to be supported by the ember-cli-babel version that it depends on. Specifically, the version of ember-cli-babel we depend on prior to this change uses `@babel/parser@7.3.3` which does not support the `function foo(id: string | null) asserts id is not null {}` syntax we use in `fetch-manager.ts`. The dependency structure looks like this (with links):
* [ember-cli-babel@7.13.2 depends on broccoli-babel-transpiler@7.3.0](https://github.com/babel/ember-cli-babel/blob/v7.13.2/package.json#L55)
* [broccoli-babel-transpiler@7.3.0 depends on @babel/core@7.3.3](https://github.com/babel/broccoli-babel-transpiler/blob/v7.3.0/package.json#L …

Update ember-cli-babel to prevent errors with newer TS syntax

---

packages/-ember-data/addon/-private/core.js
packages/-ember-data/node-tests/fixtures/expected.js

A blank package `@ember-data` shows up due to these yuidoc comments.
I tried to get this working correctly so that an `ember-data` package would show up with a DS and VERSION export, but was unable to figure out how to do it.

[DOCS] Remove blank package '@ember-data'

---

packages/serializer/addon/rest.js

[DOC] Use native syntax in RESTSerializer documentation

---

packages/-ember-data/tests/integration/relationships/belongs-to-test.js
packages/record-data/addon/-private/record-data.ts

Visiting all related records during `_cleanupOrphanedRecordDatas` allocates and copies a large amount of unnecessary data. Using an `Iterable` this allocation is not done anymore.
In one of our applications we have a large dataset with complex relations. Destroying a large number of records timed out after 10 minutes, with this fix it still takes two minutes (but it is already a big improvement)

Optimize visiting the relating records

---

packages/record-data/addon/-private/ordered-set.ts
packages/record-data/addon/-private/relationships/state/belongs-to.ts
packages/record-data/addon/-private/relationships/state/has-many.ts
packages/record-data/addon/-private/relationships/state/relationship.ts

Analyzing a performance issue in our application, I noticed that updating an existing relationship (with a large number of records) is very expensive. A lot of time is consumed in `Array.splice`.
By changing the order: first remove all records in reverse order and then add all records in correct order, is a quick win.
See output of test application that adds each time 200 records to the same relationship until 20.000 
Test application can be found [ember-has-many-update](https://github.com/pieter-v/ember-has-many-update)
**Before**
**After**

Optimize the update of a has-many relationship.

---

.github/workflows/main.yml

Follow up #7243 
Ref - https://github.com/emberjs/data/actions/runs/170550412

[CI]: remove erroneous `name` without `run` in node-version-test

---

.github/workflows/main.yml
azure-pipelines.yml

Checking to see if the default image now has Chrome and Firefox installed.  If so, we can remove `brew` commands.
Reference for MacOS and Linux images - 
https://github.com/actions/virtual-environments/blob/bb03b541e0a63c964dcf851817585d4bb4b38675/images/linux/Ubuntu1804-README.md
https://github.com/actions/virtual-environments/blob/bb03b541e0a63c964dcf851817585d4bb4b38675/images/macos/macos-10.15-Readme.md

[CI]: remove Chrome and Firefox install from Github Actions and Azure

---

packages/store/addon/-private/system/promise-proxies.js

Relates to: https://github.com/ember-learn/ember-api-docs/pull/726
There seem to be other instances of broken links in this repo with this format:
- Go to https://api.emberjs.com/ember-data/3.10/classes/DS.RESTAdapter and click on the link for `volatile`, which is from this code: https://github.com/emberjs/data/blob/d6bd5f1b82f0ae6424f381f55574a54ea0684aff/packages/adapter/addon/rest.js#L269
I'm not sure how to test this locally with ember-api-docs so any guidance on that would be appreciated!
cc @MelSumner @kategengler from Discord convo

Fix broken link

---

packages/-ember-data/tests/unit/model-test.js
packages/serializer/addon/json-api.js

* Calling `new EmberObject()` hasn't worked for some period of time (Ember itself forbids `new EmberObject()`), removing the test for `new` since it is tested upstream by Ember.
* Remove usage/reliance on `willMergeMixin`, it was private API and has been removed. We were only using it for a warning that can easily be migrated to `init`.
---
@igorT - This resolves one of the failures that occurs for `release`/`beta`/`canary`.

[BUGFIX release] Fix testing incompatibilities with modern Ember.

---

packages/model/addon/-private/errors.js

We recently made some changes to the way arrays get consumed when
autotracking in Ember - specifically, whenever an array is return from
`Ember.get`, `@computed`, or `@tracked`, we track that array for changes
in the future. Previously, we also tracked it if it was an _EmberArray_.
This check was a bit redundant, and costly, so we removed it and now
only do it for native arrays.
The reason this is generally safe is that non-native EmberArrays usually
have a contract - you must access the state of the array via `objectAt`,
and you must update via `pushObject`, `popObject`, etc. The array is
consumed when using `objectAt`, so theres no need to do it eagerly in
`Ember.get` (and penalize all other object access).
The `Errors` class is a bit of a special case, because it adds additonal …

[BUGFIX] Entangle Errors.errorsFor properly

---

.github/workflows/main.yml

https://github.com/yarnpkg/yarn/search?utf8=%E2%9C%93&q=NETWORK_TIMEOUT&type=
Currently set to 1/2 min.  This PR sets it to 5 min.

CI: add timeout to yarn install

---

CHANGELOG.md
packages/-ember-data/config/ember-try.js
packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/model/package.json
packages/record-data/package.json
packages/serializer/package.json
packages/store/package.json
packages/unpublished-adapter-encapsulation-test-app/package.json
packages/unpublished-debug-encapsulation-test-app/package.json
packages/unpublished-fastboot-test-app/package.json
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-record-data-encapsulation-test-app/package.json
packages/unpublished-relationship-performance-test-app/package.json
packages/unpublished-serializer-encapsulation-test-app/package.json
packages/unpublished-test-infra/package.json
yarn.lock

My fault.  Improvements made to release docs as well (although I should have noticed this!).
https://github.com/emberjs/data/pull/7304

[Release]: bump ember-source in packages/ to 3.20

---

packages/adapter/addon/-private/build-url-mixin.js
packages/adapter/addon/error.js
packages/adapter/addon/index.js
packages/adapter/addon/json-api.js
packages/adapter/addon/rest.js

Updated adapter examples - reference #7256. Will continue work on the remaining packages.
I noticed that the AdapterError [page](https://api.emberjs.com/ember-data/3.20/classes/AdapterError) in the api reference is blank. I don't think that's intentional and I can open a separate issue.

[DOC adapter] convert examples to native/Octane class syntax

---

packages/private-build-infra/src/deprecations.js
packages/private-build-infra/src/features.js
packages/private-build-infra/src/packages.js

Avoid issues found in #7221 and others.
Some downsides include the need to transpile to cjs every time; however, the files are small enough that this should be a a minute penalty.
e.g.
```
npx ember-cli@beta new test-app && cd test-app && ember b
```

[Build]: disable esm cache

---

packages/private-build-infra/src/deprecations.js
packages/private-build-infra/src/features.js
packages/private-build-infra/src/packages.js

ref #7322 
While not strictly necessary, this will help those that upgrade from 3.16 to 3.20 avoid having to remove node_modules and reinstall.  Explanation in ref PR.

[Build]: disable esm cache (#7322)

---

packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/errors-utils.js
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/record-arrays/record-array.js
packages/store/addon/-private/system/references/belongs-to.js
packages/store/addon/-private/system/references/has-many.js
packages/store/addon/-private/system/snapshot-record-array.ts
packages/store/addon/-private/system/snapshot.ts

Updated store examples - this is last PR to resolve #7256.
I'm going to open a new issue because I realized that we document two different imports for the base adapter but only one is generated with the blueprints.
```javascript
// generated
import ApplicationAdapter from "./application";
// used but not generated
import Adapter from '@ember-data/adapter';
```

[DOC store] convert api examples to native classes/Octane

---

packages/-ember-data/tests/integration/model-errors-test.ts
packages/model/addon/-private/errors.js

the subarray for `errorsFor` needs to be mutated so observing templates can be notified that the array was updated.
ref https://github.com/emberjs/data/pull/7273
close https://github.com/emberjs/data/pull/7313
close https://github.com/emberjs/data/issues/7310
👋  @andreyfel

[Bug]: errors `remove` to accurately update in template

---

packages/-ember-data/tests/integration/identifiers/cache-test.ts
packages/store/addon/-private/identifiers/cache.ts

close https://github.com/emberjs/data/issues/7193

[Debug]: improved debug msg instead of [object Object]

---

packages/-ember-data/tests/acceptance/relationships/has-many-test.js
packages/-ember-data/tests/acceptance/tracking-model-id-test.js
packages/model/addon/-private/system/many-array.js

close https://github.com/emberjs/data/issues/7311 https://github.com/emberjs/ember.js/issues/19101 https://github.com/emberjs/data/issues/7328 https://github.com/emberjs/ember.js/issues/19139
ref https://github.com/emberjs/ember.js/issues/19105
Another related autotracking fix for `errorsFor` https://github.com/emberjs/data/pull/7273
Has Many Arrays implement the Mutable Array mixin.  We need to instrument `length` and `objectAt` in order to ensure autotracking works.
Follow up: convert to class based && ts file

[BUG]: Consume array access to autotrack hasMany

---

packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
packages/record-data/addon/-private/relationships/state/has-many.ts

The issue appeared in a sideposting scenario:
- model A has has many relationship to model B.
- instance of model A and instance of model B are created on the client,
- model A is saved along with model B sent in `include` section of payload; the linking is done through `lid`
- server persisted both models and sent the response with server-generated `id` along with `lid` sent by the client.
- when hasMany.updateData() was called while the response payload was  pushed to the store it couldn't match the record which was already in the store with the record data contained in the relationship data because `lid` was omitted.

Bugfix for wrong hasMany relationship state in scenario of sideposting with lid

---

packages/record-data/package.json
yarn.lock

Bumping `@ember/ordered-set` to a version running ember-cli-babel v7

[CHORE] Bump ordered-set to get on ember-cli-babel v7

---

packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/adapter/addon/-private/utils/determine-body-promise.ts

Even though this goes against the spec, we decided that it is better to be more accepting in the incoming requests, as the downside seemed low, and people seem to be running into this issue when migrating away from jquery to fetch.

Do not explode when getting back an empty payload with the accept json header

---

packages/-ember-data/tests/integration/identifiers/polymorphic-scenarios-test.ts
packages/store/addon/-private/identifiers/cache.ts

Fixes issue when encountering polymorphic records with a subtype on initial load.
Builds on #7325

[BUGFIX identifiers] Address issue with polymorphic findRecord 

---

packages/record-data/package.json

I assume this was just an oversight. I clicked the NPM repo link and was very confused for a minute.

Fix repository URL

---

packages/-ember-data/package.json
yarn.lock

Upgrade `ember-inflector` to a version using babel 7.
**EDIT**: Do I need to bump this dep in all the `packages/unpublished-*`? Would love to remove v3 from the yarn.lock file...

[CHORE] Upgrade ember-inflector to version using babel 7

---

packages/model/addon/-private/attr.js
packages/model/addon/-private/belongs-to.js
packages/model/addon/-private/errors.js
packages/model/addon/-private/has-many.js
packages/model/addon/-private/model.js
packages/model/addon/-private/system/many-array.js
packages/model/addon/-private/system/model-for-mixin.ts
packages/model/addon/index.ts

Updated model examples - reference #7256.

[DOC model] convert api examples to native classes/Octane

---

packages/store/addon/-private/system/core-store.ts

The colon in the deprecation ID is transformed into a dash for the URL of the deprecations app, so the URLs were not pointing to the correct section.

Fix deprecation URLs

---

.github/workflows/main.yml

A proposal.  Often, I'm seeing these type of tests flakey.
This PR removes all the different scenarios for `browser tests` and just does on production test run.

[CI]: simplify test run with smaller footprint for browser tests

---

packages/adapter/addon/rest.ts

Seems like we aren't documenting adapterOptions for `query` and `queryRecord` in the JSONAPIAdapter.
I've just mirrored the code in the regular adapter:
https://github.com/emberjs/data/blob/master/packages/adapter/addon/index.ts#L248
There are already tests for this, see:
https://github.com/emberjs/data/blob/ff4f9111fcfa7dd9e39804ed17f5af27a4a01378/packages/-ember-data/tests/integration/adapter/store-adapter-test.js#L1526
Support for `adapterOptions` has existed for quite a while, it was initially added in this PR: https://github.com/emberjs/data/pull/4856/

Document adapterOptions on REST adapter

---

packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
packages/record-data/addon/-private/relationships/state/belongs-to.ts

This PR aims to fix #7424.
The issue appeared in the sideposting scenario:
- model A has belongs to relationship to model B.
- instance of model A and instance of model B are created on the client,
- model A is saved along with model B sent in `include` section of payload; the linking is done through `lid`
- server persisted both models and sent the response with server-generated `id` along with `lid` sent by the client.
- when belongsTo.updateData() was called while the response payload was pushed to the store it couldn't match the record which was already in the store with the record data contained in the relationship data  because `lid` was omitted.
Add a test which ensures that the belongsTo() relationship has correct status in the sideposting with lid scenario.

Pass lid from relationship data to get record data

---

packages/serializer/addon/json-api.js

An example in docs used to incorrectly import the serializer from `@ember-data/serializer/json` instead of `'@ember-data/serializer/json-api'`. This PR fixes that.

[DOC] Fix `JSONAPISerializer` import in docs

---

packages/model/addon/-private/errors.js
packages/store/addon/-private/system/record-arrays/record-array.js

These classes are defined in ember package, not in ember-data.

[DOC] Add missing `Ember` namespace to annotations

---

packages/-ember-data/testem.js
packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/-ember-data/tests/unit/adapters/json-api-adapter/json-api-test.js
packages/-ember-data/tests/unit/adapters/rest-adapter/rest-test.js
packages/adapter/addon/index.ts
packages/adapter/addon/json-api.ts
packages/adapter/addon/rest.ts
packages/unpublished-adapter-encapsulation-test-app/testem.js
packages/unpublished-debug-encapsulation-test-app/testem.js
packages/unpublished-fastboot-test-app/testem.js
packages/unpublished-model-encapsulation-test-app/testem.js
packages/unpublished-record-data-encapsulation-test-app/testem.js
packages/unpublished-relationship-performance-test-app/testem.js
packages/unpublished-serializer-encapsulation-test-app/testem.js
packages/unpublished-test-infra/testem.js

This PR ensures that a user with non native class Adapter will be able to define their own `coalesceFindRequests` field.
Will patch to release and beta.
close #7438 
ref #7358

Bugfix: coalesceFindRequests should work with non native Adapter classes

---

.github/workflows/alpha-release.yml
RELEASE.md
bin/determine-next-alpha-version.js
bin/publish.js

Hi folks,
Similar to https://github.com/emberjs/ember.js/commit/0079b11d0aaec9980aa5e24d165653faf942a791, I'm adding a cron job that runs at 12pm every Monday that checks out the current master and run the publish script for alpha versions.
Repo owners need to add `NODE_AUTH_TOKEN` to the secrets for this to fully work.

[CHORE] auto publish alpha versions

---

packages/store/addon/-private/system/core-store.ts

For [issue 737 in the ember-api-docs repository,](https://github.com/ember-learn/ember-api-docs/issues/737) it turned out the fix needed to be made in the yuidocs that are used to generate the markup for the ember-data docs page.
11 links throughout the page, which are intended to link internally to other parts of the page, were all broken because of an incorrect filepath in the docs. They prepended `classes/Store/` to the path unnecessarily.
I am uncertain of valid tests to add for this, as there doesn't appear to be any current testing for the yuidocs generating the docs page.
I also am aware that to fully update the docs--which will likely want to be done for all versions of Ember-Data's docs--the files on s3 will need to be replaced, which is not something I am able to generate or …

[BUGFIX] Updated the yuidocs for the broken ember-data links linking to elsewhere on the page.

---

packages/record-data/addon/-private/record-data.ts

similar to the internal-model cleanup earlier this should marginally improve payload size as well as ensure we don't pay the initialization cost for class fields.

cleanup: record-data should use declare syntax

---

packages/store/addon/-private/system/model/internal-model.ts

neither of these has a big impact but I noticed them a few times working on other PRs and it helps reduce over-notification of property changes.

fix: IM recordData setter and don't setId if no recordData instance yet

---

packages/unpublished-relationship-performance-test-app/app/serializers/application.js

We don't need to process the payloads since they are already JSON:API.

chore: simpler serializer for perf test app to reduce noise

---

packages/-ember-data/addon/setup-container.js
packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
packages/-ember-data/tests/acceptance/relationships/has-many-test.js
packages/adapter/addon/rest.ts
packages/model/addon/-private/model.js
packages/serializer/addon/rest.js
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/deprecated-evented.js
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/references/belongs-to.js
packages/store/addon/-private/system/references/reference.ts
packages/store/addon/-private/system/store/finders.js
packages/store/types/@ember/debug/index.d.ts
packages/unpublished-test-infra/addon-test-support/assert-all-deprecations.js

- fixes all but 20 deprecations we encounter running the test suite.
- adds a types file that can be removed as soon as this PR is merged to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52397
Remaining deprecations we will need to investigate
- 2 for use of Globals Resolver (potentially intentional testing?)
- 3 for use of injected store (potentially intentional testing?)
- 15 for use of array observers (more than likely intentional for these tests)

chore: resolve implicit this and deprecation-staging deprecations

---

.github/workflows/main.yml
package.json

cc @patocallaghan we were skipping the factory-guy tests since they were failing for so long. Now that it's maintained I've updated the link and if passing will allow it to fail our test suite again.

chore: fix factory-guy link, activate model-fragments, remove ember-data-change-tracker

---

packages/-ember-data/tests/integration/records/load-test.js
packages/-ember-data/tests/integration/records/unload-test.js
packages/model/addon/-private/attr.js
packages/model/addon/-private/model.js
packages/model/addon/-private/system/many-array.js
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/model/states.js
packages/store/addon/-private/system/references/belongs-to.js
packages/store/addon/-private/system/references/has-many.js
packages/store/addon/-private/system/references/record.ts
packages/store/addon/-private/system/store/finders.js
packages/store/addon/-private/system/store/record-data-store-wrapper.ts

Each commit here removes a method or property from InternalModel for which either a different InternalModel codepath is just as efficient to use OR the codepath is unused OR the codepath has a non InternalModel equivalent of the same efficiency.
The motivation is to shrink the surface area of InternalModel until what remains is logic we need to move elsewhere, helping us get a clearer picture of what InternalModel is still handling for us. It comes with the added win of reducing our payload size slightly.

[CHORE] burndown of InternalModel methods that can be eliminated safely

---

.github/workflows/main.yml

cc @patocallaghan this is potentially related to https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/393
I'll unskip model-fragments once I've gotten a fix in place, but initial investigation suggested the fix needed to be upstream.

ci: skip model-fragments until fixed

---

packages/record-data/addon/-private/record-data.ts
packages/record-data/addon/-private/ts-interfaces/relationship-record-data.ts
packages/record-data/package.json
packages/record-data/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
packages/record-data/tests/integration/graph/edge-removal/helpers.ts
packages/record-data/tests/integration/graph/edge-removal/setup.ts
packages/store/addon/-private/index.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/record-data-for.ts
packages/store/addon/-private/ts-interfaces/ds-model.ts
yarn.lock

While refactoring the relationship layer in #7470 I noticed that some of the changes I was making did not fail very many tests despite altering semantics of the relationship layer we ought to have been aware of changes happening to.
This adds test coverage to the relationship cache to a wide range of scenarios. I've written the tests in a way where the underlying implementation can be easily swapped out with only minor alterations to how the tests in the test suite gain access to the cache data. This will let us more easily spot semantics changes and evaluate if that change is a regression or improvement.
The test matrix for the graph covers 96 unique situations around what happens when a record is either `unloaded/deleted/deleted+persisted/deleted+persisted+unloaded` from a …

chore: Improved test coverage for internal relationship state

---

.github/workflows/alpha-release.yml

Adding `environment` entry with `deployment` value for the release job

CHORE: configure alpha-releases to use deploymeent environment

---

packages/serializer/addon/json.js

I was having a really hard time parsing the
docs on the normalization process; the combination
of pipes (|) for grouping the method names and
dash (-) to separate the method name(s) from
the description is pretty confusing to me, so
I made a few tweaks:
1. numbered list for the flow
2. line breaks + bullets for the description
I tried a few variations but this is the best
one I could come up with that yuidoc would allow
Before:
After:

[DOC] Cleanup JSONSerializer normalize docs

---

.github/workflows/alpha-release.yml
bin/publish.js

Attempting to figure out what issue in CI the publish flow is experiencing in the latest run: https://pipelines.actions.githubusercontent.com/lh3ErhSVHNJYpee7hUnIdVxnbJYs0oNN73X4KLsoKw0nHpv7za/_apis/pipelines/1/runs/9213/signedlogcontent/13?urlExpires=2021-05-05T21%3A29%3A53.3513399Z&urlSigningMethod=HMACV1&urlSignature=rjfTrQNjTyJzW0lZnFR8ouNYMcZ8qPtC78E6EuLfD%2FU%3D
The script is experiencing `npm ERR! 404 Not Found - PUT https://registry.npmjs.org/ember-data - Not found\n` which I have not been able to reproduce.
I'm switching to daily run (will revert back to weekly when we get this fixed) and adding `npm view ember-data --verbose` to be run before the publish script for sanity check

chore: fix alpha release script

---

.github/workflows/alpha-release.yml
bin/publish.js

The saga continues.  The latest run of Alpha release failed today: https://github.com/emberjs/data/actions/runs/818083776. 
@runspired suggested we set explicitly registry like in this reported issue: https://github.com/actions/setup-node/issues/130
I added `--verbose` to the publish command executed in the publish script to get more information. I Will remove it once everything works

chore: fix alpha release script attempt 2 - set registry

---

.github/workflows/alpha-release.yml
bin/publish.js

Removing the debugging commands from the github action and publish script.
The solution is ultimately setting the `registry-url` in the github action and ensuring the npmjs package setting allows publishing from an automation token i.e.
I missed that the recent failure for the publish script was a 403 vs before which was a 404. I was able to recreate the issues with a dummy repo. To summarize these are conditions that causes the following issue:
- Valid token + no set registry-url + whatever npmjs security setting = 404
- Valid token + set-registry - 2fa only npmjs security setting = 403
@igorT we need all the ember-data related repos to allow publishing from automation token

chore: fix automation script - remove debugging info

---

packages/-ember-data/tests/integration/adapter/rest-adapter-test.js

Adds tests that were originally created in this PR: https://github.com/emberjs/data/pull/7287
Splitting off from 7287, because the original problem is [already fixed](https://github.com/emberjs/data/pull/7287#issuecomment-834295693).

Add has many tests

---

.github/workflows/alpha-release.yml

Now that the alpha release action is [verified](https://github.com/emberjs/data/actions/runs/823765513) working, we can set the schedule back to Wednesday.

chore: set alpha release github action to run on Wednesdays

---

packages/-ember-data/tests/acceptance/relationships/tracking-record-state-test.js
packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/-ember-data/tests/integration/adapter/store-adapter-test.js
packages/-ember-data/tests/integration/record-array-test.js
packages/-ember-data/tests/integration/record-data/record-data-test.ts
packages/-ember-data/tests/integration/records/delete-record-test.js
packages/-ember-data/tests/integration/records/load-test.js
packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
packages/-ember-data/tests/unit/model-test.js
packages/-ember-data/tests/unit/model/lifecycle-callbacks-test.js
packages/model/addon/-private/attr.js
packages/model/addon/-private/errors.js
packages/model/addon/-private/model.js
packages/model/addon/-private/notify-changes.ts
packages/model/addon/-private/record-state.ts
packages/model/addon/-private/tmp-cached-polyfill.js
packages/model/index.js
packages/model/package.json
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/types/@ember/object/compat.d.ts
packages/store/types/@ember/runloop/-private/backburner.d.ts
packages/store/types/@glimmer/tracking.d.ts
packages/unpublished-relationship-performance-test-app/app/routes/destroy.js
yarn.lock

close https://github.com/emberjs/data/issues/5006
close https://github.com/emberjs/data/pull/5455
Port of changes from #7217

feat: record.destroyRecord should also unload the record

---

package.json
packages/-ember-data/ember-cli-build.js
packages/-ember-data/package.json
packages/adapter/package.json
packages/canary-features/package.json
packages/debug/package.json
packages/model/package.json
packages/private-build-infra/package.json
packages/private-build-infra/src/addon-build-config-for-data-package.js
packages/private-build-infra/src/utilities/rollup-private-module.js
packages/record-data/package.json
packages/serializer/package.json
packages/store/package.json
packages/unpublished-adapter-encapsulation-test-app/package.json
packages/unpublished-debug-encapsulation-test-app/package.json
packages/unpublished-fastboot-test-app/package.json
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-record-data-encapsulation-test-app/package.json
packages/unpublished-relationship-performance-test-app/package.json
packages/unpublished-serializer-encapsulation-test-app/package.json
packages/unpublished-test-infra/addon-test-support/assert-all-deprecations.js
packages/unpublished-test-infra/package.json
yarn.lock

[BUGFIX] rollup step should deactivate ember modules polyfill >= 3.27

---

packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/-ember-data/tests/integration/adapter/rest-adapter/find-record-test.js

Update tests for `findRecord` functionality in test adapter. Since the rest-adapter tests file is quite long, it is hard to make some changes that involve not using global variables and defining all test requirements within the test context. 
This is a follow up on this one: https://github.com/emberjs/data/pull/7522
**What has changed**
- Separate the tests of the adapter in multiple files within a rest-adapter folder. Let me know if it is ok.
- Change imports to stop using global DS import and use the specific packages instead.
- I made some changes to how the `ajaxResponse` works, instead of using a global share adapter variable, it is getting the adapter as a function param and returning a callback function to get the information about the ajax execution. It was just an experiment, so, …

test: Updating syntax of rest-adapter-test.js - Only findRecord

---

packages/-ember-data/tests/integration/snapshot-test.js

@Herriau I'm not sure this test is enough to show the exact same scenario as in #7040. It seems to be green here.
It would be great if you can double check your original issue against master. 
resolves #7040

add test for #7040

---

.github/dependabot.yml

Bumping to weekly because monthly has meant we've lagged on getting updates we actually needed.

bump dependabot to weekly (vs monthly) and remove unneeded ignores

---

packages/-ember-data/tests/unit/model-test.js
packages/model/addon/-private/attr.js
packages/model/addon/-private/belongs-to.js
packages/model/addon/-private/has-many.js
packages/model/addon/-private/model.js

Resolves #5732 and supersedes #5755

[BUGFIX Model] assert when 'content' is used as a property on a record

---

packages/-ember-data/tests/integration/references/belongs-to-test.js
packages/store/addon/-private/system/store/finders.js

fix: #7039 Ensure meta and links update when fetched relationship is empty or does not include the data key

---

packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js
packages/-ember-data/tests/unit/store/adapter-interop-test.js
packages/store/addon/-private/system/store/finders.js

The underlying issue was resolved with the `optionsMap` passed to _findMany. So the test from #5054 is passing without the other changes. I think this test should be kept, because I didn't see other scenarios where both coalescing+adapterOptions where tested at the same time.
closes #5054 
resolves #5050

test: ensure coalesced find requests properly associate options and includes with their snapshot

---

packages/-ember-data/tests/integration/relationships/one-to-many-test.js
packages/record-data/addon/-private/graph/index.ts
packages/record-data/addon/-private/graph/operations/replace-related-record.ts
packages/record-data/addon/-private/graph/operations/replace-related-records.ts
packages/record-data/addon/-private/graph/operations/update-relationship.ts
packages/record-data/addon/-private/relationships/state/belongs-to.ts
packages/record-data/addon/-private/relationships/state/has-many.ts
packages/record-data/tests/integration/graph/edge-test.ts

fix: belongsTo should not attempt load if inverse in payload provided its data (#7049)

---

packages/-ember-data/tests/unit/store/push-test.js

This is only a rebase of master against #7402. I've only taken the tests as per @runspired comment: https://github.com/emberjs/data/issues/7401#issuecomment-839466783

test: Ensure many-many order preserved when pushing individual records

---

packages/-ember-data/tests/integration/records/load-test.js
packages/-ember-data/tests/integration/relationships/belongs-to-test.js
packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/store/addon/-private/system/fetch-manager.ts
packages/store/addon/-private/system/store/finders.js

resolves #7547 
resolves #6920
In the case of belongsTo/hasMany this would already have thrown an error but it would have been a confusing one. You will still get a somewhat more confusing one if the response contains only links but not meta as it will fail `validateDocumentStructure` as JSON:API insists that documents have at-least one-of data/errors/meta

fix: add asserts and assert tests for belongsTo/hasMany/findRecord empty responses

---

packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
packages/record-data/addon/-private/graph/operations/replace-related-record.ts

resolves #6867
closes #6874
Thank you again @runspired for this quick (and dirty :sweat_smile: ) pairing session

[BUGFIX] reset previously failed linked async belongs-to now works

---

packages/adapter/addon/error.js
packages/adapter/addon/index.ts
packages/model/addon/-private/model.js
packages/model/addon/-private/system/many-array.js
packages/serializer/addon/index.ts
packages/serializer/addon/json.js
packages/store/addon/-private/system/core-store.ts

Fixes broken `EmberObject` link mentioned in https://github.com/ember-learn/ember-api-docs/issues/759

[DOC] Fixes broken EmberObject links and updates this._super in native class examples

---

packages/store/addon/-private/system/core-store.ts

Step 1: turn on `assert` (instead of deprecate)
Step 2: After full release cycle, remove `deprecate` block.

[Chore]: shouldAssertMethodCallsOnDestroyedStore: true

---

packages/adapter/addon/rest.ts

"Fixes" #7590.
I imagine I'm not the first nor the last person to wonder why `status` is a string when everywhere else in the adapter it's an integer.

Add a comment explaining setting an errors status as a string

---

.github/workflows/perf-check.yml
packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
packages/-ember-data/tests/integration/adapter/find-test.js
packages/-ember-data/tests/integration/application-test.js
packages/-ember-data/tests/integration/injection-test.js
packages/-ember-data/tests/integration/multiple-stores-test.js
packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
packages/-ember-data/tests/integration/record-data/record-data-test.ts
packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
packages/-ember-data/tests/integration/records/relationship-changes-test.js
packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/-ember-data/tests/integration/request-state-service-test.ts
packages/-ember-data/tests/integration/snapshot-test.js
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
packages/-ember-data/tests/unit/model/rollback-attributes-test.js
packages/-ember-data/tests/unit/system/snapshot-record-array-test.js
packages/adapter/addon/index.ts
packages/adapter/addon/rest.ts
packages/store/types/@ember/version.d.ts
packages/store/types/ember-compatibility-helpers/index.d.ts
packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
packages/unpublished-test-infra/addon-test-support/qunit-asserts/utils/symbol-ponyfill.ts
packages/unpublished-test-infra/package.json

Resolves the issues causing canary publish and nightly chrons to fail.
Note: we will still need to "actually" resolve many of these deprecations for 4.0, but this wraps the ones that we know of currently in `expectDeprecation` to prevent the test suite from failing.
The `ember-global` deprecation when accessing Namespace is not expected, and the message it prints is a red-herring (that ember-cli-babel brought by ember-maybe-import-regenerator-runtime is outdated). That addon is not using Ember in any capacity, so while it should be updated it is not what is causing the deprecation spew.
When accessing:
```ts
import Namespace from '@ember/application/namespace';
Namespace.byName('DS');
```
Ember iterates through all the keys of `window`, and if they start with a capital letter it accesses …

chore: fix or silence-expected deprecations

---

packages/model/package.json
packages/private-build-infra/src/addon-build-config-for-data-package.js
yarn.lock

and use ember-cached-decorator-polyfill@0.1.4

@ember-data/model: Simplify @cached transpilation

---

packages/-ember-data/tests/unit/model-test.js
packages/-ember-data/tests/unit/model/attr-test.js
packages/model/addon/-private/attr.js
packages/model/addon/-private/belongs-to.js
packages/model/addon/-private/has-many.js
packages/model/addon/-private/model.js

I opened https://github.com/emberjs/data/pull/7682 to be able to illustrate the issue in https://github.com/emberjs/data/issues/7679 with a failing test. This PR adds the same test but also reverts https://github.com/emberjs/data/pull/7545 which is causing the issue 👍 so hopefully the tests will pass.
As with my other PR I know that I'm probably not targeting the right branch here so let me know if you want to merge this and I can retarget the correct branch once it is created 👍

Revert assertion on content attribute and add test to prevent regression

---

packages/private-build-infra/src/utilities/rollup-private-module.js

Fix for - > https://github.com/embroider-build/embroider/issues/946
This appears to fix the problem locally (builds work in `ember new foo` & `ember new foo-embroider --embroider` builds
This effects 3.27.1 -> current canary and most likely needs the following backports:
* 3.28
* 3.27
* beta branch

[Bugfix] ensure `shouldCompileModules` is once again respected

---

packages/private-build-infra/src/utilities/rollup-private-module.js

Backport of #7680
Fixes Embroider compatibility

[Bugfix] ensure `shouldCompileModules` is once again respected (#7680)

---

packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json
yarn.lock

The prior version used deprecated import paths that error under ember-source v4.0.
This will need to be backported to beta and released.

[BUGFIX] Update @ember/string to the latest version to fix compatibility with ember-source 4.x

---

packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json
yarn.lock

version used deprecated import paths that error under ember-source v4.0
Backport of https://github.com/emberjs/data/pull/7697

[BACKPORT Release] @ember/string to the latest version. The prior (#7697)

---

packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json
yarn.lock

version used deprecated import paths that error under ember-source v4.0
Backport of #7697

[BACKPORT Beta] Update @ember/string to the latest version. The prior (#7697)

---

.github/workflows/main.yml

Some runs need a bit more leeway in their testing timeouts

CI timeouts testing bump

---

.github/workflows/main.yml
packages/-ember-data/config/ember-try.js
packages/-ember-data/ember-cli-build.js
packages/-ember-data/tests/dummy/config/targets.js
packages/adapter/tests/dummy/config/targets.js
packages/debug/tests/dummy/config/targets.js
packages/model/tests/dummy/config/targets.js
packages/record-data/tests/dummy/config/targets.js
packages/serializer/tests/dummy/config/targets.js
packages/store/tests/dummy/config/targets.js
packages/unpublished-adapter-encapsulation-test-app/config/targets.js
packages/unpublished-debug-encapsulation-test-app/config/targets.js
packages/unpublished-fastboot-test-app/config/targets.js
packages/unpublished-model-encapsulation-test-app/config/targets.js
packages/unpublished-model-encapsulation-test-app/testem.js
packages/unpublished-record-data-encapsulation-test-app/config/targets.js
packages/unpublished-serializer-encapsulation-test-app/config/targets.js
packages/unpublished-test-infra/tests/dummy/config/targets.js

prep for 4.0!
There are some comments about IE11 in the codebase and features we couldn't use due to lack of APIs.  Will follow up after to remove all comments and apply necessary changes.
This PR ultimately aligns our browser targets with ember.js
- https://github.com/emberjs/ember.js/blob/master/config/targets.js

Remove TARGET_IE11 flag

---

packages/-ember-data/tests/integration/application-test.js
packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
packages/-ember-data/tests/integration/store/adapter-for-test.js
packages/-ember-data/tests/integration/store/serializer-for-test.js
packages/-ember-data/tests/unit/store/peek-record-test.js
packages/adapter/addon/rest.ts
packages/canary-features/addon/index.ts
packages/record-data/addon/-private/record-data.ts
packages/record-data/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
packages/serializer/addon/json.js
packages/store/addon/-private/identifiers/cache.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/record-array-manager.js
packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
packages/store/addon/-private/system/snapshot.ts
packages/store/addon/-private/system/store/finders.js
packages/unpublished-test-infra/addon-test-support/public-props.js

Fix deprecated assign usage from @ember/assign

---

.github/workflows/main.yml

Lots of failures from that package.  I don't have the time to go fix them in the short term.  This should get us back to green.

Disable ilios partner test

---

packages/-ember-data/tests/integration/store/model-name-test.js
packages/private-build-infra/src/stripped-build-plugins.js
packages/record-data/tests/integration/graph/edge-removal/setup.ts
packages/store/addon/-private/identifiers/utils/uuid-v4.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/store/finders.js

Remove IE11 hacks

---

packages/store/addon/-private/system/references/reference.ts

The `meta` field is supposed to be inside of the relationship object, not inside of `links`

reference: Fix broken `meta()` snippet

---

.github/workflows/asset-size-check.yml
.github/workflows/enforce-pr-labels-beta.yml
.github/workflows/enforce-pr-labels-canary.yml
.github/workflows/enforce-pr-labels-lts-prev.yml
.github/workflows/enforce-pr-labels-lts.yml
.github/workflows/enforce-pr-labels-old-release.yml
.github/workflows/enforce-pr-labels-release.yml
.github/workflows/main.yml
.github/workflows/perf-check.yml

cancels jobs on PRs that aren't for the current head commit.

chore: cancel older CI jobs

---

.eslintrc.js
packages/-ember-data/tests/integration/references/autotracking-test.js
packages/-ember-data/tests/integration/references/has-many-test.js
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/record-notification-manager.ts
packages/store/addon/-private/system/references/belongs-to.ts
packages/store/addon/-private/system/references/has-many.ts
packages/store/addon/-private/system/references/record.ts
packages/store/addon/-private/system/references/reference.ts
packages/store/addon/-private/ts-interfaces/ds-model.ts
packages/store/index.js
packages/store/package.json
tsconfig.json
yarn.lock

feat: autotracking for reference id access

---

packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
packages/record-data/addon/-private/record-data.ts
packages/store/addon/-private/identifiers/cache.ts
packages/store/addon/-private/system/model/states.js

update test and fix lid reflection

---

packages/-ember-data/tests/integration/records/create-record-test.js
packages/-ember-data/tests/integration/store-test.js
packages/model/addon/-private/model.js
packages/store/addon/-private/system/ds-model-store.ts

createRecord crashes when a setter which sets an attribute is involved
in the createRecord.
resolves #7772

Fix: assign unknown properties in init after initialization is finished to ensure proper setup timing

---

packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
packages/model/addon/-private/system/promise-many-array.ts
packages/store/types/ember/index.d.ts

fix: A(PromiseManyArray) should have no-effect

---

packages/-ember-data/tests/integration/relationships/has-many-test.js
yarn.lock

* deactivate broken partner tests
* feat: autotracking for reference id access (#7796)
* feat: autotracking for reference id access
* ensure references are torn down
* fix build
* add dep
* add to deps
* fix invalid json:api support and add valid json:api support
* autotracking tests and cleanup
* fix test failure, add comment
* skip tests when feature not available
* update test and fix lid reflection (#7800)
* update test and fix lid reflection
* remove debugger
* fix ff off branch
* add test and fix push of duplicate identifiers to a relationship (#7801)
* add test + fix for chained async has many (#7691)
* [bugfix]: fix for chained async has many
* add fix and update tests
* remove console.logs
* make work with flags off
* fix test for lts
Co-authored-by: Chris Thoburn …

Backport Train for Release (#7803)

---

packages/adapter/addon/index.ts

_Note: Re-opening from [previous PR](https://github.com/emberjs/data/pull/7681) that was incorrectly targeting the wrong base branch._
Description for `coalesceFindRequests` indicates that it will attempt to coalesce `fetchRecord` calls, but the relevant public API concept is `findRecord`. It is a bit confusing to have `fetchRecord` here since it hints at a framework concept that does not have any definition in the public API.
- updates "fetchRecord" -> "findRecord" in `coalesceFindRequests` docstring

[chore] update `coalesceFindRequests` docstring

---

packages/-ember-data/tests/integration/serializers/rest-serializer-test.js
packages/serializer/addon/-private/embedded-records-mixin.js
packages/serializer/addon/json.js
packages/serializer/addon/rest.js

Using `array.push(...spread)` is quite nice and convenient, but unfortunately providing too many arguments to a function call can cause a stack overflow, which happened to us.
[Minimum reproduction Twiddle](https://ember-twiddle.com/a8b1b503f15f0c20fde2afe1be5d5bcb?openFiles=routes.application%5C.js%2C)
Also unfortunately, using `Array#concat` changes the API, since it returns a new array rather than modifying the original. Also also unfortunately, simply iterating over an array and pushing one-by-one is significantly slower than using spread or concat.
[Performance tests JSBin](https://jsbin.com/suropipiyi/edit?js,console)
This implementation is a hybrid approach of looping and spreading that remains stack safe.
If we can guarantee that using concat is safe, that'd be an even better …

Don't use array.push(...spread) with unknown input

---

.eslintrc.js
package.json
packages/-ember-data/node-tests/docs/test-coverage.js
packages/store/addon/-private/system/references/belongs-to.ts
packages/store/addon/-private/ts-interfaces/minimum-adapter-interface.ts
scripts/lint-changed-js.js
scripts/publish.js

Here are the changes I made. There's essentially no behavior change from any of these except now catching unused disable directives.
* Switch to prettier [recommended](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration) config as a better way of enabling prettier
* Alphabetize lists of rules in .eslintrc.js
* Have ESLint report and autofix [unused disable directives](https://eslint.org/docs/user-guide/command-line-interface#--report-unused-disable-directives)
* ESLint now allows `extends` in an override without a hack so we can use this for `plugin:node/recommended`

Cleanup eslint config

---

packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/ds-model-store.ts
packages/store/addon/-private/system/model/shim-model-class.ts
packages/store/addon/-private/system/schema-definition-service.ts
packages/store/addon/-private/system/snapshot.ts
packages/store/addon/-private/system/store/record-data-store-wrapper.ts
packages/store/addon/-private/ts-interfaces/schema-definition-service.ts

[RFC 794](https://github.com/emberjs/rfcs/pull/794)
TODO

RFC 794: Simplifying Schema Definition Service type signatures

---

.eslintrc.js
package.json
packages/-ember-data/lib/yui-docs-preprocessor.js
packages/unpublished-test-infra/addon-test-support/assert-all-deprecations.js
scripts/lint-changed-js.js
yarn.lock

Alternative to using ESLint's built-in [--no-unused-disable-directives](https://eslint.org/docs/user-guide/command-line-interface#--report-unused-disable-directives) CLI option, since that CLI option cannot be disable in a single problematic location, as we encountered issues with in https://github.com/emberjs/data/pull/7882/files#r809271031.
If necessary, we can use:
```js
// eslint-disable-next-line eslint-comments/no-unused-disable
```
to avoid the same problem.

chore: add eslint-plugin-eslint-comments

---

.eslintrc.js
package.json
packages/-ember-data/node-tests/docs/test-coverage.js
packages/record-data/addon/-private/graph/index.ts
packages/record-data/addon/-private/graph/operations/replace-related-records.ts
packages/record-data/tests/integration/graph/operations-test.ts
tsconfig.json
yarn.lock

reported by @wagenet 
Affects 4.0, 4.1, 4.2 so should be backported as a critical fix to all three.
TL;DR our previous fix for filtering duplicates in relationships was incorrect: #7786. It had the effect that the first time a duplicate is encountered the loop would exit and all entries in the new state array after that would be empty.
We should deprecate (later assert) many relationships having duplicates, as we discard them anyway.
Doing this work reminds me of the common ask to explicitly *allow* duplicates in collection relationships. I do believe with the new relationship infrastructure that this is something we could potentially allow. If anyone wants to take on an RFC the constraints are roughly:
- relationships that can have duplicate must specify both `inverse: null` and …

fix: dont early exit loop when filtering duplicates from relationship updates

---

packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
packages/model/addon/-private/system/promise-many-array.ts

fix for #7904 computed chains not updated for async hasMany loading

---

packages/-ember-data/addon/index.js
packages/-ember-data/package.json
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/schema-definition-service.ts
packages/store/addon/-private/system/snapshot.ts
packages/store/addon/-private/system/store/internal-model-factory.ts
packages/store/addon/-private/system/store/record-data-store-wrapper.ts
packages/store/index.js
packages/store/package.json
yarn.lock

Came across `embroider-optimized` build issues in https://github.com/poteto/ember-changeset/pull/630 and it appears we need a fix similar to https://github.com/miragejs/ember-cli-mirage/pull/2297.
Looks like TS is not happy as `importSync` return type is `unknown` whereas `require()` was successfully resolved by TS.
@ef4 Would you maybe have some advise here how to make TS happy?

Remove some usage of runtime require

---

packages/-ember-data/tests/integration/adapter/client-side-delete-test.js

[CHORE]: Modernize client-side-delete-test

---

packages/-ember-data/tests/integration/adapter/record-persistence-test.js

[CHORE]: Modernize record-persistence-test

---

packages/-ember-data/tests/integration/adapter/json-api-adapter-test.js

[CHORE]: Modernize json-api-adapter-test

---

packages/serializer/addon/json.js

hoping no tests fail 🤞🏻 
will add new tests if this appears safe.
noticed that the embedded records mixin was failing when configured to deserialize records but serialize ids because the args weren't passed to keyForRelationship appropriately.

fix: pass correct args to keyFor<Attribute|Relationship> when normalizing

---

packages/-ember-data/tests/integration/adapter/handle-response-test.js

[CHORE]: Modernize Handle-Response-Test

---

package.json
packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/model/package.json
packages/record-data/package.json
packages/serializer/package.json
packages/store/addon/-private/system/core-store.ts
packages/store/addon/-private/system/model/internal-model.ts
packages/store/addon/-private/system/model/states.js
packages/store/package.json
packages/unpublished-adapter-encapsulation-test-app/package.json
packages/unpublished-debug-encapsulation-test-app/package.json
packages/unpublished-fastboot-test-app/package.json
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-record-data-encapsulation-test-app/package.json
packages/unpublished-relationship-performance-test-app/package.json
packages/unpublished-serializer-encapsulation-test-app/package.json
packages/unpublished-test-infra/package.json
yarn.lock

We were still running all the plumbing for firing lifecycle events on models even though we removed the Evented and trigger infra. The deletes that, saves bytes and should speed up some things.

chore: remove unused evented infra

---

packages/-ember-data/tests/integration/record-data/record-data-test.ts
packages/-ember-data/tests/integration/relationships/has-many-test.js
packages/record-data/addon/-private/record-data.ts

close https://github.com/emberjs/data/issues/7844

test for async hasMany does not trigger relationship fetch

---

LICENSE.md

The `README` references a `LICENSE.md` file, which does not exist in this repo.

Add `LICENSE.md`

---

packages/model/addon/-private/has-many.js
packages/model/addon/-private/model.js

This PR fixes a couple of statements in docs that import from `@ember-decorators` to `@ember-data`
Closes #8001

Update imports in doc code samples

---

packages/adapter/blueprints/adapter-test/index.js
packages/adapter/blueprints/adapter-test/mocha-rfc-232-files/__root__/__path__/__test__.js
packages/adapter/blueprints/adapter-test/qunit-files/__root__/__path__/__test__.js
packages/adapter/node-tests/blueprints/adapter-test.js
packages/adapter/node-tests/fixtures/adapter-test/mocha-rfc232-addon.js
packages/adapter/node-tests/fixtures/adapter-test/rfc232-addon.js
packages/model/blueprints/model-test/index.js
packages/model/node-tests/blueprints/model-test.js
packages/model/node-tests/fixtures/model-test/mocha-rfc232-addon.js
packages/model/node-tests/fixtures/model-test/rfc232-addon.js
packages/private-build-infra/src/utilities/module-prefix-for-project.js
packages/serializer/blueprints/serializer-test/index.js
packages/serializer/blueprints/transform-test/index.js
packages/serializer/blueprints/transform-test/mocha-rfc-232-files/__root__/__path__/__test__.js
packages/serializer/blueprints/transform-test/qunit-files/__root__/__path__/__test__.js
packages/serializer/node-tests/blueprints/serializer-test.js
packages/serializer/node-tests/blueprints/transform-test.js
packages/serializer/node-tests/fixtures/serializer-test/mocha-rfc232-addon.js
packages/serializer/node-tests/fixtures/serializer-test/rfc232-addon.js
packages/serializer/node-tests/fixtures/transform-test/mocha-rfc232-addon.js
packages/serializer/node-tests/fixtures/transform-test/rfc232-addon.js

I introduced a regression when implementing https://github.com/emberjs/data/pull/7887.
The project's module prefix should be used instead of the addon's package name when generating these import paths, as these test setup functions are _not_ located in the addon's `addon` folder, but in `/tests/helpers/index.js`.

[BUGFIX release] Fix generated import paths for test setup functions in addons

---

packages/-ember-data/tests/integration/debug-adapter-test.js
packages/debug/addon/index.js

schedule watchTypeIfUnseen to prevent loop

---

packages/-ember-data/tests/integration/adapter/queries-test.js
packages/-ember-data/tests/integration/store-test.js
packages/-ember-data/tests/unit/store/async-leak-test.js
packages/store/addon/-private/system/core-store.ts

fix: waiter should be always on

---

packages/-ember-data/tests/unit/utils/serialize-query-params-test.js
packages/adapter/addon/-private/utils/serialize-query-params.ts

While moving off jquery, I noticed a difference in how the ember-data serializes `null` in arrays in query params.
jQuery's buildParams  ([link](https://github.com/jquery/jquery/blob/main/src/serialize.js)) checks for `null` in an array and sets it to an empty string
```js
buildParams(prefix + "[" + ( typeof v === "object" && v != null ? i : "" ) + "]" ...
```
ember-data doesn't have the explicit `null` check ([link](https://github.com/emberjs/data/blob/v4.4.0/packages/adapter/addon/-private/utils/serialize-query-params.ts)), so `null` values in arrays get treated like objects.
This results in urls that decode to:
```
filter[children][0]=&...
```
rather than the expected
```
filter[children][]=&...
```
This PR fixes this by adding an explicit null check. 
Would like to see this fix …

[BUGFIX] Serialize null array items as empty strings

---

packages/-ember-data/tests/integration/adapter/store-adapter-test.js

[CHORE]: Modernized store-adapter-test

---

packages/private-build-infra/src/addon-build-config-for-data-package.js
packages/store/addon/-private/caches/identifier-cache.ts
packages/store/addon/-private/utils/uuid-polyfill.ts
packages/store/ember-cli-build.js

resolves #8097 
resolves #8106 
To use the polyfill:
```
let app = new EmberApp(defaults, {
'@embroider/macros': {
setConfig: {
'@ember-data/store': {
polyfillUUID: true
},
},
},
});
```

add optional polyfill

---

.github/workflows/main.yml
packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
packages/-ember-data/tests/unit/store/adapter-interop-test.js
packages/record-data/addon/-private/record-data.ts
packages/serializer/addon/json-api.js
packages/store/addon/-private/caches/identifier-cache.ts
packages/store/addon/-private/legacy-model-support/record-reference.ts
packages/store/addon/-private/legacy-model-support/shim-model-class.ts
packages/store/addon/-private/managers/record-notification-manager.ts
packages/store/addon/-private/network/fetch-manager.ts
packages/store/addon/-private/network/snapshot.ts
packages/unpublished-adapter-encapsulation-test-app/tests/integration/coalescing-test.js
packages/unpublished-serializer-encapsulation-test-app/tests/integration/relationships-test.js

resolves #8110 
Note: haven't fixed multi-options yet for the coalescing case, only the individual finds case

fix: account for multi-options-per-identifer possibility

---

ember-data-types/q/record-data-record-wrapper.ts
ember-data-types/q/record-data.ts
packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
packages/-ember-data/tests/integration/record-data/record-data-test.ts
packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
packages/-ember-data/tests/unit/model-test.js
packages/model/addon/-private/attr.js
packages/record-data/addon/-private/record-data.ts
packages/store/addon/-private/legacy-model-support/schema-definition-service.ts
packages/store/addon/-private/network/snapshot.ts

This prevents needing to instantiate and iterate the record to retrieve default values. We may end up needing to deprecate record-access, but the hope is that folks generally weren't using the undocumented arguments passed to defaultValue.
Additionally, this lets us remove the un-spec'd `hasAttr` from V1 cache which was necessary to distinguish between `undefined` meaning never-set and `undefined` meaning set to undefined for default-value determination.

fix: move defaultValue into RecordData to better encapsulate and prevent eager instantiations

---

packages/model/addon/-private/model.js

Call original reopen with "...arguments"
Recall the original reopen function with "arguments" instead of "...arguments".
Does this PR need to be described in the Ember release blog post? Please briefly describe what should be shared.

fix: reopen deprecation should properly pass original arguments

---

packages/-ember-data/tests/integration/store-test.js
packages/model/addon/-private/legacy-relationships-support.ts
packages/store/addon/-private/caches/instance-cache.ts
packages/store/addon/-private/network/fetch-manager.ts
packages/store/addon/-private/store-service.ts

Currently doesn't appear to be a regression here, but probably a good test to have around anyway. The regression might be in the timing of the promise-record setup, if so we'll need more info to track it down. Another hypothesis is there is an unloadRecord call involved which previously the findRecord call was "cancelling". Now the unloadRecord call would succeed and the data be cleared and refetch required.

fix: backgroundReloads should not affect recordIsLoaded (#8125)

---

packages/-ember-data/tests/integration/peek-all-test.js
packages/-ember-data/tests/integration/record-array-manager-test.js
packages/-ember-data/tests/unit/record-arrays/record-array-test.js
packages/store/addon/-private/caches/instance-cache.ts
packages/store/addon/-private/managers/record-array-manager.ts
packages/store/addon/-private/managers/record-data-store-wrapper.ts
packages/store/addon/-private/record-arrays/adapter-populated-record-array.ts
packages/store/addon/-private/record-arrays/record-array.ts
packages/store/addon/-private/store-service.ts

This is a complementary PR to #8134 which prepares the RecordArrayManager to better support RecordArray's built using Native Proxies. It also improves performance out-of-the-box by eliminating full-traversals of the store's huge array when doing partial updates to the RecordArray. 
Users can expect up to 50% faster RecordArray updates and and initial value calculations (the return value of `findAll` and `peekAll`). These changes also improve the cost of record instantiation. In an app running in latest Chrome on ubuntu loading 100k records this would save ~425ms.

feat: efficient manager

---

packages/-ember-data/tests/unit/model-test.js
packages/model/addon/-private/model.js
packages/store/addon/-private/store-service.ts

Ports @ember-data/model init optimizations from #8134. Same as #8139 this is to ensure that the benchmark for that PR is as close as possible to "just the cost of moving to proxies"

perf: optimize factory.create

---

.github/workflows/perf-over-release.yml
scripts/perf-tracking/create-comment.js

lets us measure against the current release branch. May require that we catch the perf-test harness on release-branch up to speed.

chore: add release perf check

---

packages/store/addon/-private/caches/identifier-cache.ts
packages/store/addon/-private/utils/uuid-polyfill.ts

rollup doesn't understand `importSync`, so we can't use it within a module.
cc @kiwi-josh
@jrjohnson this will need back ported.

fix: uuid polyfill logic

---

packages/store/addon/-private/record-arrays/identifier-array.ts

Will display the correct deprecation message for toArray instead of one for unshiftObjects.

fix: correct deprecation message for toArray

---

packages/-ember-data/tests/unit/record-arrays/record-array-test.js
packages/store/addon/-private/record-arrays/identifier-array.ts

FilterBy can be called with and without a second argument, when the second argument is used the filter should compare that value to the value in the record.
I slapped the test for this in a sort of random spot because I wasn't sure where it goes.

fix: filterBy should compare values

---

packages/-ember-data/tests/integration/model-errors-test.ts
packages/store/addon/-private/system/model/states.js

Changed base branch from #8009 
Hey guys,
I faced a problem and did a test + added a fix, the simplest way to replicate:
```js
myModel = this.store.createRecord('my-model');
myModel.errors.add('fieldA', ['blank']);
myModel.errors.add('fieldB', ['blank']);
later(() => {
set(myModel, 'fieldA', 'value');
set(myModel, 'fieldB', 'value');
}, 1000);
```
It raises an error: 
```
Attempted to handle event `becameValid` on <my-model:null> while in state root.loaded.created.uncommitted.
```
I'm not sure why it is being raised only if there are 2 or more fields with errors.

[BUGFIX] Model state error 3.28

---

packages/-ember-data/tests/integration/debug-adapter-test.js
packages/-ember-data/tests/unit/utils/serialize-query-params-test.js
packages/adapter/addon/-private/utils/serialize-query-params.ts
packages/debug/addon/index.js
packages/record-data/addon/-private/graph/operations/replace-related-records.ts
packages/record-data/tests/integration/graph/operations-test.ts

- backport fix for #7786 from #7882
- backport fix for #8006 from #8008 
- backport fix for null query params serialization from #8083 
- backport [fix from](https://github.com/emberjs/data/pull/8182/commits/a97126f3b37913e0aac2e6b35693a9d77e56bb27) https://github.com/emberjs/data/pull/7834 [for](https://github.com/emberjs/data/pull/8182/commits/a97126f3b37913e0aac2e6b35693a9d77e56bb27) https://github.com/emberjs/data/issues/7824

backport fixes to 3.28 lts

---

packages/-ember-data/tests/unit/record-arrays/record-array-test.js
packages/store/addon/-private/record-arrays/identifier-array.ts

Array.at isn't [supported in Safari until 15.4](https://caniuse.com/?search=array.at), using brackets isn't as pretty, but enjoys universal support.
No

Use array notation instead of at for accessing values

---

packages/-ember-data/tests/unit/record-arrays/record-array-test.js
packages/store/addon/-private/record-arrays/identifier-array.ts

Backport #8184 to release:
Array.at isn't supported in Safari until 15.4, using brackets isn't as pretty, but enjoys universal support.

Use array notation instead of at for accessing values (#8184)

---

packages/-ember-data/tests/unit/record-arrays/record-array-test.js
packages/store/addon/-private/record-arrays/identifier-array.ts

Array.at isn't supported in Safari until 15.4, using brackets isn't as pretty, but enjoys universal support.

Use array notation instead of at for accessing object at values

---

packages/-ember-data/tests/unit/record-arrays/record-array-test.js
packages/store/addon/-private/record-arrays/identifier-array.ts

Backport #8189 to release
Array.at isn't supported in Safari until 15.4, using brackets isn't as pretty, but enjoys universal support.

Use array notation instead of at for accessing object at values (#8189)

---

packages/-ember-data/tests/integration/references/autotracking-test.js
packages/model/addon/-private/references/has-many.ts

fix: ManyReference.value should recompute when data is first received

---

packages/debug/addon/setup.js

fix: inspector type detection 2. attempt #8205

---

packages/private-build-infra/src/addon-build-config-for-data-package.js
packages/private-build-infra/src/utilities/rollup-private-module.js

No release notes required.
Because the ember-data packages opt out of the standard ember-cli preprocessor registry, they won't get analyzed correctly by ember-auto-import. Instead, they're forced to manually configure the analyzer. That's what this PR does.
The `ember-auto-import/babel-plugin` that was being added before was doing nothing. As documented, it exists to support dynamic imports, which ember-data doesn't use. It's unrelated to the import analysis.
I confirmed manually that these changes make ember-auto-import work in both the public and private parts of the packages. The proper way to add test coverage for this is to start using it, as was begun in the branch ember-auto-import-v2-addon-bug.

Invoke ember-auto-import analyzer

---

.github/workflows/alpha-release.yml
.github/workflows/asset-size-check.yml
.github/workflows/main.yml
.github/workflows/nightly.yml
.github/workflows/partner-tests.yml
.github/workflows/perf-check.yml
.github/workflows/perf-over-release.yml
package.json
packages/-ember-data/package.json
packages/adapter/package.json
packages/canary-features/package.json
packages/debug/package.json
packages/model/package.json
packages/private-build-infra/package.json
packages/record-data/package.json
packages/serializer/package.json
packages/store/package.json
packages/unpublished-adapter-encapsulation-test-app/package.json
packages/unpublished-debug-encapsulation-test-app/package.json
packages/unpublished-fastboot-test-app/package.json
packages/unpublished-model-encapsulation-test-app/package.json
packages/unpublished-record-data-encapsulation-test-app/package.json
packages/unpublished-relationship-performance-test-app/package.json
packages/unpublished-serializer-encapsulation-test-app/package.json
packages/unpublished-test-infra/package.json

replaces #8235 which didn't bump pnpm in github actions

chore: bump pnpm version

---

packages/debug/package.json
packages/record-data/package.json
packages/unpublished-test-infra/package.json
pnpm-lock.yaml

just ensuring we don't ship a larger node_modules tree than necessary

chore: remove uneeded dep on ember-cli-test-info

---

packages/store/addon/-private/managers/record-array-manager.ts
tests/main/tests/unit/fast-push-test.js

fix: fast-push should adjust end based on start

---

packages/model/addon/-private/belongs-to.js
packages/model/addon/-private/has-many.js
packages/model/addon/-private/legacy-data-fetch.js
packages/model/addon/-private/legacy-relationships-support.ts
packages/model/addon/-private/many-array.ts
packages/model/addon/-private/references/belongs-to.ts
packages/model/addon/-private/references/has-many.ts
packages/private-build-infra/src/addon-build-config-for-data-package.js
packages/private-build-infra/src/debug-macros.js
packages/private-build-infra/src/deprecations.js
packages/private-build-infra/src/transforms/babel-plugin-convert-existence-checks-to-macros/index.js
packages/private-build-infra/src/transforms/babel-plugin-transform-deprecations/index.js
packages/private-build-infra/src/transforms/babel-plugins-transform-features/index.js
packages/record-data/addon/-private/graph/-edge-definition.ts
packages/store/addon/-debug/index.js
packages/store/addon/-private/caches/instance-cache.ts
packages/store/addon/-private/legacy-model-support/schema-definition-service.ts
packages/store/addon/-private/managers/record-data-store-wrapper.ts
packages/store/addon/-private/store-service.ts
pnpm-lock.yaml
tests/main/ember-cli-build.js
tests/main/package.json

seems to be working locally; however, output feels weird. Suspect `@embroider/macros` has a bug we need to address for `getOwnConfig` wherein it hard codes the config path from system root, which is obviously unpublishable but fine so long as we continue to publish v1 addons

feat: strip deprecations with macros

---

packages/store/addon/-private/caches/identifier-cache.ts

Add a little assert message when crypto.randomUUID does not exist
Sidenote: I was not able to test this, since I wasnt able to boot an app with the linked ember-data. :(

assert missing crypto.randomUUID

---

.github/workflows/perf-check.yml
.github/workflows/perf-over-release.yml
packages/store/addon/-private/managers/record-array-manager.ts
tests/main/tests/integration/peek-all-test.js

fix: dont skip LiveArray remove if pending queue is not empty

---

packages/store/addon/-private/store-service.ts
tests/main/tests/acceptance/relationships/has-many-test.js

resolves #8262 
I'm not entirely convinced this is safe, though it passes tests. We're close to disentangling from the runloop entirely, should probably try to finish that off so we can be certain.
The rough cause of the issue is that Ember apparently now flushes render after every `run`, so nested runs are no longer safe. Unsure when this changed.

fix: use join vs run for deleteRecord destroy of new records

---

packages/record-data/addon/-private/record-data.ts
tests/main/tests/unit/model-test.js

fix: <Cache>.changedAttrs should be empty if no local mutations exist

---

packages/store/addon/-private/caches/instance-cache.ts
packages/store/addon/-private/managers/record-array-manager.ts
tests/main/tests/integration/record-array-test.js

also defends against cache duplicate notifications for removals since user-land API calls could otherwise similarly trigger this.
resolves #8327

fix: dont notify RecordArrayManager if deletion already accounted

---

packages/model/addon/-private/promise-belongs-to.ts
packages/model/addon/-private/references/belongs-to.ts
tests/main/tests/integration/references/autotracking-test.js
tests/main/tests/integration/relationships/belongs-to-test.js

fix: expose PromiseBelongsTo.id and recompute on BelongsToRef.value when initially null

---

packages/store/addon/-private/record-arrays/identifier-array.ts
tests/main/tests/unit/model/relationships/has-many-test.js

fixes #7886 
This issue has existed for so long we shouldn't backport unless requested.

fix: rollbackAttributes|unloadRecord during hasMany forEach should not error

---

packages/model/addon/-private/legacy-relationships-support.ts
packages/model/addon/-private/references/belongs-to.ts
packages/model/addon/-private/references/has-many.ts
tests/main/tests/integration/references/belongs-to-test.js

I think it should be possible to call .load() on a sync belongsTo reference,
but if you do, you get an AssertionError:
Assertion Failed: You looked up the 'team' relationship on a 'person' with id 1
but some of the associated records were not loaded. Either make sure they are
all loaded together with the parent record, or specify that the relationship
is async (`belongsTo({ async: true })`)
This commit adds a breaking test to demonstrate this.
Might be worth checking sync hasMany's handling of this too.
Note: for some reason, `.reload()` works (e.g. `model.belongsTo('foo').reload()`) but not `.load()`.

feat: allow .load()ing sync relationships

---

packages/record-data/addon/-private/graph/-utils.ts
tests/main/tests/integration/relationships/belongs-to-test.js
tests/main/tests/integration/relationships/has-many-test.js

fix: improve object stringify and verbiage for relationship identifier errors

---

packages/record-data/addon/-private/record-data.ts

fix: give more meaningful error if id matches but is number instead of string

---

ember-data-types/q/ds-model.ts
packages/store/addon/-private/legacy-model-support/shim-model-class.ts
packages/store/addon/-private/store-service.ts
tests/main/tests/integration/store/shim-model-test.js

fix: Schema.eachTransformedAttribute API should match Model.eachTransformedAttribute

---

packages/store/addon/-private/store-service.ts
tests/main/tests/integration/application-test.js
tests/main/tests/integration/identifiers/configuration-test.ts
tests/main/tests/integration/record-data/record-data-errors-test.ts
tests/main/tests/integration/record-data/record-data-state-test.ts
tests/main/tests/integration/record-data/record-data-test.ts
tests/main/tests/integration/record-data/store-wrapper-test.ts
tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
tests/main/tests/unit/store/asserts-test.js

If anyone happens to still be doing `Store.extend` we can restore with a deprecation. Extending the Store as a pattern was rare enough until well into Octane that likely this is safe-enough.

feat: don't extend EmberObject/Service for Store

---

packages/adapter/rollup.config.mjs
packages/adapter/src/error.js
packages/graph/rollup.config.mjs
packages/json-api/rollup.config.mjs
packages/model/index.js
packages/model/rollup.config.mjs
tests/main/tests/unit/adapter-errors-test.js

Ember 3.8 began simply re-exporting `Error` at this specifier, and Ember 5.0 drops the old package entirely. Switch to just using native `Error` accordingly, and drop all bits referring to the old class.
N/A (I think?) – this shouldn't change literally anything from consumers' POV.
---
This unblocks emberjs/ember.js#20379 (part of the Ember 5.0 cleanup).

cleanup: Switch all uses of `@ember/error` to native Error

---

packages/store/src/-private/record-arrays/identifier-array.ts
tests/main/tests/unit/record-arrays/record-array-test.js

If an optional value supplied as second arg to `rejectBy` it should be compared to the value retrieved using the `key`.
Fix regression in deprecated `rejectBy` behaviour when optional value to test against is used.

fix: deprecated record-array rejectBy use optional value if supplied

---

packages/store/src/-private/record-arrays/identifier-array.ts
tests/main/tests/unit/record-arrays/record-array-test.js

`reject` expects a callback function
Fix regression in deprecated reject function so callback is used.

fix: deprecated record-array reject use callback

---

packages/store/src/-private/proxies/promise-proxies.ts

fix: de-cycle ember-concurrency access of promise

---

packages/graph/src/-private/graph/graph.ts
packages/graph/src/-private/graph/index.ts
packages/json-api/src/-private/cache.ts
packages/model/src/-private/model.js
packages/store/src/-private/caches/instance-cache.ts
packages/store/src/-private/caches/record-data-for.ts
packages/store/src/-private/index.ts
pnpm-lock.yaml
tests/main/package.json
tests/main/tests/unit/model-test.js

- Fixes memory leaks where during application teardown the graph would be re-instantiated
- cleans up some smaller leakage that should only affect Data's own tests.

perf: fix: eliminate SSR/Test memory leak

---

packages/model/src/-private/model.js

The `.relatedTypes` method returns the names of the model classes as small-case strings. Correction made to the related documentation.

Correction made to the Model.relatedTypes documentation

---

ember-data-types/q/ds-model.ts
ember-data-types/q/record-data-schemas.ts
packages/json-api/src/-private/cache.ts
packages/store/src/-private/legacy-model-support/shim-model-class.ts
tests/json-api/tests/integration/cache/documents-test.ts

feat: cache.peek(<RecordIdentifier>)

---

.eslintrc.js
packages/graph/index.js
packages/json-api/index.js
packages/model/index.js
packages/model/src/-private/attr.js
packages/serializer/blueprints/transform/files/__root__/__path__/__name__.js
packages/serializer/blueprints/transform/native-files/__root__/__path__/__name__.js
packages/serializer/index.js
packages/serializer/rollup.config.mjs
packages/serializer/src/-private/embedded-records-mixin.js
packages/serializer/src/-private/transforms/boolean.js
packages/serializer/src/-private/transforms/date.js
packages/serializer/src/-private/transforms/number.js
packages/serializer/src/-private/transforms/string.js
packages/serializer/src/-private/transforms/transform.js
packages/serializer/src/json-api.js
packages/serializer/src/json.js
packages/serializer/src/rest.js
packages/store/rollup.config.mjs
packages/store/src/-private/record-arrays/identifier-array.ts
tests/blueprints/tests/transform-test.js
tests/main/tests/unit/model/rollback-attributes-test.js

For unplug we want to lint against imports which would keep us entangled with Ember.
refactors Transforms to simple native classes. If anyone turns out to be extending these with classic syntax we'll restore the extend from EmberObject, but by-and-large these are simple enough that anyone overriding ought to have simply been replacing... we hope.

chore: begin restricting imports

---

.github/workflows/enforce-pr-labels-beta.yml
.github/workflows/enforce-pr-labels-canary.yml
.github/workflows/enforce-pr-labels-lts-prev.yml
.github/workflows/enforce-pr-labels-lts.yml
.github/workflows/enforce-pr-labels-old-release.yml
.github/workflows/enforce-pr-labels-release.yml

don't re-run label checks for commits

chore: reduce PR CI noise

---

packages/-ember-data/addon/-private/index.ts
packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
packages/request/README.md
packages/request/src/-private/debug.ts
packages/request/src/-private/manager.ts
packages/store/src/-private/cache-handler.ts
packages/store/src/-private/index.ts
packages/store/src/-private/store-service.ts
packages/store/src/index.ts
tests/adapter-encapsulation/app/services/store.js
tests/graph/app/services/store.ts
tests/serializer-encapsulation/app/services/store.js

updates to lifetimes service and CacheHandler install

---

packages/private-build-infra/virtual-packages/deprecations.d.ts
packages/private-build-infra/virtual-packages/deprecations.js
tests/docs/fixtures/expected.js

- DEPRECATE_EARLY_STATIC
- DEPRECATE_HELPERS
- DEPRECATE_PROMISE_MANY_ARRAY_BEHAVIORS
- DEPRECATE_RELATIONSHIPS_WITHOUT_TYPE
- DEPRECATE_RELATIONSHIPS_WITHOUT_ASYNC
- DEPRECATE_RELATIONSHIPS_WITHOUT_INVERSE
- DEPRECATE_NON_EXPLICIT_POLYMORPHISM
- DEPRECATE_COMPUTED_CHAINS

docs: add additional 4.x deprecation guides

---

packages/json-api/src/-private/cache.ts
packages/store/src/-private/cache-handler.ts
packages/store/src/-private/caches/instance-cache.ts
packages/store/src/-private/managers/record-array-manager.ts
packages/store/src/-private/store-service.ts
tests/main/app/cache-handler/meta-package-setup-test.js
tests/main/app/cache-handler/store-package-setup-test.ts
tests/main/public/assets/demo-fetch.json

- Adds additional testing for the CacheHandler. resolves #8510 
- Ensures `cacheOptions.key` is used before `url` (needs test). resolves #8516 
- resolves #8515 by ensuring keyedArrays is setup properly (needs test)

fix: ensure cache-handler works as expected

---

.eslintrc.js
ember-data-types/q/identifier.ts
packages/model/src/-private/legacy-relationships-support.ts
packages/model/src/-private/model.js
packages/request/src/-private/types.ts
packages/store/src/-private/cache-handler.ts
packages/store/src/-private/caches/identifier-cache.ts
packages/store/src/-private/store-service.ts
packages/unpublished-test-infra/addon-test-support/todo.js
tests/main/tests/integration/identifiers/configuration-test.ts
tests/main/tests/integration/identifiers/scenarios-test.ts

resolves #8530 
Originally for the RFC we'd intended for the lifetimes service to take a stable identifier, as the implementation was built it felt like maybe we didn't actually need this concept, but now that we're deeper in we find our initial design was correct.
This makes use of the existing `IdentifiersCache` which serves as a configurable way to determine stable identity from any opaque data (in this case, the `Request`). We provide default generation of identity (`cacheOptions.key` falling back to `url` only when `method` is absent or `GET`), but users may configure this themselves.

feat: stable document identity

---

packages/request/src/-private/context.ts
packages/request/src/-private/manager.ts
packages/request/src/-private/types.ts
packages/store/src/-private/cache-handler.ts
packages/store/src/-private/document.ts
packages/store/src/-private/store-service.ts
tests/main/tests/integration/cache-handler/meta-package-setup-test.js
tests/main/tests/integration/cache-handler/store-package-setup-test.ts

Implements `Document` class for hydrated responses.
Adds tests for various hydrated/non-hydrated/re-fetch scenarios
resolves #8535

feat: Rich Documents

---

packages/graph/src/-private/graph/graph.ts
packages/model/blueprints/model/HELP.md
packages/model/blueprints/model/index.js
packages/model/src/-private/belongs-to.js
tests/blueprints/tests/model-test.js

also show correct relationship definitions in some docs, generally api docs need a lot of review for correctness in this sort of area. Grep shows at least 30 places to audit.

feat: full-relationship definitions when scaffolding with blueprints

---

packages/store/src/-private/managers/record-array-manager.ts
tests/main/tests/integration/record-array-test.js

resolves #8569
Previously, removing a record only checked that the record was still a member of the array if `removes.length !== state.length`, this missed the case where when exactly two records exist and one is removed and the removal is double-notified the record to remove may not be the record in the array.
The double-notification is something we should also investigate, it's likely that we should not notify the state change for `isDeleted`, only for when the deletion is persisted. We also likely should not notify when unloadRecord is called on something whose deletion has been persisted. Both of these cases are leading the over-notification, the first for an extra add, the second for an extra remove.

Fix: don't clear RecordArray if remaining record does not match the removed record

---

README.md
packages/-ember-data/addon/index.js
packages/store/src/-private/managers/record-array-manager.ts
tests/main/tests/integration/record-array-test.js

resolves #8569
Previously, removing a record only checked that the record was still a member of the array if `removes.length !== state.length`, this missed the case where when exactly two records exist and one is removed and the removal is double-notified the record to remove may not be the record in the array.
The double-notification is something we should also investigate, it's likely that we should not notify the state change for `isDeleted`, only for when the deletion is persisted. We also likely should not notify when unloadRecord is called on something whose deletion has been persisted. Both of these cases are leading the over-notification, the first for an extra add, the second for an extra remove.

[backport / beta] Fix: don't clear RecordArray if remaining record does not match the removed record

---

packages/store/src/-private/managers/record-array-manager.ts
tests/main/tests/integration/record-array-test.js

resolves #8569
Previously, removing a record only checked that the record was still a member of the array if `removes.length !== state.length`, this missed the case where when exactly two records exist and one is removed and the removal is double-notified the record to remove may not be the record in the array.
The double-notification is something we should also investigate, it's likely that we should not notify the state change for `isDeleted`, only for when the deletion is persisted. We also likely should not notify when unloadRecord is called on something whose deletion has been persisted. Both of these cases are leading the over-notification, the first for an extra add, the second for an extra remove.

[backport / release] Fix: don't clear RecordArray if remaining record does not match the removed record

---

packages/store/addon/-private/managers/record-array-manager.ts
tests/main/tests/integration/record-array-test.js

resolves #8569
Previously, removing a record only checked that the record was still a member of the array if `removes.length !== state.length`, this missed the case where when exactly two records exist and one is removed and the removal is double-notified the record to remove may not be the record in the array.
The double-notification is something we should also investigate, it's likely that we should not notify the state change for `isDeleted`, only for when the deletion is persisted. We also likely should not notify when unloadRecord is called on something whose deletion has been persisted. Both of these cases are leading the over-notification, the first for an extra add, the second for an extra remove.

[backport / lts-4-8] Fix: don't clear RecordArray if remaining record does not match the removed record

---

packages/store/src/-private/store-service.ts

We'll be deprecating using anything Classic with Store in 5.x

fix: restore Store extends EmberObject :(

---

packages/model/src/-private/legacy-relationships-support.ts
tests/main/tests/integration/relationships/belongs-to-test.js

fix: dont share promise cache for all fields

---

.gitignore
ember-data-types/cache/cache.ts
packages/json-api/src/-private/cache.ts
packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
packages/store/src/-private/managers/cache-manager.ts
packages/store/src/-private/store-service.ts
tests/main/tests/integration/adapter/rest-adapter-test.js
tests/main/tests/integration/record-data/record-data-errors-test.ts
tests/main/tests/integration/record-data/record-data-state-test.ts
tests/main/tests/integration/record-data/record-data-test.ts
tests/main/tests/integration/references/autotracking-test.js

Since the [elimination of InternalModel](https://github.com/emberjs/data/commit/7e66606481bf9b601f18a209ef20d58a41473936) in 4.7.0, every time an existing record is updated, the Record Data/Cache (by invoking InstanceCache.setRecordId) notifies that the `identity` of the record has changed, even if the `id` was not changed, which is the typical case.  
This behavior leads to unnecessary invalidation (and therefore recomputation) of properties that are subscribed to `model.id`, leading to worse performance and possible bugs due to the unexpected behavior.
N/A?

Avoid unnecessary identity notification when record is saved

---

packages/store/README.md
packages/store/src/index.ts

We initially referred to RequestManager as FetchManager to help illuminate its role as decoration over fetch. But because requests can be fulfilled from any source and not just fetch we ultimately opted to call it RequestManager.

docs: fix forgotten references to FetchManager

---

.gitignore
docs-generator/compile-docs.js
ember-data-types/cache/cache.ts
packages/adapter/src/rest.ts
packages/json-api/src/-private/cache.ts
packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
packages/model/src/-private/legacy-relationships-support.ts
packages/request/src/-private/context.ts
packages/store/README.md
packages/store/src/-private/managers/cache-manager.ts
packages/store/src/-private/store-service.ts
packages/store/src/index.ts
tests/adapter-encapsulation/tests/integration/queries-test.js
tests/docs/index.js
tests/main/tests/integration/adapter/rest-adapter-test.js
tests/main/tests/integration/record-data/record-data-errors-test.ts
tests/main/tests/integration/record-data/record-data-state-test.ts
tests/main/tests/integration/record-data/record-data-test.ts
tests/main/tests/integration/references/autotracking-test.js
tests/main/tests/integration/relationships/belongs-to-test.js

- fix: restore Store extends EmberObject (#8594)
- fix: LegacyHandler should provide unfrozen options to Adapters (#8576)
- fix: dont share promise cache for all fields (#8597)
- fix: docs generation should maintain a stable relative path (#8598)
- docs: fix forgotten references to FetchManager (#8601)
- Avoid unnecessary identity notification when record is saved (#8566)
- fix: normalizeErrorResponse should be resilient to non-string details (#8621)

Various Backported Fixes for 4.12 LTS

---

packages/store/src/-private/legacy-model-support/record-reference.ts
packages/store/src/-private/managers/notification-manager.ts
packages/store/src/-private/managers/record-array-manager.ts
tests/main/tests/acceptance/concurrency-test.js

The underlying bug is that the NotificationManager was storing callbacks for `resource` and `document` in the global Cache where we only need to store the callbacks for actual identifiers.
While investigating I also noticed that RecordArrayManager.clear cleared a global cache that it did not own. So on top of fixing those things I also reviewed teardown for the NotificationManager global cache, and opted to make it more safely encapsulated.

fix: NotificationManager should only invoke resource/document callbacks owned by the originating store

---

packages/model/src/-private/record-state.ts
packages/store/src/-private/cache-handler.ts
packages/store/src/-private/record-arrays/identifier-array.ts
packages/tracking/addon-main.js
packages/tracking/babel.config.js
packages/tracking/babel.config.json
packages/tracking/package.json
packages/tracking/rollup.config.mjs
packages/tracking/src/-private.ts
pnpm-lock.yaml
tests/main/tests/end-user-dx/meaningful-backtracking-errors-test.js

threads additional context into Tag objects to ensure debuggability. In dev builds captures and replaces backtracking render errors with more meaningful context.

DX: Nicer backtracking errors

---

packages/store/src/-private/store-service.ts
tests/main/tests/integration/records/unload-test.js

Addresses an issue reported in discord where in 4.12+ unloadAll(void) led to silently no data appearing to be in the store. This was due to improper teardown timing of the notification manager which this PR fixes.
https://discord.com/channels/480462759797063690/486549196837486592/1126451975467323422

fix: unloadAll(void) should not destroy the notification manager

---

packages/store/src/-private/store-service.ts
tests/main/tests/integration/records/unload-test.js

* fix: unloadAll(void) should not destroy the notification manager
* fix lint

fix: unloadAll(void) should not destroy the notification manager (backports #8684)

---

packages/debug/package.json

This fix will need to be brought forward for newer releases as well.
resolves #8701

fix: @ember-data/debug should declare its peer-dependency on @ember-data/store

---

packages/graph/src/-private/graph/graph.ts
tests/graph/tests/integration/graph/unload-test.ts

resolves #8702 
also adds a bunch tests of various ordered unload/delete calls to try to spread a broader net for detecting this sort of issue.

fix: make implicit relationship teardown following delete of related record safe

---

packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
tests/adapter-encapsulation/tests/integration/coalescing-test.js

fix: de-dupe coalescing when includes or adapterOptions is present but still use findRecord

---

.eslintrc.js
ember-data-types/q/identifier.ts
packages/debug/addon/index.js
packages/graph/src/-private/graph/-edge-definition.ts
packages/graph/src/-private/graph/graph.ts
packages/json-api/src/-private/cache.ts
packages/model/src/-private/legacy-relationships-support.ts
packages/serializer/src/index.ts
packages/store/src/-private/caches/identifier-cache.ts
packages/store/src/-private/caches/instance-cache.ts
packages/store/src/-private/caches/resource-utils.ts
packages/store/src/-private/network/request-cache.ts
packages/store/src/-private/store-service.ts
pnpm-lock.yaml
tests/json-api/tests/integration/cache/collection-data-documents-test.ts
tests/json-api/tests/integration/cache/meta-documents-test.ts
tests/json-api/tests/integration/cache/resource-data-documents-test.ts
tests/main/ember-cli-build.js
tests/main/tests/integration/cache-handler/store-package-setup-test.ts
tests/main/tests/integration/identifiers/configuration-test.ts
tests/main/tests/integration/identifiers/polymorphic-scenarios-test.ts
tests/main/tests/integration/identifiers/scenarios-test.ts
tests/main/tests/integration/record-array-test.js
tests/main/tests/integration/record-data/record-data-state-test.ts
tests/main/tests/integration/record-data/record-data-test.ts
tests/main/tests/integration/records/rematerialize-test.js
tests/main/tests/integration/store-test.js
tests/performance/ember-cli-build.js
tests/performance/package.json
tsconfig.json

similar to #8725 but with an approach more likely to be perf happy

chore: refactor IdentityCache to make resource more opaque

---

tests/embroider-basic-compat/ember-cli-build.js

noticed while looking at https://github.com/emberjs/data/issues/8748 that our embroider compat adapter removal in our test is no longer aggressive enough. We should backport this to 4.12 since its a long-term LTS though it shouldn't affect any actual compatibility since most of these packages weren't there at the time.

fix: ensure we are not allowing embroider to do anything

---

packages/debug/package.json
packages/graph/src/-private/graph/graph.ts
packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
packages/model/src/-private/many-array.ts
packages/store/src/-private/managers/record-array-manager.ts
packages/store/src/-private/record-arrays/identifier-array.ts
packages/store/src/-private/store-service.ts
tests/adapter-encapsulation/tests/integration/coalescing-test.js
tests/graph/tests/integration/graph/unload-test.ts
tests/main/tests/integration/record-array-manager-test.js
tests/main/tests/integration/records/new-record-unload-test.js
tests/main/tests/integration/records/save-test.js
tests/main/tests/integration/records/unload-test.js

Bringing  #8703 #8704 #8705 and #8708 into the release branch.

Backport into release

---

packages/graph/src/-private/-utils.ts
packages/graph/src/-private/edges/collection.ts
packages/graph/src/-private/edges/implicit.ts
packages/graph/src/-private/graph.ts
packages/graph/src/-private/operations/merge-identifier.ts
packages/json-api/src/-private/cache.ts
tests/graph/tests/integration/graph/edge-removal/helpers.ts
tests/graph/tests/integration/graph/edge-removal/setup.ts
tests/main/tests/helpers/accessors.ts

chore: refactor implicit edge to match resource and collection pattern

---

packages/graph/src/-private/operations/update-relationship.ts
packages/store/src/-private/caches/identifier-cache.ts
tests/main/tests/integration/records/delete-record-test.js
tests/main/tests/integration/relationships/has-many-test.js

eliminates most GC work during graph build out. Metas are still a big hot spot but we should wait for some of the schema work before diving in too hard on optimizing them as there's a lot of cross over.

perf: reduce allocations during graph population

---

packages/model/src/-private/belongs-to.js

More context for error message in belongsTo when missing inverse or async attribute
Fixes: #8765 
More context for error message in belongsTo when missing inverse or async attribute

fix: More context for error message in belongsTo 

---

packages/serializer/src/json-api.js

Use `!Snapshot.isNew` instead of `Snapshot.record && !Snapshot.record.isNew` to avoid the access to `record`. Accessing `record` creates an entry in `instanceCache.record` which causes the `hasRecord` checks in `Snapshot` to return true. This results in an error when serializing associated records via hasMany that have not been loaded.
fixes #8793

Fix check for new records in JSONAPISerializer.serializeHasMany

---

ember-data-types/cache/document.ts
packages/json-api/src/-private/cache.ts
packages/request-utils/src/index.ts
packages/request/src/fetch.ts

Various bits of polish extracted from the DataWorker effort in #8698 
- Provides additional request utils
- Adds a simple lifetimes handler good for most applications.
- Updates the StructuredDocument API to return `included` records as well for use in advanced caching scenarios

feat: implement a simple LifetimeService utility, improve document reconstruction

---

packages/graph/src/-private/graph.ts
packages/json-api/src/-private/cache.ts
tests/graph/ember-cli-build.js
tests/graph/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
tests/main/tests/index.html
tests/main/tests/integration/records/new-record-unload-test.js

Unloading a new record that is related to another record does not remove it from the relationships. This then causes issues if the other record also is unloaded or if code expects the relationships to no longer include the unloaded record. This adds a failing test case.
This behavior seems to have changed in EmberData v4.7+, older versions seemingly work as expected.
Related Discord thread: https://discord.com/channels/480462759797063690/1143193491250368583
Similar issue: https://github.com/emberjs/data/issues/8262

fix: clear relationships properly when unloading new records

---

packages/serializer/src/json.js

`##` Description
Reported here: https://github.com/emberjs/data/issues/7996
JSON API Serializer `shouldSerializeHasMany` third param `relation` is of type `RelationshipSchema`.

fix: `JSONAPISerializer.shouldSerializeHasMany` relation param type

---

packages/-ember-data/addon/store.ts
tests/adapter-encapsulation/app/services/store.js
tests/graph/app/services/store.ts
tests/serializer-encapsulation/app/services/store.js

While refactoring for 5.3 we'd ended up in a position where `graphFor` needed to be called from the store's constructor. We no longer need this.

fix: graph instantiation should not be required

---

packages/active-record/src/-private/builders/find-record.ts
packages/active-record/src/-private/builders/query.ts
packages/active-record/src/request.ts
packages/json-api/src/-private/builders/find-record.ts
packages/json-api/src/-private/builders/query.ts
packages/json-api/src/request.ts
packages/rest/src/-private/builders/query.ts
tests/docs/fixtures/expected.js

Documents `findRecord` and `query` for ActiveModel/Rest/JSON:API as well as their respective `/request` sub packages

feat: more docs for builders

---

packages/store/src/-private/store-service.ts
tests/adapter-encapsulation/tests/integration/generate-id-test.js

realistically we shouldn't be taking this code-path when using fully modern, though we do allow use of the legacy finders without using adapters/serializers as a potential migration path so we should still fix this.

fix createRecord error when no adapter is present

---

packages/request/src/fetch.ts

Fixes an error reported in Discord. There's no good way to test this yet until we have real http server to test against :(

fix: set headers after setResponse in Fetch handler

---

packages/request/src/-private/context.ts
packages/request/src/fetch.ts

Response headers returned by fetch are both readonly and Immutable:
- listed as readonly https://developer.mozilla.org/en-US/docs/Web/API/Response/headers
- spec lists it as immutable https://fetch.spec.whatwg.org/#concept-headers-guard
This clones the response, allowing us to adjust the response headers, but does so in a way that passes the stream through.

fix: handle Immutable Response objects

---

packages/active-record/src/-private/builders/find-record.ts
packages/json-api/src/-private/builders/find-record.ts
packages/request-utils/src/index.ts
packages/rest/src/-private/builders/find-record.ts

Add more documentation to find-record builder in json-api/rest/active-record packages.

feat: add request options documentation parts to find-record builder

---

packages/model/src/-private/promise-many-array.ts
packages/store/src/-private/record-arrays/identifier-array.ts

Overwrite addMixin

---

tests/main/tests/integration/records/unload-test.js

test passes locally for 5.3. Will test 4.12 just to be sure but all fixes in 5.x have also been applied to 4.12

test: confirm records unload properly for #8863

---

packages/request-utils/src/index.ts
tests/builders/tests/unit/parse-cache-control-test.ts

Covering happy path for parseCacheControl request util 
@runspired I made a failing tests for assert that does not exist yet, not sure if it would be useful or not, please take a look

Add tests for parse-cache-control

---

packages/request-utils/src/index.ts
tests/builders/tests/unit/filter-empty-test.ts

@runspired small quick one PR here, please let me know if there is some cases I missed. Please also check if I put this file in correct place. 
there is 2 commented out fields, it fails `SerializablePrimitive` type, so I cannot even put it there... I am not sure if those should be even tested.

Add tests for filter-empty request util

---

packages/request/src/fetch.ts

fix: Fetch handler should account for empty body

---

packages/-ember-data/app/transforms/boolean.js
packages/-ember-data/app/transforms/date.js
packages/-ember-data/app/transforms/number.js
packages/-ember-data/app/transforms/string.js

This fixes the paths in the deprecation messages about "auto-magically installing" transforms.
Example error when using the current paths:
```
Uncaught Error: Could not find module `ember-data/serializer/transform` imported from `<MY_APP>/transforms/date`
at missingModule (loader.js:247:1)
at findModule (loader.js:258:1)
at Module.findDeps (loader.js:168:1)
at findModule (loader.js:262:1)
at requireModule (loader.js:24:1)
at ModuleRegistry.get (index.js:25:1)
at Resolver._extractDefaultExport (index.js:377:1)
at Resolver.resolveOther (index.js:139:1)
at Resolver.resolve (index.js:160:1)
at resolve (index.js:743:1)
```

doc: Fix paths in transform deprecations

---

packages/store/src/-private/managers/record-array-manager.ts
tests/main/tests/integration/records/unload-all-test.js

test from #8926
resolves #8924 
adds test for unloadAll not fully cleaning up
The rough issue is that if all records are removed and the same number re-added before the array has synced we were then fully clearing membership which would make the next sync after this fail to work properly.
e.g.
```ts
arr.length; // 2
arrSet.size; // 2
<add> C
<add> D
<rem> A
<rem> B
if (rem.length === arr.length) { arrSet.clear() }
arr.length; // 2
arrSet.size; // 0
```

fix: live-array delete sync should not clear the set on length match

---

packages/store/src/-private/managers/record-array-manager.ts
tests/main/tests/integration/records/unload-all-test.js

test for #8924 
fix is likely just to wipe record-array membership at the point of the unloadAll
This feels similar to an issue reported before that was already fixed, we might have a fix in later versions already. Will port the test forward to find out.

fix: unloadAll should cleanup live-array membership

---

packages/model/src/-private/record-state.ts

probably not actually a fix for anything but noticed this while poking around the `isLoaded` codepaths. We already always ran this in prod. As we move more and more away from `@ember-data/model` the odds of this occurring in dev too go up so the guard isn't needed.

chore: get last request for any record on instantiation

---

packages/legacy-compat/src/legacy-network-handler/snapshot.ts
tests/main/tests/integration/relationships/has-many-test.js

fixes an issue leading to errors about missing resources in the cache
see https://discord.com/channels/480462759797063690/1156535621108645918/1156877504561295360
and https://discord.com/channels/480462759797063690/486549196837486592/1153701498820247642

fix: JSONAPISerializer should not reify empty records

---

ember-data-types/q/ember-data-json-api.ts
packages/schema-record/src/record.ts
packages/store/src/-private/store-service.ts
tests/main/tests/integration/cache-handler/store-package-setup-test.ts
tests/schema-record/tests/reads/resource-test.ts

feat (private): implement resource relationships for SchemaRecord

---

packages/schema-record/src/record.ts
packages/tracking/package.json
packages/tracking/rollup.config.mjs
packages/tracking/src/-private.ts
packages/tracking/src/index.ts
pnpm-lock.yaml
tests/schema-record/tests/-utils/reactive-context.ts
tests/schema-record/tests/reactivity/basic-fields-test.ts
tests/schema-record/tests/reactivity/derivation-test.ts
tests/schema-record/tests/reactivity/resource-test.ts
tests/schema-record/tests/test-helper.js

more work for #8880 and #8888 
This implements reactivity for simple fields in SchemaRecord

feat(private): reactive simple fields

---

packages/json-api/src/-private/cache.ts

It said "mutated attributes" but should be "mutated relationships"
-

docs: typo in hasChangedRelationships description

---

packages/holodeck/bin/cmd/run.js
packages/holodeck/bin/cmd/spawn.js
tests/main/package.json

node 18.18 bump is failing due to recursive pnpm job while running holodeck, this remove a layer of indirection to avoid that

chore: fix recursive pnpm on node 18.18

---

packages/store/addon/-private/system/promise-proxies.js

backporting https://github.com/emberjs/data/pull/8435 to 4.4

decycle property lookups on promise proxies to fix usage in ember-concurrency

---

ember-data-types/q/ds-model.ts
packages/json-api/src/-private/cache.ts
packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
packages/legacy-compat/src/legacy-network-handler/serializer-response.ts
packages/legacy-compat/src/legacy-network-handler/snapshot.ts
packages/model/src/-private/model.d.ts
packages/model/src/-private/record-state.ts
packages/store/src/-private/legacy-model-support/schema-definition-service.ts
packages/store/src/-private/legacy-model-support/shim-model-class.ts
packages/store/src/-private/store-service.ts
tests/main/tests/integration/records/concurrent-save-test.ts
tests/main/tests/integration/records/delete-record-test.js

the timing changes in 4.12 made this race condition slightly easier to hit. The approach here is still "known to be buggy" but results in less potential information loss.

fix: make willCommit slightly safer when race conditions occur

---

packages/-ember-data/tsconfig.json
packages/active-record/tsconfig.json
packages/adapter/tsconfig.json
packages/core-types/tsconfig.json
packages/diagnostic/tsconfig.json
packages/graph/tsconfig.json
packages/holodeck/tsconfig.json
packages/json-api/tsconfig.json
packages/legacy-compat/tsconfig.json
packages/model/tsconfig.json
packages/request-utils/tsconfig.json
packages/request/tsconfig.json
packages/rest/tsconfig.json
packages/serializer/tsconfig.json
packages/store/tsconfig.json
packages/tracking/tsconfig.json

switch to composite mode for tsc to help cut down build/rebuild time. Required for `references`.
progress on #9045

chore: use composite mode for tsc

---

.vscode/settings.json
config/eslint/base.cjs
config/package.json
packages/active-record/package.json
packages/adapter/package.json
packages/core-types/package.json
packages/debug/package.json
packages/diagnostic/package.json
packages/graph/package.json
packages/holodeck/package.json
packages/json-api/package.json
packages/legacy-compat/package.json
packages/model/package.json
packages/request-utils/package.json
packages/request/package.json
packages/rest/package.json
packages/serializer/package.json
packages/store/package.json
packages/tracking/package.json
pnpm-lock.yaml
scripts/validate-deps.js

Fix ESLint for VSCode

---

config/eslint/qunit.cjs
config/package.json
packages/-ember-data/.eslintrc.cjs
pnpm-lock.yaml

- Extracts reusable ESLint config for QUnit files
- Uses that config in the one place we currently have QUnit stuff that is linted
- Adds `eslint-plugin-qunit`
Will probably ignore some of the `eslint-plugin-qunit` rules as I use this config on more projects in the monorepo.

Extract qunit ESLint config

---

.prettierignore
config/eslint/ignore.cjs
config/eslint/mocha.cjs
config/eslint/qunit.cjs
config/package.json
pnpm-lock.yaml
tests/blueprints/.eslintrc.cjs
tests/blueprints/package.json
tests/blueprints/tests/adapter-test.js
tests/blueprints/tests/model-test.js
tests/blueprints/tests/serializer-test.js
tests/blueprints/tests/transform-test.js

- Adds ESLint config for `tests/blueprints` project.
- Adds `eslint-plugin-mocha` and ESLint config for Mocha tests.
- Autofixes the resulting lint.

Initial lint config for tests/blueprints

---

packages/request/README.md
packages/request/src/-private/manager.ts

Folks weren't realizing that the details sections were expand/collapse. This makes them normal headers and adds links.

docs: unroll details sections

---

packages/adapter/README.md
packages/debug/README.md
packages/diagnostic/README.md
packages/json-api/README.md
packages/json-api/src/-private/cache.ts
packages/json-api/src/index.ts
packages/serializer/README.md
packages/store/README.md
packages/store/src/index.ts

ensures notes are formatted nicely in markdown

docs: fix note notation to make use of github formatting

---

package.json
packages/-ember-data/addon/store.ts
packages/json-api/src/-private/builders/-utils.ts
packages/json-api/src/-private/builders/find-record.ts
packages/json-api/src/-private/builders/query.ts
packages/json-api/src/-private/builders/save-record.ts
packages/json-api/src/request.ts
packages/request-utils/src/index.ts
tests/docs/fixtures/expected.js
tests/main/tests/integration/store-extension-test.ts

This PR introduces two small features to improve extension and configuration
1) `ember-data/store` will only create a `RequestManager` if one does not exist.
2) `@ember-data/json-api/request` now extends and re-exports `setBuildURLConfig` to allow users to specify which json-api extensions and profiles are in use.

feat: Improve extensibility

---

.github/workflows/main.yml
config/package.json
package.json
packages/schema-record/package.json
pnpm-lock.yaml
tests/warp-drive__schema-record/app/app.ts
tests/warp-drive__schema-record/app/services/store.ts
tests/warp-drive__schema-record/package.json
tests/warp-drive__schema-record/tests/-utils/reactive-context.ts
tests/warp-drive__schema-record/tests/reads/resource-test.ts
tests/warp-drive__schema-record/tsconfig.json
turbo.json

- Install typescript
- Add tsconfig
- Fix TS errors where possible, `@ts-expect-error` where not

Add type-checking to tests/warp-drive__schema-record

---

docs-generator/compile-docs.js
packages/graph/src/-private/-edge-definition.ts
packages/json-api/src/-private/builders/-utils.ts

This is a fix for decorator handling in code comment blocks. This introduces part of https://github.com/cibernox/ember-cli-yuidoc, a dep of ember.js and is what processes the ember.js docs and allows ember.js yui doc generation to handle decorator syntax. Since we have our own bespoke doc compilation process in EmberData that the addon doesn't address, we are introducing this 1 change here rather than adding `ember-cli-yuidoc` itself as a dependency.
See: https://github.com/cibernox/ember-cli-yuidoc/blob/master/lib/broccoli-yuidoc.js
This also fixes a few code blocks that were unclosed and only became exposed in failing tests once decorators were being handled properly and the docs were fully building (previously we were missing some of the code comments in docs because of the decorator …

fix: allow decorator syntax in code comments during yui doc processing

---

packages/core-types/src/cache.ts
packages/json-api/src/-private/cache.ts

docs: fix return signature of peekRequest

---

packages/request-utils/src/index.ts

resolves #9107 
resolves #9118

fix: url configuration should respect / for host and error more meaningfully when invalid

---

.vscode/settings.json
packages/store/src/-private/caches/identifier-cache.ts
tests/main/tests/integration/identifiers/configuration-test.ts
tests/main/tests/integration/identifiers/scenarios-test.ts
tests/main/tests/integration/records/polymorphic-find-record-test.ts

fix: keep a backreference for previously merged identifiers

---

@types/ember-data-qunit-asserts/index.d.ts
packages/model/src/-private/many-array.ts
packages/private-build-infra/virtual-packages/deprecations.d.ts
packages/private-build-infra/virtual-packages/deprecations.js
packages/store/src/-private/managers/cache-capabilities-manager.ts
packages/store/src/-private/managers/cache-manager.ts
packages/store/src/-private/record-arrays/identifier-array.ts
pnpm-lock.yaml
tests/docs/fixtures/expected.js
tests/ember-data__graph/tests/integration/graph/edge-removal/helpers.ts
tests/main/tests/helpers/reactive-context.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-test.ts
tests/main/tests/integration/serializers/embedded-records-mixin-test.js
tests/main/tests/integration/snapshot-test.js
tests/main/tsconfig.json
tests/warp-drive__schema-record/package.json

Forward-port of https://github.com/emberjs/data/pull/9126 (see https://github.com/emberjs/data/issues/9119)
Re-enables deduplication of duplicate records added to ManyArrays, but with a deprecation (`ember-data:deprecate-many-array-duplicates`) as described below:
```js
/**
* **id: ember-data:deprecate-many-array-duplicates**
*
* When the flag is `true` (default), adding duplicate records to a `ManyArray`
* is deprecated in non-production environments. In production environments,
* duplicate records added to a `ManyArray` will be deduped and no error will
* be thrown.
*
* When the flag is `false`, an error will be thrown when duplicates are added.
*
* @property DEPRECATE_MANY_ARRAY_DUPLICATES
* @since 5.3
* @until 6.0
* @public
*/
```

fix: mutating ManyArray should handle duplicates gracefully (with deprecation)

---

packages/request/src/fetch.ts

- Allow `store.request` to be intercepted by Mirage
- This is necessary because Mirage doesn't mock `fetch` until after EmberData closes over `fetch`.
- Don't `cloneResponse` for Mirage mock responses
- This is necessary because Mirage does not implement `Response.body`, which is required for `cloneResponse`. Since `cloneResponse` only exists because updating the headers on a real `Response` isn't allowed (but Mirage also--conveniently--doesn't implement this limitation), we can just update the headers on the Mirage mock response instead.

fix: Fetch handler hacks for Mirage

---

packages/request/src/fetch.ts

Port https://github.com/emberjs/data/pull/9199 to canary

Port 4.12 fetch updates to canary

---

packages/graph/src/-private/-diff.ts
tests/main/tests/integration/relationships/rollback-test.ts

fixes #9207 
Adds the test from that PR. Root cause is that typically we can presume `replaceRelatedRecords` is receiving an array reference it can safely re-use for localState/remoteState as appropriate. However in this case we generate the operation from the existing remoteState array and so this led to the two arrays having the same reference.
This meant that the next mutation on localState was then partially reflected into remoteState, preventing rollbackRelationships from working properly. Only partially reflected because the bookkeeping sets would still see this relationship as empty remotely.

fix: prevent rollbackRelationships from setting remoteState and localState to the same array reference

---

.vscode/settings.json
packages/legacy-compat/src/legacy-network-handler/snapshot.ts
packages/request-utils/src/index.ts
packages/store/src/-private/caches/identifier-cache.ts
tests/main/tests/integration/identifiers/configuration-test.ts
tests/main/tests/integration/identifiers/scenarios-test.ts
tests/main/tests/integration/records/polymorphic-find-record-test.ts
tests/main/tests/integration/relationships/has-many-test.js

backports #8934 #9183 and #9164 to 5.3

fix: backport various fixes to 5.3

---

.github/workflows/release_publish-canary.yml
.github/workflows/release_publish-lts.yml
.github/workflows/release_publish-stable.yml

the chron does not apply the default value for increment, so we use exec to filter out undefined increment values and use the release script's default instead which is also `patch`.

chore: fix canary chron publishing & release changelog generation

---

release/core/publish/steps/generate-tarballs.ts

if the types strategy is private, avoid installation of core-types as a dep or peer-dep

chore: fix publishing of core-types when strategy is private

---

release/utils/flags-config.ts

before we would check and download `latest` vs a specific channel and download the archive even when unneeded.

chore: better "from" version default value population

---

release/core/publish/steps/generate-tarballs.ts

when running prepack all deps/peer-deps need to be present in package.json for rollup to resolve correctly. With this change, we run the prepack command separately before modifying package.json.

chore: manually run prepack

---

packages/adapter/package.json
packages/debug/package.json
release/core/publish/steps/generate-tarballs.ts

we rely on symbols provided by core-types (the intersection of symbols and types is otherwise hard to break out of cycles), thus we do need access to a published version even if its the alpha and we don't use the types.

fix: keep core-type peer-deps

---

release/core/publish/steps/generate-tarballs.ts

converts .d.ts files from es-module syntax to declare-module syntax, inserting references as needed. This will make using canary types possible.
does a simple string parse for now, with some error guards to alert us to whether we need an AST.
To use the types, apps will have to declare all of the EmberData packages that the `ember-data` package brings and configure them as types sources.
package.json:
```ts
"ember-data": "5.4.0-alpha.33",
"@ember-data/store": "5.4.0-alpha.33",
"@ember-data/adapter": "5.4.0-alpha.33",
"@ember-data/graph": "5.4.0-alpha.33",
"@ember-data/json-api": "5.4.0-alpha.33",
"@ember-data/legacy-compat": "5.4.0-alpha.33",
"@ember-data/request": "5.4.0-alpha.33",
"@ember-data/request-utils": "5.4.0-alpha.33",
"@ember-data/serializer": "5.4.0-alpha.33", …
```

feat: publish types as module defs

---

packages/model/src/-private/belongs-to.ts
packages/model/src/-private/has-many.ts
packages/model/src/-private/model.type-test.ts

the types were authored with accessor syntax in mind, but without accessor syntax don't work for async: true properly. This fixes that.

feat: fix types for legacy decorator syntax

---

packages/graph/src/-private/operations/replace-related-records.ts
packages/model/src/-private/many-array.ts
tests/main/tests/integration/references/has-many-test.js

fix: notify during replace if existing localState never previously calculated

---

packages/model/src/-private/legacy-relationships-support.ts
packages/model/src/-private/many-array.ts
packages/model/src/-private/model-methods.ts
packages/model/src/-private/promise-belongs-to.ts
packages/model/src/-private/references/has-many.ts
release/core/publish/steps/generate-tarballs.ts

fixes some types locations to ensure more types properly resolve. Adds additional safety to module compilation.

feat: improve alpha types support

---

turbo.json

removes an unused key that's been preventing us from upgrading

fix: remove unused turbo key

---

packages/request/src/fetch.ts

Update IS_MAYBE_MIRAGE function to check for Mirage in development mode.
If application uses Mirage in development mode (basically running `ember s` with mirage enabled) IS_MAYBE_MIRAGE does not work.

Update IS_MAYBE_MIRAGE function to check for Mirage in development mode

---

packages/request/README.md

I think this could be confusing, and unless I miss something such handler does not exist, and I didn't see any open issue/PR in the ESA repo mentionning it

doc: don't mention unexisting ESA auth handler

---

.github/workflows/compat-tests.yml

chore: bump timeout for floating dep check in CI

---

packages/active-record/src/-private/builders/save-record.ts
packages/json-api/src/-private/builders/save-record.ts
packages/rest/src/-private/builders/save-record.ts

Sometimes was `this.store` other times `store`, changed to `this.store` consistently

doc: use store for save-record docs 

---

packages/model/addon/-private/many-array.ts

Port https://github.com/emberjs/data/pull/8413 to 4.6.

Notify on length when notifying that many-array has changed

---

packages/-ember-data/package.json

potential resolution for #9255 since `npm pack` also seems to have recently gone crazy

fix: be more specific in files in case .npmignore is ignored

---

packages/diagnostic/src/-define.ts
packages/diagnostic/src/-types.ts
packages/diagnostic/src/internals/run.ts
packages/ember/src/-private/promise-state.ts
packages/model/src/-private/promise-belongs-to.ts
packages/model/src/-private/promise-many-array.ts
tests/warp-drive__ember/tests/integration/get-promise-state-test.gts

changes to legacy proxies should be backported

feat: ensure data utils work well with legacy relationship proxies

---

packages/core-types/src/request.ts
packages/request-utils/src/index.ts
packages/store/src/-private/cache-handler.ts
tests/main/tests/integration/cache-handler/lifetimes-test.ts
tests/main/tests/integration/cache-handler/store-package-setup-test.ts

- adds support for 204 requests that run through the CacheHandler
- adds support for 201 requests with empty responses that run through the CacheHandler when no records were specified
- adds support for invalidating the cache based on createRecord operations that don't contain any records

feat: improve lifetime handling of ad-hoc createRecord requests

---

release/core/promote/index.ts
release/core/publish/steps/publish-packages.ts

when publishing alpha/beta stage projects, the first publish sets "latest" but later publishes only update the canary/beta channel as appropriate. This ensures that we keep latest in-sync when doing this.

chore: ensure latest tag is canary/beta tag for early stage packages

---

guides/index.md
guides/typescript/0-installation.md
guides/typescript/1-configuration.md
guides/typescript/2-why-brands.md
guides/typescript/3-typing-models.md
guides/typescript/index.md

[Rendered](https://github.com/emberjs/data/blob/typescript-guide/guides/typescript/index.md)

docs: add typescript guide

---

packages/schema-record/src/managed-object.ts
packages/schema-record/src/record.ts
packages/schema-record/src/schema.ts
packages/store/src/-types/q/schema-service.ts
tests/warp-drive__schema-record/tests/reads/object-test.ts
tests/warp-drive__schema-record/tests/writes/object-test.ts

feat: implement managed object for schemaRecord

---

packages/store/src/-private.ts
packages/store/src/-private/caches/identifier-cache.ts
packages/store/src/-types/q/identifier.ts
packages/store/src/index.ts
tests/docs/fixtures/expected.js

This hooks is required if you want to fully utilize a non `id` primary key

feat: make setKeyInfoForResource public

---

packages/graph/src/-private/operations/replace-related-record.ts

This is a fix for the deprecation @ https://deprecations.emberjs.com/ember-data/v5.x/#toc_ember-data-deprecate-relationship-remote-update-clearing-local-state
In the case of a **remote update with a local change**, I think we want to have the remote state as the local state in the old way.
@runspired Does this make sense? Just encountered this issue in our upgrade from v4 => v5. Perhaps this is a copy/paste issue from the deprecation warning in line #89...
---
In v4 we run into this branch:
https://github.com/emberjs/data/blob/v4.12.7/packages/graph/src/-private/graph/operations/replace-related-record.ts#L131
```ts
if (localState !== remoteState) {
relationship.localState = remoteState;
```
In v5 we run into this branch:
```ts
if (localState !== remoteState && localState === …
```

fix: restore old behavior in deprecation

---

.github/ISSUE_TEMPLATE.md

- Looking at the [pnpm list docs](https://pnpm.io/cli/list) I can't see `--pattern` option.
- My `pnpm` version complains about this: ` ERROR  Unknown option: 'pattern'`
- My `pnpm` version is: `8.15.6`

docs: Update ISSUE_TEMPLATE.md to follow latest pnpm

---

guides/typescript/0-installation.md

- Manually uninstalling packages is error prone
- Make it so that the user can just copy&paste one command
- Unfortunatelly `pnpm` will halt when it tries to remove a package that is not part of `package.json`, hence the one-liner shell script

fix: Automate uninstall process

---

packages/ember/README.md

`<name/>` apparently results in `name-`

docs: fix readme links in @warp-drive/ember

---

packages/request/src/fetch.ts

- In previous version we fixed the code for FireFox that can now work in FireFox which has different `.toString()` implementation
- This change should make it more error prone as it completely removes whitespace from the strings and then compares them
- Follow-up for #9360

fix: Make IS_MAYBE_MIRAGE simplified

---

release/strategy.json

ensures `@warp-drive-mirror/schema-record` is also published for use with the two-store strategy

Update strategy.json to mirror publish @warp-drive/schema-record

---

packages/codemods/package.json
packages/schema/package.json

will help make the binaries more stable until a tool exists to pin bun version

chore: dont --compile during prepack

---

packages/legacy-compat/src/utils.ts

adds `expectId` which is useful when you expect to only have existing records and may accidentally encounter a record in the isNew state

feat: add expectId util

---

packages/serializer/src/-private/embedded-records-mixin.js
packages/serializer/src/json.js

extension of #7956 
We don't want to automatically include `lid` in the payloads generated to be sent to the server as this would probably be a breaking change, but we can at least attempt to preserve any lid the API reflects back to us.
cc @amk221

feat: preserve lids returned by the API in legacy normalization

---

packages/store/src/-private/store-service.ts
packages/store/src/-private/store-service.type-test.ts

Fix incorrect types being expected by the store service’s `createRecord()` method. This could happen when the record being created had, for example, a `belongsTo` relationship, in which case the type for the property with the relationship was `PromiseBelongsTo<SomeModel>` rather than `SomeModel`.
When determining the TS type for properties that can be passed to `createRecord()` a `CreateRecordProperties` utility type is used. It in turn uses a `FilteredKeys` type to narrow the properties to only the model attributes. Promise types were not being handled here and only filtered, leading to the issue.
To resolve any promise types like `PromiseBelongsTo`, a new `AwaitedKeys<Type>` utiltity type was added that wraps `FilteredKeys`. It’s a mapped type that applies …

fix: Resolve promise types for props passed to `store.createRecord()`

---

packages/json-api/src/-private/cache.ts
tests/json-api/tests/integration/cache/resource-data-documents-test.ts

* Backport of #9355
* defaultValue function results should persist after initialization
* clear default values on patch changes
* defaultValue caching test
---------

Fix: @attr defaultValue() results should persist after init (#9355)

---

packages/core-types/src/-private.ts
packages/core-types/src/request.ts
packages/request/src/-private/manager.ts
packages/request/src/-private/promise-cache.ts

In order for `@warp-drive/ember` to be directly compatible with both mirror and non-mirror versions of Ember, a few global concepts need to be universal (shared even across EmberData versions)

feat: universal consts

---

packages/-ember-data/package.json
packages/-ember-data/src/store.ts
packages/adapter/src/json-api.ts
packages/adapter/src/rest.ts
packages/debug/src/data-adapter.ts
packages/model/src/-private/errors.ts
packages/model/src/-private/many-array.ts
packages/model/src/-private/model-methods.ts
packages/model/src/-private/model.ts
packages/model/src/-private/model.type-test.ts
packages/model/src/-private/references/belongs-to.ts
packages/model/src/-private/references/has-many.ts
packages/model/src/-private/type-utils.ts
packages/store/src/-private/store-service.ts
packages/store/src/-private/store-service.type-test.ts
tests/fastboot/app/models/person.ts
tests/main/tests/integration/cache-handler/lifetimes-test.ts
tests/main/tests/integration/identifiers/lid-reflection-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-test.ts
tests/main/tests/unit/custom-class-support/custom-class-model-test.ts

- disentangles EmberObject type from @ember-data/store
- fixes #9404 by changing how the types get merged into Model
- fixes #9405 by falling back to `string` when keys resolves to `never`
- fixes #9402 by reducing any array-like to array
- improves createRecord type by filtering Model properties

feat: improve typing around Model and createRecord

---

packages/json-api/src/-private/cache.ts
packages/model/src/-private/schema-provider.ts
packages/model/src/migration-support.ts
packages/schema-record/src/managed-array.ts
packages/schema-record/src/managed-object.ts
packages/schema-record/src/record.ts
packages/schema-record/src/schema.ts
packages/store/src/-types/q/schema-service.ts
tests/ember-data__json-api/tests/utils/schema.ts
tests/ember-data__model/tests/utils/schema.ts
tests/main/tests/integration/cache-handler/lifetimes-test.ts
tests/main/tests/integration/cache-handler/store-package-setup-test.ts
tests/main/tests/utils/schema.ts
tests/warp-drive__schema-record/tests/reads/basic-fields-test.ts
tests/warp-drive__schema-record/tests/reads/derivation-test.ts

RFC emberjs/rfcs#1027
updates the signatures of `transformation()` `hashFn()` and `derivation()` to take a full field, updates error messages to take advantage of the added context.

feat: update SchemaService to reflect RFC updates

---

packages/build-config/src/-private/utils/features.ts
packages/build-config/vite.config.mjs

enables apps to use `setConfig` correctly

fix: config version lookup needs to be project location aware

---

packages/ember/src/-private/request-state.ts

Fixes the following error encountered when using `state.abort` (yielded by the `Request` component) with the `on` modifier:
```
util.js:579 Uncaught Error: You accessed `this._future` from a function passed to the `on` modifier, but the function itself was not bound to a valid `this` context. Consider updating to use a bound function (for instance, use an arrow function, `() => {}`).
at assertOnProperty (util.js:579:1)
at Object.get (util.js:583:1)
at Proxy.abort (index.js:30:1364)
```

Allow RequestState.abort to be used with on modifier

---

packages/-ember-data/package.json

Context https://x.com/nullvoxpopuli/status/1798383255718416516
I'm using a patch here: https://github.com/NullVoxPopuli/ember-warpdrive-demo-starwars-api/blob/main/patches/ember-data%405.4.0-alpha.74.patch

Fix exports for 'ember-data'

---

packages/schema-record/src/-private/compute.ts
packages/schema-record/src/-private/managed-object.ts
packages/schema-record/src/record.ts
tests/warp-drive__schema-record/tests/-utils/reactive-context.ts
tests/warp-drive__schema-record/tests/reactivity/object-test.ts
tests/warp-drive__schema-record/tests/reactivity/schema-object-test.ts
tests/warp-drive__schema-record/tests/reads/schema-object-test.ts
tests/warp-drive__schema-record/tests/writes/schema-object-test.ts

Implements schema-object features in keeping with definitions in the [Schema Service RFC](https://github.com/emberjs/rfcs/pull/1027).

feat: implement schema-object for schema-record

---

packages/legacy-compat/src/builders/find-all.ts
packages/legacy-compat/src/builders/find-record.ts
packages/legacy-compat/src/builders/query.ts
packages/store/src/types.ts

Pulls legacy store method type improvements from https://github.com/emberjs/data/pull/9387 into the legacy-compat/builders, which should accept the same params.

Improve query types for legacy-compat/builders

---

packages/-ember-data/addon-main.cjs
packages/build-config/src/cjs-set-config.ts
packages/build-config/src/index.ts
packages/build-config/vite.config-cjs.mjs

one step closer to a stable release

fix: add deprecation and avoid breaking configs

---

packages/json-api/src/request.ts

In the JSON API request documentation, there's an issue with a code snippet. The snippet is intended to be displayed as a comment, but it instead shows up with unwanted characters.
resolves:

fix: code snippet in json-api/request api docs

---

packages/-ember-data/addon-main.cjs
packages/-ember-data/src/version.ts
packages/core-types/addon-main.cjs
packages/core-types/src/-private.ts

This eliminates the need for embroider macros to provide packages their own name and version. That is not a good use case for macros, since it can never change post-publication. The prepublication Vite build here has built-in support for reading from package.json.
(Also, this is being motivated  by the fact that addon-main.js in v2 addons in not guaranteed to be run by embroider. It's a classic file that does nothing under our Vite build. Having an alternative that allows apps to manipulate the macros config is planned as a blocker for releasing the vite blueprint.)
This PR is only a WIP, because I suspect the package publication process here needs to change to ensure that `vite build` gets run after each of the mirror package names and/or versions gets set. There's a lot going on in the …

Use vite's built-in package.json loading to inline names and versions

---

packages/request-utils/src/deprecation-support.ts

ember-inflector mutates the singular and plural default arrays with user provided values, so to detect rules that aren't defaults we need to use our own list.

fix: dont trust ember-inflector

---

packages/-warp-drive/package.json
packages/-warp-drive/src/-private/shared/npm.ts
packages/-warp-drive/src/-private/shared/repo.ts
packages/-warp-drive/src/-private/shared/utils.ts
packages/-warp-drive/src/-private/warp-drive/cmd.config.ts
packages/-warp-drive/src/-private/warp-drive/commands/retrofit.ts
pnpm-lock.yaml

adds `-m` or `--monorepo` as an argument to `npx warp-drive retrofit` which will run the retrofit on all packages found in a monorepo.
For instance, to retrofit to the types from the version tagged `latest` across all packages in the monorepo:
```
npx warp-drive retrofit types@latest -m
```

feat: monorepo support for npx warp-drive

---

packages/-ember-data/addon-main.cjs

fix: attempt traversal to find project

---

packages/request-utils/package.json

@ember/string v4 was recently published https://github.com/emberjs/ember-string/releases/tag/v4.0.0-%40ember%2Fstring
it's not possible to upgrade as `@ember-data/store` still requires v3.

Add @ember/string v4 to peerDependencies

---

packages/-ember-data/tests/unit/adapter-errors-test.js
packages/adapter/addon/error.js
packages/model/addon/-private/model.js
packages/model/index.js
packages/store/index.js

Essentially a port of https://github.com/emberjs/data/pull/8412 to the 4.6 branch. Removes usage of `@ember/error` package which has been deprecated/removed from Ember.
Improves compatibility with future Ember.js versions by removing deprecated/removed `@ember/error` usage.

[cleanup 4.6] Remove deprecated Ember.Error usage

---

packages/rest/src/-private/builders/query.ts

Previously it was suggested that one of the parameters is `urlParamsSetting` (singular), but [looking at this line](https://github.com/emberjs/data/blob/eb9e8a9213d1dc74a132c36646929974d7acc742/packages/rest/src/-private/builders/query.ts#L93) (and experimenting with my code) I concluded that it should be `urlParamsSettings` (plural).

fix: Doc for query.ts

---

packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/legacy-compat/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json
packages/unpublished-test-infra/package.json
pnpm-lock.yaml
tests/adapter-encapsulation/package.json
tests/blueprints/package.json
tests/debug-encapsulation/package.json
tests/embroider-basic-compat/package.json
tests/fastboot/package.json
tests/full-data-asset-size-app/package.json
tests/graph/package.json
tests/json-api-encapsulation/package.json
tests/json-api/package.json
tests/main/package.json
tests/model-encapsulation/package.json
tests/performance/package.json
tests/request/package.json
tests/serializer-encapsulation/package.json

@ember/string v4 was recently published https://github.com/emberjs/ember-string/releases/tag/v4.0.0-%40ember%2Fstring
it's not possible to upgrade as `@ember-data/store` still requires v3.

Backport #9511 to lts-4-12: Add @ember/string v4 to peerDependencies

---

guides/typescript/1-configuration.md

Without the `./node_modules/` prefix, TS can't find the types. This is also what the warp-drive retrofit command does: https://github.com/emberjs/data/blob/536192b15822c49226b462a905fa39e47a790fea/packages/-warp-drive/src/-private/warp-drive/commands/retrofit.ts#L408
Related to the changes in https://github.com/ember-cli/ember-cli/pull/10507

Update the paths in the canary tsconfig example

---

contributing/setting-up-the-project.md
packages/holodeck/server/ensure-cert.js
packages/holodeck/server/index.js

This PR aims to improve the `setting-up-the-project.md` file, based on our findings during the setup of the project on my local environment.
1. Moves to recommending the usage of `pnpx` instead of `npx`
. Since the project relies on pnpm, recommend running scripts with pnpm commands
. The only script affected is the holodeck ensure-cert
2. It adds steps related to holodeck certificates
. Install `mkcert` and `nss` (as needed)
. Run the ensure-cert script to create the certificates
3. Remove the env manipulation from the holodeck `index.js` file
. Rely on running the ensure-cert script instead
4. Add more granular log and error messages

Improvement: Setting Up The Project

---

packages/schema-record/src/-private/managed-array.ts
packages/schema-record/src/hooks.ts
packages/schema-record/src/record.ts
tests/warp-drive__schema-record/tests/writes/array-test.ts
tests/warp-drive__schema-record/tests/writes/object-test.ts
tests/warp-drive__schema-record/tests/writes/schema-array-test.ts
tests/warp-drive__schema-record/tests/writes/schema-object-test.ts

spike with @richgt of ensuring immutability. We will want some tests that we are in fact (deeply) immutable when in read-only mode, and to continue to build out tests that we are (deeply) mutable once we checkout.

fix: ensure SchemaRecord immutability

---

packages/model/src/-private/schema-provider.ts
packages/schema-record/src/schema.ts
packages/store/src/-private/store-service.ts

The `ember-data:schema-service-updates` deprecation was planned to introduce in 5.4, but we see this depreaction already in 5.3.9 🤔 (thats no problem, because we can move already now away)...
In additional the `until` is incorrect (must be 6.0 instead of 5.0)
This PR fix only the `until`. I'm not sure if this solves also the other bug that depreacation is already visible...

Fix `until` in deprecation warning `ember-data:schema-service-updates` (must be 6.0 instead of 5.0)

---

packages/-ember-data/package.json
packages/ember/package.json
packages/legacy-compat/package.json
packages/request/package.json
pnpm-lock.yaml
tests/ember-data__adapter/package.json

v4 is a v2 addon
Widen support of `@ember/test-waiters` to include v3 and v4

Support @ember/test-waiters v4

---

package.json
pnpm-lock.yaml
tests/vite-basic-compat/package.json
tests/vite-basic-compat/tsconfig.json

Fix vite app via fixin' deps

---

tests/main/tests/integration/relationships/collection/mutating-has-many-partition-1-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-10-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-11-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-12-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-13-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-14-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-15-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-16-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-17-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-18-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-19-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-2-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-20-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-3-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-4-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-5-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-6-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-7-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-8-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-partition-9-test.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-test-infra.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-test.ts

I think this should let us split and parallelize these tests across all 4 available browser instances
appears to be ~6-7min faster on just the "test chrome" scenario, let alone all the try scenarios

chore: make tests more splittable

---

.github/workflows/perf-check.yml
.github/workflows/perf-over-release.yml
packages/core-types/src/identifier.ts
packages/json-api/src/-private/cache.ts
packages/model/src/-private/notify-changes.ts
packages/store/src/-private.ts
packages/store/src/-private/caches/identifier-cache.ts
packages/store/src/-private/caches/instance-cache.ts
packages/store/src/-private/debug/utils.ts
packages/store/src/-private/managers/cache-capabilities-manager.ts
packages/store/src/-private/managers/notification-manager.ts
packages/store/src/-types/q/cache-capabilities-manager.ts
scripts/perf-tracking/browser-flags.mjs
tests/main/ember-cli-build.js
tests/main/tests/integration/cache/spec-cache-errors-test.ts
tests/main/tests/integration/cache/spec-cache-state-test.ts
tests/main/tests/integration/cache/spec-cache-test.ts
tests/main/tests/unit/custom-class-support/custom-class-model-test.ts

While debugging 4.13 with @gitKrystan I noticed that the attribute notifications were noisier than I would have expected, this will reduce that noise especially for newly created records.
This PR also fixes a few invariant method signatures and drops use of the global IDENTIFIERS set as it is no longer required.
This PR also improves the logging output, and updates our perf-test harness. However, due to an issue somewhere with chrome+tracerbench I've not been able to get it to run yet.

perf: dont notify for attrs on insertions or committed changes that are referentially equal

---

packages/graph/src/-private/operations/replace-related-records.ts
tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
tests/ember-data__graph/tests/test-helper.ts

We encountered a bug when upgrading to 4.13 (see also #9639) where the following series of steps resulted in an unexpected outcome in the deprecated code-path for handling of remoteState updates. We traced this down to an issue that originates when support for graph-diffing was first added in 5.x
Steps to reproduce:
- `await findRecord (backgroundReload)`
- updated hasMany to a new state
- receive updated payload from backgroundReload with the exact same remote state as before
- [expected] notice new hasMany state has been reverted
- [actual (bug)] graph throws error
This can be more tersely described as
- mutate a hasMany
- receive remote state update for hasMany with exact remote state as before
- [expected] notice hasMany mutation has been cleared
- [actual (bug)] graph throws error …

fix: treat uncommitted mutations as local operations when receiving remote updates

---

packages/core-types/src/spec/document.ts
packages/graph/src/-private/-diff.ts
packages/graph/src/-private/operations/replace-related-records.ts
packages/json-api/src/-private/cache.ts
tests/main/tests/integration/relationships/collection/mutating-has-many-test-infra.ts
tests/main/tests/integration/relationships/not-overly-reactive-test.ts
tests/main/tests/integration/relationships/rollback-test.ts

If this works, this would fix one issue we noticed in 4.13-canary

perf: reduce notifications on relationship remote state updates

---

packages/json-api/src/-private/builders/save-record.ts
tests/docs/fixtures/expected.js

adds a shorthand for `updateRecord(record, { patch: true })`

feat: add patchRecord util to JSON:API

---

packages/core-types/src/request.ts
packages/json-api/src/-private/builders/save-record.ts
packages/json-api/src/-private/cache.ts
packages/schema-record/src/-private/compute.ts
packages/schema-record/src/record.ts
packages/store/src/-private/managers/notification-manager.ts
packages/store/src/-private/store-service.ts
tests/warp-drive__schema-record/tests/edit-workflow-test.ts

Also add more tests around edit workflows,
[x] requires editable vs immutable record PRs to land first such as #9624

feat: immutable records should show only remote state, make builder types more useful

---

packages/json-api/src/-private/cache.ts
packages/json-api/src/-private/validate-document-fields.ts
packages/model/src/-private.ts
packages/model/src/-private/legacy-relationships-support.ts
packages/model/src/-private/model.type-test.ts
packages/model/src/-private/promise-many-array.ts
packages/model/src/-private/references/has-many.ts
packages/model/src/-private/type-utils.ts
packages/model/src/index.ts
packages/schema-record/src/-private/compute.ts
packages/schema-record/src/-private/managed-array.ts
packages/schema-record/src/-private/many-array-manager.ts
packages/schema-record/src/record.ts
packages/store/src/-private.ts
packages/store/src/-private/managers/record-array-manager.ts
packages/store/src/-private/record-arrays/identifier-array.ts
packages/store/src/-private/record-arrays/many-array.ts
tests/warp-drive__schema-record/tests/reads/has-many-test.ts

Adds hasMany relationship to SchemaRecord in links mode
Rebased from #9617

Feat: hasMany linksMode

---

packages/json-api/src/-private/serialize.ts

fix: make serialize utils smarter

---

packages/json-api/src/-private/cache.ts
packages/model/src/-private/model.ts
tests/main/eslint.config.mjs
tests/main/tests/acceptance/relationships/tracking-record-state-test.js
tests/main/tests/acceptance/tracking-create-record-test.js
tests/main/tests/helpers/create-tracking-context.gjs
tests/main/tests/integration/cache/json-api-cache-2-test.ts
tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
tests/main/tests/unit/model-test.js
tests/main/tests/unit/store/push-test.js

Fixes a bug where we would notify changes to data that wasn't actually registered with the schema. This seems to only cause issues if the data is coincidentally tracked for some other reason (e.g. `id` or a tracked property with the same name).
NOTE:
Currently (including with this change), we do not discard this data in the cache. So when you get the resource data out of the cache, we include it. Since some APIs are dependent on payloads being complete when you send them back, some users may rely on the current behavior. So we don't delete the value itself so that it's still merged in. We should probably deprecate this eventually.

fix: Don't notify changes for attributes not registered with the schema

---

packages/diagnostic/server/bun/socket-handler.js
packages/diagnostic/server/reporters/default.js
packages/diagnostic/src/internals/run.ts

I noticed there were some failing tests on main that aren't causing the test suite to fail when using diagnostic. I suspect the exit code for global failures wasn't being applied.

internal: fixup diagnostic reporting

---

packages/json-api/src/-private/cache.ts

perf: faster iteration of relationship payloads

---

guides/index.md
guides/reactive-data/index.md
guides/reactive-data/legacy/overview.md
guides/reactive-data/polaris/overview.md
guides/relationships/features/links-mode.md
guides/relationships/features/polymorphism.md
guides/relationships/index.md

[Rendered](https://github.com/emberjs/data/blob/links-mode-guide/guides/relationships/features/links-mode.md)

docs: LinksMode and Polymorphic Relationship Guide, stubs out guide for LegacyMode vs PolarisMode

---

guides/relationships/features/links-mode.md
guides/relationships/features/polymorphism.md
packages/core-types/src/identifier.ts
packages/schema-record/src/-private/record.ts
packages/store/src/-private/caches/identifier-cache.ts
packages/store/src/-private/record-arrays/identifier-array.ts
pnpm-lock.yaml
tests/example-json-api/package.json
tests/warp-drive__schema-record/package.json

Adds a better debugging experience in dev mode to SchemaRecord, RecordArray and Identifier
allowing more visibility through these proxies more quickly.
Also cleans up spacing in some of the guides and fixes two missing deps in test apps
Note: SchemaRecord's getter for debugging will show the value of EVERYTHING in the schema including derived fields, which is why the model in legacy mode shows all the legacy APIs when expanded in the screenshot below.

feat: improve debuggability of SchemaRecord, RecordArray and Identifier

---

packages/build-config/src/runtime.ts

persists runtime config into sessionStorage if available
so for instance `setWarpDriveLogging({ LOG_NOTIFICATIONS: true })` will persist for the session across refresh making debugging easier

feat: persist runtime config

---

packages/graph/src/-private/operations/replace-related-records.ts
tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
tests/ember-data__graph/tests/test-helper.ts

Theoretically the diff function is smart enough for this to no longer be necessary. Reduces overnotification.

Don't set isDirty to true in diff callbacks

---

internal-tooling/src/tasks/sync-scripts.ts
packages/schema-record/src/-private/fields/managed-object.ts
packages/schema-record/src/-private/record.ts
packages/schema-record/src/-private/schema.ts
tests/warp-drive__schema-record/package.json
tests/warp-drive__schema-record/tests/legacy/legacy-mode-activation-test.ts
tests/warp-drive__schema-record/tests/polaris/managed-array-iterable-test.ts
tests/warp-drive__schema-record/tests/polaris/object-iterable-test.gts
tests/warp-drive__schema-record/tests/polaris/record-array-iterable-test.ts
tests/warp-drive__schema-record/tests/polaris/record-iterable-test.gts
tests/warp-drive__schema-record/tests/polaris/schema-array-iterable-test.ts

With SchemaRecord we want to ensure we support by-default in an overridable manner the following:
- JSON.stringify(record)
- JSON.stringify(managedObject)
- JSON.stringify(managedArray)
- JSON.stringify(recordArray)
- `{ ...record }`
- `{ ...managedObject }`
- `[ ...managedArray]`
- `[ ...recordArray]`
- `for (const key in record) {}`
- `for (const key in managedObject) {}`
- `for (const [key, value] of record) {}`
- `for (const [key, value] of managedObject) {}`
- `for (const value of managedArray) {}`
- `for (const value of recordArray) {}`
- `{{#each-in record as |key value|}}`
- `{{#each record as |entry|}}`
- `{{#each-in managedObject as |key value|}}`
- `{{#each managedObject as |entry|}}`
- `Object.keys(record)`
- `Object.keys(managedObject)`
- `Object.values(record)`
- …

feat: ensure objects behave amazeballs

---

packages/request-utils/package.json

Supports the [6.0.0 release](https://github.com/emberjs/ember-inflector/releases/tag/v6.0.0-ember-inflector) of inflector which had a very minimal breaking change to make `meta` uncountable.

Widen Peer Range for ember-inflector

---

packages/adapter/src/index.ts
packages/debug/src/data-adapter.ts
packages/serializer/src/index.ts

We will still need to do similar anywhere it is in the test suite
resolves #9772

chore: cleanup @ember/service deprecation from shipped library code

---

tests/warp-drive__schema-record/tests/polaris/basic-fields-field-read-test.ts

Added tests to determine if mutating a related record from a checked-out record  
triggers an automatic checkout or results in an error

Add: tests verify behavior mutating a record 

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
contributing/become-a-contributor.md
contributing/writing-api-docs.md
packages/core-types/src/schema/fields.ts
packages/experiments/src/persisted-cache/cache.ts

[Rendered](https://github.com/emberjs/data/blob/more-docs-guidance/contributing/writing-api-docs.md)

chore: improve contributing guidance for api documentation

---

packages/core-types/src/runtime.ts

This PR attempts to retrieve session storage within a try catch block to handle cases where it is blocked.
This should resolve #9784.

Handle case when sessionStorage is blocked

---

pnpm-lock.yaml
tests/smoke-tests/dt-types/package.json
tests/smoke-tests/native-types/package.json
tests/vite-basic-compat/package.json

deprecated because eslint now provides its own types

chore: remove @types/eslint__js

---

packages/serializer/src/json-api.js

resolves https://github.com/emberjs/data/issues/9611 even more
https://github.com/emberjs/data/pull/9885 was incomplete

fix: make warnMessageNoModelForKey (and similar) even more safe in prod

---

packages/serializer/src/json-api.js

backport https://github.com/emberjs/data/pull/9894

backport fix: make warnMessageNoModelForKey (and similar) even more safe in prod

---

packages/build-config/src/canary-features.ts
packages/json-api/package.json
packages/json-api/src/-private/cache.ts
packages/json-api/src/-private/validator/1.1/7.1_top-level-document-members.ts
packages/json-api/src/-private/validator/1.1/7.2_resource-objects.ts
packages/json-api/src/-private/validator/1.1/links.ts
packages/json-api/src/-private/validator/index.ts
packages/json-api/src/-private/validator/utils.ts
packages/model/src/-private/schema-provider.ts
packages/model/src/migration-support.ts
packages/schema-record/src/-private/schema.ts
packages/store/src/-types/q/schema-service.ts
pnpm-lock.yaml
tests/docs/fixtures/expected.js
tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
tests/ember-data__json-api/tests/integration/cache/validation-errors-test.ts
tests/ember-data__json-api/tests/utils/schema.ts
tests/ember-data__model/tests/utils/schema.ts
tests/main/tests/integration/cache-handler/lifetimes-test.ts
tests/main/tests/integration/cache-handler/store-package-setup-test.ts
tests/main/tests/utils/schema.ts

resolves #4727 
There's a huge amount of trivial errors we could catch and help folks with by validating the data that gets inserted into the cache against the expected format.
This adds that. It will always run, but initially it will log its output only when asked to:
```ts
setWarpDriveLogging({ LOG_PAYLOADS: true })
```
but eventually we will set it to not only always log, but also to throw if more than a warning is present.
The validation will be *slightly* configurable, specifics forthcoming, with two kinds of supported configuration:
- extensions, to support json:api extensions, will pass any fields for a registered extension to a validator registered for that extension.
- strict mode, which has a number of specific settings
- linkage: whether to validate the full-linkage requirement …

feat: whoa debugging

---

packages/store/src/-private/store-service.ts

Deprecation guide will exist with https://github.com/ember-learn/deprecation-app/pull/1400
URL is knowable as it is based on the id.

Add a URL to the deprecate Store extends EmberObject

---

packages/build-config/src/index.ts
packages/ember/package.json
packages/request/package.json
pnpm-lock.yaml
tests/ember-data__adapter/package.json

attempts shifting install of test-waiters to avoid 3.1 to address recent rise in timeouts

chore: silence deprecation, attempt to fix CI

---

packages/store/src/-private/managers/record-array-manager.ts

This resolves #9945, confirmed in the reproduction via patch

fix: dont notify during population if the array is a collection

---

packages/schema-record/src/-private/fields/compute.ts
packages/schema-record/src/-private/fields/many-array-manager.ts
tests/warp-drive__schema-record/tests/polaris/has-many-field-mutate-test.ts

mutations were double mutating the original source array bc we were no longer divorcing the ref before instantiating the ManyArray. This fixes that and adds a basic test for mutation of a hasMany on a SchemaRecord.

fix: enable mutation to work as expected

---

packages/model/src/-private/belongs-to.ts
packages/model/src/-private/model.ts
tests/main/tests/integration/records/create-record-test.js

A few of our recent efforts (reactivity hooks, granular patches / signal updates to relationships and attrs) have surprisingly shown perf regressions in the `unloadAll` scenario. This scenario mostly matters for test suite performance and not app performance, but this PR is one of a few that seeks to diagnose underlying causes and fix/improve the perf in that area.
This particular change removes notification of belongsTo relationships during record teardown, resulting in their values being stale if accessed. This has been a long standing thing we've thought of changing and has some risks for test suites so I'm making this as a stand alone change in case we need to revert it.
I suspect quite a bit of the regression was that this notification resulted in a bunch of work that we weren't …

perf: fix teardown perf

---

packages/ember/src/install.ts
packages/ember/vite.config.mjs
packages/graph/package.json
packages/graph/src/-private/-utils.ts
packages/request-utils/package.json
packages/schema-record/package.json
packages/store/package.json
packages/store/src/-private/managers/notification-manager.ts
packages/store/src/-private/new-core-tmp/reactivity/configure.ts
packages/store/vite.config.mjs
packages/tracking/eslint.config.mjs
packages/tracking/src/index.ts
packages/tracking/vite.config.mjs

🎉 With this PR, WarpDrive becomes usable by any signals-compatible framework or library.
To do so still requires the following constraints:
- Use SchemaRecord in Polaris Mode only (no Legacy Mode)
- Use zero legacy features (no model, legacy-compat, adapter, serializer packages)
- Do not install ember-inspector support (`@ember-data/debug`)
- Set all deprecations (especially for store extending EmberObject) as resolved. This is most easily done via `compatWith: 5.5`
- There are 3 uses of `await import()` to wrap async calls with `@ember/test-waiters`. Either use a version of this package that does not require ember-source, or set requests to deactivate test waiter behaviors to avoid the async import.
- There are 16 uses of `warn` and `deprecate` from `@ember/debug`, we will eventually …

feat: unlock universal 🌌

---

packages/build-config/src/debugging.ts
packages/request-utils/src/index.ts
tests/docs/fixtures/expected.js
tests/warp-drive__ember/tests/integration/request-component-invalidation-test.gts

Adds additional mechanisms by which to determine if a request has expired to use in addition to `apiCacheHardExpires`
Supports: `cache-control` `expires` and `x-warpdrive-expires` headers
Supports: `isExpired` configured method
Additionally adjusts the policy to disable isSoftExpired in testing envs

feat: constraints based CachePolicy features

---

packages/-ember-data/package.json
packages/adapter/package.json
packages/debug/package.json
packages/diagnostic/package.json
packages/ember/package.json
packages/legacy-compat/package.json
packages/model/package.json
packages/serializer/package.json
packages/store/package.json
packages/tracking/package.json
packages/unpublished-test-infra/package.json
pnpm-lock.yaml

this may need backported to 5.5 to help folks that hit the @cached bug that motivated fixing this up in the first place

fix: simplify peer configuration to avoid bringing extra copies of glimmer/validator

---

docs-viewer/package.json
internal-tooling/package.json
internal-tooling/src/tasks/sync-license.ts
internal-tooling/src/tasks/sync-logos.ts
packages/build-config/cjs-src/transforms/babel-plugin-transform-asserts.js
packages/build-config/cjs-src/transforms/babel-plugin-transform-deprecations.js
packages/build-config/cjs-src/transforms/babel-plugin-transform-features.js
packages/build-config/cjs-src/transforms/babel-plugin-transform-logging.js
packages/build-config/src/babel-macros.ts
packages/build-config/src/index.ts
pnpm-lock.yaml
pnpm-workspace.yaml
release/strategy.json
tsconfig.json
warp-drive-packages/core/package.json

chore: prepare more infra for @warp-drive/core package

---

packages/schema-record/eslint.config.mjs
packages/schema-record/package.json
packages/schema-record/src/-private.ts
packages/schema-record/tsconfig.json
packages/schema-record/vite.config.mjs
pnpm-lock.yaml
tests/warp-drive__experiments/tsconfig.json
warp-drive-packages/core/src/reactive.ts
warp-drive-packages/core/src/reactive/-private.ts
warp-drive-packages/core/src/reactive/-private/fields/compute.ts
warp-drive-packages/core/src/reactive/-private/fields/managed-array.ts
warp-drive-packages/core/src/reactive/-private/fields/managed-object.ts
warp-drive-packages/core/src/reactive/-private/fields/many-array-manager.ts
warp-drive-packages/core/src/reactive/-private/hooks.ts
warp-drive-packages/core/src/reactive/-private/record.ts
warp-drive-packages/core/src/reactive/-private/schema.ts
warp-drive-packages/core/src/reactive/-private/symbols.ts
warp-drive-packages/core/tsconfig.json
warp-drive-packages/core/vite.config.mjs
warp-drive-packages/experiments/tsconfig.json
warp-drive-packages/legacy/src/model/migration-support.ts

in order to land this we will need to decide how to deal with the optional dep between schema-record and legacy model that exists for legacy mode.
I suspect the answer is to implement some version of #9534 where the "kind" functions are registered with the schema service and the model provides its own kind function for hasMany/belongsTo
It may be simpler to put an optional peer-dep on @warp-drive/legacy from @warp-drive/core but because there are only two packages now this may create a circular type dependency that is unfixable.

feat: @warp-drive/core/reactive

---

warp-drive-packages/utilities/src/-private/json-api/serialize.ts

fix #10025 
The `serializeResources` returns after accessing a belongsTo (`this.model.father`) which is not loaded to API `null` as value. This means, that the API removes the relation, which is incorrectly.
Bug Example:
```
console.log(serializeResources(this.store.cache, recordIdentifierFor(this.model)));
console.log(this.model.hotel);
console.log(serializeResources(this.store.cache, recordIdentifierFor(this.model)));
```
The bug was introduced here: https://github.com/emberjs/data/pull/9692/files#diff-95214a0755a845deee5df27f8b6c90016ad9e0b4ea77500579882748262e43d6R92
After removing the line 92, we are running into the issue that we are getting belongsTo like `father: {}` in payload, which is also unwanted / incorrect and should be removed before returing the `serializeResources` …

Fix `serializeResource` (avoid adding all belongsTo as `null` & remove emtpy relationships)

---

tests/warp-drive__schema-record/tests/schema/traits-test.ts
warp-drive-packages/build-config/src/canary-features.ts
warp-drive-packages/core/src/reactive/-private/schema.ts
warp-drive-packages/core/src/store/-types/q/schema-service.ts
warp-drive-packages/core/src/types/schema/fields.ts

resolves #10036 
We've been allowing resources to specify traits they have, but to this point it still meant they needed to include all of that trait's fields on their own. The original motivation was to encourage pre-flattening of the schemas by build-tools.
However, this composition at runtime is not particularly hard and in the absence of a DSL and compiler for doing said pre-flattening it appears better to enable runtime composition. This in theory also reduces the payload size of delivering resource schemas that rely heavily on traits.
TODO

feat: Traits!

---

tests/main/tests/integration/emergent-behavior/recovery/belongs-to-test.ts
tests/main/tests/integration/emergent-behavior/recovery/has-many-test.ts
tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
warp-drive-packages/legacy/src/compat/legacy-network-handler/snapshot.ts

Serializers that handle ModelFragments need to be able to handle the modern version of them we are working to build as a compat layer.
This change allows a custom `modelFor` implementation to produce a `ModelSchema` that serializers designed to work with fragments might understand a bit better out of the box.

feat: cleanup Snapshot and make it defer to modelFor for schema iteration

---

tests/warp-drive__schema-record/tests/polaris/kind/schema-object/deep-changes-test.ts
warp-drive-packages/core/src/reactive/-private/fields/managed-array.ts
warp-drive-packages/core/src/reactive/-private/record.ts

there's probably additional tests we want, and we should implement tests around what we expect to happen with orphaned objects and arrays, probably as part of #10061

test: add tests for deep-change mutations and rollback

---

tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
warp-drive-packages/core/src/store/-private/caches/identifier-cache.ts
warp-drive-packages/core/src/types/identifier.ts
warp-drive-packages/json-api/src/-private/cache.ts

shifts request-key to same key-owner strategy as resource-key, prepares for additional type/naming cleanup

chore: improve isDocumentIdentifier and isRecordIdentifier checks

---

packages/schema-record/README.md
packages/schema-record/src/index.ts
warp-drive-packages/core/src/reactive.ts

While making some tests with warp-drive i have seen that in docs the typings are incorrect.
All the usages in ember-data code base tests are `[Checkout](): Promise<SchemaRecord>`, but docs are saying `[Checkout]: Promise<SchemaRecord>`
The issue in TS:

Fix `[Checkout]` typing in documentation

---

packages/diagnostic/src/-types.ts
packages/diagnostic/src/-types/report.ts
packages/diagnostic/src/helpers/-dom/-helper-context.ts
packages/diagnostic/src/helpers/-dom/helper-hooks.ts
packages/diagnostic/src/helpers/install.ts
packages/diagnostic/src/internals/config.ts
packages/diagnostic/src/internals/delegating-reporter.ts
packages/diagnostic/src/internals/diagnostic.ts
packages/diagnostic/src/internals/run.ts
packages/diagnostic/src/reporters/dom.ts
packages/diagnostic/src/styles/dom-reporter.css
tests/builders/tests/test-helper.js
tests/ember-data__adapter/tests/test-helper.js
tests/ember-data__graph/tests/test-helper.ts
tests/ember-data__json-api/tests/test-helper.js
tests/ember-data__model/tests/test-helper.js
tests/ember-data__request/tests/test-helper.ts
tests/framework-ember/start.ts
tests/warp-drive__experiments/tests/test-helper.ts
tests/warp-drive__react/tests/test-helper.ts

TL;DR plumbing to be able to provide tracing in tests to understand visually the outcome.
- would be nice ... integrate with app code somehow to capture stuff like requests. Potentially use a performanceobserver

feat: Diagnostic Timeline

---

guides/the-manual/misc/migrating/two-store-migration.md

Ironically, I typo-ed the commit message and don't feel like fixing it.

Fix typo in migration docs

---

tests/builders/tests/integration/create-record-test.ts
tests/builders/tests/integration/delete-record-test.ts
tests/builders/tests/integration/update-record-test.ts
tests/main/tests/integration/cache/spec-cache-errors-test.ts
tests/main/tests/integration/cache/spec-cache-state-test.ts
tests/main/tests/integration/cache/spec-cache-test.ts
warp-drive-packages/core/src/store/-private/cache-handler/handler.ts
warp-drive-packages/core/src/store/-private/managers/cache-manager.ts
warp-drive-packages/core/src/types/cache.ts
warp-drive-packages/experiments/src/data-worker/cache-handler.ts
warp-drive-packages/json-api/src/-private/cache.ts

- relaxes the contraint on mutation ops that records must be provided
- performs the associated cache operation for every record listed

feat: easier transactional commits

---

packages/eslint-plugin-warp-drive/docs/no-invalid-relationships.md
packages/eslint-plugin-warp-drive/src/rules/no-create-record-rerender.js
packages/eslint-plugin-warp-drive/src/rules/no-external-request-patterns.js
packages/eslint-plugin-warp-drive/src/rules/no-invalid-relationships.js
packages/eslint-plugin-warp-drive/src/rules/no-invalid-resource-ids.js
packages/eslint-plugin-warp-drive/src/rules/no-invalid-resource-types.js
packages/eslint-plugin-warp-drive/src/rules/no-legacy-request-patterns.js
tests/ember-data__graph/README.md

Update some broken references, realized that they where pointing to `docs/rules` and that was the wrong path now

chore: update some broken references in docs

---

guides/the-manual/misc/typescript/configuration.md

Smol change to make the docs copy&pasteable

fix: Docs typo

---

guides/the-manual/misc/relational-data/index.md

Align the naming with the names of the sub-pages.
I also flipped it so that the `1:N` terminology is in parenthesis, because it's the more advanced naming.

Update relational data configuration labels
